/* CIRCUITBENCH interchange, routing, assembly and hierarchy UI. GPL-3.0-only. */
let assemblyViewer=null;
function assemblyDialog(){if(assemblyViewer)assemblyViewer.dispose();assemblyViewer=null;dialog('3D assembly inspection',`<p class="helptext">Dimensioned component envelopes, actual board thickness, copper, holes and cutouts. Drag to orbit, right-drag to pan, scroll to zoom. These are generic bodies; external STEP models are not loaded.</p><div class="buttonrow">${['iso','top','bottom'].map(a=>`<button data-3d-view="${a}">${a[0].toUpperCase()+a.slice(1)}</button>`).join('')}<button data-extra="assembly-png">Save image</button></div><div id="assemblyViewport"></div><div class="row3"><label>Explode bodies<input id="assemblyExplode" type="range" min="0" max="20" value="0" step=".5"></label><label class="inlinecheck"><input type="checkbox" data-3d-visible="bodies" checked> Bodies</label><label class="inlinecheck"><input type="checkbox" data-3d-visible="copper" checked> Copper</label><label class="inlinecheck"><input type="checkbox" data-3d-visible="silk" checked> Silkscreen</label></div><p id="assemblyState" role="status"></p>`);$('#dialog').classList.add('assemblyDialog');try{assemblyViewer=CB3D.create($('#assemblyViewport'),p,CB);$('#assemblyState').textContent=p.components.length+' dimensioned bodies · '+p.board.thickness+' mm board · top and bottom copper';window.Circuitbench.assembly=()=>assemblyViewer?.stats();}catch(e){$('#assemblyState').textContent='3D needs WebGL in this browser. The 2D design and exports remain available. '+e.message;}}
$('#dialog').addEventListener('close',()=>{assemblyViewer?.dispose();assemblyViewer=null;$('#dialog').classList.remove('assemblyDialog');});
CBWorkbench.actions['assembly-png']=()=>{if(!assemblyViewer)return;let a=document.createElement('a');a.href=assemblyViewer.png();a.download=slug()+'-assembly.png';a.click();};
document.addEventListener('click',e=>{let b=e.target.closest('[data-3d-view]');if(b)assemblyViewer?.view(b.dataset['3dView']);});
document.addEventListener('input',e=>{if(e.target.id==='assemblyExplode')assemblyViewer?.explode(Number(e.target.value));});
document.addEventListener('change',e=>{if(e.target.hasAttribute('data-3d-visible'))assemblyViewer?.visibility(e.target.dataset['3dVisible'],e.target.checked);});

routeDialog=function(){let sheet=CBWorkbench.getSheet(),terminals=CB.pads(p,view==='sch'?'sch':'pcb').filter(a=>view!=='sch'||a.sheet===sheet),list=terminals.map(a=>[a.id,a.label+' · '+(a.net||'unassigned')]);dialog(view==='sch'?'Connect schematic pins':'Route between pins',`<p class="helptext">${view==='sch'?'Creates a wire on the current sheet.':'Finds a path around foreign copper, cutouts and mechanical holes. Zones regenerate around the new track. It does not move existing tracks. Review the completed route.'}</p><label>From<select id="routeFrom">${options(list,list[0]?.[0])}</select></label><label>To<select id="routeTo">${options(list,list[1]?.[0])}</select></label>${view!=='sch'?`<div class="row2"><label>Layer<select id="routeLayer">${options([['F','Front'],['B','Back']],$('#layer').value)}</select></label><label>Width mm<input id="routeWidth" type="number" value="${$('#trackWidth').value}" min=".05" max="10" step=".05"></label></div>`:''}<button data-action="routeApply" class="primary">${view==='sch'?'Connect pins':'Find and add route'}</button><p id="routeError" role="alert"></p>`);};
routeApply=function(){try{let from=$('#routeFrom').value,to=$('#routeTo').value;if(!from||!to||from===to)throw Error('Choose two different pins.');let [aid,apin]=from.split(':'),[bid,bpin]=to.split(':');if(view==='sch'){closeDialog();connectPins({id:aid,pin:apin},{id:bid,pin:bpin});return;}let a=findTerminal(aid,apin),b=findTerminal(bid,bpin),layer=$('#routeLayer').value,width=Number($('#routeWidth').value);if(!a.net||a.net!==b.net)throw Error('Both pins must belong to the same net.');if([a,b].some(x=>x.pad.mount==='smd'&&x.component.pcb.side!==layer))throw Error('Choose a layer matching both SMD pads, or use a plated via.');let points=CB.routeBetween(p,a,b,a.net,layer,width,Number($('#grid').value));if(CBWorkbench.safeEdit(()=>p.tracks.push({id:CB.uid(),net:a.net,layer,width,points}),'Obstacle-aware route added. Review the design checks.'))closeDialog();}catch(e){$('#routeError').textContent=e.message;}};
finishRoute=function(end){if(!route)return;if(end&&end.net!==route.net)return say('Choose a terminal on the same net.');try{let points=CB.clone(route.points);if(end&&CB.dist(points.at(-1),end)>.0001){let segment=CBWorkbench.getRouteAssist()?CB.routeBetween(p,points.at(-1),end,route.net,route.layer,route.width,Number($('#grid').value)):[points.at(-1),{x:end.x,y:end.y}];points.push(...segment.slice(1));}points=CB.simplifyTrack(points);if(points.length<2)return say('Add a corner or destination first.');let r=route;if(CBWorkbench.safeEdit(()=>p.tracks.push({id:CB.uid(),net:r.net,layer:r.layer,width:r.width,points}),'Track committed. Review its clearances.')){route=null;renderCanvas();}}catch(e){say(e.message);}};
CBWorkbench.actions['route-transition']=()=>{if(!route)return say('Start a route and place a corner at the intended via location first.');if(route.points.length<2)return say('Click the via location to place a route corner first.');const r=CB.clone(route),q=r.points.at(-1),width=Math.max(.9,2*p.rules.annular+.4);if(CBWorkbench.safeEdit(()=>{p.tracks.push({id:CB.uid(),net:r.net,layer:r.layer,width:r.width,points:CB.simplifyTrack(r.points)});p.vias.push({id:CB.uid(),net:r.net,x:q.x,y:q.y,diameter:width,drill:.4});},'Via added; continue routing on the other layer.')){route={...r,layer:r.layer==='F'?'B':'F',points:[q]};$('#layer').value=route.layer;renderCanvas();}};
CBWorkbench.actions['route-cleanup']=()=>CBWorkbench.safeEdit(()=>{let seen=new Set();p.tracks=p.tracks.map(t=>({...t,points:CB.simplifyTrack(t.points)})).filter(t=>{if(t.points.length<2)return false;let key=JSON.stringify([t.net,t.layer,t.width,t.points]);if(seen.has(key))return false;seen.add(key);return true;});},'Removed duplicate points, collinear corners and identical duplicate tracks.');
$('#pcbTools').insertAdjacentHTML('beforeend','<button data-extra="route-transition" title="Commit the current route corner, add a via and continue on the other layer">Via transition</button><button data-extra="route-cleanup">Clean tracks</button>');

function sheetsDialog(){const W=CBWorkbench,F=W.field2,current=W.getSheet(),sheet=p.sheets.find(s=>s.id===current);dialog('Schematic sheets & ports',`<p class="helptext">All sheets share one PCB. Global labels connect across sheets. Use a sheet-prefixed net, such as Sensor/SIGNAL, for a local connection. A child port explicitly binds an existing local net to a parent/global net.</p><div class="tablewrap"><table><thead><tr><th>Sheet</th><th>Parent</th><th>Parts</th><th></th></tr></thead><tbody>${p.sheets.map(s=>`<tr><td><button data-open-sheet="${s.id}">${esc(s.name)}</button></td><td>${esc(p.sheets.find(a=>a.id===s.parent)?.name||'Root')}</td><td>${p.components.filter(c=>c.sheet===s.id).length}</td><td>${s.parent?`<button data-delete-sheet="${s.id}">Delete empty</button>`:''}</td></tr>`).join('')}</tbody></table></div><div class="row2">${F('New sheet name','sheetName','') }<label>Parent<select id="sheetParent">${options(p.sheets.map(s=>[s.id,s.name]),current)}</select></label></div>${W.extra('Add child sheet','sheet-add')}<h3>${esc(sheet.name)} · ports</h3>${sheet.parent?`<div class="row2">${F('Port name','portName','')}<label>Direction<select id="portDirection">${options(['input','output','bidirectional','power'],'input')}</select></label><label>Local net<select id="portLocal">${options(p.nets,p.nets[0])}</select></label><label>Parent / global net<select id="portGlobal">${options(p.nets,p.nets[0])}</select></label></div>${W.extra('Bind port','port-add')}<p class="helptext">Binding merges the selected nets throughout the project. Deleting a port removes its annotation; rename and reassign pins to separate its connectivity, or Undo the binding.</p>`:'<p>Open a child sheet to define ports.</p>'}<ul>${p.ports.filter(a=>a.sheet===current).map(a=>`<li>${esc(a.name)} · ${esc(a.direction)} → ${esc(a.net)} <button data-delete-port="${a.id}">Delete annotation</button></li>`).join('')||'<li>No ports on this sheet.</li>'}</ul>`);}
CBWorkbench.actions['sheet-add']=()=>{let name=$('#sheetName').value.trim(),parent=$('#sheetParent').value,id=CB.uid();if(!name)return CBWorkbench.showFormError(Error('Enter a sheet name.'));if(CBWorkbench.safeEdit(()=>p.sheets.push({id,name,parent}),'Child sheet added.')){CBWorkbench.setSheet(id);selected=null;closeDialog();setView('sch');}};
CBWorkbench.actions['port-add']=()=>{if(CBWorkbench.safeEdit(()=>CB.bindPort(p,CBWorkbench.getSheet(),$('#portName').value.trim(),$('#portLocal').value,$('#portGlobal').value,$('#portDirection').value),'Sheet port bound to the parent net.'))sheetsDialog();};
function blocksDialog(){const W=CBWorkbench,ids=W.selection.size?[...W.selection]:p.components.filter(c=>c.sheet===W.getSheet()).map(c=>c.id);dialog('Reusable circuit blocks',`<p class="helptext">Capture selected parts (Shift-click or “Select for block”), or all parts on the current sheet when nothing is selected. Blocks contain symbols, footprints and internal wires. PCB tracks are deliberately rerouted after placement. New instances use separate net prefixes unless you explicitly share nets.</p>${W.field2('Block name','blockName','')}${W.extra('Capture '+ids.length+' parts','block-save')}<hr><label>Saved block<select id="blockChoice">${options(p.library.blocks.map(b=>[b.id,b.name]))}</select></label><div class="row3">${W.field2('Instance prefix','blockPrefix','B'+(p.library.blocks.length+1))}${W.field2('PCB center X mm','blockX',p.board.width/2,'number')}${W.field2('PCB center Y mm','blockY',p.board.height/2,'number')}</div>${W.field2('Shared nets · comma separated, blank keeps all private','blockShared','')}${W.extra('Place on current sheet','block-place','primary')}<p class="helptext">Saved blocks travel with project JSON and exported libraries.</p>`);}
CBWorkbench.actions['block-save']=()=>{let W=CBWorkbench,name=$('#blockName').value.trim(),ids=W.selection.size?[...W.selection]:p.components.filter(c=>c.sheet===W.getSheet()).map(c=>c.id);if(!name)return W.showFormError(Error('Enter a block name.'));if(W.safeEdit(()=>p.library.blocks.push(CB.captureBlock(p,ids,name)),'Circuit block saved.'))blocksDialog();};
CBWorkbench.actions['block-place']=()=>{let b=p.library.blocks.find(a=>a.id===$('#blockChoice').value);if(!b)return CBWorkbench.showFormError(Error('Save or import a circuit block first.'));if(CBWorkbench.safeEdit(()=>{let ids=CB.instantiateBlock(p,b,CBWorkbench.getSheet(),{x:Number($('#blockX').value),y:Number($('#blockY').value),sx:zoom.sch.cx,sy:zoom.sch.cy,prefix:$('#blockPrefix').value.trim(),shared:$('#blockShared').value.split(',').map(x=>x.trim()).filter(Boolean)});CBWorkbench.selection.clear();ids.forEach(id=>CBWorkbench.selection.add(id));selected=ids[0];},'Block placed with new references and scoped nets.')){closeDialog();fit();}};
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.openSheet){CBWorkbench.setSheet(b.dataset.openSheet);selected=null;closeDialog();setView('sch');}if(b.dataset.deleteSheet){let id=b.dataset.deleteSheet;if(p.components.some(c=>c.sheet===id)||p.junctions.some(a=>a.sheet===id)||p.sheets.some(s=>s.parent===id))return CBWorkbench.showFormError(Error('Remove parts, junctions and child sheets first.'));if(CBWorkbench.safeEdit(()=>{p.sheets=p.sheets.filter(s=>s.id!==id);p.ports=p.ports.filter(a=>a.sheet!==id);},'Empty sheet removed.'))sheetsDialog();}if(b.dataset.deletePort){if(CBWorkbench.safeEdit(()=>p.ports=p.ports.filter(a=>a.id!==b.dataset.deletePort),'Port annotation removed; net assignments retained.'))sheetsDialog();}});

CBWorkbench.actions['kicad-export']=()=>{if(p.importNotes.some(n=>n.startsWith('BLOCKING:')))return CBWorkbench.showFormError(Error('This imported board contains omitted unsupported features. Resolve the import diagnostics before manufacturing or exporting a replacement board.'));download(slug()+'.kicad_pcb',CB.exportKiCad(p),'text/plain');};
CBWorkbench.actions['kicad-import']=()=>{let input=document.createElement('input');input.type='file';input.accept='.kicad_pcb';input.id='kicadInput';$('#dialogBody').append(input);input.onchange=async()=>{try{let file=input.files[0];if(!file||file.size>1e7)throw Error('Choose a .kicad_pcb file under 10 MB.');const result=CB.importKiCad(await file.text());window.CBImportPreview=result;dialog('KiCad import preview',`<p>${result.project.components.length} components · ${result.project.tracks.length} track segments · ${result.project.holes.length} mechanical holes</p><p>Supported two-layer board subset. Original schematic and external 3D files are not reconstructed. Your current project is retained until you accept this preview.</p><ul>${result.diagnostics.map(d=>`<li><strong>${esc(d.severity.toUpperCase())}</strong> ${esc(d.message)}</li>`).join('')||'<li>No unsupported board features detected in the implemented parser.</li>'}</ul>${result.diagnostics.some(d=>d.severity==='blocking')?'<div class="notice">This is a partial inspection import. Fabrication and native board export remain blocked while blocking diagnostics are present. Continue the original design in KiCad for unsupported features.</div>':''}<button data-extra="kicad-accept" class="primary">Open imported board · Undo preserves current project</button>`);}catch(e){CBWorkbench.showFormError(e);}};input.click();};
CBWorkbench.actions['kicad-accept']=()=>{if(!window.CBImportPreview)return;if(CBWorkbench.safeEdit(()=>{p=CB.clone(window.CBImportPreview.project);selected=null;},'KiCad board imported. Review diagnostics and regenerated fills.')){delete window.CBImportPreview;closeDialog();setView('pcb');}};
