/* CIRCUITBENCH schematic sheets and reusable circuit blocks. GPL-3.0-only. */
(function(root){'use strict';const C=typeof module!=='undefined'?require('./routing.js'):root.CB;
function captureBlock(p,ids,name){const selected=new Set(ids),components=C.clone(p.components.filter(c=>selected.has(c.id)));if(!components.length)throw Error('Select components or use a nonempty current sheet.');const sheets=new Set(components.map(c=>c.sheet));if(sheets.size!==1)throw Error('Capture one schematic sheet at a time.');const sheet=components[0].sheet,junctions=C.clone(p.junctions.filter(j=>j.sheet===sheet));let allowed=e=>e.kind==='junction'||selected.has(e.component),wires=C.clone(p.wires.filter(w=>w.sheet===sheet&&allowed(w.from)&&allowed(w.to))),used=new Set();let reachable=new Set(components.flatMap(c=>c.pads.map(a=>c.id+':'+a.n))),again=true;while(again){again=false;for(let w of wires)if(reachable.has(C.endpointKey(w.from))||reachable.has(C.endpointKey(w.to)))for(let e of [w.from,w.to]){let k=C.endpointKey(e);if(!reachable.has(k)){reachable.add(k);again=true;}}}wires=wires.filter(w=>reachable.has(C.endpointKey(w.from)));wires.forEach(w=>[w.from,w.to].forEach(e=>{if(e.kind==='junction')used.add(e.id);}));let nets=[...new Set(components.flatMap(c=>c.pads.map(a=>a.net)).filter(Boolean))];return {id:C.uid(),name,components,wires,junctions:junctions.filter(j=>used.has(j.id)),labels:C.clone(p.labels.filter(l=>selected.has(l.component))),nets};}
function instantiateBlock(p,block,sheet,{x=30,y=20,sx=50,sy=40,prefix='B1',shared=[]}={}){if(!p.sheets.some(s=>s.id===sheet))throw Error('Choose an existing target sheet.');if(!/^[A-Za-z0-9_-]{1,20}$/.test(prefix))throw Error('Use 1–20 letters, digits, underscore or dash for the instance prefix.');const b=C.clone(block),ids=new Map([...b.components,...b.junctions,...b.wires,...b.labels].map(a=>[a.id,C.uid()])),nets=new Map(b.nets.map(n=>[n,shared.includes(n)?n:prefix+'/'+n]));if([...nets.values()].some(n=>n.length>60))throw Error('An instance net name exceeds 60 characters.');if(b.nets.some(n=>!shared.includes(n)&&p.nets.includes(nets.get(n))))throw Error('This prefix already exists. Choose another instance prefix.');for(let n of nets.values())if(!p.nets.includes(n))p.nets.push(n);let cx=b.components.reduce((s,c)=>s+c.pcb.x,0)/b.components.length,cy=b.components.reduce((s,c)=>s+c.pcb.y,0)/b.components.length,csx=b.components.reduce((s,c)=>s+c.sch.x,0)/b.components.length,csy=b.components.reduce((s,c)=>s+c.sch.y,0)/b.components.length;const shift=q=>{q.x=C.round(q.x+sx-csx);q.y=C.round(q.y+sy-csy);};
 for(let c of b.components){c.id=ids.get(c.id);let ref=c.ref.replace(/[0-9]+$/,'')||'X',i=1;while(p.components.some(x=>x.ref===ref+i))i++;c.ref=ref+i;c.sheet=sheet;c.locked=false;c.pcb.x=C.round(c.pcb.x+x-cx);c.pcb.y=C.round(c.pcb.y+y-cy);shift(c.sch);for(let a of c.pads){a.net=nets.get(a.net)||'';a.labelNet=nets.get(a.labelNet)||'';}p.components.push(c);}
 for(let j of b.junctions){j.id=ids.get(j.id);j.sheet=sheet;j.net=nets.get(j.net)||'';shift(j);p.junctions.push(j);}for(let w of b.wires){w.id=ids.get(w.id);w.sheet=sheet;w.net=nets.get(w.net);for(let e of [w.from,w.to])if(e.kind==='pin')e.component=ids.get(e.component);else e.id=ids.get(e.id);w.points.forEach(shift);p.wires.push(w);}for(let l of b.labels){l.id=ids.get(l.id);l.component=ids.get(l.component);l.net=nets.get(l.net);p.labels.push(l);}C.rebuildNets(p);return b.components.map(c=>c.id);
}
function bindPort(p,sheet,name,localNet,parentNet,direction){let s=p.sheets.find(s=>s.id===sheet);if(!s?.parent)throw Error('Ports belong to child sheets.');if(!name.trim()||!p.nets.includes(localNet)||!p.nets.includes(parentNet))throw Error('Enter a port name and existing nets.');if(p.ports.some(a=>a.sheet===sheet&&a.name===name))throw Error('A port with this name already exists on the sheet.');if(localNet!==parentNet)C.mergeNet(p,parentNet,localNet);p.ports.push({id:C.uid(),sheet,name,net:parentNet,direction});C.rebuildNets(p);}
Object.assign(C,{captureBlock,instantiateBlock,bindPort});if(typeof module!=='undefined')module.exports=C;else root.CB=C;
})(typeof globalThis!=='undefined'?globalThis:this);
