/* CIRCUITBENCH board geometry, fabrication and rule editing. GPL-3.0-only. */
function boardDialog(kind){const W=CBWorkbench,x=selectedObject();if(!kind)kind=p.holes.includes(x)?'hole':p.zones.includes(x)?'zone':p.silk.includes(x)?x.kind:p.cutouts.includes(x)?'cutout':'outline';dialog('Board fabrication tools',`<label>Tool<select id="boardTool">${options([['outline','Board outline'],['hole','Mounting hole / slot'],['zone','Copper zone'],['text','Silkscreen text'],['line','Silkscreen line'],['cutout','Board cutout']],kind)}</select></label><div id="boardForm"></div><p id="extraError" role="alert"></p>`);renderBoardForm(kind);}
function renderBoardForm(kind){const W=CBWorkbench,F=W.field2,x=selectedObject(),existing=kind==='hole'&&p.holes.includes(x)||kind==='zone'&&p.zones.includes(x)||kind==='cutout'&&p.cutouts.includes(x)||(kind==='text'||kind==='line')&&p.silk.includes(x)&&x.kind===kind,q=existing?x:null;$('#boardForm').dataset.editId=q?.id||'';let html='';
 if(kind==='outline'||kind==='cutout'){let points=kind==='outline'?CB.G.outline(p):q?.points||[{x:20,y:15},{x:30,y:15},{x:30,y:25},{x:20,y:25}];html=`<p class="helptext">One X,Y vertex per line, in millimeters. The path closes automatically. Outline coordinates must start at an origin with minimum X=0 and Y=0; cutouts must be inside the board.</p><textarea id="shapePoints" rows="8">${points.map(a=>a.x+','+a.y).join('\n')}</textarea>`;}
 if(kind==='hole')html=`<div class="row2">${F('X mm','objX',q?.x??5,'number','step=".1"')}${F('Y mm','objY',q?.y??5,'number','step=".1"')}${F('Drill / slot width mm','holeDrill',q?.drill??3.2,'number','step=".1"')}${F('Total slot length mm · 0 = round','holeSlot',q?.slot??0,'number','step=".1"')}${F('Rotation °','objRotation',q?.rotation??0,'number','step="15"')}</div><p class="helptext">Mechanical holes and slots are nonplated and go into Nonplated.drl. Pad slots belong in the footprint editor.</p>`;
 if(kind==='zone')html=`<div class="row2"><label>Net<select id="zoneNet">${options(p.nets,q?.net||activeNet||p.nets[0])}</select></label><label>Copper layer<select id="objLayer">${options([['F','Front'],['B','Back']],q?.layer||$('#layer').value)}</select></label>${F('Clearance mm','zoneClearance',q?.clearance??p.rules.clearance,'number','min=".1" step=".05"')}${F('Thermal gap mm','zoneGap',q?.thermalGap??.3,'number','min=".1" step=".05"')}${F('Spoke width mm','zoneSpoke',q?.spoke??.5,'number','min=".1" step=".05"')}</div><label class="inlinecheck"><input id="zoneThermal" type="checkbox" ${q?.thermal===false?'':'checked'}> Thermal relief at same-net component pads</label><label>Boundary · blank fills the board<textarea id="shapePoints" rows="5" placeholder="0,0&#10;60,0&#10;60,40&#10;0,40">${(q?.points||[]).map(a=>a.x+','+a.y).join('\n')}</textarea></label><p class="helptext">Fill recalculates from source geometry after every edit. Earlier-created zones have priority. Separate islands remain separate in connectivity checks. Vias connect solidly.</p>`;
 if(kind==='text')html=`${F('Text · A–Z, 0–9, + - . / _ :','silkText',q?.text||'REV '+p.revision)}<div class="row2">${F('X mm','objX',q?.x??($('#layer').value==='B'?p.board.width-5:5),'number','step=".1"')}${F('Y mm','objY',q?.y??p.board.height-5,'number','step=".1"')}${F('Character height mm','silkSize',q?.size??1.4,'number','min=".5" step=".1"')}${F('Rotation °','objRotation',q?.rotation??0,'number','step="15"')}<label>Side<select id="objLayer">${options([['F','Front'],['B','Back']],q?.layer||$('#layer').value)}</select></label></div><p class="helptext">Text uses a vectorized 5 × 7 font. Bottom text is mirrored automatically, so it reads correctly from the underside.</p>`;
 if(kind==='line')html=`<div class="row2">${F('Start X','lineAX',q?.a.x??5,'number','step=".1"')}${F('Start Y','lineAY',q?.a.y??5,'number','step=".1"')}${F('End X','lineBX',q?.b.x??20,'number','step=".1"')}${F('End Y','lineBY',q?.b.y??5,'number','step=".1"')}${F('Width mm','silkWidth',q?.width??.2,'number','step=".05"')}<label>Side<select id="objLayer">${options([['F','Front'],['B','Back']],q?.layer||$('#layer').value)}</select></label></div>`;
 html+=`<div class="buttonrow">${W.extra(existing?'Update object':'Apply / create','board-apply','primary')}${W.extra('Generate reference silkscreen','silk-refs')}</div>`;$('#boardForm').innerHTML=html;
}
function applyBoardObject(){const W=CBWorkbench,kind=$('#boardTool').value,editId=$('#boardForm').dataset.editId,id=editId||CB.uid(),number=s=>Number($(s).value);let target,value;
 try{if(kind==='outline'||kind==='cutout'){let pts=W.parsePoints($('#shapePoints').value);if(!CB.G.polygonValid(pts))throw Error('Use at least three distinct vertices forming a non-self-intersecting polygon.');if(kind==='outline'){let b=CB.G.bounds([pts]);if(Math.abs(b.minX)>.001||Math.abs(b.minY)>.001)throw Error('Outline minimum X and Y must each be zero.');if(W.safeEdit(()=>{p.board.width=b.maxX;p.board.height=b.maxY;p.board.outline=pts;},'Board outline updated.')){closeDialog();fit();}return;}if(CB.G.difference([pts],CB.G.boardMaterial({...p,cutouts:p.cutouts.filter(c=>c.id!==editId)})).length)throw Error('Cutout must be entirely within existing board material.');target='cutouts';value={id,points:pts};}
 if(kind==='hole'){target='holes';value={id,x:number('#objX'),y:number('#objY'),drill:number('#holeDrill'),slot:number('#holeSlot'),rotation:number('#objRotation'),plated:false};if(value.slot>0&&value.slot<value.drill)throw Error('Slot length must be at least its drill width.');}
 if(kind==='zone'){target='zones';let points=W.parsePoints($('#shapePoints').value);if(points.length&&!CB.G.polygonValid(points))throw Error('Zone boundary must be a valid polygon.');value={id,points,net:$('#zoneNet').value,layer:$('#objLayer').value,clearance:number('#zoneClearance'),thermalGap:number('#zoneGap'),spoke:number('#zoneSpoke'),thermal:$('#zoneThermal').checked};}
 if(kind==='text'){target='silk';value={id,kind,layer:$('#objLayer').value,x:number('#objX'),y:number('#objY'),text:$('#silkText').value.toUpperCase(),size:number('#silkSize'),rotation:number('#objRotation'),width:.2,mirror:$('#objLayer').value==='B'};CB.silkPaths(value);}
 if(kind==='line'){target='silk';value={id,kind,layer:$('#objLayer').value,width:number('#silkWidth'),a:{x:number('#lineAX'),y:number('#lineAY')},b:{x:number('#lineBX'),y:number('#lineBY')}};}
 if(W.safeEdit(()=>{let i=p[target].findIndex(a=>a.id===editId);if(i>=0)p[target][i]=value;else p[target].push(value);selected=id;},'Board geometry updated; checks and exports use this same geometry.'))closeDialog();}catch(e){W.showFormError(e);}
}
function rulesDialog(){const W=CBWorkbench,F=W.field2;dialog('Design rules & net classes',`<p class="helptext">Rules are explicit design assumptions. The conservative JLCPCB example uses a subset of published two-layer FR-4 capabilities with extra margin; confirm current order options with the fabricator.</p><div class="buttonrow">${W.extra('Workshop defaults','rules-default')}${W.extra('JLCPCB conservative example','rules-jlc')}</div><div class="row3">${[['minWidth','Minimum track width'],['clearance','Copper clearance'],['edge','Copper-to-edge'],['annular','Annular ring'],['drill','Hole-to-hole gap'],['mask','Mask expansion'],['maskWeb','Mask web'],['silk','Silk-to-mask gap'],['silkLine','Minimum silk feature']].map(([k,l])=>F(l+' mm','rule_'+k,p.rules[k],'number','step=".05"')).join('')}</div>${F('Rule source / verification note','ruleSource',p.rulesSource||'User-defined workshop defaults')}<div class="buttonrow">${W.extra('Apply rules','rules-apply','primary')}</div><h3>Net classes</h3><p class="helptext">A net class can increase clearance and set its minimum/recommended track width. Assign each net to no more than one class.</p><div class="row3">${F('Class name','className','Power')}${F('Track width mm','classWidth',.8,'number','step=".05"')}${F('Clearance mm','classClearance',.3,'number','step=".05"')}</div><label>Nets · comma separated<input id="classNets" placeholder="+5V, GND"></label>${W.extra('Add class','class-add')}<div class="tablewrap"><table><thead><tr><th>Class</th><th>Nets</th><th>Width</th><th>Gap</th><th></th></tr></thead><tbody>${p.netClasses.map((a,i)=>`<tr><td>${esc(a.name)}</td><td>${esc(a.nets.join(', '))}</td><td>${a.width}</td><td>${a.clearance}</td><td><button data-delete-class="${i}">Delete</button></td></tr>`).join('')}</tbody></table></div>`);}
function compareDialog(){let changes=CB.comparison(p);dialog('Revision comparison',`<p class="helptext">${p.baseline?'Compared with '+esc(p.baseline.title)+' captured '+esc(p.baseline.at):'Capture a baseline in Review first.'}</p>${p.baseline&&!p.baseline.snapshot?'<p>Legacy baseline contains counts only. Capture a new baseline for object-level comparison.</p>':''}<ul>${changes.map(s=>`<li>${esc(s)}</li>`).join('')||'<li>No object-level differences recorded.</li>'}</ul>`);}
CBWorkbench.actions['board-apply']=applyBoardObject;
CBWorkbench.actions['silk-refs']=()=>{if(CBWorkbench.safeEdit(()=>{p.silk=p.silk.filter(s=>!s.autoRef);for(let c of p.components){let text=c.ref.toUpperCase();if([...text].some(x=>!CB.FONT[x]))continue;p.silk.push({id:CB.uid(),autoRef:c.id,kind:'text',layer:c.pcb.side,x:c.pcb.x-text.length*1.2/2,y:c.pcb.y-c.body[1]/2-3,text,size:1.4,width:.2,rotation:0,mirror:c.pcb.side==='B'});}},'Reference silkscreen generated; check for pad and edge conflicts.'))closeDialog();};
CBWorkbench.actions['rules-default']=()=>{let r=CB.fresh().rules;for(let k of ['minWidth','clearance','edge','annular','drill','mask','maskWeb','silk','silkLine'])$('#rule_'+k).value=r[k];$('#ruleSource').value='CIRCUITBENCH conservative workshop defaults; user to verify against chosen process.';};
CBWorkbench.actions['rules-jlc']=()=>{for(let[k,v]of Object.entries({minWidth:.25,clearance:.25,edge:.5,annular:.15,drill:.45,mask:.05,maskWeb:.15,silk:.2,silkLine:.15}))$('#rule_'+k).value=v;$('#ruleSource').value='JLCPCB two-layer FR-4 1 oz conservative example, reviewed 2026-10-04. Published trace/space minimum 0.10 mm; pad-hole spacing 0.45 mm. Other values include project margin. https://jlcpcb.com/capabilities/pcb-capabilities';};
CBWorkbench.actions['rules-apply']=()=>{CBWorkbench.safeEdit(()=>{for(let k of ['minWidth','clearance','edge','annular','drill','mask','maskWeb','silk','silkLine'])p.rules[k]=Number($('#rule_'+k).value);p.rulesSource=$('#ruleSource').value;},'Design rules saved.');};
CBWorkbench.actions['class-add']=()=>{let name=$('#className').value.trim(),nets=$('#classNets').value.split(',').map(x=>x.trim()).filter(Boolean),width=Number($('#classWidth').value),clearance=Number($('#classClearance').value);if(!name||!nets.length)return CBWorkbench.showFormError(Error('Enter a class name and at least one net.'));if(p.netClasses.some(c=>c.name===name||c.nets.some(n=>nets.includes(n))))return CBWorkbench.showFormError(Error('Class names must be unique and each net may belong to one class.'));if(CBWorkbench.safeEdit(()=>p.netClasses.push({name,nets,width,clearance}),'Net class added.'))rulesDialog();};
document.addEventListener('change',e=>{if(e.target.id==='boardTool')renderBoardForm(e.target.value);});
document.addEventListener('click',e=>{let b=e.target.closest('[data-delete-class]');if(b){CBWorkbench.safeEdit(()=>p.netClasses.splice(Number(b.dataset.deleteClass),1),'Net class removed.');rulesDialog();}});
