/* CIRCUITBENCH v1.8.1 — GPL-3.0-only */
(function(root){
'use strict';
const VERSION='1.8.1', clone=x=>JSON.parse(JSON.stringify(x)), uid=()=> 'id'+Math.random().toString(36).slice(2,12), round=x=>Math.round(x*1e6)/1e6;
const pad=(n,x,y,name=n,diameter=1.8,drill=.8,type='passive',mount='tht')=>({n:String(n),name:String(name),x,y,diameter,drill,type,mount,net:'',nc:false});
const defs=[
 {key:'resistor',name:'Resistor · axial',prefix:'R',value:'1k',body:[6.3,2.5],pads:[pad(1,-5.08,0),pad(2,5.08,0)]},
 {key:'capacitor',name:'Capacitor · ceramic',prefix:'C',value:'100nF',body:[5,3],pads:[pad(1,-2.54,0),pad(2,2.54,0)]},
 {key:'electrolytic',name:'Capacitor · polarized',prefix:'C',value:'10µF',body:[5,5],pads:[pad(1,-1.25,0,'+'),pad(2,1.25,0,'−')]},
 {key:'led',name:'LED · 5 mm',prefix:'D',value:'LED',body:[5,5],pads:[pad(1,-1.27,0,'Anode'),pad(2,1.27,0,'Cathode')]},
 {key:'diode',name:'Diode · axial',prefix:'D',value:'1N4148',body:[4,2],pads:[pad(1,-3.81,0,'Anode'),pad(2,3.81,0,'Cathode')]},
 {key:'header2',name:'Header · 1 × 2',prefix:'J',value:'Power',body:[3,5.08],pads:[pad(1,0,-1.27),pad(2,0,1.27)]},
 {key:'header3',name:'Header · 1 × 3',prefix:'J',value:'I/O',body:[3,7.62],pads:[pad(1,0,-2.54),pad(2,0,0),pad(3,0,2.54)]},
 {key:'header6',name:'Header · 1 × 6',prefix:'J',value:'Breakout',body:[3,15.24],pads:Array.from({length:6},(_,i)=>pad(i+1,0,(i-2.5)*2.54))},
 {key:'dip8',name:'IC · DIP-8',prefix:'U',value:'DIP-8',body:[6.3,10.2],pads:Array.from({length:8},(_,i)=>pad(i+1,i<4?-3.81:3.81,(i<4?i-1.5:5.5-i)*2.54))},
 {key:'dip14',name:'IC · DIP-14',prefix:'U',value:'DIP-14',body:[6.3,18],pads:Array.from({length:14},(_,i)=>pad(i+1,i<7?-3.81:3.81,(i<7?i-3:10-i)*2.54))},
 {key:'smd2',name:'SMD · 0805, round pads',prefix:'R',value:'10k',body:[2,1.25],pads:[pad(1,-1.1,0,'1',1.2,0,'passive','smd'),pad(2,1.1,0,'2',1.2,0,'passive','smd')]},
 {key:'custom',name:'Custom · terminal block',prefix:'X',value:'Custom part',body:[8,6],pads:[pad(1,-5,0),pad(2,5,0)]}
];
function fresh(){return {format:'circuitbench',schema:1,version:VERSION,title:'Untitled circuit',revision:'A',board:{width:60,height:40,thickness:1.6,color:'#153e35'},rules:{clearance:.25,edge:.5,minWidth:.25,annular:.15,mask:.05},components:[],tracks:[],vias:[],nets:['GND','+5V'],assumptions:'Two copper layers. Board dimensions and footprints must be checked against your actual parts and fabricator capabilities.',evidence:'',baseline:null};}
function component(p,key,x=30,y=20){let d=defs.find(d=>d.key===key)||defs[0],i=1;while(p.components.some(c=>c.ref===d.prefix+i))i++;return {id:uid(),kind:d.key,ref:d.prefix+i,value:d.value,mpn:'',body:clone(d.body),pads:clone(d.pads),pcb:{x,y,rotation:0,side:'F'},sch:{x:20+(p.components.length%4)*35,y:20+Math.floor(p.components.length/4)*35,rotation:0}};}
function sample(){let p=fresh();p.title='Hello, copper';p.nets=['+5V','GND','LED+'];let specs=[['header2',9,20,20,35,'5V IN',['+5V','GND']],['resistor',28,11,60,20,'330Ω',['+5V','LED+']],['led',47,20,100,35,'Green LED',['LED+','GND']],['capacitor',28,29,60,55,'100nF',['+5V','GND']],['header2',51,32,100,65,'Test points',['+5V','GND']]];for(let [k,x,y,sx,sy,v,nets]of specs){let c=component(p,k,x,y);c.sch.x=sx;c.sch.y=sy;c.value=v;c.pads.forEach((a,i)=>a.net=nets[i]);p.components.push(c);}let a=p.components[1],b=p.components[2];let ap=position(a,a.pads[1]),bp=position(b,b.pads[0]);p.tracks.push({id:uid(),net:'LED+',layer:'F',width:.6,points:[ap,{x:bp.x,y:ap.y},bp]});p.assumptions+=' Demo uses a 5 V source and a 330 Ω LED resistor; electrical behavior is not simulated.';return p;}
function rotate(x,y,deg){let a=deg*Math.PI/180;return {x:round(x*Math.cos(a)-y*Math.sin(a)),y:round(x*Math.sin(a)+y*Math.cos(a))};}
function schLocal(c,a){let i=c.pads.indexOf(a),n=c.pads.length;if(n===2)return {x:i?10:-10,y:0};let half=Math.ceil(n/2);return {x:i<half?-12:12,y:((i<half?i:n-1-i)-(half-1)/2)*5};}
function position(c,a,view='pcb'){let t=c[view],s=view==='pcb'?{x:a.x,y:a.y}:schLocal(c,a);let r=rotate(view==='pcb'&&t.side==='B'?-s.x:s.x,s.y,t.rotation);return {x:round(t.x+r.x),y:round(t.y+r.y)};}
function pads(p,view='pcb'){return p.components.flatMap(c=>c.pads.map(a=>({...a,...position(c,a,view),id:c.id+':'+a.n,component:c.id,ref:c.ref,layer:a.mount==='tht'?'both':c.pcb.side,label:c.ref+'.'+a.n})));}
function union(n){let parent=Array.from({length:n},(_,i)=>i);function find(i){while(parent[i]!==i){parent[i]=parent[parent[i]];i=parent[i];}return i;}return {find,join:(i,j)=>parent[find(i)]=find(j)};}
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function pointSegment(p,a,b){let l=(b.x-a.x)**2+(b.y-a.y)**2;if(!l)return dist(p,a);let t=Math.max(0,Math.min(1,((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/l));return dist(p,{x:a.x+t*(b.x-a.x),y:a.y+t*(b.y-a.y)});}
function segDistance(a,b,c,d){const cross=(p,q,r)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x);let ab1=cross(a,b,c),ab2=cross(a,b,d),cd1=cross(c,d,a),cd2=cross(c,d,b);if(ab1*ab2<0&&cd1*cd2<0)return 0;return Math.min(pointSegment(a,c,d),pointSegment(b,c,d),pointSegment(c,a,b),pointSegment(d,a,b));}
function copper(p){let q=pads(p).map(a=>({id:a.id,owner:a.component,label:a.label,net:a.net,key:a.net||'unconnected:'+a.id,layer:a.layer,a,b:a,r:a.diameter/2,pad:true}));p.vias.forEach(v=>q.push({id:v.id,owner:v.id,label:'Via',net:v.net,key:v.net,layer:'both',a:v,b:v,r:v.diameter/2,via:true}));p.tracks.forEach(t=>t.points.slice(1).forEach((b,i)=>q.push({id:t.id+':'+i,owner:t.id,label:'Track',net:t.net,key:t.net,layer:t.layer,a:t.points[i],b,r:t.width/2})));return q;}
const sameLayer=(a,b)=>a.layer==='both'||b.layer==='both'||a.layer===b.layer;
function topology(p){let items=copper(p),u=union(items.length);for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){let a=items[i],b=items[j];if(a.key===b.key&&sameLayer(a,b)&&segDistance(a.a,a.b,b.a,b.b)<=a.r+b.r+1e-7)u.join(i,j);}return {items,u};}
function connections(p,view='pcb'){let ps=pads(p,view).filter(a=>a.net),lines=[],top=view==='pcb'?topology(p):null;for(let net of p.nets){let group=ps.filter(a=>a.net===net),u=union(group.length),pairs=[];if(top)for(let i=0;i<group.length;i++)for(let j=i+1;j<group.length;j++){let ai=top.items.findIndex(a=>a.id===group[i].id),bi=top.items.findIndex(a=>a.id===group[j].id);if(top.u.find(ai)===top.u.find(bi))u.join(i,j);}for(let i=0;i<group.length;i++)for(let j=i+1;j<group.length;j++)pairs.push({i,j,d:dist(group[i],group[j])});pairs.sort((a,b)=>a.d-b.d);for(let pair of pairs)if(u.find(pair.i)!==u.find(pair.j)){u.join(pair.i,pair.j);lines.push({a:group[pair.i],b:group[pair.j],net});}}return lines;}
function mergeNet(p,a,b){if(a&&a===b)return a;let target=a||b;if(!target){let n=1;while(p.nets.includes('N'+n))n++;target='N'+n;p.nets.push(target);}if(a&&b&&a!==b){p.components.forEach(c=>c.pads.forEach(pad=>{if(pad.net===b)pad.net=a;}));[...p.tracks,...p.vias].forEach(x=>{if(x.net===b)x.net=a;});p.nets=p.nets.filter(n=>n!==b);}return target;}
function checks(p){let out=[],add=(severity,code,message,target,confidence='High')=>out.push({severity,code,message,target,confidence});let ps=pads(p),items=copper(p);
 if(!p.components.length)add('warning','EMPTY','No components placed.');
 for(let a of ps){if(!a.net&&!a.nc)add('warning','UNASSIGNED',a.label+' has no net. Assign a net or mark intentional NC.',a.component);if(a.nc&&a.net)add('error','NC_CONFLICT',a.label+' is marked NC but connected.',a.component);if(a.mount==='tht'&&(a.diameter-a.drill)/2<p.rules.annular-1e-8)add('error','ANNULAR',a.label+' annular ring is smaller than the rule.',a.component);}
 for(let net of p.nets){let pins=ps.filter(a=>a.net===net);if(pins.length===1)add('warning','SINGLE_PIN',net+' contains only one pin.',pins[0].component);if(pins.filter(a=>a.type==='output').length>1)add('error','OUTPUT_CONFLICT',net+' joins multiple output pins.');if(pins.some(a=>a.type==='input')&&!pins.some(a=>['output','power_out','bidirectional'].includes(a.type)))add('warning','NO_DRIVER',net+' has input pins without a declared driver.',undefined,'Medium');}
 for(let net of p.nets){let pins=ps.filter(a=>a.net===net);if(pins.some(a=>a.type==='power_in')&&!pins.some(a=>a.type==='power_out'))add('warning','NO_POWER_DRIVER',net+' has power inputs without a declared power source.',undefined,'Medium');}
 const top=topology(p),padRoots=new Set(top.items.map((a,i)=>a.pad?top.u.find(i):null).filter(x=>x!==null));let floating=new Set();top.items.forEach((a,i)=>{if(!a.pad&&!padRoots.has(top.u.find(i))&&!floating.has(top.u.find(i))){floating.add(top.u.find(i));add('warning','FLOATING_COPPER','Copper island on '+a.net+' is not connected to any component pad.',a.owner);}});
 for(let l of connections(p))add('error','UNROUTED',l.net+': '+l.a.label+' → '+l.b.label+' is not physically connected.',l.a.component);
 for(let t of p.tracks)if(t.width<p.rules.minWidth-1e-8)add('error','WIDTH','Track on '+t.net+' is narrower than the minimum.',t.id);
 for(let v of p.vias)if((v.diameter-v.drill)/2<p.rules.annular-1e-8)add('error','ANNULAR','Via on '+v.net+' has insufficient annular ring.',v.id);
 let seen=new Set();for(let a of items){if([a.a,a.b].some(pt=>Math.min(pt.x,pt.y,p.board.width-pt.x,p.board.height-pt.y)-a.r<p.rules.edge-1e-8)){let key='edge'+a.owner;if(!seen.has(key)){add('error','EDGE',a.label+' copper is too close to or outside the board edge.',a.owner);seen.add(key);}}}
 for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){let a=items[i],b=items[j];if(a.key===b.key||!sameLayer(a,b))continue;let gap=segDistance(a.a,a.b,b.a,b.b)-a.r-b.r;if(gap<p.rules.clearance-1e-8){let code=gap<=0?'SHORT':'CLEARANCE',key=code+[a.owner,b.owner].sort().join('|');if(!seen.has(key)){add('error',code,a.label+' ('+(a.net||'no net')+') and '+b.label+' ('+(b.net||'no net')+'): '+(gap<=0?'copper overlaps.':gap.toFixed(3)+' mm clearance.'),a.owner);seen.add(key);}}}
 return out;
}
function validate(data){const fail=m=>{throw Error('Invalid project: '+m);},num=(n,min,max,label)=>{if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max)fail(label);},str=(s,max,label)=>{if(typeof s!=='string'||s.length>max)fail(label);};if(!data||data.format!=='circuitbench'||data.schema!==1)fail('expected CIRCUITBENCH schema 1.');let p=clone(data);str(p.title,160,'title');str(p.revision,40,'revision');for(let [k,min,max]of [['width',5,500],['height',5,500],['thickness',.1,10]])num(p.board?.[k],min,max,'board '+k);for(let k of ['clearance','edge','minWidth','annular','mask'])num(p.rules?.[k],0,5,'rule '+k);if(p.rules.minWidth<.05)fail('minimum width');if(!Array.isArray(p.nets)||p.nets.length>256)fail('net count');p.nets.forEach(n=>{str(n,60,'net');if(!n)fail('empty net');});if(new Set(p.nets).size!==p.nets.length)fail('duplicate nets');if(!Array.isArray(p.components)||p.components.length>150)fail('maximum 150 components');if(!Array.isArray(p.tracks)||p.tracks.length>500||!Array.isArray(p.vias)||p.vias.length>200)fail('copper count');let ids=new Set(),refs=new Set(),total=0;function id(s){str(s,100,'id');if(!/^[a-zA-Z0-9_-]+$/.test(s)||ids.has(s))fail('duplicate or malformed id');ids.add(s);}function net(n){str(n,60,'net');if(n&&!p.nets.includes(n))fail('undefined net '+n);}for(let c of p.components){id(c.id);str(c.ref,30,'reference');if(!c.ref||refs.has(c.ref))fail('duplicate or empty reference');refs.add(c.ref);for(let k of ['value','mpn','kind'])str(c[k],200,k);for(let v of ['pcb','sch']){for(let k of ['x','y'])num(c[v]?.[k],-1000,1000,'position');num(c[v]?.rotation,0,359.999,'rotation');}if(!['F','B'].includes(c.pcb.side))fail('side');if(!Array.isArray(c.body)||c.body.length!==2)fail('body');c.body.forEach(x=>num(x,.1,100,'body size'));if(!Array.isArray(c.pads)||!c.pads.length&&!c.mountingHoles?.length||c.pads.length>1024)fail('pad count');total+=c.pads.length;let ns=new Set();for(let a of c.pads){str(a.n,10,'pin number');if(!/^[a-zA-Z0-9_-]+$/.test(a.n)||ns.has(a.n))fail('duplicate pin');ns.add(a.n);str(a.name,60,'pin name');for(let k of ['x','y'])num(a[k],-100,100,'pad position');num(a.diameter,.1,30,'pad diameter');num(a.drill,0,20,'drill');if(!['tht','smd'].includes(a.mount)||a.mount==='tht'&&(a.drill<=0||a.drill>=a.diameter)||a.mount==='smd'&&a.drill!==0)fail('pad drill/mount');if(!['passive','input','output','power_in','power_out','bidirectional'].includes(a.type))fail('pin type');if(typeof a.nc!=='boolean')fail('NC flag');net(a.net);}}
 let segments=0;for(let t of p.tracks){id(t.id);net(t.net);if(!t.net||!['F','B'].includes(t.layer))fail('track net/layer');num(t.width,.05,10,'track width');if(!Array.isArray(t.points)||t.points.length<2||t.points.length>200)fail('track points');segments+=t.points.length-1;for(let q of t.points){num(q.x,-1000,1000,'track x');num(q.y,-1000,1000,'track y');}}if(segments+total+p.vias.length>2000)fail('maximum 2000 copper primitives');for(let v of p.vias){id(v.id);net(v.net);if(!v.net)fail('via net');for(let k of ['x','y'])num(v[k],-1000,1000,'via position');num(v.diameter,.2,10,'via diameter');num(v.drill,.1,v.diameter-.01,'via drill');}for(let k of ['assumptions','evidence'])str(p[k],20000,k);if(p.baseline!==null){if(!p.baseline||typeof p.baseline!=='object')fail('baseline');str(p.baseline.at,100,'baseline date');str(p.baseline.title,160,'baseline title');for(let k of ['components','tracks','vias','errors','warnings'])num(p.baseline[k],0,100000,k);}return p;
}
function csv(rows){return rows.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');}
function bom(p){return csv([['Reference','Value','MPN','Footprint','Side','X mm','Y mm','Rotation'],...p.components.map(c=>[c.ref,c.value,c.mpn,c.kind,c.pcb.side,c.pcb.x,c.pcb.y,c.pcb.rotation])]);}
function netlist(p){return csv([['Net','Reference','Pin','Pin name','Electrical type'],...p.components.flatMap(c=>c.pads.map(a=>[a.net,c.ref,a.n,a.name,a.type]))]);}
function gerber(p,layer,kind='copper'){let aps=[],ops=[],ap=d=>{let key=d.toFixed(6);if(!aps.includes(key))aps.push(key);return aps.indexOf(key)+10;};const xy=q=>'X'+Math.round(q.x*1e6)+'Y'+Math.round((p.board.height-q.y)*1e6);function line(a,b,w){ops.push('D'+ap(w)+'*',xy(a)+'D02*',xy(b)+'D01*');}function flash(a,d){ops.push('D'+ap(d)+'*',xy(a)+'D03*');}if(kind==='copper'){pads(p).filter(a=>a.layer==='both'||a.layer===layer).forEach(a=>flash(a,a.diameter));p.vias.forEach(v=>flash(v,v.diameter));p.tracks.filter(t=>t.layer===layer).forEach(t=>t.points.slice(1).forEach((b,i)=>line(t.points[i],b,t.width)));}else if(kind==='mask'){pads(p).filter(a=>a.layer==='both'||a.layer===layer).forEach(a=>flash(a,a.diameter+2*p.rules.mask));p.vias.forEach(v=>flash(v,v.diameter+2*p.rules.mask));}else if(kind==='outline'){let q=[{x:0,y:0},{x:p.board.width,y:0},{x:p.board.width,y:p.board.height},{x:0,y:p.board.height},{x:0,y:0}];q.slice(1).forEach((b,i)=>line(q[i],b,.05));}let fn=kind==='copper'?`Copper,L${layer==='F'?1:2},${layer==='F'?'Top':'Bot'}`:kind==='mask'?`Soldermask,${layer==='F'?'Top':'Bot'}`:'Profile,NP';return ['G04 CIRCUITBENCH '+VERSION+'*','%TF.GenerationSoftware,GreenShoeGarage,CIRCUITBENCH,'+VERSION+'*%','%TF.FileFunction,'+fn+'*%','%FSLAX46Y46*%','%MOMM*%','%LPD*%',...aps.map((d,i)=>'%ADD'+(i+10)+'C,'+d+'*%'),'G01*',...ops,'M02*'].join('\n');}
function drill(p){let holes=[...pads(p).filter(a=>a.mount==='tht'),...p.vias],ds=[...new Set(holes.map(a=>a.drill.toFixed(3)))].sort();return ['M48','; CIRCUITBENCH '+VERSION+' plated through holes','METRIC',...ds.map((d,i)=>'T'+(i+1).toString().padStart(2,'0')+'C'+d),'G90','%','G05',...ds.flatMap((d,i)=>['T'+(i+1).toString().padStart(2,'0'),...holes.filter(a=>a.drill.toFixed(3)===d).map(a=>'X'+a.x.toFixed(4)+'Y'+(p.board.height-a.y).toFixed(4))]),'M30'].join('\n');}
function fabrication(p){let f=checks(p);return {'F_Cu.gbr':gerber(p,'F'),'B_Cu.gbr':gerber(p,'B'),'F_Mask.gbr':gerber(p,'F','mask'),'B_Mask.gbr':gerber(p,'B','mask'),'Edge_Cuts.gbr':gerber(p,'F','outline'),'Plated.drl':drill(p),'BOM.csv':bom(p),'Netlist.csv':netlist(p),'project.circuitbench.json':JSON.stringify(p,null,2),'checks.json':JSON.stringify(f,null,2),'FABRICATION-README.txt':`CIRCUITBENCH ${VERSION}\n${p.title} — revision ${p.revision}\nBoard: ${p.board.width} x ${p.board.height} x ${p.board.thickness} mm; two copper layers.\n${f.filter(x=>x.severity==='error').length} errors; ${f.filter(x=>x.severity==='warning').length} warnings at export.\nGerber: X2, millimeters, 4.6 format. Drill: decimal millimeters, plated through holes.\nOrigin: lower left; both layers viewed from top. Do not mirror the bottom layer.\nCircular pads only. No paste, silkscreen, zones, cutouts or nonplated holes in this release. Body outlines and labels are assembly guides, not manufacturing layers.\nReview all files in an independent Gerber viewer and use your fabricator's DFM checks before ordering.\nBasic checks are not a fabrication certification.\nAssumptions: ${p.assumptions}\nEvidence: ${p.evidence}\n`};}
function zip(files){let encoder=new TextEncoder(),locals=[],central=[],offset=0;const cat=arr=>{let out=new Uint8Array(arr.reduce((s,a)=>s+a.length,0)),i=0;arr.forEach(a=>{out.set(a,i);i+=a.length;});return out;};function crc(a){let c=0xffffffff;for(let b of a){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}function bytes(n){let a=new Uint8Array(n);return [a,new DataView(a.buffer)];}for(let [name,str]of Object.entries(files)){let n=encoder.encode(name),b=str instanceof Uint8Array?str:str instanceof ArrayBuffer?new Uint8Array(str):encoder.encode(str),check=crc(b),[h,v]=bytes(30);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,33,true);v.setUint32(14,check,true);v.setUint32(18,b.length,true);v.setUint32(22,b.length,true);v.setUint16(26,n.length,true);locals.push(h,n,b);let [c,w]=bytes(46);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint16(14,33,true);w.setUint32(16,check,true);w.setUint32(20,b.length,true);w.setUint32(24,b.length,true);w.setUint16(28,n.length,true);w.setUint32(42,offset,true);central.push(c,n);offset+=30+n.length+b.length;}let cd=cat(central),[end,e]=bytes(22),count=Object.keys(files).length;e.setUint32(0,0x06054b50,true);e.setUint16(8,count,true);e.setUint16(10,count,true);e.setUint32(12,cd.length,true);e.setUint32(16,offset,true);return cat([...locals,cd,end]);}
const API={VERSION,clone,uid,round,defs,pad,fresh,sample,component,rotate,schLocal,position,pads,dist,pointSegment,segDistance,copper,topology,connections,mergeNet,checks,validate,bom,netlist,gerber,drill,fabrication,zip};root.CB=API;if(typeof module!=='undefined')module.exports=API;
})(typeof globalThis!=='undefined'?globalThis:this);
