/* CIRCUITBENCH enclosure workflow. GPL-3.0-only. */
(function(){'use strict';
const W=CBWorkbench,fmt=n=>CB.round(n).toLocaleString(undefined,{maximumFractionDigits:2}),B=(label,action,cls='')=>`<button type="button" data-enc="${action}" class="${cls}">${label}</button>`;
let state=null;
const input=(label,key,value,min,max,step=.1)=>`<label>${label}<input type="number" data-enc-setting="${key}" value="${value}" min="${min}" max="${max}" step="${step}"></label>`;
const settings=()=>p.enclosure,chosen=()=>settings().openings.find(o=>o.id===state?.opening);
function open(){
 if(!p.enclosure&&!W.safeEdit(()=>p.enclosure=CB.enclosureDefaults(p),'Enclosure settings created from this board.'))return;
 dispose();dialog('Enclosure generator',`<div class="encHeading"><p>Fit the board → raise it on standoffs → add openings → print.</p><span id="encSave" role="status">Saved with project</span></div><div class="enclosureGrid"><section class="enclosureVisual"><div class="buttonrow">${B('Isometric','iso')}${B('Top','top')}${B('Front','front-view')}${B('Side','side-view')}${B('Save image','png')}</div><div id="enclosureViewport"></div><div class="encViewControls"><label class="inlinecheck"><input id="encGhost" type="checkbox" checked> See through case</label><label class="inlinecheck"><input id="encShowBoard" type="checkbox" checked> PCB & parts</label><label class="inlinecheck"><input id="encShowLid" type="checkbox" checked> Lid</label><label>Lid lift <input id="encExplode" type="range" min="0" max="60" step="1" value="15"></label></div><div id="encDimensions" class="encDimensions"></div><p id="encBuildState" role="status">Generating solid geometry…</p><details id="encFindings"><summary id="encFindingsSummary">Fit checks</summary><div id="encIssues"></div></details></section><section class="enclosureControls"><nav class="encTabs" aria-label="Enclosure controls">${['Case','Standoffs','Openings','Parts'].map(name=>B(name,'tab-'+name.toLowerCase())).join('')}</nav><div id="encPanel"></div><p id="extraError" role="alert"></p></section></div><div class="encFooter"><div class="buttonrow">${B('Download print ZIP','zip','primary')}${B('Base STL','base-stl')}${B('Lid STL','lid-stl')}${B('Print fit report','report')}</div><div class="buttonrow">${B('Undo edit','undo')}${B('Done','done')}</div></div>`);
 $('#dialog').classList.add('enclosureDialog');state={tab:'case',face:'front',opening:settings().openings[0]?.id||null,request:0,result:null,worker:null,viewer:null,invalid:false,pending:true,plan:null};
 try{state.viewer=CB3D.createEnclosure($('#enclosureViewport'),CB);}catch(error){$('#enclosureViewport').innerHTML='<p>3D needs WebGL. The face editor, dimensions and STL exports remain available.</p>';}
 const url=URL.createObjectURL(new Blob([CB_ENCLOSURE_WORKER_SOURCE],{type:'application/javascript'}));
 try{state.worker=new Worker(url);state.worker.onmessage=receive;state.worker.onerror=()=>failed('The local geometry worker stopped. Close and reopen the enclosure tool.');}catch(error){failed(error.message);}finally{URL.revokeObjectURL(url);}
 renderPanel();generate();
}
function dispose(){if(!state)return;state.worker?.terminate();state.viewer?.dispose();state=null;}
$('#dialog').addEventListener('close',()=>{dispose();$('#dialog').classList.remove('enclosureDialog');});
function error(message){$('#extraError').textContent=message;}
function failed(message){if(!state)return;state.pending=false;state.result=null;$('#encBuildState').textContent=message;updateExports();}
function issues(){return [...(state?.plan?.issues||[]),...(state?.result&&['base','lid'].some(k=>state.result[k].parts!==1)?[{severity:'error',code:'DISCONNECTED',message:'An opening splits the base or lid into disconnected pieces. Move or shrink it.',confidence:'High'}]:[])];}
function updateExports(){let blocked=!state||state.pending||state.invalid||!state.result||issues().some(i=>i.severity==='error');for(let a of ['zip','base-stl','lid-stl'])$(`[data-enc="${a}"]`).disabled=blocked;$('[data-enc=undo]').disabled=!history.length;}
function generate(){if(!state)return;try{state.plan=CB.enclosurePlan(p);state.pending=true;state.result=null;state.invalid=false;error('');$('#encSave').textContent='Saved with project';let q=state.plan;$('#encDimensions').innerHTML=`<strong>${fmt(q.width)} × ${fmt(q.depth)} × ${fmt(q.totalHeight)} mm</strong><span>Outside W × D × H · PCB underside ${fmt(q.config.standoffHeight)} mm above floor</span><span>${q.mounts.length} standoffs · ${q.config.openings.length} openings · lift-off lid</span>`;renderFindings();$('#encBuildState').textContent='Generating solid geometry…';updateExports();if(state.worker)state.worker.postMessage({id:++state.request,plan:q});else failed('Geometry worker is unavailable in this browser.');}catch(e){state.invalid=true;error(e.message);updateExports();}}
function receive(event){if(!state||event.data.id!==state.request)return;if(event.data.error)return failed(event.data.error);state.result=event.data.result;state.pending=false;try{state.viewer?.update(state.result,state.plan);}catch(e){state.viewer?.dispose();state.viewer=null;$('#enclosureViewport').innerHTML='<p>3D preview unavailable. Solid geometry is ready for export.</p>';}$('#encBuildState').textContent='Ready · '+(state.result.base.indices.length/3+state.result.lid.indices.length/3).toLocaleString()+' triangles · millimeter STL';renderFindings();updateExports();}
function renderFindings(){let list=issues(),errors=list.filter(a=>a.severity==='error').length;$('#encFindingsSummary').textContent='Fit checks · '+errors+' errors · '+(list.length-errors)+' notes';$('#encFindings').open=errors>0;$('#encIssues').innerHTML=list.map(a=>`<p class="encIssue"><strong>${a.severity.toUpperCase()}</strong> ${esc(a.message)} <small>${esc(a.confidence)} confidence</small></p>`).join('')||'<p>No conflicts found in the modeled geometry.</p>';}
function change(fn,message='Enclosure updated.'){if(!state)return;let before=JSON.stringify(p);if(W.safeEdit(fn,message)){state.invalid=false;generate();renderPanel();}else{state.invalid=true;$('#encSave').textContent='Invalid input · not saved';updateExports();}return before!==JSON.stringify(p);}
function renderPanel(){if(!state)return;$$('.encTabs button').forEach(b=>{let active=b.dataset.enc==='tab-'+state.tab;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});const e=settings(),q=CB.enclosurePlan(p);let html='';
 if(state.tab==='case')html=`<h3>Board-sized case</h3><p class="helptext">A rectangular shell around the board and rotated component bodies. Dimensions update automatically.</p><div class="row2">${input('Side clearance · mm','clearance',e.clearance,.5,50)}${input('Wall thickness · mm','wall',e.wall,.8,10)}${input('Floor thickness · mm','floor',e.floor,.8,10)}${input('Lid thickness · mm','lid',e.lid,.8,10)}${input('PCB lift / standoff · mm','standoffHeight',e.standoffHeight,1,100)}${input('Space above parts · mm','headroom',e.headroom,.5,50)}</div><label>Inside height<select data-enc-setting="heightMode">${options([['auto','Automatic from component heights'],['manual','Set manually']],e.heightMode)}</select></label>${e.heightMode==='manual'?input('Inside height above floor · mm','insideHeight',e.insideHeight,5,200):`<p class="encValue">${fmt(q.insideHeight)} mm inside · tallest top part ${fmt(q.topHeight)} mm</p>`}<details><summary>Lid fit and underside allowance</summary><div class="row2">${input('Locating lip depth · mm','lipDepth',e.lipDepth,0,10)}${input('Lip wall · mm','lipWall',e.lipWall,.8,5)}${input('Lid clearance per side · mm','fit',e.fit,.05,2,.05)}${input('Under-board clearance · mm','underClearance',e.underClearance,0,20)}${input('Through-hole lead allowance · mm','leadClearance',e.leadClearance,0,20)}</div></details><p class="helptext">The lid lifts off; its locating lip has adjustable clearance. Print a fit sample for your printer. Part heights are editable in Parts.</p>`;
 if(state.tab==='standoffs'){let candidates=CB.enclosureCandidates(p);html=`<h3>Raise and support the PCB</h3><div class="row2">${input('Standoff height · mm','standoffHeight',e.standoffHeight,1,100)}${input('Default outer diameter · mm','standoffDiameter',e.standoffDiameter,2,30)}${input('Default bore diameter · mm','bore',e.bore,0,20)}${input('Blind bore depth · mm','boreDepth',e.boreDepth,.5,100)}</div><label>Bore style<select data-enc-setting="boreMode">${options([['blind','Blind pilot hole · floor stays closed'],['through','Through hole · opens through floor'],['solid','Solid support · no screw hole']],e.boreMode)}</select></label><p class="helptext">All supports share one PCB height. Minimum lift from stored bottom parts / leads: ${fmt(q.below+e.underClearance)} mm. Blind bores stop at least 0.4 mm above the inside floor. Unthreaded holes; select dimensions for your fastener.</p><div class="buttonrow">${B('Use recommended lift','recommended')}${B('Sync PCB holes','sync')}${B('+ Manual support','add-mount')}</div>${e.mounts.length?`<div class="encMountList">${e.mounts.map((m,i)=>{let h=candidates.find(a=>a.id===m.anchor),x=h?.x??m.x,y=h?.y??m.y;return `<fieldset class="encMount"><legend><label class="inlinecheck"><input type="checkbox" data-enc-mount="${m.id}" data-key="enabled" ${m.enabled?'checked':''}> ${esc(m.anchor?(h?h.name+' '+(i+1):'Missing PCB hole'):'Manual support '+(i+1))}</label></legend><small>${fmt(x)}, ${fmt(y)} mm on PCB${h?' · Ø'+fmt(h.drill)+' mm':''}</small>${!m.anchor?`<div class="row2">${mountInput(m,'X on PCB · mm','x',m.x)}${mountInput(m,'Y on PCB · mm','y',m.y)}</div>`:''}<div class="row2">${mountInput(m,'Outer Ø override · mm','diameter',m.diameter)}${mountInput(m,'Bore Ø override · mm','bore',m.bore)}</div><button data-enc-remove-mount="${m.id}" class="textbutton">Remove support</button></fieldset>`;}).join('')}</div>`:'<p class="notice">No mechanical holes found. Add a mounting hole in Board tools, then Sync PCB holes, or add a manual support.</p>'}<p class="helptext">Linked supports follow their PCB holes. Small mechanical holes are initially unchecked. Empty overrides use the defaults; linked default bores are limited to 0.2 mm below the PCB-hole diameter.</p>`;}
 if(state.tab==='openings'){let o=chosen();if(o)state.face=o.face;let dims=faceSize(state.face,q);html=`<h3>Openings / punchouts</h3><label>Face<select id="encFace">${options([['front','Front wall · PCB Y minimum'],['back','Back wall · PCB Y maximum'],['left','Left wall · PCB X minimum'],['right','Right wall · PCB X maximum'],['lid','Lid'],['floor','Floor']],state.face)}</select></label><div class="buttonrow">${B('+ Round','add-circle')}${B('+ Rectangle','add-rect')}${B('+ Slot','add-slot')}</div><svg id="encFaceEditor" role="img" tabindex="0" aria-label="Opening layout. Select an opening and drag it or use the numeric fields."></svg><p class="helptext">${state.face==='lid'||state.face==='floor'?'Top-view coordinates from the outer left/front corner.':'U runs along the wall; V is height above the inside floor.'} Click to move the selected opening; arrow keys move 0.5 mm.</p><label>Opening<select id="encOpening">${options([['','Choose an opening'],...e.openings.filter(a=>a.face===state.face).map(a=>[a.id,a.name])],o?.id||'')}</select></label>${o?`<label>Name<input data-enc-opening="name" maxlength="100" value="${esc(o.name)}"></label><div class="row2">${openingInput(o,o.shape==='circle'?'Diameter · mm':'Width · mm','width')}${o.shape==='circle'?'':openingInput(o,'Height · mm','height')}${openingInput(o,'Center U · mm','u')}${openingInput(o,'Center V · mm','v')}</div>${p.components.length?`<label>Center on component<select id="encAlignPart">${options([['','Choose part…'],...p.components.map(c=>[c.id,c.ref+' · '+c.value])],'')}</select></label>`:''}<div class="buttonrow">${B('Duplicate','duplicate-opening')}${B('Delete opening','delete-opening','danger')}</div>`:'<p class="notice">Choose a shape above to add a cut-through opening.</p>'}<p class="helptext">Face area: ${fmt(dims.w)} × ${fmt(dims.h)} mm. Openings cut completely through the selected wall, floor or lid.</p>`;}
 if(state.tab==='parts')html=`<h3>Component heights</h3><p class="helptext">Height is measured away from the PCB surface on the component’s side. These values also update the board’s 3D assembly.</p>${p.components.length?`<div class="tablewrap"><table><thead><tr><th>Part</th><th>Side</th><th>Height mm</th></tr></thead><tbody>${p.components.map(c=>`<tr><td><strong>${esc(c.ref)}</strong><br><small>${esc(c.value)}</small></td><td>${c.pcb.side==='F'?'Top':'Bottom'}</td><td><input type="number" min=".1" max="100" step=".1" data-enc-height="${c.id}" aria-label="${esc(c.ref)} height in millimeters" value="${c.height}"></td></tr>`).join('')}</tbody></table></div>`:'<p class="notice">This PCB has no components. The enclosure still uses its outline and mounting holes.</p>'}<p class="helptext">Library body heights are estimates. Verify actual packages and protruding leads. Bodies show dimensioned envelopes, not connector mating or STEP geometry.</p>`;
 $('#encPanel').innerHTML=html;if(state.tab==='openings'){drawFace();bindFace();}
}
function mountInput(m,label,key,value){return `<label>${label}<input type="number" data-enc-mount="${m.id}" data-key="${key}" value="${value??''}" placeholder="Default" step=".1"></label>`;}
function openingInput(o,label,key){return `<label>${label}<input type="number" data-enc-opening="${key}" value="${o[key]}" step=".5"></label>`;}
function faceSize(face,q=state.plan){return {w:['left','right'].includes(face)?q.depth:q.width,h:['lid','floor'].includes(face)?q.depth:q.insideHeight,flat:['lid','floor'].includes(face)};}
function drawFace(draft){let svg=$('#encFaceEditor');if(!svg)return;let q=state.plan||CB.enclosurePlan(p),dim=faceSize(state.face,q),margin=3,scale=Math.max(dim.w,dim.h)/140;svg.setAttribute('viewBox',`${-margin} ${-margin} ${dim.w+2*margin} ${dim.h+2*margin}`);let out=`<rect x="0" y="0" width="${dim.w}" height="${dim.h}" fill="var(--field)" stroke="var(--muted)" stroke-width="${scale}"/>`;if(!dim.flat){let y=dim.h-q.config.standoffHeight;out+=`<path d="M0 ${y}H${dim.w}" stroke="#74b398" stroke-width="${scale}" stroke-dasharray="2 1" pointer-events="none"/>`;}for(let original of settings().openings.filter(o=>o.face===state.face)){let o=draft?.id===original.id?draft:original,cy=dim.flat?o.v:dim.h-o.v,x=o.u-o.width/2,y=cy-o.height/2;out+=`<rect x="${x}" y="${y}" width="${o.width}" height="${o.height}" rx="${o.shape==='rect'?0:Math.min(o.width,o.height)/2}" fill="${o.id===state.opening?'#dbaf62':'#668ea0'}" stroke="var(--ink)" stroke-width="${scale*.65}" data-enc-pick="${o.id}" style="cursor:move"><title>${esc(o.name)}</title></rect>`;}svg.innerHTML=out;}
function bindFace(){let svg=$('#encFaceEditor'),dragging=null;const pos=e=>{let xy=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse()),dims=faceSize(state.face);return {u:Math.round(xy.x*2)/2,v:Math.round((dims.flat?xy.y:dims.h-xy.y)*2)/2};};svg.addEventListener('pointerdown',e=>{if(e.button!==0)return;let id=e.target.closest('[data-enc-pick]')?.dataset.encPick;if(id)state.opening=id;let o=chosen();if(!o)return;e.preventDefault();svg.setPointerCapture(e.pointerId);svg.focus();let at=pos(e);dragging={o:CB.clone(o),start:at,initial:{u:o.u,v:o.v},offset:!!id};if(!id){dragging.o.u=at.u;dragging.o.v=at.v;}drawFace(dragging.o);});svg.addEventListener('pointermove',e=>{if(!dragging)return;let at=pos(e);dragging.o.u=dragging.offset?dragging.initial.u+at.u-dragging.start.u:at.u;dragging.o.v=dragging.offset?dragging.initial.v+at.v-dragging.start.v:at.v;drawFace(dragging.o);});svg.addEventListener('pointerup',()=>{if(!dragging)return;let o=dragging.o;dragging=null;change(()=>Object.assign(chosen(),{u:o.u,v:o.v}),'Opening moved.');});svg.addEventListener('pointercancel',()=>{dragging=null;drawFace();});svg.addEventListener('keydown',e=>{if(!e.key.startsWith('Arrow')||!chosen())return;e.preventDefault();let delta=e.shiftKey?5:.5;change(()=>{let o=chosen();o.u+=e.key==='ArrowLeft'?-delta:e.key==='ArrowRight'?delta:0;o.v+=(faceSize(state.face).flat?1:-1)*(e.key==='ArrowUp'?-delta:e.key==='ArrowDown'?delta:0);},'Opening nudged.');$('#encFaceEditor').focus();});}
function addOpening(shape){let dims=faceSize(state.face),diameter=Math.min(8,dims.w/4,dims.h/3),width=shape==='circle'?diameter:Math.min(shape==='slot'?12:10,dims.w/3),height=shape==='circle'?diameter:Math.min(shape==='slot'?4:6,dims.h/3);let o={id:CB.uid(),name:(shape==='circle'?'Round':shape==='rect'?'Rectangle':'Slot')+' '+(settings().openings.length+1),face:state.face,shape,u:CB.round(dims.w/2),v:CB.round(dims.h/2),width,height};state.opening=o.id;change(()=>settings().openings.push(o),'Opening added.');}
function reportText(){const q=state.plan,e=q.config;return `CIRCUITBENCH ${CB.VERSION} enclosure\nProject: ${p.title} / ${p.revision}\nUnits: millimeters\nOuter dimensions: ${fmt(q.width)} x ${fmt(q.depth)} x ${fmt(q.totalHeight)}\nPCB thickness: ${p.board.thickness}; lift above inside floor: ${e.standoffHeight}\nWall / floor / lid: ${e.wall} / ${e.floor} / ${e.lid}\nInside height: ${fmt(q.insideHeight)}; top clearance: ${e.headroom}\nLocating lip depth / wall / per-side fit clearance: ${e.lipDepth} / ${e.lipWall} / ${e.fit}\nSTL origin: outer front-left-bottom corner of each print part. Both parts are already oriented flat on Z=0. Lid prints with its lip upward, and is flipped for assembly.\nStandoffs are fused into the base; bore style: ${e.boreMode}. Blind bores leave at least 0.4 mm above the inside floor. Holes are unthreaded.\n\nSTANDOFFS\n${q.mounts.map(m=>`${m.name}: PCB (${fmt(m.boardX)}, ${fmt(m.boardY)}); case (${fmt(m.x)}, ${fmt(m.y)}); outer diameter ${m.diameter}; bore ${m.bore}`).join('\n')}\n\nOPENINGS\n${e.openings.map(o=>`${o.name}: ${o.face}, ${o.shape}, ${o.width} x ${o.height}; center U=${o.u}, V=${o.v}`).join('\n')}\nWall U follows board X on front/back and board Y on left/right. Wall V is above the inside floor. Lid/floor U,V use the outer top-view origin.\n\nFIT FINDINGS\n${issues().map(i=>`${i.severity.toUpperCase()} [${i.confidence} confidence] ${i.message}`).join('\n')||'No conflicts found.'}\n\nASSUMPTIONS\nRectangular enclosure around PCB and body envelopes. Stored component heights and user clearances. Lift-off lid without latch or seal. No threaded inserts, screw heads or connector mating space are modeled.\n${p.assumptions||''}\n\nEVIDENCE\nSoftware mesh checks only; this enclosure has not been physically printed or fitted. Verify dimensions and printer tolerance in a slicer, then print a fit sample.\n${p.evidence||''}\n`;}
function exportPart(which){if(!state.result||state.pending||state.invalid||issues().some(i=>i.severity==='error'))return;download(slug()+'-enclosure-'+which+'.stl',CBEnclosureSolid.stl(state.result[which]),'model/stl');}
function exportZip(){if(!state.result||state.pending||state.invalid||issues().some(i=>i.severity==='error'))return;let files={'enclosure-base.stl':CBEnclosureSolid.stl(state.result.base),'enclosure-lid.stl':CBEnclosureSolid.stl(state.result.lid),'project.circuitbench.json':JSON.stringify(p,null,2),'ENCLOSURE-README.txt':reportText(),'enclosure-dimensions.json':JSON.stringify({units:'mm',version:CB.VERSION,width:state.plan.width,depth:state.plan.depth,height:state.plan.totalHeight,pcbOrigin:state.plan.origin,pcbBottom:state.plan.pcbBottom,settings:settings(),mounts:state.plan.mounts,issues:issues()},null,2)};download(slug()+'-enclosure.zip',CB.zip(files),'application/zip');}
function printReport(){let win=window.open('','_blank');if(!win)return error('Allow a report window to print or save PDF.');win.document.write(`<!doctype html><html><head><title>Enclosure fit report</title><style>body{font:12px Arial;color:#163e32;margin:30px}h1{font-size:24px}pre{white-space:pre-wrap;font:12px Arial;line-height:1.6}img{max-width:100%;height:240px;object-fit:contain}@media print{button{display:none}}</style></head><body><h1>Enclosure fit report</h1>${state.viewer?`<img alt="Enclosure preview" src="${state.viewer.png()}">`:''}<pre>${esc(reportText())}</pre><button onclick="window.print()">Print / save PDF</button></body></html>`);win.document.close();}
document.addEventListener('click',e=>{let key=e.target.closest('[data-enc]')?.dataset.enc;if(key==='open')return open();if(!state||!key)return;if(key.startsWith('tab-')){state.tab=key.slice(4);renderPanel();return;}const actions={done:closeDialog,iso:()=>state.viewer?.view('iso'),top:()=>state.viewer?.view('top'),'front-view':()=>state.viewer?.view('front'),'side-view':()=>state.viewer?.view('side'),png:()=>{if(!state.viewer)return;let a=document.createElement('a');a.href=state.viewer.png();a.download=slug()+'-enclosure.png';a.click();},recommended:()=>change(()=>settings().standoffHeight=Math.max(6,state.plan.below+settings().underClearance)),sync:()=>change(()=>CB.enclosureSyncMounts(p,settings())), 'add-mount':()=>change(()=>settings().mounts.push({id:CB.uid(),anchor:'',x:p.board.width/2,y:p.board.height/2,enabled:true,diameter:null,bore:null})),'add-circle':()=>addOpening('circle'),'add-rect':()=>addOpening('rect'),'add-slot':()=>addOpening('slot'),'duplicate-opening':()=>{let o=chosen();if(!o)return;let n={...CB.clone(o),id:CB.uid(),name:o.name+' copy',u:o.u+o.width+2};state.opening=n.id;change(()=>settings().openings.push(n));},'delete-opening':()=>{let id=state.opening;state.opening=null;change(()=>settings().openings=settings().openings.filter(o=>o.id!==id));},'base-stl':()=>exportPart('base'),'lid-stl':()=>exportPart('lid'),zip:exportZip,report:printReport,undo:()=>{undo();if(!p.enclosure){closeDialog();return;}state.opening=null;generate();renderPanel();}};actions[key]?.();});
document.addEventListener('click',e=>{let id=e.target.closest('[data-enc-remove-mount]')?.dataset.encRemoveMount;if(id&&state)change(()=>settings().mounts=settings().mounts.filter(m=>m.id!==id));});
document.addEventListener('change',e=>{if(!state)return;let el=e.target,key=el.dataset.encSetting;if(key){let value=el.tagName==='SELECT'?el.value:Number(el.value);change(()=>settings()[key]=value);return;}if(el.dataset.encHeight){change(()=>p.components.find(c=>c.id===el.dataset.encHeight).height=Number(el.value),'Component height updated.');return;}if(el.dataset.encMount){let m=settings().mounts.find(m=>m.id===el.dataset.encMount);if(m){let value=el.type==='checkbox'?el.checked:el.value===''?null:Number(el.value);change(()=>m[el.dataset.key]=value);}return;}if(el.dataset.encOpening){let o=chosen();if(o){let key=el.dataset.encOpening,value=key==='name'?el.value:Number(el.value);change(()=>{o[key]=value;if(o.shape==='circle'&&key==='width')o.height=value;});}return;}if(el.id==='encAlignPart'&&el.value&&chosen()){let c=state.plan.components.find(c=>c.id===el.value);change(()=>{let o=chosen(),flat=['lid','floor'].includes(o.face);o.u=CB.round(['left','right'].includes(o.face)?c.y:c.x);o.v=CB.round(flat?c.y:c.bottom+c.height/2-settings().floor);},'Opening centered on component envelope.');return;}if(el.id==='encFace'){state.face=el.value;state.opening=null;renderPanel();}if(el.id==='encOpening'){state.opening=el.value;renderPanel();}if(['encGhost','encShowBoard','encShowLid'].includes(el.id))state.viewer?.options({ghost:$('#encGhost').checked,board:$('#encShowBoard').checked,lid:$('#encShowLid').checked});});
document.addEventListener('input',e=>{if(state&&e.target.id==='encExplode')state.viewer?.options({explode:Number(e.target.value)});});
const oldRender=render;render=function(){oldRender();if(!$('#pcbDesignTools [data-enc=open]'))$('#pcbDesignTools')?.insertAdjacentHTML('beforeend',B('Enclosure','open'));};
const oldHelp=helpDialog;helpDialog=function(){oldHelp();$('#dialogBody').insertAdjacentHTML('afterbegin','<div class="notice"><strong>Enclosure workbench · v1.6</strong><p>PCB → Enclosure opens the integrated enclosure workbench. Choose a shell and screw, insert, sliding, snap-fit or pin-hinge closure. Add linked openings, text, SVG artwork, vents or functional interfaces. Configure standoffs, print fit frames and coupons, then export STL, 3MF or a complete print ZIP. All settings autosave with the PCB. Advanced mode adds assemblies and recipes.</p></div>');};
window.Circuitbench.enclosure={open,plan:()=>CB.enclosurePlan(p),state:()=>state?{ready:!!state.result&&!state.pending,issues:issues(),stats:state.viewer?.stats(),triangles:state.result?.base.indices.length/3}:null};
render();
})();
