/* CIRCUITBENCH polygon copper geometry. GPL-3.0-only; Clipper is Boost-licensed. */
(function(root){'use strict';
const C=typeof module!=='undefined'?require('./model.js'):root.CB,L=typeof module!=='undefined'?require('./vendor/clipper.js'):root.ClipperLib,S=10000,EPS=.001;
const toPath=p=>p.map(q=>({X:Math.round(q.x*S),Y:Math.round(q.y*S)})),fromPath=p=>p.map(q=>({x:q.X/S,y:q.Y/S}));
function bool(a,b,type){let c=new L.Clipper(),out=new L.Paths();if(a.length)c.AddPaths(a.map(toPath),L.PolyType.ptSubject,true);if(b.length)c.AddPaths(b.map(toPath),L.PolyType.ptClip,true);c.Execute(type,out,L.PolyFillType.pftNonZero,L.PolyFillType.pftNonZero);return out.map(fromPath);}
const union=a=>bool(a,[],L.ClipType.ctUnion),difference=(a,b)=>b.length?bool(a,b,L.ClipType.ctDifference):a,intersect=(a,b)=>bool(a,b,L.ClipType.ctIntersection);
function offset(paths,d){if(Math.abs(d)<1e-9)return C.clone(paths);let o=new L.ClipperOffset(2,.002*S),out=[];o.AddPaths(paths.map(toPath),L.JoinType.jtRound,L.EndType.etClosedPolygon);o.Execute(out,d*S);return out.map(fromPath);}
function area(poly){let a=0;for(let i=0;i<poly.length;i++){let p=poly[i],q=poly[(i+1)%poly.length];a+=p.x*q.y-q.x*p.y;}return a/2;}
function circle(x,y,r,n=Math.max(24,Math.ceil(Math.PI/Math.acos(1-Math.min(.0015/r,1))))){return Array.from({length:n},(_,i)=>({x:C.round(x+r*Math.cos(i*2*Math.PI/n)),y:C.round(y+r*Math.sin(i*2*Math.PI/n))}));}
function rect(x,y,w,h,angle=0){return [[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]].map(([xx,yy])=>{let q=C.rotate(xx,yy,angle);return {x:C.round(x+q.x),y:C.round(y+q.y)};});}
function capsule(a,b,width,n=Math.max(12,Math.ceil(Math.PI/(2*Math.acos(1-Math.min(.003/width,1)))))){let angle=Math.atan2(b.y-a.y,b.x-a.x),r=width/2,pts=[];for(let i=0;i<=n;i++){let t=angle-Math.PI/2+i*Math.PI/n;pts.push({x:C.round(b.x+r*Math.cos(t)),y:C.round(b.y+r*Math.sin(t))});}for(let i=0;i<=n;i++){let t=angle+Math.PI/2+i*Math.PI/n;pts.push({x:C.round(a.x+r*Math.cos(t)),y:C.round(a.y+r*Math.sin(t))});}return pts;}
function oval(x,y,w,h,angle=0){if(Math.abs(w-h)<EPS)return circle(x,y,w/2);let delta=C.rotate(w>h?(w-h)/2:0,h>w?(h-w)/2:0,angle);return capsule({x:x-delta.x,y:y-delta.y},{x:x+delta.x,y:y+delta.y},Math.min(w,h));}
function padPolygon(a,expand=0){const w=(a.width||a.diameter)+expand*2,h=(a.height||a.diameter)+expand*2;if(w<=0||h<=0)return [];return a.shape==='rect'?rect(a.x,a.y,w,h,a.angle||0):a.shape==='oval'?oval(a.x,a.y,w,h,a.angle||0):circle(a.x,a.y,w/2);}
function drillPolygon(a){return a.slot>a.drill?oval(a.x,a.y,a.slot,a.drill,a.angle??a.rotation??0):circle(a.x,a.y,a.drill/2);}
function outline(p){return p.board.outline.length?p.board.outline:[{x:0,y:0},{x:p.board.width,y:0},{x:p.board.width,y:p.board.height},{x:0,y:p.board.height}];}
function boardMaterial(p,inset=0){return difference(offset([outline(p)],-inset),p.cutouts.flatMap(a=>offset([a.points],inset)));}
function bounds(paths){let pts=paths.flat(),xs=pts.map(q=>q.x),ys=pts.map(q=>q.y);return {minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};}
function boxesNear(a,b,d=0){return a.minX<=b.maxX+d&&a.maxX+d>=b.minX&&a.minY<=b.maxY+d&&a.maxY+d>=b.minY;}
function inside(q,paths){let count=0;for(let p of paths){let r=L.Clipper.PointInPolygon({X:Math.round(q.x*S),Y:Math.round(q.y*S)},toPath(p));if(r===-1)return true;if(r===1)count++;}return count%2===1;}
function rawCopper(p){let all=[];const add=a=>{a.bounds=bounds(a.paths);all.push(a);};for(let a of C.pads(p)){let paths=[padPolygon(a)];if(a.drill)paths=difference(paths,[drillPolygon(a)]);add({id:a.id,owner:a.component,label:a.label,net:a.net,key:a.net||'NC:'+a.id,layer:a.layer,paths,pad:true,pin:a});}for(let v of p.vias)add({id:v.id,owner:v.id,label:'Via',net:v.net,key:v.net,layer:'both',paths:difference([circle(v.x,v.y,v.diameter/2)],[circle(v.x,v.y,v.drill/2)]),via:true,pin:v});for(let t of p.tracks)t.points.slice(1).forEach((b,i)=>add({id:t.id+':'+i,owner:t.id,label:'Track',net:t.net,key:t.net,layer:t.layer,paths:[capsule(t.points[i],b,t.width)],track:true}));return all;}
function splitRegions(paths){let outers=paths.filter(p=>area(p)>0),holes=paths.filter(p=>area(p)<0),regions=outers.map(p=>[p]);for(let hole of holes){let candidates=outers.map((p,i)=>({p,i})).filter(x=>inside(hole[0],[x.p])).sort((a,b)=>Math.abs(area(a.p))-Math.abs(area(b.p)));if(candidates.length)regions[candidates[0].i].push(hole);}return regions;}
function zones(p){let base=rawCopper(p),out=[],reserved={F:[],B:[]};for(let z of p.zones){let board=boardMaterial(p,Math.max(p.rules.edge,.01)),boundary=z.points.length?[z.points]:[outline(p)],fill=intersect(boundary,board),obstacles=[];for(let a of base){if(a.layer!=='both'&&a.layer!==z.layer)continue;if(a.net!==z.net)obstacles.push(...offset(a.paths,Math.max(p.rules.clearance,z.clearance,C.designRule?C.designRule(p,a.net,'clearance'):0,C.designRule?C.designRule(p,z.net,'clearance'):0)+.005));else if(z.thermal&&a.pad){let gap=offset([padPolygon(a.pin)],z.thermalGap),q=a.pin,span=Math.max(q.width,q.height)+2*z.thermalGap+.1,spokes=[rect(q.x,q.y,span,z.spoke,q.angle||0),rect(q.x,q.y,z.spoke,span,q.angle||0)];obstacles.push(...difference(gap,union(spokes)));}}
 for(let h of [...C.pads(p).filter(a=>a.drill),...p.vias,...p.holes])obstacles.push(...offset([drillPolygon(h)],p.holes.includes(h)?p.rules.clearance:.005));obstacles.push(...reserved[z.layer]);fill=difference(fill,union(obstacles));reserved[z.layer].push(...offset(fill,Math.max(z.clearance,p.rules.clearance)+.005));if(fill.length)splitRegions(fill).forEach((region,index)=>out.push({id:z.id+':island'+index,owner:z.id,label:'Zone',net:z.net,key:z.net,layer:z.layer,paths:region,bounds:bounds(region),zone:true}));}return out;}
let cachedKey='',cachedGeometry=null;
function copper(p){const key=JSON.stringify([p.board,p.components,p.tracks,p.vias,p.holes,p.cutouts,p.zones,p.rules,p.netClasses]);if(key===cachedKey)return cachedGeometry;cachedKey=key;cachedGeometry=[...rawCopper(p),...zones(p)];return cachedGeometry;}
function sharedLayer(a,b){return a.layer==='both'||b.layer==='both'||a.layer===b.layer;}
function overlap(a,b,tolerance=0){if(!boxesNear(a.bounds,b.bounds,tolerance))return false;return intersect(tolerance?offset(a.paths,tolerance):a.paths,b.paths).some(p=>Math.abs(area(p))>1e-8);}
function geometryDistance(a,b,max=Infinity){if(overlap(a,b))return 0;let d=max;for(let p of a.paths)for(let q of b.paths)for(let i=0;i<p.length;i++)for(let j=0;j<q.length;j++){let v=C.segDistance(p[i],p[(i+1)%p.length],q[j],q[(j+1)%q.length]);if(v<d)d=v;if(d<1e-7)return 0;}return d;}
function topology(p){let items=copper(p),parent=items.map((_,i)=>i);function find(i){while(parent[i]!==i){parent[i]=parent[parent[i]];i=parent[i];}return i;}for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){let a=items[i],b=items[j];if(a.key===b.key&&sharedLayer(a,b)&&overlap(a,b,.001))parent[find(i)]=find(j);}return {items,u:{find,join:(a,b)=>parent[find(a)]=find(b)}};}
function connections(p,view='pcb'){let ps=C.pads(p,view).filter(a=>a.net),top=view==='pcb'?topology(p):null,lines=[];for(let net of p.nets){let group=ps.filter(a=>a.net===net),parent=group.map((_,i)=>i);function find(i){while(parent[i]!==i)i=parent[i];return i;}function join(i,j){parent[find(i)]=find(j);}if(top){let index=new Map(top.items.map((a,i)=>[a.id,i]));for(let i=0;i<group.length;i++)for(let j=i+1;j<group.length;j++)if(top.u.find(index.get(group[i].id))===top.u.find(index.get(group[j].id)))join(i,j);}let pairs=[];for(let i=0;i<group.length;i++)for(let j=i+1;j<group.length;j++)pairs.push({i,j,d:C.dist(group[i],group[j])});pairs.sort((a,b)=>a.d-b.d);for(let q of pairs)if(find(q.i)!==find(q.j)){join(q.i,q.j);lines.push({a:group[q.i],b:group[q.j],net});}}return lines;}
function polygonValid(poly){if(poly.length<3||Math.abs(area(poly))<.01)return false;for(let i=0;i<poly.length;i++){let a=poly[i],b=poly[(i+1)%poly.length];if(C.dist(a,b)<.001)return false;for(let j=i+2;j<poly.length;j++){if(i===0&&j===poly.length-1)continue;if(C.segDistance(a,b,poly[j],poly[(j+1)%poly.length])<.0001)return false;}}return true;}
Object.assign(C,{G:{bool,union,difference,intersect,offset,area,circle,rect,capsule,oval,padPolygon,drillPolygon,outline,boardMaterial,bounds,boxesNear,inside,overlap,geometryDistance,sharedLayer,polygonValid,splitRegions},copper,rawCopper,zones,topology,connections});
if(typeof module!=='undefined')module.exports=C;else root.CB=C;
})(typeof globalThis!=='undefined'?globalThis:this);
