/* CIRCUITBENCH import validation and release safeguards. GPL-3.0-only. */
(function(root){'use strict';const C=typeof module!=='undefined'?require('./blocks.js'):root.CB,validateModel=C.validate,baseChecks=C.checks,baseFab=C.fabrication;
function validate(input){if(!input||JSON.stringify(input).length>5*1024*1024)throw Error('Project exceeds the 5 MB editable-file limit.');let p=validateModel(input);const fail=m=>{throw Error('Invalid project: '+m);},str=(v,n,max=160)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail(n);},identity=(v)=>{if(typeof v!=='string'||!/^[A-Za-z0-9_-]{1,100}$/.test(v))fail('malformed identity');},point=q=>{if(!q||!Number.isFinite(q.x)||!Number.isFinite(q.y)||Math.abs(q.x)>1000||Math.abs(q.y)>1000)fail('point');};
 for(let s of p.sheets){identity(s.id);str(s.name,'sheet name',80);}if(p.sheets.filter(s=>s.parent===null).length!==1)fail('exactly one root sheet is required');
 for(let c of p.components)for(let a of c.pads){if(a.mount==='smd'&&a.slot!==0)fail('SMD slot');if(a.slot>0&&a.slot<a.drill)fail('slot shorter than drill');if(a.labelNet!==''&&typeof a.labelNet!=='string')fail('pin label');}
 for(let w of p.wires){for(let e of [w.from,w.to])if(!e||!['pin','junction'].includes(e.kind))fail('wire endpoint kind');if(C.endpointKey(w.from)===C.endpointKey(w.to))fail('wire needs distinct endpoints');}
 for(let l of p.labels){let a=p.components.find(c=>c.id===l.component)?.pads.find(a=>a.n===l.pin);if(a.labelNet!==l.net)fail('label differs from its anchor');}
 for(let h of p.holes)if(h.slot>0&&h.slot<h.drill)fail('mechanical slot length');for(let s of p.silk){if(s.kind==='text'){if(typeof s.mirror!=='undefined'&&typeof s.mirror!=='boolean')fail('text mirror');if([...s.text].some(a=>!C.FONT[a.toUpperCase()]))fail('unsupported silkscreen character');}else if(s.kind==='line'&&C.dist(s.a,s.b)<.0001)fail('zero-length silkscreen line');}
 let classes=new Set(),netClasses=new Set();for(let c of p.netClasses){str(c.name,'class name');if(classes.has(c.name))fail('duplicate net class');classes.add(c.name);for(let n of c.nets){if(netClasses.has(n))fail('net belongs to multiple classes');netClasses.add(n);}}
 let portNames=new Set();for(let a of p.ports){str(a.name,'port name',60);let k=a.sheet+':'+a.name;if(portNames.has(k))fail('duplicate port name');portNames.add(k);if(!p.sheets.find(s=>s.id===a.sheet)?.parent)fail('root sheet cannot have a child port');}
 if(p.rulesSource!==undefined&&(typeof p.rulesSource!=='string'||p.rulesSource.length>1000))fail('rule source');
 function symbol(s){identity(s.id);str(s.name,'symbol name');str(s.kind,'symbol kind');if(!Array.isArray(s.pins)||s.pins.length>1024)fail('library symbol pins');let ns=new Set();for(let a of s.pins){if(!/^[A-Za-z0-9_-]{1,10}$/.test(a.n)||ns.has(a.n))fail('symbol pin numbers');ns.add(a.n);point(a);if(typeof a.name!=='string'||a.name.length>60||!['passive','input','output','power_in','power_out','bidirectional','open_collector','tri_state','no_connect'].includes(a.type))fail('symbol pin definition');}}
 function footprint(f){identity(f.id);str(f.name,'footprint name');let q=C.fresh(),c=C.component(q,'custom');c.pads=C.clone(f.pads);c.body=C.clone(f.body);c.height=f.height;c.courtyard=f.courtyard;c.mountingHoles=C.clone(f.holes||[]);q.components=[c];validateModel(q);if(c.pads.some(a=>a.net||a.labelNet))fail('library footprint must have unassigned nets');}
 let entries=new Set();for(let k of ['symbols','footprints','devices','blocks'])for(let a of p.library[k]){identity(a.id);str(a.name,'library name');if(entries.has(a.id))fail('duplicate library identity');entries.add(a.id);if(k==='symbols')symbol(a);if(k==='footprints')footprint(a);if(k==='devices'){symbol(a.symbol);footprint(a.footprint);str(a.prefix,'device reference prefix',15);if(!/^[A-Za-z][A-Za-z0-9_-]*$/.test(a.prefix)||typeof a.value!=='string'||a.value.length>200)fail('device metadata');let c=C.component(C.fresh(),'custom');c.pads=C.clone(a.footprint.pads);C.applySymbol(c,a.symbol,a.mapping);}if(k==='blocks'){if(!Array.isArray(a.components)||!a.components.length||a.components.length>150)fail('empty or oversized block');let q=C.fresh();q.nets=C.clone(a.nets);q.components=C.clone(a.components);q.components.forEach(c=>c.sheet='main');q.wires=C.clone(a.wires);q.wires.forEach(w=>w.sheet='main');q.junctions=C.clone(a.junctions);q.junctions.forEach(j=>j.sheet='main');q.labels=C.clone(a.labels);validateModel(q);}}
 if(p.baseline?.snapshot){let snap=p.baseline.snapshot;if(snap.baseline)fail('nested baseline');validateModel(snap);}
 return p;
}
function checks(p){let out=[...baseChecks(p)];for(let a of p.ports){let pins=C.pads(p).filter(x=>x.net===a.net&&x.sheet===a.sheet);if(!pins.length)out.push({severity:'warning',code:'EMPTY_PORT',message:a.name+' has no pins on its child sheet.',confidence:'High'});if(a.direction==='output'&&!pins.some(x=>['output','tri_state','open_collector','bidirectional'].includes(x.type)))out.push({severity:'warning',code:'PORT_DIRECTION',message:a.name+' is an output port without a declared child-sheet output.',confidence:'Medium'});}return out;}
function fabrication(p){if(p.importNotes.some(n=>n.startsWith('BLOCKING:')))throw Error('Fabrication is blocked: this import omitted unsupported board features. Use the original native board to complete the design.');return baseFab(p);}
Object.assign(C,{validate,checks,fabrication});if(typeof module!=='undefined')module.exports=C;else root.CB=C;
})(typeof globalThis!=='undefined'?globalThis:this);
