/* CIRCUITBENCH library engine and native KiCad library readers. GPL-3.0-only.
   Imported library data retains its upstream license. */
(function(root){'use strict';
const C=typeof module!=='undefined'?require('./hardening.js'):root.CB;
const cl=C.clone, child=(a,k)=>a.find(x=>Array.isArray(x)&&x[0]===k), children=(a,k)=>a.filter(x=>Array.isArray(x)&&x[0]===k), val=(a,k,d)=>child(a,k)?.[1]??d;
const ang=n=>((n%360)+360)%360, xy=(a,k)=>{let q=child(a,k);if(!q)throw Error('Missing '+k);return {x:Number(q[1]),y:Number(q[2])};};
function libraryId(s){let h=2166136261;for(let c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return 'lib_'+(h>>>0).toString(16);}
function arcPoints(start,mid,end){let ax=start.x,ay=start.y,bx=mid.x,by=mid.y,cx=end.x,cy=end.y,d=2*(ax*(by-cy)+bx*(cy-ay)+cx*(ay-by));if(Math.abs(d)<1e-9)throw Error('Degenerate arc');let aa=ax*ax+ay*ay,bb=bx*bx+by*by,cc=cx*cx+cy*cy,o={x:(aa*(by-cy)+bb*(cy-ay)+cc*(ay-by))/d,y:(aa*(cx-bx)+bb*(ax-cx)+cc*(bx-ax))/d},r=C.dist(o,start),t=Math.atan2(ay-o.y,ax-o.x),m=Math.atan2(by-o.y,bx-o.x),e=Math.atan2(cy-o.y,cx-o.x),norm=a=>(a+Math.PI*4)%(Math.PI*2);let span=norm(e-t);if(norm(m-t)>span)span-=2*Math.PI;let n=Math.max(8,Math.ceil(Math.abs(span)/.09));return Array.from({length:n+1},(_,i)=>({x:o.x+r*Math.cos(t+span*i/n),y:o.y+r*Math.sin(t+span*i/n)}));}
function graphic(g,symbol=false,unit=1){let k=g[0].replace(/^fp_/,''),points=[],width=Number(val(child(g,'stroke')||[],'width',val(g,'width',.15)))||.15,fill=val(child(g,'fill')||[],'type',val(g,'fill','none')),q;
 if(k==='polyline'||k==='poly')points=children(child(g,'pts')||[],'xy').map(a=>({x:Number(a[1]),y:Number(a[2])}));
 else if(k==='rectangle'||k==='rect'){let a=xy(g,'start'),b=xy(g,'end');points=[a,{x:b.x,y:a.y},b,{x:a.x,y:b.y},a];}
 else if(k==='line')points=[xy(g,'start'),xy(g,'end')];
 else if(k==='circle'){let o=xy(g,'center'),r=child(g,'radius')?Number(val(g,'radius',0)):C.dist(o,xy(g,'end'));points=C.G.circle(o.x,o.y,r,64);points.push(points[0]);}
 else if(k==='arc')points=arcPoints(xy(g,'start'),xy(g,'mid'),xy(g,'end'));
 else if(k==='text'&&symbol){let at=child(g,'at')||['at',0,0,0],font=child(child(g,'effects')||[],'font')||[];return {kind:'text',text:String(g[1]),x:Number(at[1]),y:-Number(at[2]),size:Number(child(font,'size')?.[1]||1.27),rotation:ang(-Number(at[3]||0)),unit};}
 else throw Error('Unsupported graphic '+g[0]);
 if(width<0)width=.15;if(symbol)points=points.map(a=>({x:a.x,y:-a.y}));return {kind:'polyline',points,width,fill:fill==='none'?'none':fill==='background'?'background':'solid',unit,layer:String(val(g,'layer','F.Fab'))};
}
function importSymbols(text,sourceName='Imported'){let tree=C.parseSexpr(text);if(tree[0]!=='kicad_symbol_lib')throw Error('Expected .kicad_sym');let raw=new Map(children(tree,'symbol').map(a=>[String(a[1]),a])),resolved=new Map(),diagnostics=[],symbols=[];
 function resolve(name,chain=[]){if(chain.includes(name))throw Error('Symbol inheritance cycle');if(resolved.has(name))return resolved.get(name);let node=raw.get(name);if(!node)throw Error('Missing inherited symbol '+name);let parent=val(node,'extends',''),base=parent?resolve(String(parent),[...chain,name]):null,result=base?cl(base):{properties:{},shapes:[]};for(let pr of children(node,'property'))result.properties[String(pr[1])]=String(pr[2]);if(children(node,'symbol').length)result.shapes=children(node,'symbol');resolved.set(name,result);return result;}
 for(let [name]of raw){try{let r=resolve(name),pins=[],graphics=[],unitNumbers=new Set(),seen=new Set(),notes=[];for(let node of r.shapes){let match=String(node[1]).match(/_(\d+)_(\d+)$/);if(!match)throw Error('Unknown unit name '+node[1]);let unit=Number(match[1]),style=Number(match[2]);if(style>1){if(!notes.includes('Alternate De Morgan body style omitted; standard body retained.'))notes.push('Alternate De Morgan body style omitted; standard body retained.');continue;}unitNumbers.add(unit);
 for(let g of node.slice(2).filter(Array.isArray)){if(g[0]==='pin'){let n=String(val(g,'number','')),at=child(g,'at'),name=String(val(g,'name',n)),type=({open_emitter:'open_collector',free:'passive',unspecified:'passive'})[g[1]]||String(g[1]);if(!at||!n)throw Error('Missing pin position or number');if(seen.has(n))continue;seen.add(n);pins.push({n,name,type,x:Number(at[1]),y:-Number(at[2]),angle:ang(-Number(at[3]||0)),length:Number(val(g,'length',2.54)),shape:String(g[2]),unit,hidden:g.includes('hide')});}
 else graphics.push(graphic(g,true,unit));}}
 let ns=[...unitNumbers].filter(n=>n>0).sort((a,b)=>a-b);if(!ns.length)ns=[1];let units=ns.map((n,i)=>{let pts=[...pins.filter(a=>a.unit===n),...graphics.filter(a=>a.unit===n).flatMap(a=>a.points||[a])],bb=pts.length?C.G.bounds([pts]):{minX:-5,maxX:5,minY:-5,maxY:5};return {n,x:i?Math.floor(i%3)*Math.max(35,bb.maxX-bb.minX+12):0,y:i?Math.floor(i/3)*Math.max(35,bb.maxY-bb.minY+12):0};});
 let props=r.properties,id=libraryId(sourceName+':symbol:'+name);symbols.push({id,name:sourceName+':'+name,kind:'native',pins,graphics,units,prefix:props.Reference||'U',value:props.Value||name,description:props.Description||'',datasheet:props.Datasheet||'',footprint:props.Footprint||'',filters:(props.ki_fp_filters||'').split(' ').filter(Boolean),keywords:props.ki_keywords||'',source:{format:'KiCad symbol',file:sourceName+'.kicad_sym',name},notes});
 }catch(e){diagnostics.push({severity:'error',entry:name,message:e.message});}}
 return {symbols,diagnostics};
}
function importFootprint(text,sourceName='Imported'){let tree=C.parseSexpr(text);if(!['footprint','module'].includes(tree[0]))throw Error('Expected .kicad_mod');let name=String(tree[1]),pads=[],holes=[],apertures=[],keepouts=[],graphics=[],diagnostics=[],seen=new Map();
 for(let z of children(tree,'zone')){let k=child(z,'keepout');if(!k)throw Error('Footprint copper zones are unsupported.');let layers=(child(z,'layers')?.slice(1)||[val(z,'layer','F.Cu')]).map(String).filter(l=>['F.Cu','B.Cu','*.Cu'].includes(l));if(!layers.length)continue;for(let poly of children(z,'polygon')){let points=children(child(poly,'pts')||[],'xy').map(a=>({x:Number(a[1]),y:Number(a[2])}));if(!C.G.polygonValid(points))throw Error('Invalid footprint keepout polygon.');keepouts.push({points,layers,prohibit:Object.fromEntries(['tracks','vias','pads','copperpour','footprints'].map(key=>[key,val(k,key,'allowed')==='not_allowed']))});}}
 for(let k of ['solder_mask_margin','solder_paste_margin','solder_paste_ratio','clearance','zone_connect','thermal_width','thermal_gap'])if(child(tree,k))throw Error('Footprint-specific '+k+' is unsupported.');
 for(let a of children(tree,'pad')){let number=String(a[1]),mount=a[2],shape=a[3],at=child(a,'at')||['at',0,0,0],size=child(a,'size'),dr=child(a,'drill'),width=Number(size?.[1]),height=Number(size?.[2]),rotation=ang(-Number(at[3]||0)),drill=dr?Number(dr[1]==='oval'?Math.min(dr[2],dr[3]):dr[1]):0,slot=dr?.[1]==='oval'?Math.max(Number(dr[2]),Number(dr[3])):0;
 if(dr&&child(dr,'offset'))throw Error('Offset drill on pad '+number+' unsupported.');
 if(mount==='np_thru_hole'){if(!['circle','oval'].includes(shape))throw Error('Unsupported mechanical hole shape');holes.push({x:Number(at[1]),y:Number(at[2]),rotation:ang(rotation+(dr?.[1]==='oval'&&dr[3]>dr[2]?90:0)),drill,slot,plated:false});continue;}
 if(!['thru_hole','smd'].includes(mount)||!['circle','rect','oval','roundrect'].includes(shape))throw Error('Unsupported '+mount+' / '+shape+' pad '+number+'. Entry was not imported.');
 let layers=child(a,'layers')?.slice(1)||[];if(!layers.some(l=>l.endsWith('.Cu'))){if(layers.every(l=>['F.Paste','F.Mask'].includes(l))&&mount==='smd'){apertures.push({x:Number(at[1]),y:Number(at[2]),width,height,diameter:Math.min(width,height),rotation,shape,radiusRatio:Number(val(a,'roundrect_rratio',.25)),layers});continue;}throw Error('Unsupported non-copper pad layers');}if(!layers.includes(mount==='smd'?'F.Cu':'*.Cu'))throw Error('Unsupported copper layer set on pad '+number);
 for(let k of ['solder_mask_margin','solder_paste_margin','solder_paste_margin_ratio','clearance','thermal_gap','thermal_bridge_width','chamfer','chamfer_ratio'])if(child(a,k))throw Error('Unsupported per-pad '+k+' on '+number);
 if(!number)throw Error('Unnumbered copper pads require a numbered logical connection.');if(dr?.[1]==='oval'&&dr[3]>dr[2]){[width,height]=[height,width];rotation=ang(rotation+90);}
 let count=(seen.get(number)||0)+1;seen.set(number,count);pads.push({n:count===1?number:number+'__'+count,number,pin:number,name:number,type:'passive',x:Number(at[1]),y:Number(at[2]),width,height,diameter:Math.min(width,height),drill,slot,rotation,shape,radiusRatio:Number(val(a,'roundrect_rratio',.25)),pasteMargin:0,zoneConnect:Number(val(a,'zone_connect',-1)),mount:mount==='smd'?'smd':'tht',net:'',labelNet:'',nc:false,paste:layers.includes('F.Paste')||layers.includes('*.Paste'),mask:layers.includes('F.Mask')||layers.includes('*.Mask'),maskSides:layers.includes('*.Mask')?['F','B']:layers.filter(l=>l.endsWith('.Mask')).map(l=>l[0])});}
 for(let g of tree.filter(a=>Array.isArray(a)&&String(a[0]).startsWith('fp_'))){let layer=String(val(g,'layer',''));if(layer.endsWith('.Cu'))throw Error('Footprint copper graphics unsupported.');if(g[0]==='fp_text'){if(!['reference','value'].includes(g[1]))diagnostics.push({severity:'warning',entry:name,message:'Static footprint text '+String(g[2])+' omitted; inspect markings.'});continue;}
 if(!['F.SilkS','B.SilkS','F.Fab','B.Fab','F.CrtYd','B.CrtYd'].includes(layer))continue;try{graphics.push(graphic(g));}catch(e){throw Error(e.message+' on '+layer);}}
 if(children(tree,'model').length)diagnostics.push({severity:'info',entry:name,message:'External 3D models are not bundled; assembly uses a body envelope.'});
 let bodies=graphics.filter(g=>g.layer.endsWith('.Fab')).flatMap(g=>g.points||[]),points=bodies.length?bodies:[...pads,...holes];if(!points.length)throw Error('Footprint contains no usable geometry.');let bb=C.G.bounds([points]),cx=(bb.minX+bb.maxX)/2,cy=(bb.minY+bb.maxY)/2;for(let a of [...pads,...holes,...apertures]){a.x=C.round(a.x-cx);a.y=C.round(a.y-cy);}for(let k of keepouts)k.points=k.points.map(a=>({x:C.round(a.x-cx),y:C.round(a.y-cy)}));for(let g of graphics)g.points=g.points.map(a=>({x:C.round(a.x-cx),y:C.round(a.y-cy)}));let footprint={id:libraryId(sourceName+':footprint:'+name),name:sourceName+':'+name,body:[Math.max(.1,C.round(bb.maxX-bb.minX)),Math.max(.1,C.round(bb.maxY-bb.minY))],height:3,courtyard:.25,pads,holes,apertures,keepouts,graphics,source:{format:'KiCad footprint',file:sourceName+'.pretty/'+name+'.kicad_mod',originOffset:{x:cx,y:cy}},notes:diagnostics.map(a=>a.message)};
 return {footprint,diagnostics};
}
function instantiateDevice(p,d,f,x=30,y=20){f=f||d.footprint;if(!f)throw Error('Select a compatible footprint.');let c=C.component(p,'custom',x,y),i=1;while(p.components.some(c=>c.ref===d.prefix+i))i++;Object.assign(c,{ref:d.prefix+i,kind:'device',value:d.value||d.name,mpn:d.mpn||'',pads:cl(f.pads),body:cl(f.body),height:f.height,courtyard:f.courtyard,footprintName:f.name,footprintGraphics:cl(f.graphics||[]),mountingHoles:cl(f.holes||[]),apertures:cl(f.apertures||[]),keepouts:cl(f.keepouts||[]),librarySource:{device:cl(d.source||{}),symbol:cl(d.symbol.source||{}),footprint:cl(f.source||{}),datasheet:d.symbol.datasheet||'',catalogId:d.id,version:C.VERSION},deviceName:d.name});C.applySymbol(c,d.symbol,d.mapping);for(let a of c.pads)if(a.type==='no_connect')a.nc=true;return c;}
function validateLibrary(lib){if(!lib||typeof lib!=='object'||JSON.stringify(lib).length>50*1024*1024)throw Error('Library pack exceeds 50 MB or is malformed.');let result={},seen=new Set();for(let kind of ['symbols','footprints','devices','blocks']){let entries=lib[kind]||[];if(!Array.isArray(entries)||entries.length>2000)throw Error('Maximum 2,000 '+kind+' per pack.');result[kind]=entries.map(entry=>{if(seen.has(entry.id))throw Error('Duplicate library identity '+entry.id);seen.add(entry.id);let q=C.fresh();q.library[kind]=[cl(entry)];return C.validate(q).library[kind][0];});}return result;}
const beforeValidate=C.validate;
function validate(p){let q=beforeValidate(p),bad=m=>{throw Error('Invalid library geometry: '+m);};const number=(n,min=-1000,max=1000)=>{if(!Number.isFinite(n)||n<min||n>max)bad('number');},point=a=>{number(a.x);number(a.y);};
 function graphics(gs){if(!Array.isArray(gs)||gs.length>5000)bad('graphics limit');for(let g of gs){if(g.kind==='text'){point(g);number(g.size,.1,20);if(typeof g.text!=='string'||g.text.length>300)bad('graphic text');}else if(g.kind==='polyline'){if(!Array.isArray(g.points)||g.points.length<2||g.points.length>1000)bad('polyline');g.points.forEach(point);number(g.width,.001,10);}else bad('graphic kind');}}
 function symbol(s){graphics(s.graphics||[]);for(let u of s.units||[]){number(u.n,0,100);point(u);}for(let a of s.pins||[]){if(a.unit!==undefined)number(a.unit,0,100);if(a.length!==undefined)number(a.length,0,100);if(a.angle!==undefined)number(a.angle,0,360);}}
 function footprint(f){graphics(f.graphics||f.footprintGraphics||[]);let hs=f.holes||f.mountingHoles||[];if(!Array.isArray(hs)||hs.length>200)bad('hole count');for(let a of hs){point(a);number(a.drill,.1,30);number(a.slot,0,60);number(a.rotation,0,360);if(a.slot&&a.slot<a.drill)bad('slot length');}for(let k of f.keepouts||[]){if(!C.G.polygonValid(k.points))bad('keepout polygon');k.points.forEach(point);if(!Array.isArray(k.layers)||!k.layers.every(l=>['F.Cu','B.Cu','*.Cu'].includes(l)))bad('keepout layers');for(let key of ['tracks','vias','pads','copperpour','footprints'])if(typeof k.prohibit?.[key]!=='boolean')bad('keepout prohibition');}for(let a of f.apertures||[]){point(a);number(a.width,.05,30);number(a.height,.05,30);number(a.rotation,0,360);if(!['circle','rect','oval','roundrect'].includes(a.shape)||!Array.isArray(a.layers)||!a.layers.every(l=>['F.Paste','F.Mask'].includes(l)))bad('aperture');}for(let a of f.pads){if(a.pasteMargin!==undefined)number(a.pasteMargin,-Math.min(a.width,a.height)/2+.00001,5);if(a.zoneConnect!==undefined&&(!Number.isInteger(a.zoneConnect)||a.zoneConnect< -1||a.zoneConnect>2))bad('zone connection');if(a.maskSides!==undefined&&(!Array.isArray(a.maskSides)||!a.maskSides.every(l=>['F','B'].includes(l))))bad('mask side');for(let key of ['paste','mask'])if(a[key]!==undefined&&typeof a[key]!=='boolean')bad('opening flag');if(a.radiusRatio!==undefined)number(a.radiusRatio,0,.5);if(a.pin!==undefined&&!/^[A-Za-z0-9_-]{1,10}$/.test(a.pin))bad('logical pin');if(a.number!==undefined&&!/^[A-Za-z0-9_-]{1,10}$/.test(a.number))bad('pad number');}}
 for(let c of q.components){symbol(c.symbol);footprint(c);let groups=new Map();for(let a of c.pads){let key=a.pin||a.n;if(groups.has(key)){let b=groups.get(key);if(a.net!==b.net||a.nc!==b.nc||a.labelNet!==b.labelNet)bad('repeated pads disagree on logical assignment');}else groups.set(key,a);}}
 for(let s of q.library.symbols)symbol(s);for(let f of q.library.footprints)footprint(f);for(let d of q.library.devices){symbol(d.symbol);footprint(d.footprint);}return q;
}
const beforeSch=C.schLocal;C.schLocal=function(c,a){let n=a.pin||a.n,s=c.symbol?.pins?.find(p=>p.n===n),u=c.symbol?.units?.find(u=>u.n===s?.unit),q=beforeSch(c,a);return {x:q.x+(u?.x||0),y:q.y+(u?.y||0)};};
// The shared model's position function calls schLocal directly, so expose unit offsets there too.
const beforePos=C.position;C.position=function(c,a,view='pcb'){if(view!=='sch')return beforePos(c,a,view);let q=C.schLocal(c,a),r=C.rotate(q.x,q.y,c.sch.rotation);return {x:C.round(c.sch.x+r.x),y:C.round(c.sch.y+r.y)};};
C.pads=function(p,view='pcb'){return p.components.flatMap(c=>(view==='sch'?C.logicalPads(c):c.pads).map(a=>({...a,...C.position(c,a,view),n:view==='sch'?a.pin||a.n:a.n,id:c.id+':'+(view==='sch'?a.pin||a.n:a.n),component:c.id,ref:c.ref,sheet:c.sheet,angle:c.pcb.rotation+(c.pcb.side==='B'?-a.rotation:a.rotation),layer:a.mount==='tht'?'both':c.pcb.side,side:c.pcb.side,label:c.ref+'.'+(a.pin||a.n)})));};
function padOpening(a,layer,kind){if(kind==='paste')return a.mount==='smd'&&a.layer===layer&&a.paste!==false;if(a.mask===false)return false;if(a.maskSides)return a.maskSides.map(l=>a.side==='B'?(l==='F'?'B':'F'):l).includes(layer);return a.layer==='both'||a.layer===layer;}
function apertures(p,layer,kind){return p.components.flatMap(c=>(c.apertures||[]).filter(a=>a.layers.includes('F.'+(kind==='paste'?'Paste':'Mask'))&&c.pcb.side===layer).map(a=>({...a,...C.position(c,a),angle:c.pcb.rotation+(c.pcb.side==='B'?-a.rotation:a.rotation)})));}
function keepouts(p){return p.components.flatMap(c=>(c.keepouts||[]).map((k,i)=>({...k,id:c.id+'_keepout'+i,owner:c.id,points:k.points.map(a=>C.position(c,a)),layers:k.layers.map(l=>l==='*.Cu'?l:(c.pcb.side==='B'?(l==='F.Cu'?'B.Cu':'F.Cu'):l))})));}
const beforeChecks=C.checks;function checks(p){let out=[...beforeChecks(p)];for(let k of keepouts(p)){let paths=[k.points],bounds=C.G.bounds(paths),region={paths,bounds},layers=k.layers.includes('*.Cu')?['F','B']:k.layers.map(l=>l[0]);for(let a of C.copper(p)){let type=a.pad?'pads':a.via?'vias':a.track?'tracks':'copperpour';if(!k.prohibit[type]||a.layer!=='both'&&!layers.includes(a.layer))continue;if(C.G.overlap(region,a))out.push({severity:'error',code:'FOOTPRINT_KEEPOUT',message:a.label+' enters a footprint '+type+' keepout.',target:k.owner,confidence:'High'});}if(k.prohibit.footprints)for(let c of p.components){if(c.id===k.owner||!layers.includes(c.pcb.side))continue;let ps=[C.G.rect(c.pcb.x,c.pcb.y,...c.body,c.pcb.rotation)],a={paths:ps,bounds:C.G.bounds(ps)};if(C.G.overlap(region,a))out.push({severity:'warning',code:'BODY_KEEPOUT',message:c.ref+' overlaps a footprint keepout.',target:c.id,confidence:'Medium'});}}return out;}
function deviceFrom(c,name){let symbol=C.symbolFrom(c,name),footprint=C.footprintFrom(c,name),mapping=Object.fromEntries(symbol.pins.map(a=>[a.n,c.pads.filter(p=>(p.pin||p.n)===a.n).map(p=>p.n)]));return {id:C.uid(),name,prefix:c.ref.replace(/[0-9]+$/,'')||'U',value:c.value,mpn:c.mpn,category:'My parts',symbol,footprint,mapping,source:cl(c.librarySource||{})};}
Object.assign(C,{deviceFrom,keepouts,checks,padOpening,apertures,libraryId,importSymbols,importFootprint,instantiateDevice,validateLibrary,validate});if(typeof module!=='undefined')module.exports=C;else root.CB=C;
})(typeof globalThis!=='undefined'?globalThis:this);
