/* Shared symbol drawing and footprint previews. GPL-3.0-only. */
(function(root){'use strict';const C=root.CB,E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),P=pts=>pts.map((q,i)=>(i?'L':'M')+q.x+','+q.y).join(' ');
function symbolMarkup(c,{interactive=false,labels=true,selected=false}={}){let s=c.symbol,ink='var(--ink)',green='var(--accent)',fill='var(--panel)',out='',pins=C.logicalPads(c),units=s.units?.length?s.units:[{n:1,x:0,y:0}],graphics=s.graphics||[];
 if(graphics.length){for(let u of units){out+=`<g data-symbol-unit="${u.n}" transform="translate(${u.x} ${u.y})">`;for(let g of graphics.filter(g=>g.unit===u.n||g.unit===0)){if(g.kind==='text')out+=`<text x="${g.x}" y="${g.y}" font-size="${g.size}" fill="${ink}" text-anchor="middle">${E(g.text)}</text>`;else out+=`<path d="${P(g.points)}" fill="${g.fill==='background'?fill:g.fill==='solid'?ink:'none'}" stroke="${selected?'#b5832f':ink}" stroke-width="${g.width}"/>`;}if(units.length>1)out+=`<text x="0" y="-13" font-size="2" text-anchor="middle" fill="${green}">${E(c.ref)}${u.n}</text>`;out+='</g>';}}
 else{let ps=pins.map(a=>C.schLocal(c,a)),bb=ps.length?C.G.bounds([ps]):{minX:-6,maxX:6,minY:-4,maxY:4};out+=`<rect x="${bb.minX+3}" y="${bb.minY-3}" width="${Math.max(8,bb.maxX-bb.minX-6)}" height="${Math.max(6,bb.maxY-bb.minY+6)}" fill="${fill}" stroke="${ink}" stroke-width=".3"/>`;}
 for(let a of pins){let n=a.pin||a.n,def=s.pins?.find(p=>p.n===n)||{},q=C.schLocal(c,a),dir=C.rotate(1,0,def.angle??(q.x>0?180:0)),len=def.length??3,inside={x:q.x+dir.x*len,y:q.y+dir.y*len};out+=`<path d="M${q.x} ${q.y}L${inside.x} ${inside.y}" stroke="${ink}" stroke-width=".22"/>`;
 if(def.shape?.includes('inverted'))out+=`<circle cx="${inside.x}" cy="${inside.y}" r=".5" fill="${fill}" stroke="${ink}" stroke-width=".2"/>`;if(def.shape?.includes('clock')){let ort={x:-dir.y,y:dir.x};out+=`<path d="M${inside.x+ort.x*.7} ${inside.y+ort.y*.7}l${dir.x*1.2-ort.x*.7} ${dir.y*1.2-ort.y*.7}l${-dir.x*1.2-ort.x*.7} ${-dir.y*1.2-ort.y*.7}" fill="none" stroke="${ink}" stroke-width=".2"/>`;}
 out+=`<circle cx="${q.x}" cy="${q.y}" r=".65" fill="${a.net?green:fill}" stroke="${ink}" stroke-width=".18" ${interactive?`data-terminal="${E(c.id)}" data-pin="${E(n)}" tabindex="0" role="button" aria-label="${E(c.ref+' pin '+n+' '+a.name)}"`:''}><title>${E(n+' · '+a.name+' · '+a.type)}</title></circle>`;
 let nx=(q.x+inside.x)/2,ny=(q.y+inside.y)/2;out+=`<text x="${nx+.3}" y="${ny-.6}" font-size="1.3" fill="${ink}" pointer-events="none">${E(n)}</text>`;
 if(a.name&&a.name!=='~'&&a.name!==n){let text=a.name.replace(/~\{([^}]+)\}/g,'$1'),tx=inside.x+dir.x*.8,ty=inside.y+dir.y*.8;out+=`<text x="${tx}" y="${ty+.4}" font-size="1.4" fill="${ink}" text-anchor="${dir.x>.5?'start':dir.x<-.5?'end':'middle'}" ${Math.abs(dir.y)>.5?`transform="rotate(-90 ${tx} ${ty})"`:''} pointer-events="none">${E(text)}</text>`;}
 if(a.labelNet){let end={x:q.x-dir.x*6,y:q.y-dir.y*6};out+=`<path d="M${q.x} ${q.y}L${end.x} ${end.y}" stroke="${green}" stroke-width=".25"/><text x="${end.x-dir.x}" y="${end.y-1}" text-anchor="${dir.x>.5?'end':'start'}" font-size="1.6" fill="${green}" pointer-events="none">${E(a.labelNet)}</text>`;}
 if(a.nc)out+=`<path d="M${q.x-1} ${q.y-1}l2 2m-2 0l2-2" stroke="#c87345" stroke-width=".3"/>`;
 }
 let pts=[...pins.map(a=>C.schLocal(c,a)),...graphics.flatMap(g=>g.points||[g])],b=pts.length?C.G.bounds([pts]):{minX:-7,maxX:7,minY:-4,maxY:4};if(labels)out+=`<text x="${(b.minX+b.maxX)/2}" y="${b.minY-4}" text-anchor="middle" fill="${ink}" font-weight="bold" font-size="2.3">${E(c.ref)}</text><text x="${(b.minX+b.maxX)/2}" y="${b.maxY+4}" text-anchor="middle" fill="${ink}" font-size="2">${E(c.value)}</text>`;return out;
}
function symbolPreview(s){let c={id:'preview',ref:s.prefix||'U',value:s.value||s.name,symbol:s,pads:s.pins.map(a=>({...a,pin:a.n,net:'',labelNet:'',nc:false})),sch:{x:0,y:0,rotation:0}},ps=c.pads.map(a=>C.schLocal(c,a)),b=ps.length?C.G.bounds([ps]):{minX:-10,maxX:10,minY:-10,maxY:10};return `<svg class="partPreview" role="img" aria-label="Symbol preview" viewBox="${b.minX-8} ${b.minY-9} ${Math.max(25,b.maxX-b.minX+16)} ${Math.max(25,b.maxY-b.minY+18)}">${symbolMarkup(c)}</svg>`;}
function footprintPreview(f){let pts=f.pads.flatMap(a=>C.G.padPolygon({...a,angle:a.rotation})).concat((f.holes||[]).map(a=>({x:a.x,y:a.y}))),b=pts.length?C.G.bounds([pts]):{minX:-4,maxX:4,minY:-4,maxY:4};let out=`<rect x="${-f.body[0]/2}" y="${-f.body[1]/2}" width="${f.body[0]}" height="${f.body[1]}" fill="none" stroke="#7d9c8c" stroke-width=".12"/>`;for(let g of f.graphics||[])if(g.layer.endsWith('SilkS')||g.layer.endsWith('Fab'))out+=`<path d="${P(g.points)}" fill="${g.fill==='solid'?'#f2f3d9':'none'}" stroke="${g.layer.endsWith('SilkS')?'#f2f3d9':'#91b9a5'}" stroke-width="${g.width}"/>`;for(let a of f.pads){let poly=C.G.padPolygon({...a,angle:a.rotation});out+=`<path d="${P(poly)}Z" fill="#f1b775"/>`;if(a.drill)out+=`<path d="${P(C.G.drillPolygon({...a,angle:a.rotation}))}Z" fill="#153e35"/>`;out+=`<text x="${a.x}" y="${a.y+.23}" text-anchor="middle" font-size=".65" fill="#fff">${E(a.number||a.pin||a.n)}</text>`;}for(let h of f.holes||[])out+=`<path d="${P(C.G.drillPolygon(h))}Z" fill="#071f18" stroke="#c8d6cc" stroke-width=".15"/>`;return `<svg class="partPreview footprintPreview" role="img" aria-label="Footprint preview in millimeters, top view" viewBox="${Math.min(b.minX,-f.body[0]/2)-3} ${Math.min(b.minY,-f.body[1]/2)-3} ${Math.max(b.maxX-b.minX,f.body[0])+6} ${Math.max(b.maxY-b.minY,f.body[1])+6}">${out}</svg>`;}
root.CBLibraryRender={symbolMarkup,symbolPreview,footprintPreview};
})(globalThis);
