/* CIRCUITBENCH shared model, schema migration and schematic graph. GPL-3.0-only. */
(function(root){
'use strict';
const C=typeof module!=='undefined'?require('./core.js'):root.CB,base={...C};
C.VERSION='1.6.0';
const id=()=>C.uid(),cl=C.clone;
function migrate(input){let p=cl(input);if(p.format!=='circuitbench'||![1,2].includes(p.schema))throw Error('Unsupported project. Expected CIRCUITBENCH schema 1 or 2.');
 const legacy=p.schema===1;p.schema=2;p.version=C.VERSION;
 p.sheets??=[{id:'main',name:'Main circuit',parent:null}];p.wires??=[];p.junctions??=[];p.labels??=[];p.ports??=[];p.holes??=[];p.cutouts??=[];p.silk??=[];p.zones??=[];p.library??={symbols:[],footprints:[],devices:[],blocks:[]};p.netClasses??=[];p.importNotes??=[];p.rules.drill??=.25;p.rules.maskWeb??=.1;p.rules.courtyard??=.25;p.rules.silk??=.15;p.rules.silkLine??=.15;
 p.board.outline??=[];p.board.origin??={x:0,y:0};
 for(let c of p.components){c.sheet??='main';c.height??=c.kind==='led'?8:c.kind.startsWith('header')?8.5:c.kind.startsWith('dip')?4:3;c.courtyard??=.25;c.locked??=false;c.symbol??={kind:c.kind,pins:[]};c.footprintName??=c.kind;for(let a of c.pads){a.shape??='circle';a.width??=a.diameter;a.height??=a.diameter;a.rotation??=0;a.labelNet??=legacy?a.net:'';a.slot??=0;}}
 if(legacy){for(let l of base.connections(p,'sch'))p.wires.push({id:id(),net:l.net,sheet:'main',from:{kind:'pin',component:l.a.component,pin:l.a.n},to:{kind:'pin',component:l.b.component,pin:l.b.n},points:[{x:(l.a.x+l.b.x)/2,y:l.a.y},{x:(l.a.x+l.b.x)/2,y:l.b.y}]});}
 return p;
}
function blank(){return migrate(base.fresh());}
function sample(){let p=migrate(base.sample());p.title='Hello, copper';p.wires=p.wires.filter(w=>w.net==='LED+');return p;}
function component(p,key,x,y){let d=base.component(p,key,x,y);d.sch.x=20+(p.components.length%10)*35;d.sch.y=20+Math.floor(p.components.length/10)*35;d.sheet=p.activeSheet||'main';d.height=d.kind==='led'?8:d.kind.startsWith('header')?8.5:3;d.courtyard=.25;d.locked=false;d.symbol={kind:d.kind,pins:[]};d.footprintName=d.kind;for(let a of d.pads)Object.assign(a,{shape:'circle',width:a.diameter,height:a.diameter,rotation:0,labelNet:'',slot:0});return d;}
function schLocal(c,a){let custom=c.symbol?.pins?.find(p=>p.n===(a.pin||a.n));return custom?{x:custom.x,y:custom.y}:base.schLocal(c,a);}
function position(c,a,view='pcb'){let t=c[view],s=view==='pcb'?a:C.schLocal(c,a),r=C.rotate(view==='pcb'&&t.side==='B'?-s.x:s.x,s.y,t.rotation);return {x:C.round(t.x+r.x),y:C.round(t.y+r.y)};}
function pads(p,view='pcb'){return p.components.flatMap(c=>(view==='sch'?logicalPads(c):c.pads).map(a=>({...a,...position(c,a,view),id:c.id+':'+a.n,component:c.id,ref:c.ref,sheet:c.sheet,angle:c.pcb.rotation+(c.pcb.side==='B'?-a.rotation:a.rotation),layer:a.mount==='tht'?'both':c.pcb.side,label:c.ref+'.'+a.n})));}
function endpointKey(e){return e.kind==='pin'?e.component+':'+e.pin:'j:'+e.id;}
function endpoint(p,e){if(e.kind==='pin'){let c=p.components.find(c=>c.id===e.component),a=c?.pads.find(a=>(a.pin||a.n)===e.pin);return a?{...position(c,a,'sch'),net:a.net,sheet:c.sheet,pad:a,component:c}:null;}return p.junctions.find(j=>j.id===e.id)||null;}
function wirePath(p,w){let a=endpoint(p,w.from),b=endpoint(p,w.to);return a&&b?[{x:a.x,y:a.y},...w.points,{x:b.x,y:b.y}]:[];}
function mergeNet(p,a,b){if(a&&b&&a!==b){let ca=p.netClasses.find(c=>c.nets.includes(a)),cb=p.netClasses.find(c=>c.nets.includes(b));if(ca&&cb&&ca!==cb)throw Error('Assign these nets to the same net class before merging.');}const target=base.mergeNet(p,a,b);if(a&&b&&a!==b){for(let c of p.components)for(let d of c.pads)if(d.labelNet===b)d.labelNet=a;for(let x of [...p.wires,...p.junctions,...p.labels,...p.zones,...p.ports])if(x.net===b)x.net=a;for(let c of p.netClasses)c.nets=[...new Set(c.nets.map(n=>n===b?a:n))];}return target;}
function rebuildNets(p){const nodes=new Map(),parent=new Map();for(let c of p.components)for(let a of c.pads){let k=c.id+':'+(a.pin||a.n);if(!nodes.has(k)){nodes.set(k,a);parent.set(k,k);}}for(let j of p.junctions){let k='j:'+j.id;nodes.set(k,j);parent.set(k,k);}function find(k){let r=k;while(parent.get(r)!==r)r=parent.get(r);while(k!==r){let next=parent.get(k);parent.set(k,r);k=next;}return r;}function join(a,b){if(parent.has(a)&&parent.has(b))parent.set(find(a),find(b));}
 for(let w of p.wires)join(endpointKey(w.from),endpointKey(w.to));const labels=new Map();for(let[k,a]of nodes){if(a.labelNet){if(labels.has(a.labelNet))join(k,labels.get(a.labelNet));else labels.set(a.labelNet,k);}}
 const groups=new Map();for(let [k,a]of nodes){let r=find(k);if(!groups.has(r))groups.set(r,[]);groups.get(r).push([k,a]);}let used=new Set(),counter=1;function newNet(){while(p.nets.includes('N'+counter)||used.has('N'+counter))counter++;let n='N'+counter++;p.nets.push(n);return n;}
 for(let[r,g]of groups){let wired=p.wires.some(w=>find(endpointKey(w.from))===r),explicit=[...new Set(g.map(([k,a])=>a.labelNet).filter(Boolean))];if(explicit.length>1)throw Error('A wire joins conflicting named nets: '+explicit.join(', '));let n=explicit[0]||'';if(!n&&wired){n=g.map(([k,a])=>a.net).find(n=>n&&!used.has(n)&&!labels.has(n))||newNet();}if(n){used.add(n);if(!p.nets.includes(n))p.nets.push(n);}for(let[k,a]of g){a.net=n;if(wired&&a.nc)a.nc=false;}for(let w of p.wires)if(find(endpointKey(w.from))===r)w.net=n;}
 for(let c of p.components){let first=new Map();for(let a of c.pads){let k=a.pin||a.n;if(first.has(k)){let b=first.get(k);Object.assign(a,{net:b.net,labelNet:b.labelNet,nc:b.nc});}else first.set(k,a);}}
 return p;
}
function link(p,from,to,points=[]){const a=endpoint(p,from),b=endpoint(p,to);if(!a||!b||a.sheet!==b.sheet)throw Error('Wire endpoints must exist on the same sheet.');if(endpointKey(from)===endpointKey(to))throw Error('Choose two different terminals.');let n=mergeNet(p,a.net,b.net);if(a.pad){a.pad.net=n;a.pad.nc=false;}else a.net=n;if(b.pad){b.pad.net=n;b.pad.nc=false;}else b.net=n;const w={id:id(),sheet:a.sheet,net:n,from:cl(from),to:cl(to),points:cl(points)};p.wires.push(w);rebuildNets(p);return w;}
function splitWire(p,wid,q){let w=p.wires.find(w=>w.id===wid);if(!w)throw Error('Wire no longer exists.');let pts=wirePath(p,w),best=null;for(let i=0;i<pts.length-1;i++){let a=pts[i],b=pts[i+1],len=(b.x-a.x)**2+(b.y-a.y)**2,t=len?Math.max(0,Math.min(1,((q.x-a.x)*(b.x-a.x)+(q.y-a.y)*(b.y-a.y))/len)):0,pt={x:C.round(a.x+t*(b.x-a.x)),y:C.round(a.y+t*(b.y-a.y))},d=C.dist(q,pt);if(!best||d<best.d)best={i,pt,d};}if(C.dist(best.pt,pts[0])<.001)return w.from;if(C.dist(best.pt,pts.at(-1))<.001)return w.to;let j={id:id(),sheet:w.sheet,net:w.net,...best.pt};p.junctions.push(j);let ref={kind:'junction',id:j.id};p.wires.push({id:id(),sheet:w.sheet,net:w.net,from:ref,to:cl(w.to),points:pts.slice(best.i+1,-1)});w.to=ref;w.points=pts.slice(1,best.i+1);return ref;}
function removeWire(p,id){p.wires=p.wires.filter(w=>w.id!==id);rebuildNets(p);}
function removeComponent(p,id){p.components=p.components.filter(c=>c.id!==id);p.wires=p.wires.filter(w=>![w.from,w.to].some(e=>e.kind==='pin'&&e.component===id));p.labels=p.labels.filter(l=>l.component!==id);rebuildNets(p);}
function renumber(p,c,map){for(let w of p.wires)for(let e of [w.from,w.to])if(e.kind==='pin'&&e.component===c.id&&map[e.pin])e.pin=map[e.pin];for(let l of p.labels)if(l.component===c.id&&map[l.pin])l.pin=map[l.pin];for(let pin of c.symbol.pins)if(map[pin.n])pin.n=map[pin.n];}
function logicalPads(c){let seen=new Set();return c.pads.filter(a=>{let n=a.pin||a.n;if(seen.has(n))return false;seen.add(n);return true;});}
function symbolFrom(c,name){return {id:id(),name,source:cl(c.librarySource?.symbol||{}),datasheet:c.librarySource?.datasheet||'',kind:c.symbol.kind,graphics:cl(c.symbol.graphics||[]),units:cl(c.symbol.units||[]),pins:logicalPads(c).map(a=>({n:a.pin||a.n,name:a.name,type:a.type,...schLocal(c,a),...(c.symbol.pins.find(x=>x.n===(a.pin||a.n))||{})}))};}
function footprintFrom(c,name){return {id:id(),name,source:cl(c.librarySource?.footprint||{}),body:cl(c.body),height:c.height,courtyard:c.courtyard,graphics:cl(c.footprintGraphics||[]),holes:cl(c.mountingHoles||[]),apertures:cl(c.apertures||[]),keepouts:cl(c.keepouts||[]),pads:c.pads.map(a=>({...cl(a),pin:a.number||a.pin||a.n,net:'',labelNet:'',nc:false}))};}
function applySymbol(c,s,mapping){let pins=new Set(s.pins.map(a=>a.n));if(mapping){for(let a of c.pads){let target=Object.entries(mapping).find(([n,ids])=>ids.includes(a.n));if(!target)throw Error('Every copper pad needs a logical pin mapping.');a.pin=target[0];}}
 let actual=[...new Set(c.pads.map(a=>a.pin||a.n))].sort().join('|'),expected=[...pins].sort().join('|');if(actual!==expected)throw Error('Symbol pins and footprint pad numbers do not match. Map every pin to its physical pads.');c.symbol={kind:s.kind,pins:cl(s.pins),graphics:cl(s.graphics||[]),units:cl(s.units||[])};for(let a of c.pads){let pin=s.pins.find(x=>x.n===(a.pin||a.n));a.name=pin.name;a.type=pin.type;}}
function applyFootprint(c,f){let nets=new Map(c.pads.map(a=>[a.pin||a.n,a]));if([...nets.keys()].sort().join('|')!==[...new Set(f.pads.map(a=>a.pin||a.n))].sort().join('|'))throw Error('Footprint pin numbers do not match the symbol.');c.body=cl(f.body);c.height=f.height;c.courtyard=f.courtyard;c.footprintName=f.name;c.footprintGraphics=cl(f.graphics||[]);c.mountingHoles=cl(f.holes||[]);c.apertures=cl(f.apertures||[]);c.keepouts=cl(f.keepouts||[]);c.pads=f.pads.map(a=>({...cl(a),net:nets.get(a.pin||a.n).net,labelNet:nets.get(a.pin||a.n).labelNet,nc:nets.get(a.pin||a.n).nc,name:nets.get(a.pin||a.n).name,type:nets.get(a.pin||a.n).type}));}
function holes(p){return [...p.holes,...p.components.flatMap(c=>(c.mountingHoles||[]).map((a,i)=>({...cl(a),...position(c,a),angle:c.pcb.rotation+(c.pcb.side==='B'?-a.rotation:a.rotation),rotation:c.pcb.rotation+(c.pcb.side==='B'?-a.rotation:a.rotation),id:c.id+'_hole'+i,component:c.id,plated:false})))];}
function silks(p){return [...p.silk,...p.components.flatMap(c=>(c.footprintGraphics||[]).filter(g=>g.layer==='F.SilkS'||g.layer==='B.SilkS').flatMap((g,i)=>{let layer=g.layer[0]==='F'?c.pcb.side:(c.pcb.side==='F'?'B':'F');return g.fill==='solid'?[{id:c.id+'_silk'+i,kind:'polygon',layer,points:g.points.map(a=>position(c,a)),width:g.width||.12}]:g.points.slice(1).map((b,j)=>({id:c.id+'_silk'+i+'_'+j,kind:'line',layer,a:position(c,g.points[j]),b:position(c,b),width:g.width||.12}));}))];}
function validate(input){let p=migrate(input),legacy=cl(p);legacy.schema=1;legacy.baseline=legacy.baseline?{...legacy.baseline,snapshot:undefined}:null;for(let c of legacy.components)for(let a of c.pads){a.diameter=Math.max(a.diameter,a.width,a.height,a.drill+.01);if(['open_collector','tri_state','no_connect'].includes(a.type))a.type='passive';}base.validate(legacy);
 const fail=m=>{throw Error('Invalid project: '+m);},num=(v,lo,hi,n)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<lo||v>hi)fail(n);},str=(s,n,max=100)=>{if(typeof s!=='string'||s.length>max)fail(n);},point=q=>{num(q?.x,-1000,1000,'X coordinate');num(q?.y,-1000,1000,'Y coordinate');},arr=(a,max,n)=>{if(!Array.isArray(a)||a.length>max)fail(n);},ids=new Set([...p.components,...p.tracks,...p.vias].map(x=>x.id));function checkId(x){str(x.id,'object identity');if(!/^[\w-]+$/.test(x.id)||ids.has(x.id))fail('duplicate object identity');ids.add(x.id);}const net=n=>{if(!p.nets.includes(n))fail('unknown net '+n);};
 arr(p.sheets,40,'sheets');if(!p.sheets.length)fail('missing sheet');let sids=new Set(p.sheets.map(s=>s.id));if(sids.size!==p.sheets.length)fail('duplicate sheet');for(let s of p.sheets){str(s.id,'sheet id');str(s.name,'sheet name',80);if(s.parent!==null&&!sids.has(s.parent))fail('unknown parent sheet');let seen=new Set([s.id]),a=s;while(a.parent){if(seen.has(a.parent))fail('sheet hierarchy cycle');seen.add(a.parent);a=p.sheets.find(x=>x.id===a.parent);}}
 for(let c of p.components){if(!sids.has(c.sheet))fail('component sheet');num(c.height,.1,100,'body height');num(c.courtyard,0,10,'courtyard');str(c.footprintName,'footprint name',200);if(typeof c.locked!=='boolean')fail('locked flag');str(c.symbol.kind,'symbol kind');arr(c.symbol.pins,1024,'symbol pins');let pinNumbers=new Set();for(let a of c.symbol.pins){str(a.n,'symbol pin');if(pinNumbers.has(a.n)||!c.pads.some(b=>(b.pin||b.n)===a.n))fail('symbol pin mapping');pinNumbers.add(a.n);point(a);}for(let a of c.pads){if(!['circle','rect','oval','roundrect'].includes(a.shape))fail('pad shape');num(a.width,.1,30,'pad width');num(a.height,.1,30,'pad height');num(a.rotation,0,359.999,'pad rotation');num(a.slot,0,30,'slot length');if(a.labelNet)net(a.labelNet);if(a.mount==='tht'&&(a.drill>=Math.min(a.width,a.height)||a.slot>a.width))fail('pad drill/slot larger than copper');if(a.shape==='circle'&&Math.abs(a.width-a.height)>1e-6)fail('circular pad width/height mismatch');}}
 arr(p.junctions,500,'junctions');for(let j of p.junctions){checkId(j);point(j);if(!sids.has(j.sheet))fail('junction sheet');if(j.net)net(j.net);}arr(p.wires,1000,'wires');for(let w of p.wires){checkId(w);net(w.net);arr(w.points,100,'wire corners');w.points.forEach(point);let a=endpoint(p,w.from),b=endpoint(p,w.to);if(!a||!b||a.sheet!==w.sheet||b.sheet!==w.sheet)fail('wire endpoint');if(a.net!==w.net||b.net!==w.net)fail('wire net does not match its endpoints');}
 arr(p.labels,300,'labels');for(let l of p.labels){checkId(l);str(l.pin,'label pin');net(l.net);if(!['label','power','ground'].includes(l.kind)||!p.components.some(c=>c.id===l.component&&c.pads.some(a=>a.n===l.pin)))fail('label anchor');}
 const polygon=(a,n)=>{arr(a,200,n);if(a.length&&a.length<3)fail(n+' needs at least three points');a.forEach(point);};polygon(p.board.outline,'outline');arr(p.cutouts,30,'cutouts');for(let a of p.cutouts){checkId(a);polygon(a.points,'cutout');}
 arr(p.holes,100,'holes');for(let a of p.holes){checkId(a);point(a);num(a.drill,.2,30,'hole drill');num(a.slot,0,60,'hole slot');num(a.rotation,0,359.999,'hole rotation');if(typeof a.plated!=='boolean'||a.plated)fail('mechanical holes must be nonplated');}
 arr(p.silk,300,'silkscreen');let imageRunCount=0;for(let a of p.silk){checkId(a);if(!['F','B'].includes(a.layer)||!['text','line','image'].includes(a.kind))fail('silkscreen type');if(a.kind!=='image')num(a.width,.05,3,'silkscreen width');if(a.kind==='image'){point(a);str(a.name,'image name',160);num(a.rotation,0,359.999,'image rotation');num(a.sizeX,.1,500,'image width');num(a.sizeY,.1,500,'image height');num(a.pixelWidth,1,256,'raster width');num(a.pixelHeight,1,256,'raster height');if(!Number.isInteger(a.pixelWidth)||!Number.isInteger(a.pixelHeight)||typeof a.mirror!=='boolean')fail('image raster');arr(a.runs,6000,'image rectangles');imageRunCount+=a.runs.length;if(!a.runs.length||imageRunCount>12000)fail('image rectangle budget');for(let r of a.runs){if(!Array.isArray(r)||r.length!==4||r.some(n=>!Number.isInteger(n))||r[0]<0||r[1]<0||r[2]<1||r[3]<1||r[0]+r[2]>a.pixelWidth||r[1]+r[3]>a.pixelHeight)fail('image rectangle');}}else if(a.kind==='text'){point(a);str(a.text,'silkscreen text',120);num(a.size,.5,10,'silkscreen text size');num(a.rotation,0,359.999,'silkscreen rotation');}else{point(a.a);point(a.b);}}
 arr(p.zones,20,'zones');for(let z of p.zones){checkId(z);net(z.net);if(!['F','B'].includes(z.layer))fail('zone layer');polygon(z.points,'zone boundary');num(z.clearance,.1,5,'zone clearance');num(z.thermalGap,.1,5,'thermal gap');num(z.spoke,.1,5,'thermal spoke');if(typeof z.thermal!=='boolean')fail('thermal flag');}
 for(let k of ['drill','maskWeb','courtyard','silk','silkLine'])num(p.rules[k],0,5,'design rule '+k);
 arr(p.ports,100,'ports');for(let a of p.ports){checkId(a);if(!sids.has(a.sheet))fail('port sheet');str(a.name,'port name',60);net(a.net);if(!['input','output','bidirectional','power'].includes(a.direction))fail('port direction');}
 arr(p.netClasses,20,'net classes');for(let a of p.netClasses){str(a.name,'class name');arr(a.nets,256,'class nets');a.nets.forEach(net);num(a.width,.05,10,'class width');num(a.clearance,.05,5,'class clearance');}
 if(!p.library||typeof p.library!=='object')fail('library');for(let k of ['symbols','footprints','devices','blocks']){arr(p.library[k],2000,'library '+k);for(let a of p.library[k]){str(a.id,'library id');str(a.name,'library name',160);if(JSON.stringify(a).length>200000)fail('oversize library entry');}}arr(p.importNotes,100,'import notes');p.importNotes.forEach(a=>str(a,'import note',1000));return p;
}
Object.assign(C,{logicalPads,holes,silks,migrate,validate,fresh:blank,sample,component,schLocal,position,pads,endpoint,endpointKey,wirePath,mergeNet,rebuildNets,link,splitWire,removeWire,removeComponent,renumber,symbolFrom,footprintFrom,applySymbol,applyFootprint});
if(typeof module!=='undefined')module.exports=C;else root.CB=C;
})(typeof globalThis!=='undefined'?globalThis:this);
