/* CIRCUITBENCH dimensioned 3D assembly viewer. GPL-3.0-only. Three.js is MIT. */
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
export function create(host,p,C){
 const G=C.G,scene=new THREE.Scene();scene.background=new THREE.Color('#e8ede4');const camera=new THREE.PerspectiveCamera(40,1,.05,4000);camera.up.set(0,0,1);const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D assembly: drag to orbit, wheel to zoom, right-drag to pan');renderer.domElement.tabIndex=0;const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.target.set(p.board.width/2,-p.board.height/2,0);controls.minDistance=2;controls.maxDistance=2000;let dead=false;
 scene.add(new THREE.HemisphereLight(0xffffff,0x364d40,2.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(30,-30,90);scene.add(light);const fill=new THREE.DirectionalLight(0xffffff,2);fill.position.set(-30,30,-80);scene.add(fill);
 const group=new THREE.Group(),bodies=new THREE.Group(),copper=new THREE.Group(),silk=new THREE.Group();scene.add(group,bodies,copper,silk);const material=(color,roughness=.5)=>new THREE.MeshStandardMaterial({color,roughness,metalness:color===0xc5a36a?.5:0,side:THREE.DoubleSide});
 function makePath(poly,shape){let path=shape?new THREE.Shape():new THREE.Path();poly.forEach((q,i)=>i?path.lineTo(q.x,-q.y):path.moveTo(q.x,-q.y));path.closePath();return path;}
 function shapes(paths){return G.splitRegions(G.union(paths)).map(region=>{let s=makePath(region[0],true);s.holes=region.slice(1).map(h=>makePath(h,false));return s;});}
 function plane(paths,z,color,target){for(let shape of shapes(paths)){let mesh=new THREE.Mesh(new THREE.ShapeGeometry(shape),material(color));mesh.position.z=z;target.add(mesh);}}
 let holes=[...C.pads(p).filter(a=>a.drill),...p.vias,...C.holes(p)].map(a=>G.drillPolygon(a)),board=G.difference(G.boardMaterial(p),holes);for(let s of shapes(board)){let geo=new THREE.ExtrudeGeometry(s,{depth:p.board.thickness,bevelEnabled:false,steps:1,curveSegments:24}),mesh=new THREE.Mesh(geo,material(C.boardAppearance(p.board).color));mesh.position.z=-p.board.thickness/2;group.add(mesh);}
 for(let side of ['F','B']){let z=(side==='F'?1:-1)*(p.board.thickness/2+.025);plane(G.union(C.copper(p).filter(a=>a.layer==='both'||a.layer===side).flatMap(a=>a.paths)),z,0xc5a36a,copper);plane(G.union(C.silks(p).filter(a=>a.layer===side).flatMap(a=>C.silkPaths(a))),z+(side==='F'?.015:-.015),C.boardAppearance(p.board).ink,silk);}
 for(let c of p.components){let geo;if(['led','electrolytic'].includes(c.kind)){geo=new THREE.CylinderGeometry(Math.min(...c.body)/2,Math.min(...c.body)/2,c.height,32);geo.rotateX(Math.PI/2);}else geo=new THREE.BoxGeometry(c.body[0],c.body[1],c.height);let mesh=new THREE.Mesh(geo,material(c.kind==='led'?0x53b978:c.kind==='resistor'?0xb49561:c.kind.includes('capacitor')?0x947044:0x303633));mesh.position.set(c.pcb.x,-c.pcb.y,(c.pcb.side==='F'?1:-1)*(p.board.thickness/2+c.height/2));mesh.rotation.z=-c.pcb.rotation*Math.PI/180;mesh.userData={ref:c.ref,baseZ:mesh.position.z,side:c.pcb.side};bodies.add(mesh);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:0x66796b}));mesh.add(edges);}
 function draw(){if(!dead)renderer.render(scene,camera);}controls.addEventListener('change',draw);const resize=new ResizeObserver(()=>{if(dead)return;camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);draw();});resize.observe(host);
 function view(name){let span=Math.max(p.board.width,p.board.height,20)*1.1,t=controls.target;camera.position.set(t.x+span*.7,t.y-span*.8,t.z+span);if(name==='top')camera.position.set(t.x,t.y-.001,t.z+span*1.5);if(name==='bottom')camera.position.set(t.x,t.y+.001,t.z-span*1.5);controls.update();draw();}view('iso');
 return {view,explode(value){for(let m of bodies.children)m.position.z=m.userData.baseZ+(m.userData.side==='F'?1:-1)*value;draw();},visibility(key,value){({bodies,copper,silk})[key].visible=value;draw();},png:()=>renderer.domElement.toDataURL('image/png'),stats:()=>({meshes:group.children.length+bodies.children.length+copper.children.length+silk.children.length,bodies:bodies.children.length,boardColor:group.children[0]?.material.color.getHexString(),renderer:renderer.info.render}),dispose(){dead=true;resize.disconnect();controls.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material)for(let m of Array.isArray(o.material)?o.material:[o.material])m.dispose();});renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();}};
}

// Enclosure preview reuses the offline renderer and orbit controls. Geometry
// comes from the same solid meshes that are written to STL.
export function createEnclosure(host,C){
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,1,.05,5000);camera.up.set(0,0,1);
 const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.appendChild(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Enclosure preview. Drag to orbit; scroll to zoom; right-drag to pan.');
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minDistance=5;controls.maxDistance=2500;
 scene.add(new THREE.HemisphereLight(0xffffff,0x394d49,2.7));for(let [x,y,z,intensity] of [[50,-70,130,3],[-60,50,80,2]]){let l=new THREE.DirectionalLight(0xffffff,intensity);l.position.set(x,y,z);scene.add(l);}
 const shell=new THREE.Group(),board=new THREE.Group(),bodies=new THREE.Group();scene.add(shell,board,bodies);let current=null,base=null,lid=null,dead=false,explode=15,ghost=true,showLid=true,showBoard=true;
 const mat=(color)=>new THREE.MeshStandardMaterial({color,roughness:.65,side:THREE.DoubleSide});
 function clear(group){for(let child of [...group.children]){child.traverse(o=>{o.geometry?.dispose();if(o.material)for(let m of Array.isArray(o.material)?o.material:[o.material])m.dispose();});group.remove(child);}}
 function draw(){if(!dead)renderer.render(scene,camera);}
 function mesh(data,color){let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(data.positions,3));g.setIndex(new THREE.BufferAttribute(data.indices,1));g.computeVertexNormals();let m=new THREE.Mesh(g,mat(color));shell.add(m);return m;}
 function path(poly,shape){let s=shape?new THREE.Shape():new THREE.Path();poly.forEach((q,i)=>i?s.lineTo(q.x,-q.y):s.moveTo(q.x,-q.y));s.closePath();return s;}
 function refresh(){if(!current)return;base.material.transparent=ghost;base.material.opacity=ghost?.36:1;base.material.depthWrite=!ghost;lid.visible=showLid;lid.position.set(0,-current.depth,current.baseTop+current.config.lid+explode);lid.rotation.x=Math.PI;lid.scale.set(1,-1,1);board.visible=bodies.visible=showBoard;draw();}
 function update(data,plan){let first=!current;current=plan;clear(shell);clear(board);clear(bodies);base=mesh(data.base,0x327485);base.scale.y=-1;lid=mesh(data.lid,0xd7b774);
  const G=C.G,paths=G.difference(G.difference([plan.board.outline],plan.board.cutouts),plan.board.holes);
  for(let region of G.splitRegions(G.union(paths))){let s=path(region[0],true);s.holes=region.slice(1).map(h=>path(h,false));let geometry=new THREE.ExtrudeGeometry(s,{depth:plan.pcbThickness,bevelEnabled:false,steps:1}),m=new THREE.Mesh(geometry,mat(C.boardAppearance(plan.board).color));m.position.z=plan.pcbBottom;board.add(m);}
  for(let c of plan.components){let m=new THREE.Mesh(new THREE.BoxGeometry(c.width,c.depth,c.height),mat(c.side==='B'?0x946a45:0x3c4143));m.position.set(c.x,-c.y,c.bottom+c.height/2);m.rotation.z=-c.rotation*Math.PI/180;bodies.add(m);}
  const dark=document.body.dataset.theme!=='light';scene.background=new THREE.Color(dark?'#162a28':'#e8ede4');refresh();if(first)view('iso');
 }
 function view(name){if(!current)return;let p=current,span=Math.max(p.width,p.depth,p.totalHeight+explode)*1.5,t=new THREE.Vector3(p.width/2,-p.depth/2,p.totalHeight/2);controls.target.copy(t);camera.position.set(t.x+span*.65,t.y-span*.85,t.z+span*.85);if(name==='top')camera.position.set(t.x,t.y-.001,t.z+span*1.6);if(name==='front')camera.position.set(t.x,span,t.z+span*.12);if(name==='side')camera.position.set(p.width+span,t.y,t.z+span*.12);controls.update();draw();}
 const resize=new ResizeObserver(()=>{if(dead)return;camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);draw();});resize.observe(host);controls.addEventListener('change',draw);
 return {update,view,options(o){explode=o.explode??explode;ghost=o.ghost??ghost;showLid=o.lid??showLid;showBoard=o.board??showBoard;refresh();},png:()=>renderer.domElement.toDataURL('image/png'),stats:()=>({parts:shell.children.length,components:bodies.children.length,triangles:renderer.info.render.triangles}),dispose(){dead=true;resize.disconnect();controls.dispose();clear(shell);clear(board);clear(bodies);renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();}};
}
