/* CIRCUITBENCH dimensioned 3D assembly viewer. GPL-3.0-only. Three.js is MIT. */
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
export function create(host,p,C){
 const G=C.G,scene=new THREE.Scene();scene.background=new THREE.Color('#e8ede4');const camera=new THREE.PerspectiveCamera(40,1,.05,4000);camera.up.set(0,0,1);const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D assembly: drag to orbit, wheel to zoom, right-drag to pan');renderer.domElement.tabIndex=0;const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.target.set(p.board.width/2,-p.board.height/2,0);controls.minDistance=2;controls.maxDistance=2000;let dead=false;
 scene.add(new THREE.HemisphereLight(0xffffff,0x364d40,2.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(30,-30,90);scene.add(light);const fill=new THREE.DirectionalLight(0xffffff,2);fill.position.set(-30,30,-80);scene.add(fill);
 const group=new THREE.Group(),bodies=new THREE.Group(),copper=new THREE.Group(),silk=new THREE.Group();scene.add(group,bodies,copper,silk);const material=(color,roughness=.5)=>new THREE.MeshStandardMaterial({color,roughness,metalness:color===0xc5a36a?.5:0,side:THREE.DoubleSide});
 function makePath(poly,shape){let path=shape?new THREE.Shape():new THREE.Path();poly.forEach((q,i)=>i?path.lineTo(q.x,-q.y):path.moveTo(q.x,-q.y));path.closePath();return path;}
 function shapes(paths){return G.splitRegions(G.union(paths)).map(region=>{let s=makePath(region[0],true);s.holes=region.slice(1).map(h=>makePath(h,false));return s;});}
 function plane(paths,z,color,target){for(let shape of shapes(paths)){let mesh=new THREE.Mesh(new THREE.ShapeGeometry(shape),material(color));mesh.position.z=z;target.add(mesh);}}
 let holes=[...C.pads(p).filter(a=>a.drill),...p.vias,...C.holes(p)].map(a=>G.drillPolygon(a)),board=G.difference(G.boardMaterial(p),holes);for(let s of shapes(board)){let geo=new THREE.ExtrudeGeometry(s,{depth:p.board.thickness,bevelEnabled:false,steps:1,curveSegments:24}),mesh=new THREE.Mesh(geo,material(0x205f48));mesh.position.z=-p.board.thickness/2;group.add(mesh);}
 for(let side of ['F','B']){let z=(side==='F'?1:-1)*(p.board.thickness/2+.025);plane(G.union(C.copper(p).filter(a=>a.layer==='both'||a.layer===side).flatMap(a=>a.paths)),z,0xc5a36a,copper);plane(G.union(C.silks(p).filter(a=>a.layer===side).flatMap(a=>C.silkPaths(a))),z+(side==='F'?.015:-.015),0xf6f5df,silk);}
 for(let c of p.components){let geo;if(['led','electrolytic'].includes(c.kind)){geo=new THREE.CylinderGeometry(Math.min(...c.body)/2,Math.min(...c.body)/2,c.height,32);geo.rotateX(Math.PI/2);}else geo=new THREE.BoxGeometry(c.body[0],c.body[1],c.height);let mesh=new THREE.Mesh(geo,material(c.kind==='led'?0x53b978:c.kind==='resistor'?0xb49561:c.kind.includes('capacitor')?0x947044:0x303633));mesh.position.set(c.pcb.x,-c.pcb.y,(c.pcb.side==='F'?1:-1)*(p.board.thickness/2+c.height/2));mesh.rotation.z=-c.pcb.rotation*Math.PI/180;mesh.userData={ref:c.ref,baseZ:mesh.position.z,side:c.pcb.side};bodies.add(mesh);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:0x66796b}));mesh.add(edges);}
 function draw(){if(!dead)renderer.render(scene,camera);}controls.addEventListener('change',draw);const resize=new ResizeObserver(()=>{if(dead)return;camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);draw();});resize.observe(host);
 function view(name){let span=Math.max(p.board.width,p.board.height,20)*1.1,t=controls.target;camera.position.set(t.x+span*.7,t.y-span*.8,t.z+span);if(name==='top')camera.position.set(t.x,t.y-.001,t.z+span*1.5);if(name==='bottom')camera.position.set(t.x,t.y+.001,t.z-span*1.5);controls.update();draw();}view('iso');
 return {view,explode(value){for(let m of bodies.children)m.position.z=m.userData.baseZ+(m.userData.side==='F'?1:-1)*value;draw();},visibility(key,value){({bodies,copper,silk})[key].visible=value;draw();},png:()=>renderer.domElement.toDataURL('image/png'),stats:()=>({meshes:group.children.length+bodies.children.length+copper.children.length+silk.children.length,bodies:bodies.children.length,renderer:renderer.info.render}),dispose(){dead=true;resize.disconnect();controls.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material)for(let m of Array.isArray(o.material)?o.material:[o.material])m.dispose();});renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();}};
}
