/* CIRCUITBENCH extended editors. GPL-3.0-only. */
(function(){'use strict';
const old={render,renderInspector,renderLeft,renderReview,renderCanvas,setView,setTool,drawLive,selectedObject,footprintDialog,applyFootprint,deleteSelected,exportDialog,helpDialog,projectDialog,printReport};
let sheet='main',pendingWire=null,groupSelection=new Set(),routeAssist=true,showZones=true,showSilk=true,showCourtyard=false;
const polyPath=paths=>paths.map(poly=>poly.length?poly.map((q,i)=>(i?'L':'M')+q.x+','+q.y).join(' ')+'Z':'').join(' '),num=(s)=>Number($(s).value),extra=(label,action,cls='')=>`<button class="${cls}" data-extra="${action}">${label}</button>`;
function selectedC(){return p.components.find(c=>c.id===selected);}
function sheetComponents(){return p.components.filter(c=>c.sheet===sheet);}
function reject(e){e.preventDefault();e.stopImmediatePropagation();}
selectedObject=function(){return old.selectedObject()||[...p.wires,...p.junctions,...p.holes,...p.cutouts,...p.silk,...p.zones].find(x=>x.id===selected)||null;};
function field2(label,id,value,type='text',more=''){return `<label>${label}<input id="${id}" type="${type}" value="${esc(value)}" ${more}></label>`;}
function showFormError(e){let el=$('#extraError');if(!el){$('#dialogBody').insertAdjacentHTML('beforeend','<p id="extraError" role="alert" class="notice"></p>');el=$('#extraError');}el.textContent=e.message||String(e);}
function safeEdit(fn,msg){let before=JSON.stringify(p);try{fn();p=CB.validate(p);history.push(before);if(history.length>60)history.shift();future=[];changed(msg);return true;}catch(e){p=JSON.parse(before);say(e.message);if($('#dialog').open)showFormError(e);return false;}}
function addControls(){if(!$('#extendedTools')){$('#editorToolbar').insertAdjacentHTML('afterend',`<div id="extendedTools" class="extendedTools"><span id="schematicTools"><label>Sheet <select id="sheetSelect"></select></label>${extra('Sheets','sheets')}${extra('Junction','junction')}${extra('Label / power','power')}</span><span id="pcbTools">${extra('Board tools','board')}${extra('Route to pin','route-dialog')}${extra('3D assembly','assembly')}</span><span class="spacer"></span>${extra('Libraries','libraries')}${extra('Blocks','blocks')}<span id="groupHint"></span></div>`);}$('#extendedTools').hidden=view==='review';$('#schematicTools').hidden=view!=='sch';$('#pcbTools').hidden=view!=='pcb';$('#sheetSelect').innerHTML=options(p.sheets.map(s=>[s.id,(s.parent?'↳ ':'')+s.name]),sheet);$('#groupHint').textContent=groupSelection.size?groupSelection.size+' selected':'';}
render=function(){if(!p.sheets.some(s=>s.id===sheet))sheet=p.sheets[0].id;old.render();addControls();$('.version').textContent='v'+CB.VERSION;$('#canvasEyebrow').textContent=view==='sch'?'SCHEMATIC / '+(p.sheets.find(s=>s.id===sheet)?.name||''):($('#layer').value==='F'?'FRONT COPPER · F.Cu':'BACK COPPER · B.Cu')+' / TOP VIEW';};
setView=function(next){pendingWire=null;groupSelection.clear();let c=selectedC();if(next==='sch'&&c)sheet=c.sheet;old.setView(next);};
setTool=function(next){pendingWire=null;old.setTool(next);};
renderLeft=function(){old.renderLeft();if(prefs.left==='library'){$('#leftContent').insertAdjacentHTML('beforeend',`<div class="inspectSection"><h4>Saved devices</h4>${p.library.devices.filter(d=>d.name.toLowerCase().includes(libraryQuery.toLowerCase())).map(d=>`<button class="part" data-device="${esc(d.id)}"><span><strong>${esc(d.name)}</strong><small>Reusable symbol + footprint</small></span><span>+</span></button>`).join('')||'<small>Save a selected part in Libraries.</small>'}</div>`);}else{if(view==='sch')for(let b of $$('#leftContent [data-select]')){let c=p.components.find(c=>c.id===b.dataset.select);if(c&&c.sheet!==sheet)b.hidden=true;}$('#leftContent').insertAdjacentHTML('beforeend',`<div class="inspectSection"><h4>Board objects</h4>${[['Tracks',p.tracks],['Vias',p.vias],['Holes',p.holes],['Zones',p.zones],['Silkscreen',p.silk],['Cutouts',p.cutouts]].map(([name,items])=>`<details><summary>${name} · ${items.length}</summary>${items.map((x,i)=>`<button class="objectRow" data-select="${x.id}">${esc(x.text||x.name||x.net||name.slice(0,-1)+' '+(i+1))}</button>`).join('')}</details>`).join('')}</div>`);}};
renderInspector=function(){let x=selectedObject();if(x&&p.wires.includes(x)){$('#selectionType').textContent='WIRE';$('#inspector').innerHTML=`<div class="inspectSection"><h3>${esc(x.net)}</h3><p>Wire on ${esc(p.sheets.find(s=>s.id===x.sheet)?.name)}. Endpoints follow their pins or junctions.</p>${extra('Edit corners','wire-edit')}${extra('Delete wire','delete','danger')}<p>Deleting a wire splits unnamed connections. Matching explicit net labels remain connected.</p></div>`;return;}if(x&&p.junctions.includes(x)){$('#selectionType').textContent='JUNCTION';$('#inspector').innerHTML=`<div class="inspectSection"><h3>Junction · ${esc(x.net)}</h3>${field2('X','junctionX',x.x,'number','step="1"')}${field2('Y','junctionY',x.y,'number','step="1"')}${extra('Apply position','junction-apply')}${extra('Delete junction','delete','danger')}</div>`;return;}if(x&&(p.holes.includes(x)||p.cutouts.includes(x)||p.silk.includes(x)||p.zones.includes(x))){renderBoardObject(x);return;}
 old.renderInspector();let c=selectedC();if(c){$('#inspector').insertAdjacentHTML('afterbegin',`<div class="inspectSection compact"><label class="inlinecheck"><input id="lockPart" type="checkbox" ${c.locked?'checked':''}> Lock placement</label>${extra('Save to library','save-device')}${extra('Select for block','select-group')}</div>`);if(prefs.mode==='advanced')$('#inspector').insertAdjacentHTML('beforeend',`<div class="inspectSection"><h4>Assembly & sheet</h4>${field2('Component height mm','componentHeight',c.height,'number','min="0.1" max="100" step="0.1"')}${field2('Courtyard margin mm','componentCourtyard',c.courtyard,'number','min="0" max="10" step="0.1"')}<label>Sheet<select id="componentSheet">${options(p.sheets.map(s=>[s.id,s.name]),c.sheet)}</select></label>${extra('Apply assembly properties','component-assembly')}${extra('Symbol geometry','symbol-edit')}</div>`);}else if(!x){$('#inspector').insertAdjacentHTML('beforeend',`<div class="inspectSection"><h4>Board & fabrication</h4>${extra('Outline, holes & copper','board')}${extra('Design rules & net classes','rules')}${extra('Revision comparison','compare')}</div>`);}
 if(view==='pcb')$('#inspector').insertAdjacentHTML('beforeend',`<div class="inspectSection"><h4>Display & route</h4><label class="inlinecheck"><input id="showZones" type="checkbox" ${showZones?'checked':''}> Copper zones</label><label class="inlinecheck"><input id="showSilk" type="checkbox" ${showSilk?'checked':''}> Manufacturing silkscreen</label><label class="inlinecheck"><input id="showCourtyard" type="checkbox" ${showCourtyard?'checked':''}> Courtyards</label><label class="inlinecheck"><input id="routeAssist" type="checkbox" ${routeAssist?'checked':''}> Obstacle-aware route to pin</label></div>`);
};
boardSVG=function(forPrint=false){let G=CB.G,out=`<path d="${polyPath(G.boardMaterial(p))}" fill="#153e35" fill-rule="evenodd" stroke="#67967b" stroke-width=".15"/>`;const active=$('#layer').value, layers=forPrint?['B','F']:showOther?[active==='F'?'B':'F',active]:[active], layerStyle=l=>forPrint?'':`data-board-layer="${l}" opacity="${l===active?1:.18}" ${l!==active?'pointer-events="none"':''}`;if(showZones||forPrint)for(let a of CB.zones(p).filter(z=>layers.includes(z.layer)))out+=`<path d="${polyPath(a.paths)}" fill="${a.layer==='F'?'#e8a264':'#60a6e0'}" fill-rule="evenodd" opacity="${forPrint||a.layer===active?.42:.08}" data-board-layer="${a.layer}" ${!forPrint&&a.layer!==active?'pointer-events="none"':''} data-object="${a.owner}"/>`;
 for(let layer of layers)for(let t of p.tracks.filter(t=>t.layer===layer)){out+=`<g ${layerStyle(layer)}>`;out+=`<path d="${path(t.points)}" fill="none" stroke="${layer==='F'?'#eea574':'#67b5f3'}" stroke-width="${t.width}" stroke-linecap="round" stroke-linejoin="round" data-object="${t.id}"/><path d="${path(t.points)}" fill="none" stroke="transparent" stroke-width="${Math.max(t.width,1.25)}" data-object="${t.id}"/>`;if(selected===t.id&&!forPrint)out+=`<path d="${path(t.points)}" fill="none" stroke="#fff" stroke-width=".16" stroke-dasharray=".6 .4" pointer-events="none"/>`;out+='</g>';}
 for(let c of p.components){let pos=c.pcb,b=c.body,stroke=selected===c.id||groupSelection.has(c.id)?'#fff':'#9bb6a4';out+=`<g data-object="${c.id}" ${layerStyle(pos.side)}><g transform="translate(${pos.x} ${pos.y}) rotate(${pos.rotation})"><rect x="${-b[0]/2}" y="${-b[1]/2}" width="${b[0]}" height="${b[1]}" rx=".2" fill="#224c4240" stroke="${stroke}" stroke-width="${selected===c.id?.3:.14}"/>${showCourtyard?`<rect x="${-b[0]/2-c.courtyard}" y="${-b[1]/2-c.courtyard}" width="${b[0]+2*c.courtyard}" height="${b[1]+2*c.courtyard}" fill="none" stroke="#c3a6da" stroke-dasharray=".7 .4" stroke-width=".1"/>`:''}</g>`;if(showLabels||forPrint)out+=`<text x="${pos.x}" y="${pos.y-b[1]/2-1.5}" font-size="1.25" fill="#edf3dc" text-anchor="middle" pointer-events="none">${esc(c.ref)}${c.locked?' [L]':''}</text><text x="${pos.x}" y="${pos.y+b[1]/2+2}" font-size=".9" fill="#b3cdb9" text-anchor="middle" pointer-events="none">${esc(c.value)}</text>`;out+='</g>';}
 for(let a of CB.pads(p)){if(a.layer!=='both'&&!layers.includes(a.layer))continue;let paths=[G.padPolygon(a)];if(a.drill)paths=G.difference(paths,[G.drillPolygon(a)]);out+=`<g data-object="${a.component}" ${a.layer==='both'?'':layerStyle(a.layer)}><path d="${polyPath(paths)}" fill="${a.layer==='B'?'#78bfff':'#efbb7c'}" fill-rule="evenodd" stroke="${activeNet===a.net&&a.net?'#fff':'none'}" stroke-width=".16" ${terminalAttrs(a.component,a.n)}/>${a.drill?`<path d="${polyPath([G.drillPolygon(a)])}" fill="#0b1c17" ${terminalAttrs(a.component,a.n)}/>`:''}<text x="${a.x}" y="${a.y+.22}" font-size=".6" text-anchor="middle" fill="#fff" pointer-events="none">${esc(a.n)}</text></g>`;}
 for(let v of p.vias)out+=`<g data-object="${v.id}"><circle cx="${v.x}" cy="${v.y}" r="${v.diameter/2}" fill="#dbbe74" stroke="${selected===v.id?'white':'#9cbaa7'}" stroke-width=".1" ${terminalAttrs(v.id,'via')}/><circle cx="${v.x}" cy="${v.y}" r="${v.drill/2}" fill="#0a1d18" ${terminalAttrs(v.id,'via')}/></g>`;
 for(let h of CB.holes(p))out+=`<path d="${polyPath([G.drillPolygon(h)])}" fill="var(--field)" stroke="${selected===h.id?'white':'#76968b'}" stroke-width=".12" data-object="${h.id}"/>`;
 if(showSilk||forPrint)for(let s of CB.silks(p).filter(a=>layers.includes(a.layer))){try{out+=`<path d="${polyPath(CB.silkPaths(s))}" fill-rule="evenodd" fill="${selected===s.id?'#ffea94':'#f1f3d9'}" ${layerStyle(s.layer)} data-object="${s.id}"/>`;}catch(e){}}
 if(!forPrint)for(let k of CB.keepouts?CB.keepouts(p):[])out+=`<path d="${polyPath([k.points])}" fill="#d2719320" stroke="#d28cac" stroke-width=".15" stroke-dasharray=".8 .5" pointer-events="none"/>`;
 if(showRats&&!forPrint)for(let l of CB.connections(p))out+=line(l.a,l.b,l.net===activeNet?'#fff':'#c1d88d',.12,'stroke-dasharray=".7 .5" opacity=".8" pointer-events="none"');return out;
};
schematicSVG=function(){let ink=prefs.theme==='light'?'#263d35':'#e4eddf',green=prefs.theme==='light'?'#267148':'#9cdeb4',out='';if(showWireMap)for(let l of CB.connections(p,'sch').filter(l=>l.a.sheet===sheet&&l.b.sheet===sheet))out+=line(l.a,l.b,'#b58c42',.14,'stroke-dasharray="1 1" pointer-events="none"');for(let w of p.wires.filter(w=>w.sheet===sheet)){let pts=CB.wirePath(p,w);out+=`<path d="${path(pts)}" fill="none" stroke="${selected===w.id?'#ba7e26':green}" stroke-width="${selected===w.id?.55:.3}" data-wire="${w.id}"/><path d="${path(pts)}" fill="none" stroke="transparent" stroke-width="1.8" data-wire="${w.id}"/>`;}
 for(let j of p.junctions.filter(j=>j.sheet===sheet))out+=`<circle cx="${j.x}" cy="${j.y}" r=".85" fill="${selected===j.id?'#ba7e26':green}" data-junction="${j.id}"/>`;
 for(let c of sheetComponents()){if(c.symbol.graphics?.length&&window.CBLibraryRender){out+=`<g data-object="${c.id}" transform="translate(${c.sch.x} ${c.sch.y}) rotate(${c.sch.rotation})">${CBLibraryRender.symbolMarkup(c,{interactive:true,labels:showLabels,selected:selected===c.id})}</g>`;continue;}let t=c.sch,n=c.pads.length,h=n===2?6:Math.max(8,Math.ceil(n/2)*5),fill=prefs.theme==='light'?'#fbfcf4':'#20392e';out+=`<g data-object="${c.id}"><g transform="translate(${t.x} ${t.y}) rotate(${t.rotation})"><rect x="-7" y="${-h/2}" width="14" height="${h}" rx=".4" fill="${fill}" stroke="${selected===c.id||groupSelection.has(c.id)?'#b5832f':ink}" stroke-width="${selected===c.id?.6:.35}"/>`;if(['resistor','smd2'].includes(c.symbol.kind))out+=`<path d="M-5 0h1l1-2 2 4 2-4 2 4 1-2h1" fill="none" stroke="${ink}" stroke-width=".4"/>`;else if(['capacitor','electrolytic'].includes(c.symbol.kind))out+=`<path d="M-5 0h4m0-2v4m2-4v4m0-2h4" stroke="${ink}" stroke-width=".4"/>`;else if(['led','diode'].includes(c.symbol.kind))out+=`<path d="M-3-2L1 0 -3 2Z M1-2v4m-6-2h2m4 0h3" fill="none" stroke="${ink}" stroke-width=".4"/>`;out+='</g>';
 for(let a of c.pads){let q=CB.position(c,a,'sch'),l=CB.schLocal(c,a),d=CB.rotate(Math.sign(l.x)||1,0,t.rotation),inner=CB.rotate(Math.sign(l.x)*7,l.y,t.rotation);out+=line(q,{x:t.x+inner.x,y:t.y+inner.y},ink,.3,'pointer-events="none"');out+=`<circle cx="${q.x}" cy="${q.y}" r="1.0" fill="${a.net?green:fill}" stroke="${ink}" stroke-width=".2" ${terminalAttrs(c.id,a.n)}/><text x="${q.x+d.x*2}" y="${q.y-1.5}" font-size="1.5" text-anchor="middle" fill="${ink}" pointer-events="none">${esc(a.n)}</text>`;if(a.labelNet){let end={x:q.x+d.x*5,y:q.y+d.y*5};out+=line(q,end,green,.3,'pointer-events="none"');out+=`<text x="${end.x+d.x}" y="${end.y-1}" text-anchor="${d.x<0?'end':'start'}" font-size="1.7" fill="${green}" pointer-events="none">${esc(a.labelNet)}</text>`;let label=p.labels.find(x=>x.component===c.id&&x.pin===a.n);if(label?.kind==='ground')out+=`<path d="M${end.x-2} ${end.y+1}h4m-3 1h2m-1.5 1h1" fill="none" stroke="${green}" stroke-width=".3" pointer-events="none"/>`;if(label?.kind==='power')out+=`<path d="M${end.x} ${end.y}v-3m-1.5 1.5l1.5-1.5 1.5 1.5" fill="none" stroke="${green}" stroke-width=".3" pointer-events="none"/>`;}
 if(a.nc)out+=`<path d="M${q.x-1.4} ${q.y-1.4}l2.8 2.8m-2.8 0l2.8-2.8" stroke="#bf6c49" stroke-width=".4" pointer-events="none"/>`;}
 if(showLabels)out+=`<text x="${t.x}" y="${t.y-h/2-3}" text-anchor="middle" fill="${ink}" font-size="2.6" font-weight="bold" pointer-events="none">${esc(c.ref)}</text><text x="${t.x}" y="${t.y+h/2+4}" text-anchor="middle" fill="${ink}" font-size="2.1" pointer-events="none">${esc(c.value)}</text>`;out+='</g>';}
 return out;};
drawLive=function(){old.drawLive();if(pendingWire&&view==='sch'){let start=CB.endpoint(p,pendingWire.from);if(start)$('#live')?.insertAdjacentHTML('beforeend',`<path d="${path([start,...pendingWire.points,lastPoint])}" fill="none" stroke="#b88537" stroke-width=".35" stroke-dasharray="1 .6" pointer-events="none"/>`);}};
renderCanvas=function(){old.renderCanvas();if(view==='pcb'){$('#canvasEyebrow').textContent=($('#layer').value==='F'?'FRONT COPPER · F.Cu':'BACK COPPER · B.Cu')+' / TOP VIEW';$('#layer').dataset.side=$('#layer').value;}if(view==='sch'&&tool==='connect')$('#interactionHint').textContent=pendingWire?'Click corners; finish on a pin, junction or existing wire. Esc cancels.':'Click a pin or junction, add corners, then choose the destination.';};
connectPins=function(a,b){let from={kind:'pin',component:a.id,pin:a.pin},to={kind:'pin',component:b.id,pin:b.pin},aa=CB.endpoint(p,from),bb=CB.endpoint(p,to);if(aa?.net&&bb?.net&&aa.net!==bb.net&&!confirm('Merge '+aa.net+' and '+bb.net+'?'))return;safeEdit(()=>CB.link(p,from,to,[{x:bb.x,y:aa.y}]),'Wire created and PCB net connectivity updated.');};
svg.addEventListener('pointerdown',e=>{if(e.button!==0)return;let term=e.target.closest('[data-terminal]'),w=e.target.closest('[data-wire]'),j=e.target.closest('[data-junction]'),obj=e.target.closest('[data-object]');if(view==='sch'&&tool==='connect'){reject(e);let end=term?{kind:'pin',component:term.dataset.terminal,pin:term.dataset.pin}:j?{kind:'junction',id:j.dataset.junction}:null;let splitBefore=null;if(!end&&w){let before=JSON.stringify(p);splitBefore=before;try{end=CB.splitWire(p,w.dataset.wire,point(e));if(!pendingWire){history.push(before);future=[];persist();}}catch(err){say(err.message);return;}}
 if(!pendingWire){if(!end)return say('Start at a pin, junction or wire.');pendingWire={from:end,points:[]};renderCanvas();return;}if(!end){pendingWire.points.push(point(e));renderCanvas();return;}let a=CB.endpoint(p,pendingWire.from),b=CB.endpoint(p,end);if(a?.net&&b?.net&&a.net!==b.net&&!confirm('Merge nets '+a.net+' and '+b.net+'?')){if(splitBefore)p=JSON.parse(splitBefore);return;}let draft=pendingWire,staged=splitBefore?CB.clone(p):null;if(splitBefore)p=JSON.parse(splitBefore);if(safeEdit(()=>{if(staged)p=staged;CB.link(p,draft.from,end,draft.points);},'Wire connected.'))pendingWire=null;renderCanvas();return;}
 if(view==='sch'&&tool==='junction'){reject(e);if(!w)return say('Click an existing wire to create an electrical junction.');safeEdit(()=>{let ref=CB.splitWire(p,w.dataset.wire,point(e));selected=ref.id||null;},'Junction created. Use Connect to add a branch.');return;}
 if(view==='sch'&&(w||j)&&tool==='select'){reject(e);selected=w?.dataset.wire||j.dataset.junction;render();return;}
 let c=obj?p.components.find(c=>c.id===obj.dataset.object):null;if(e.shiftKey&&c&&tool==='select'){reject(e);groupSelection.has(c.id)?groupSelection.delete(c.id):groupSelection.add(c.id);selected=c.id;render();return;}if(c?.locked&&tool==='select'){reject(e);pick(c.id);say(c.ref+' is locked. Unlock in the inspector to move it.');}
},true);
svg.addEventListener('pointermove',()=>{if(pendingWire)drawLive();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){pendingWire=null;renderCanvas();}if(!$('#dialog').open&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)&&(e.key==='Delete'||e.key==='Backspace')){let x=selectedObject();if(x&&(p.wires.includes(x)||p.junctions.includes(x)||p.holes.includes(x)||p.silk.includes(x)||p.zones.includes(x)||p.cutouts.includes(x))){reject(e);deleteSelected();}}},true);
deleteSelected=function(){let x=selectedObject();if(!x)return;if(groupSelection.size>1){safeEdit(()=>{for(let id of groupSelection)CB.removeComponent(p,id);groupSelection.clear();selected=null;},'Selected components removed.');return;}safeEdit(()=>{if(p.components.includes(x))CB.removeComponent(p,x.id);else if(p.wires.includes(x))CB.removeWire(p,x.id);else if(p.junctions.includes(x)){p.wires=p.wires.filter(w=>![w.from,w.to].some(e=>e.kind==='junction'&&e.id===x.id));p.junctions=p.junctions.filter(j=>j.id!==x.id);CB.rebuildNets(p);}else for(let key of ['tracks','vias','holes','silk','zones','cutouts'])p[key]=p[key].filter(a=>a.id!==x.id);selected=null;},'Object removed. Undo is available.');};
footprintDialog=function(){let c=selectedC();if(!c)return;dialog(c.ref+' · Footprint and pin mapping',`<p class="helptext">Physical pad IDs map to logical symbol pins; repeated pads share their assigned net. Renumbering updates attached wires and labels. Dimensions are local millimeters, before component rotation and back-side mirroring.</p><div class="row2">${field2('Body width','bodyWidth',c.body[0],'number','step="0.1"')}${field2('Body height','bodyHeight',c.body[1],'number','step="0.1"')}</div><div class="tablewrap"><table id="padTable"><thead><tr><th>Pin</th><th>Name</th><th>X</th><th>Y</th><th>Shape</th><th>W</th><th>H</th><th>Angle</th><th>Drill</th><th>Slot</th><th>Mount</th><th>Type</th><th></th></tr></thead><tbody>${c.pads.map(a=>padRow(a)).join('')}</tbody></table></div><div class="buttonrow">${extra('Add pin','pad-add')}${extra('Apply footprint','footprint-apply','primary')}</div><p class="helptext">Circle requires equal W/H. Slot is total hole length, zero for a round drill. Only plated pad slots; mechanical slots use Board tools.</p>`);};
padRow=function(a){return `<tr data-pad-row data-old-pin="${esc(a.n)}" data-net-value="${esc(a.net)}" data-label-net="${esc(a.labelNet||'')}" data-nc-value="${a.nc}">${['n','name','x','y'].map(k=>`<td><input data-pad-field="${k}" value="${esc(a[k])}" ${['x','y'].includes(k)?'type="number" step=".01"':''} aria-label="Pin ${esc(a.n)} ${k}"></td>`).join('')}<td><select data-pad-field="shape">${options(['circle','rect','oval','roundrect'],a.shape||'circle')}</select></td>${['width','height','rotation','drill','slot'].map(k=>`<td><input type="number" step=".01" data-pad-field="${k}" value="${a[k]??(k==='width'||k==='height'?a.diameter:0)}" aria-label="Pin ${esc(a.n)} ${k}"></td>`).join('')}<td><select data-pad-field="mount">${options(['tht','smd'],a.mount)}</select></td><td><select data-pad-field="type">${options(['passive','input','output','power_in','power_out','bidirectional','open_collector','tri_state','no_connect'],a.type)}</select></td><td>${extra('×','pad-remove')}</td></tr>`;};
function applyNewFootprint(){let c=selectedC(),rows=$$('#padTable tbody tr'),map={},newpads=rows.map(row=>{let original=c.pads.find(a=>a.n===row.dataset.oldPin),a={...CB.clone(original||{}),net:row.dataset.netValue,labelNet:row.dataset.labelNet,nc:row.dataset.ncValue==='true'};row.querySelectorAll('[data-pad-field]').forEach(e=>a[e.dataset.padField]=e.type==='number'?Number(e.value):e.value);a.diameter=Math.min(a.width,a.height);if(original?.pin&&original.pin!==a.n&&a.n!==row.dataset.oldPin)throw Error('Use Create mapped device to change mapped pad IDs.');if(original?.pin===row.dataset.oldPin)a.pin=a.n;map[row.dataset.oldPin]=a.n;return a;});if(safeEdit(()=>{let removed=c.pads.filter(a=>!map[a.n]);p.wires=p.wires.filter(w=>![w.from,w.to].some(e=>e.kind==='pin'&&e.component===c.id&&removed.some(a=>a.n===e.pin)));p.labels=p.labels.filter(l=>l.component!==c.id||!removed.some(a=>a.n===l.pin));CB.renumber(p,c,map);c.symbol.pins=c.symbol.pins.filter(a=>newpads.some(b=>b.n===a.n));c.body=[num('#bodyWidth'),num('#bodyHeight')];c.pads=newpads;CB.rebuildNets(p);},'Footprint geometry and pin mapping updated.'))closeDialog();}
function symbolDialog(){let c=selectedC();if(!c)return;dialog(c.ref+' · Symbol geometry',`<label>Drawing style<select id="symbolKind">${options(['custom','resistor','capacitor','electrolytic','diode','led','dip8','header2'],c.symbol.kind)}</select></label><div class="tablewrap"><table id="symbolPins"><thead><tr><th>Pin → pad</th><th>X drawing units</th><th>Y drawing units</th></tr></thead><tbody>${c.pads.map(a=>{let q=CB.schLocal(c,a);return `<tr data-n="${esc(a.n)}"><td>${esc(a.n+' · '+a.name)}</td><td><input type="number" value="${q.x}"></td><td><input type="number" value="${q.y}"></td></tr>`;}).join('')}</tbody></table></div>${extra('Apply symbol','symbol-apply','primary')}`);}
function powerDialog(){let c=selectedC();if(!c)return say('Select a component first, then choose Label / power.');dialog('Net label or power symbol',`<label>Pin<select id="labelPin">${options(c.pads.map(a=>[a.n,a.n+' · '+a.name]),c.pads[0].n)}</select></label><label>Symbol<select id="labelKind">${options(['label','power','ground'],'label')}</select></label>${field2('Net name','labelNet',activeNet||'GND')}<p class="helptext">Matching named labels connect across the design. Power symbols label the net; declare a real source pin as power_out for electrical checks.</p>${extra('Apply label','label-apply','primary')}`);}
function libraryDialog(){dialog('Symbols, footprints & devices',`<p class="helptext">Libraries travel inside the project JSON and can be exported separately. Symbols define logical appearance; footprints define board geometry. Compatible pin numbers join them.</p><div class="buttonrow">${extra('Save selected device','save-device')}${extra('Save selected symbol','save-symbol')}${extra('Save selected footprint','save-footprint')}${extra('Export library','library-export')}${extra('Import library','library-import')}</div><div class="row2">${['symbols','footprints','devices'].map(k=>`<section><h3>${k[0].toUpperCase()+k.slice(1)}</h3>${p.library[k].map(a=>`<div class="libraryRow"><span>${esc(a.name)}</span><button data-library-apply="${k}:${esc(a.id)}">${k==='devices'?'Place':'Apply'}</button><button data-library-delete="${k}:${esc(a.id)}" aria-label="Delete ${esc(a.name)}">×</button></div>`).join('')||'<p class="helptext">None saved yet.</p>'}</section>`).join('')}</div>`);}
function saveLibrary(kind){let c=selectedC();if(!c)return say('Select a component first.');let name=prompt('Library name',c.value+' · '+c.footprintName);if(!name)return;safeEdit(()=>{let item=kind==='symbols'?CB.symbolFrom(c,name):kind==='footprints'?CB.footprintFrom(c,name):{id:CB.uid(),name,symbol:CB.symbolFrom(c,name),footprint:CB.footprintFrom(c,name),value:c.value,prefix:c.ref.replace(/[0-9]+$/,'')||'X'};p.library[kind].push(item);},'Library entry saved.');libraryDialog();}
function placeDevice(d){safeEdit(()=>{let c=CB.component(p,'custom',zoom.pcb.cx,zoom.pcb.cy);let i=1;while(p.components.some(c=>c.ref===d.prefix+i))i++;c.ref=d.prefix+i;c.value=d.value;c.pads=CB.clone(d.footprint.pads);c.body=CB.clone(d.footprint.body);c.height=d.footprint.height;c.courtyard=d.footprint.courtyard;c.footprintName=d.footprint.name;c.sheet=sheet;CB.applySymbol(c,d.symbol);if(view==='sch'){c.sch.x=zoom.sch.cx;c.sch.y=zoom.sch.cy;}p.components.push(c);selected=c.id;},'Saved device placed.');closeDialog();}
function editWireDialog(){let w=p.wires.find(x=>x.id===selected);if(!w)return;dialog('Wire corners',`<p class="helptext">Endpoints remain attached to their pin or junction. Enter one X,Y corner per line. Leave empty for a direct wire.</p><textarea id="wirePoints" rows="8">${w.points.map(q=>q.x+','+q.y).join('\n')}</textarea>${extra('Apply corners','wire-apply','primary')}`);}
function parsePoints(text){if(!text.trim())return [];return text.trim().split(/\n|;/).filter(Boolean).map(line=>{let [x,y,...rest]=line.trim().split(/[ ,]+/).map(Number);if(!Number.isFinite(x)||!Number.isFinite(y)||rest.length)throw Error('Enter exactly X,Y on each line.');return {x,y};});}
function writeNet(p,old,n){if(!n||p.nets.includes(n)&&n!==old)throw Error('Use a unique, nonempty net name.');p.nets=p.nets.map(x=>x===old?n:x);for(let c of p.components)for(let a of c.pads){if(a.net===old)a.net=n;if(a.labelNet===old)a.labelNet=n;}for(let a of [...p.wires,...p.junctions,...p.labels,...p.tracks,...p.vias,...p.zones,...p.ports])if(a.net===old)a.net=n;for(let cls of p.netClasses)cls.nets=cls.nets.map(x=>x===old?n:x);}
document.addEventListener('change',e=>{let el=e.target;if(el.hasAttribute('data-pin-net')){reject(e);let c=selectedC(),a=c?.pads.find(a=>a.n===el.dataset.pinNet);if(!a)return;let value=el.value;safeEdit(()=>{p.labels=p.labels.filter(l=>l.component!==c.id||l.pin!==a.n);if(value==='__NC__'){p.wires=p.wires.filter(w=>![w.from,w.to].some(t=>t.kind==='pin'&&t.component===c.id&&t.pin===a.n));a.labelNet='';a.net='';a.nc=true;}else{a.nc=false;if(value&&a.net&&value!==a.net)CB.mergeNet(p,value,a.net);a.labelNet=value;a.net=value;}CB.rebuildNets(p);},'Pin assignment and connected wires updated.');return;}if(el.hasAttribute('data-rename-net')){reject(e);let n=el.value.trim();if(safeEdit(()=>writeNet(p,el.dataset.renameNet,n),'Net renamed throughout the project.'))netsDialog();return;}if(el.id==='sheetSelect'){sheet=el.value;selected=null;pendingWire=null;render();fit();return;}if(el.id==='lockPart'){safeEdit(()=>selectedC().locked=el.checked,'Placement lock updated.');return;}if(['showZones','showSilk','showCourtyard','routeAssist'].includes(el.id)){if(el.id==='showZones')showZones=el.checked;if(el.id==='showSilk')showSilk=el.checked;if(el.id==='showCourtyard')showCourtyard=el.checked;if(el.id==='routeAssist')routeAssist=el.checked;renderCanvas();}},true);
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;let action=b.dataset.extra;if(b.dataset.action==='delete'){reject(e);deleteSelected();return;}if(b.dataset.action==='footprint'){reject(e);footprintDialog();return;}if(b.dataset.action==='applyFootprint'){reject(e);applyNewFootprint();return;}if(b.hasAttribute('data-remove-net')){reject(e);let n=b.dataset.removeNet;if(!confirm('Remove '+n+' and its wires, copper, labels and pin assignments?'))return;safeEdit(()=>{p.nets=p.nets.filter(x=>x!==n);for(let c of p.components)for(let a of c.pads){if(a.net===n)a.net='';if(a.labelNet===n)a.labelNet='';}for(let key of ['wires','junctions','labels','tracks','vias','zones','ports'])p[key]=p[key].filter(a=>a.net!==n);for(let c of p.netClasses)c.nets=c.nets.filter(x=>x!==n);},'Net removed.');netsDialog();return;}
 if(b.dataset.device){reject(e);let d=p.library.devices.find(d=>d.id===b.dataset.device);if(d)placeDevice(d);return;}if(b.dataset.libraryApply){reject(e);let[k,id]=b.dataset.libraryApply.split(':'),entry=p.library[k].find(a=>a.id===id);if(k==='devices')placeDevice(entry);else{let c=selectedC();if(!c)return showFormError(Error('Select a component first.'));if(safeEdit(()=>k==='symbols'?CB.applySymbol(c,entry):CB.applyFootprint(c,entry),'Library entry applied.'))closeDialog();}return;}if(b.dataset.libraryDelete){reject(e);let[k,id]=b.dataset.libraryDelete.split(':');safeEdit(()=>p.library[k]=p.library[k].filter(a=>a.id!==id),'Library entry removed.');libraryDialog();return;}
 if(!action)return;reject(e);try{switch(action){case'junction':setTool('junction');break;case'power':powerDialog();break;case'label-apply':{let c=selectedC(),a=c.pads.find(a=>(a.pin||a.n)===$('#labelPin').value),n=$('#labelNet').value.trim(),kind=$('#labelKind').value;if(!n)throw Error('Enter a net name.');if(safeEdit(()=>{if(!p.nets.includes(n))p.nets.push(n);if(a.net&&a.net!==n)CB.mergeNet(p,n,a.net);a.labelNet=n;a.net=n;a.nc=false;p.labels=p.labels.filter(l=>l.component!==c.id||l.pin!==a.n);p.labels.push({id:CB.uid(),component:c.id,pin:a.n,net:n,kind});CB.rebuildNets(p);},'Named net label applied.'))closeDialog();break;}case'libraries':libraryDialog();break;case'save-device':saveLibrary('devices');break;case'save-symbol':saveLibrary('symbols');break;case'save-footprint':saveLibrary('footprints');break;case'library-export':download(slug()+'-library.json',JSON.stringify({format:'circuitbench-library',schema:1,library:p.library},null,2),'application/json');break;case'library-import':importLibrary();break;case'footprint-apply':applyNewFootprint();break;case'pad-add':{let ns=$$('#padTable [data-pad-field=n]').map(x=>x.value),n=1;while(ns.includes(String(n)))n++;$('#padTable tbody').insertAdjacentHTML('beforeend',padRow({...CB.pad(n,0,0),shape:'circle',width:1.8,height:1.8,rotation:0,labelNet:'',slot:0}));break;}case'pad-remove':b.closest('tr').remove();break;case'delete':deleteSelected();break;case'wire-edit':editWireDialog();break;case'wire-apply':{let points=parsePoints($('#wirePoints').value);if(safeEdit(()=>p.wires.find(w=>w.id===selected).points=points,'Wire corners updated.'))closeDialog();break;}case'junction-apply':safeEdit(()=>Object.assign(p.junctions.find(j=>j.id===selected),{x:num('#junctionX'),y:num('#junctionY')}),'Junction moved.');break;case'select-group':if(selected)groupSelection.has(selected)?groupSelection.delete(selected):groupSelection.add(selected);render();break;case'symbol-edit':symbolDialog();break;case'symbol-apply':{let c=selectedC(),pins=$$('#symbolPins tr[data-n]').map(r=>({n:r.dataset.n,x:Number(r.querySelectorAll('input')[0].value),y:Number(r.querySelectorAll('input')[1].value)})),kind=$('#symbolKind').value;if(safeEdit(()=>c.symbol={kind,pins},'Symbol geometry updated.'))closeDialog();break;}case'component-assembly':{let c=selectedC(),next=$('#componentSheet').value;if(next!==c.sheet&&p.wires.some(w=>[w.from,w.to].some(e=>e.kind==='pin'&&e.component===c.id)))throw Error('Remove attached wires before moving a part to another sheet.');safeEdit(()=>{c.height=num('#componentHeight');c.courtyard=num('#componentCourtyard');c.sheet=next;},'Assembly properties updated.');break;}default:handleLater(action,b);}}catch(err){showFormError(err);say(err.message);}},true);
function importLibrary(){let input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{let f=input.files[0];if(!f||f.size>5e6)throw Error('Choose a library JSON file smaller than 5 MB.');let data=JSON.parse(await f.text());if(data.format!=='circuitbench-library'||data.schema!==1)throw Error('Expected a CIRCUITBENCH library file.');if(safeEdit(()=>{for(let k of ['symbols','footprints','devices','blocks'])for(let a of data.library[k]||[])p.library[k].push({...a,id:CB.uid()});},'Library imported.'))libraryDialog();}catch(e){showFormError(e);}};input.click();}
function renderBoardObject(x){$('#selectionType').textContent='BOARD OBJECT';$('#inspector').innerHTML=`<div class="inspectSection"><h3>Board object</h3><p>${esc(x.net||x.text||x.id)}</p>${extra('Edit board object','board-edit')}${extra('Delete','delete','danger')}</div>`;}
function handleLater(action){if(action==='board'||action==='board-edit')boardDialog();else if(action==='rules')rulesDialog();else if(action==='compare')compareDialog();else if(action==='route-dialog')routeDialog();else if(action==='sheets')sheetsDialog();else if(action==='blocks')blocksDialog();else if(action==='assembly')assemblyDialog();else if(window.CBWorkbench?.actions?.[action])window.CBWorkbench.actions[action]();}
// Batch modules register complete dialogs and actions here.
window.CBWorkbench={actions:{},safeEdit,extra,field2,parsePoints,polyPath,showFormError,getSheet:()=>sheet,setSheet:s=>sheet=s,selection:groupSelection,getRouteAssist:()=>routeAssist};
render();
})();
