const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),output=path.join(root,'test-output');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{let name=req.url.split('?')[0].replace(/^\//,'')||'index.html',file=path.join(root,name);if(name.includes('..')||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':'text/html');fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/',browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader']});const ctx=await browser.newContext({viewport:{width:1500,height:1050}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept(d.type()==='prompt'?'Bench device':undefined));const project=()=>page.evaluate(()=>Circuitbench.project()),act=a=>page.locator(`[data-action="${a}"]:visible`).first().click(),extra=a=>page.locator(`[data-extra="${a}"]:visible`).first().click(),close=()=>act('closeDialog'),pass=n=>console.log('PASS',n);page.setDefaultTimeout(12000);
try{
 await page.goto(url);await page.waitForFunction(()=>!!window.Circuitbench);await extra('assembly');await page.waitForFunction(()=>window.Circuitbench.assembly?.()?.bodies===5);await page.locator('[data-3d-view=bottom]').click();await page.locator('#assemblyExplode').fill('8');assert.equal(await page.evaluate(()=>Circuitbench.assembly().bodies),5);await page.locator('[data-3d-view=iso]').click();await page.screenshot({path:path.join(output,'3d-assembly.png')});let download=page.waitForEvent('download');await extra('assembly-png');await(await download).saveAs(path.join(output,'assembly.png'));await close();pass('Real WebGL assembly meshes, bottom view, explode and image export');
 await extra('board');await page.locator('#boardTool').selectOption('hole');await page.locator('#objX').fill('5');await page.locator('#objY').fill('5');await page.locator('#holeSlot').fill('5');await extra('board-apply');assert.equal((await project()).holes.length,1);await extra('board');await page.locator('#boardTool').selectOption('zone');await page.locator('#zoneNet').selectOption('GND');await page.locator('#objLayer').selectOption('B');await extra('board-apply');assert.equal((await project()).zones.length,1);await extra('board');await page.locator('#boardTool').selectOption('text');await page.locator('#silkText').fill('BENCH');await page.locator('#objLayer').selectOption('B');await extra('board-apply');assert.equal((await project()).silk[0].mirror,true);await page.screenshot({path:path.join(output,'zones-board.png')});pass('Board tools create slotted holes, thermal zones and mirrored silkscreen');
 await page.locator('[data-left=design]').click();let c=(await project()).components[1];await page.locator(`[data-select="${c.id}"]`).click();await page.locator('#lockPart').check();let x=(await project()).components[1].pcb.x;await page.locator('#canvas').focus();await page.keyboard.press('ArrowRight');assert.equal((await project()).components[1].pcb.x,x);await extra('save-device');await page.waitForFunction(()=>Circuitbench.project().library.devices.length===1);assert.equal((await project()).library.devices.length,1);await close();pass('Placement locks and saved device library');
 await page.locator('[data-view=sch]').click();await extra('sheets');await page.locator('#sheetName').fill('Sensor');await extra('sheet-add');assert.equal((await project()).sheets.length,2);await page.locator('[data-left=library]').click();await page.locator('.templates').evaluate(el=>el.open=true);await page.locator('[data-add=resistor]').click();c=(await project()).components.at(-1);assert.equal(c.sheet,(await project()).sheets[1].id);await extra('blocks');await page.locator('#blockName').fill('Sensor resistor');await extra('block-save');await page.locator('#blockPrefix').fill('S2');await extra('block-place');assert.equal((await project()).components.length,7);assert.equal((await project()).library.blocks.length,1);pass('Child sheets and reusable block capture/placement');
 await page.locator('[data-view=review]').click();await act('baseline');assert((await project()).baseline.snapshot);await extra('compare');assert((await page.locator('#dialogBody').textContent()).includes('No object-level differences'));await close();pass('Full snapshot baseline and object-level comparison');
 await act('project');download=page.waitForEvent('download');await extra('kicad-export');const nativeFile=path.join(output,'ui-roundtrip.kicad_pcb');await(await download).saveAs(nativeFile);await extra('kicad-import');await page.locator('#kicadInput').setInputFiles(nativeFile);await page.waitForFunction(()=>document.querySelector('#dialogTitle').textContent==='KiCad import preview');await extra('kicad-accept');assert.equal((await project()).components.length,7);assert.equal((await project()).holes.length,1);await act('undo');assert.equal((await project()).sheets.length,2);pass('Native KiCad UI export, preview, import and undo');
 await page.waitForTimeout(350);const second=await ctx.newPage();second.on('pageerror',e=>errors.push(e.message));await second.goto(url);await second.waitForFunction(()=>!!window.Circuitbench);await second.locator('[data-action=project]:visible').first().click();await second.locator('#titleEdit').fill('Other tab saved');await second.locator('[data-action=projectApply]').click();await page.waitForFunction(()=>window.CBSaveBlocked===true);await act('project');assert((await page.locator('#dialogBody').textContent()).includes('Autosave paused'));await extra('save-adopt');assert.equal((await project()).title,'Other tab saved');await second.close();pass('Multi-tab conflict pauses autosave and explicitly adopts the saved copy');
 await act('project');await page.locator('#titleEdit').fill('Release verified');await act('projectApply');await page.waitForTimeout(350);await page.reload();await page.waitForFunction(()=>Circuitbench.project().title==='Release verified');assert.equal((await project()).schema,2);pass('Schema 2 reload preserves libraries, blocks and baseline');
 const corrupt=await browser.newContext(),cp=await corrupt.newPage();cp.on('pageerror',e=>errors.push(e.message));await cp.addInitScript(()=>{localStorage.setItem('circuitbench.project.v1','BROKEN ORIGINAL');});await cp.goto(url);await cp.waitForFunction(()=>!!window.Circuitbench);assert.equal(await cp.evaluate(()=>window.CBSaveBlocked),true);await cp.locator('[data-action=closeDialog]').click();await cp.locator('.templates').evaluate(el=>el.open=true);await cp.locator('[data-add=resistor]').click();await cp.waitForTimeout(350);assert.equal(await cp.evaluate(()=>localStorage.getItem('circuitbench.project.v1')),'BROKEN ORIGINAL');await corrupt.close();pass('Corrupt stored data remains untouched while autosave is paused');
 assert.deepEqual(errors,[]);pass('No uncaught errors across advanced workflows');
}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
