const assert=require('node:assert/strict'),C=require('../hardening.js');
let n=0;function test(name,fn){fn();console.log('PASS',name);n++;}
function pair(){let p=C.fresh(),a=C.component(p,'custom',10,20),b=C.component(p,'custom',50,20);b.ref='X2';a.sch={x:20,y:20,rotation:0};b.sch={x:80,y:20,rotation:0};a.pads=[{...a.pads[0],n:'1',x:0,y:0}];b.pads=[{...b.pads[0],n:'1',x:0,y:0}];p.components.push(a,b);return {p,a,b};}
const pin=c=>({kind:'pin',component:c.id,pin:'1'});
test('Schema 1 migration preserves geometry, nets, and backup compatibility',()=>{const old=require('../examples/hello-copper.circuitbench.json'),p=C.validate(old);assert.equal(p.schema,2);assert.equal(p.components.length,old.components.length);assert.deepEqual(p.tracks,old.tracks);assert.deepEqual(p.components.map(c=>c.pads.map(a=>a.net)),old.components.map(c=>c.pads.map(a=>a.net)));assert(p.components.every(c=>c.pads.every(a=>a.shape==='circle')));});
test('Explicit wire connects and deleting it splits an unnamed net',()=>{let {p,a,b}=pair();C.link(p,pin(a),pin(b),[{x:35,y:20}]);assert(a.pads[0].net);assert.equal(a.pads[0].net,b.pads[0].net);C.validate(p);C.removeWire(p,p.wires[0].id);assert.equal(a.pads[0].net,'');assert.equal(b.pads[0].net,'');});
test('Junction split and branch maintain one electrical net',()=>{let {p,a,b}=pair(),c=C.component(p,'custom',30,30);c.pads=[{...c.pads[0],n:'1',x:0,y:0}];p.components.push(c);let w=C.link(p,pin(a),pin(b),[]),pts=C.wirePath(p,w),mid={x:(pts[0].x+pts[1].x)/2,y:(pts[0].y+pts[1].y)/2},j=C.splitWire(p,w.id,mid);C.link(p,pin(c),j,[]);assert.equal(p.junctions.length,1);assert.equal(p.wires.length,3);assert.equal(new Set(p.components.map(c=>c.pads[0].net)).size,1);C.validate(p);});
test('Explicit matching labels remain connected after a drawing wire is removed',()=>{let {p,a,b}=pair();a.pads[0].net=a.pads[0].labelNet='GND';b.pads[0].net=b.pads[0].labelNet='GND';C.link(p,pin(a),pin(b));C.removeWire(p,p.wires[0].id);assert.equal(a.pads[0].net,'GND');assert.equal(b.pads[0].net,'GND');});
test('Renumbering updates wire anchors without changing electrical identity',()=>{let {p,a,b}=pair();C.link(p,pin(a),pin(b));C.renumber(p,a,{'1':'A'});a.pads[0].n='A';assert.equal(p.wires[0].from.pin,'A');C.validate(p);});
test('Reusable symbol and footprint applications retain nets and reject mismatched pin maps',()=>{let {p,a,b}=pair();a.pads[0].net=a.pads[0].labelNet='GND';let f=C.footprintFrom(a,'Wide'),s=C.symbolFrom(a,'Terminal');f.pads[0].width=4;f.pads[0].shape='rect';C.applyFootprint(a,f);C.applySymbol(a,s);assert.equal(a.pads[0].net,'GND');assert.equal(a.pads[0].width,4);s.pins[0].n='99';assert.throws(()=>C.applySymbol(a,s));});
test('A trace wholly inside a plated drill void does not connect to the pad',()=>{let {p,a,b}=pair();a.pads[0].net=b.pads[0].net='GND';p.tracks.push({id:'tiny',net:'GND',layer:'F',width:.05,points:[{x:10,y:20},{x:10.1,y:20}]});let top=C.topology(p),pad=top.items.findIndex(x=>x.id===a.id+':1'),trace=top.items.findIndex(x=>x.owner==='tiny');assert.notEqual(top.u.find(pad),top.u.find(trace));});
test('Rectangular pad dimensions and rotation control real copper geometry',()=>{let {p,a,b}=pair();a.pads[0].shape='rect';a.pads[0].width=8;a.pads[0].height=2;a.pads[0].drill=.8;let before=C.rawCopper(p).find(x=>x.owner===a.id).bounds;a.pcb.rotation=90;let after=C.rawCopper(p).find(x=>x.owner===a.id).bounds;assert.equal(before.maxX-before.minX,8);assert.equal(after.maxX-after.minX,2);assert.equal(after.maxY-after.minY,8);});
test('Disconnected copper-zone islands do not falsely resolve an airwire',()=>{let {p,a,b}=pair();a.pads[0].net=b.pads[0].net='GND';p.cutouts=[{id:'cut',points:[{x:29,y:0},{x:31,y:0},{x:31,y:40},{x:29,y:40}]}];p.zones=[{id:'zone',layer:'F',net:'GND',points:[],clearance:.25,thermal:false,thermalGap:.3,spoke:.4}];assert.equal(C.zones(p).length,2);assert.equal(C.connections(p).length,1);});
test('Copper plane joins same-net pads and clears a foreign-net pad',()=>{let {p,a,b}=pair();a.pads[0].net=b.pads[0].net='GND';let c=C.component(p,'custom',30,20);c.pads=[{...c.pads[0],n:'1',x:0,y:0,net:'+5V'}];p.components.push(c);p.zones=[{id:'zone',layer:'F',net:'GND',points:[],clearance:.3,thermal:true,thermalGap:.3,spoke:.4}];assert.equal(C.connections(p).length,0);assert(!C.checks(p).some(f=>f.code==='SHORT'||f.code==='CLEARANCE'));});
test('Mask, drill, courtyard and silkscreen checks expose fabrication conflicts',()=>{let {p,a,b}=pair();b.pcb.x=10.5;b.pads[0].net='+5V';a.pads[0].net='GND';p.silk=[{id:'silk',layer:'F',kind:'line',width:.2,a:{x:8,y:20},b:{x:12,y:20}}];let codes=C.checks(p).map(f=>f.code);for(let c of ['SHORT','DRILL_SPACING','COURTYARD','MASK_WEB','SILK_PAD'])assert(codes.includes(c),c);});
test('Manufacturing output includes separate plated/NPTH drills, paste, silk and placement',()=>{let p=C.sample();p.holes.push({id:'hole',x:5,y:5,drill:3,slot:6,rotation:0,plated:false});p.silk.push({id:'text',kind:'text',layer:'F',x:5,y:35,text:'REV A',size:1.4,width:.2,rotation:0});let out=C.fabrication(p);for(let file of ['Nonplated.drl','F_Paste.gbr','B_Paste.gbr','F_SilkS.gbr','Placement.csv'])assert(out[file]!==undefined);assert(out['Nonplated.drl'].includes('G85'));assert(out['F_SilkS.gbr'].includes('G36*'));});
console.log(n+' extended test groups passed');
