'use strict';
const C=require('../enclosure-adapter'),M=require('../enclosure-workshop/model'),G=require('../enclosure-workshop/geometry'),S=require('../enclosure-workshop/solid');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const out=path.join(__dirname,'../test-output/board-templates');fs.mkdirSync(out,{recursive:true});
let count=0;const test=(label,fn)=>{fn();count++;console.log('PASS '+label);};process.on('exit',()=>{if(count!==11){console.error('Incomplete board-template verification '+count+'/11');process.exitCode=1;}});
const close=(a,b,eps=.00001)=>assert(Math.abs(a-b)<=eps,`${a} != ${b}`);
test('Four source dimensions, Uno stepped edge and rounded corner areas across four orientations',()=>{
 const expected={'uno-r3':[68.58,53.34,9,0],mkr:[61.5,25,68,2],pi40:[65,56,68,3],'giga-r1-wifi':[101.6,53.34,57,0]};
 for(const [id,[w,h,n,r]] of Object.entries(expected))for(const rotation of [0,90,180,270]){let s=C.boardTemplate(id,{rotation});assert.equal(s.width,rotation%180?h:w);assert.equal(s.height,rotation%180?w:h);assert.equal(s.outline.length,n);assert(C.G.polygonValid(s.outline));assert.deepEqual(C.G.bounds([s.outline]),{minX:0,minY:0,maxX:s.width,maxY:s.height});if(r)close(Math.abs(C.G.area(s.outline)),w*h-(4-Math.PI)*r*r,.05);}
 assert.deepEqual(C.boardTemplate('uno-r3').outline.slice(2,5),[{x:66.04,y:1.524},{x:66.04,y:12.954},{x:68.58,y:15.494}]);
});
test('Mounting patterns retain source diameters and clockwise handedness without scaling',()=>{
 for(const [id,first,last,dia] of [['uno-r3',[15.24,2.54],[66.04,45.72],3.2],['mkr',[2.31,2.31],[59.19,22.69],2.25],['pi40',[3.5,3.5],[61.5,52.5],2.7]]){const s=C.boardTemplate(id),r=C.boardTemplate(id,{rotation:90});assert.deepEqual([s.holes[0].x,s.holes[0].y],first);assert.deepEqual([s.holes[3].x,s.holes[3].y],last);close(r.holes[0].x,s.height-first[1]);close(r.holes[0].y,first[0]);assert(s.holes.every(h=>h.drill===dia&&C.G.inside(h,[s.outline])));}
});
const gigaHoles=[[15.24,2.54],[90.17,2.54],[66.04,17.78],[66.0656,45.7073],[13.9956,50.7873],[96.52,50.8]];
assert.deepEqual(C.boardTemplate('giga-r1-wifi').holes.map(h=>[h.x,h.y]),gigaHoles);
for(const rotation of [0,90,180,270]){const s=C.boardTemplate('giga-r1-wifi',{rotation});assert.equal(s.holes.length,6);for(let i=0;i<6;i++){let [x,y]=gigaHoles[i],expected=rotation===0?[x,y]:rotation===90?[53.34-y,x]:rotation===180?[101.6-x,53.34-y]:[y,101.6-x];close(s.holes[i].x,expected[0]);close(s.holes[i].y,expected[1]);assert.equal(s.holes[i].drill,3.2);assert(C.G.inside(s.holes[i],[s.outline]));}}
{let p=C.fresh();p.board.color='#643688';C.applyBoardTemplate(p,'giga-r1-wifi');const holes=C.clone(p.holes);assert.equal(C.validate(p).holes[5].boardTemplate.index,5);C.applyBoardTemplate(p,'giga-r1-wifi');assert.deepEqual(p.holes,holes);assert.equal(p.board.color,'#643688');p.holes[5].boardTemplate.index=6;assert.throws(()=>C.validate(p),/template/i);}
test('Applying a preset preserves electrical design, artwork, manual holes, thickness and outside objects',()=>{
 let p=C.sample();p.board.thickness=2.4;p.holes=[{id:'manual',x:40,y:15,drill:3,slot:0,rotation:0,plated:false}];p.silk=[{id:'text',kind:'text',text:'TEST',x:4,y:10,size:1,rotation:0,width:.15,layer:'F'}];p.components[0].pcb.x=100;const original=C.clone(p);C.applyBoardTemplate(p,'mkr');for(const k of ['components','tracks','vias','wires','nets','silk','cutouts','zones'])assert.deepEqual(p[k],original[k]);assert.equal(p.board.thickness,2.4);assert.deepEqual(p.holes.find(h=>h.id==='manual'),original.holes[0]);assert(C.checks(p).some(f=>/EDGE|OUTSIDE/.test(f.code)));
});
test('Reapply is idempotent, rotation keeps anchors, switching replaces only untouched preset holes',()=>{
 let p=C.fresh();C.applyBoardTemplate(p,'uno-r3');let ids=p.holes.map(h=>h.id);C.applyBoardTemplate(p,'uno-r3');assert.deepEqual(p.holes.map(h=>h.id),ids);C.applyBoardTemplate(p,'uno-r3',{rotation:90});assert.deepEqual(p.holes.map(h=>h.id),ids);p.holes[0].x+=1;let edited=C.clone(p.holes[0]);delete edited.boardTemplate;C.applyBoardTemplate(p,'pi40');assert.equal(p.holes.length,5);assert.deepEqual(p.holes.find(h=>h.id===ids[0]),edited);C.applyBoardTemplate(p,'mkr',{holes:false});assert.deepEqual(p.holes,[edited]);
 p=C.fresh();p.holes=[{id:'existing',x:3.5,y:3.5,drill:2.7,slot:0,rotation:0,plated:false}];C.applyBoardTemplate(p,'pi40');assert.equal(p.holes.length,4);C.applyBoardTemplate(p,'pi40');assert.equal(p.holes.length,4);assert.equal(p.holes[0].id,'existing');
});
test('Atomic invalid requests, malformed metadata and hole limits reject without partial edits; JSON and legacy migrate',()=>{
 let p=C.fresh(),original=JSON.stringify(p);for(const [id,opt] of [['unknown',{}],['mkr',{rotation:45}],['mkr',{holes:'yes'}]]){assert.throws(()=>C.applyBoardTemplate(p,id,opt));assert.equal(JSON.stringify(p),original);}C.applyBoardTemplate(p,'mkr');assert.deepEqual(C.validate(JSON.parse(JSON.stringify(p))),p);for(const mutate of [q=>q.board.template.rotation=1,q=>q.holes[0].boardTemplate.index=10,q=>q.board.template.family='<script>',q=>q.holes[0].boardTemplate=null]){let q=C.clone(p);mutate(q);assert.throws(()=>C.validate(q),/template/i);}C.resizeBoard(p,100,50);assert.equal(C.validate(p).board.width,100);let q=C.fresh();q.schema=1;assert.equal(C.validate(q).schema,2);
 q=C.fresh();q.holes=Array.from({length:100},(_,i)=>({id:'h'+i,x:10,y:10,drill:1,slot:0,rotation:0,plated:false}));original=JSON.stringify(q);assert.throws(()=>C.applyBoardTemplate(q,'pi40'));assert.equal(JSON.stringify(q),original);
});
test('Gerber, Excellon and KiCad contain every boundary segment and NPTH at all orientations',()=>{
 for(const id of ['uno-r3','mkr','pi40','giga-r1-wifi'])for(const rotation of [0,90,180,270]){let p=C.fresh();C.applyBoardTemplate(p,id,{rotation});const gerber=C.gerber(p,'F','outline'),drill=C.drill(p,false),text=C.exportKiCad(p),tree=C.parseSexpr(text),edges=tree.filter(t=>t[0]==='gr_line'),feet=tree.filter(t=>t[0]==='footprint');assert.equal(edges.length,p.board.outline.length);assert.equal(feet.length,p.holes.length);for(const q of p.board.outline)assert(gerber.includes('X'+Math.round(q.x*1e6)+'Y'+Math.round((p.board.height-q.y)*1e6)));for(const h of p.holes)assert(drill.includes('X'+h.x.toFixed(4)+'Y'+(p.board.height-h.y).toFixed(4)));assert.equal((text.match(/np_thru_hole/g)||[]).length,p.holes.length);for(let i=0;i<edges.length;i++){const start=edges[i].find(a=>a[0]==='start');close(start[1],p.board.outline[i].x);close(start[2],p.board.outline[i].y);}fs.writeFileSync(path.join(out,id+'-'+rotation+'.kicad_pcb'),text);}
});
test('Enclosure handoff uses all holes, stable support anchors and updated board dimensions',()=>{
 let p=C.fresh();C.applyBoardTemplate(p,'uno-r3');p.enclosureWorkshop=C.enclosureWorkshopCreate(p);const ids=M.mounts(p.enclosureWorkshop).filter(h=>h.enabled).map(h=>h.id);assert.equal(ids.length,4);C.applyBoardTemplate(p,'uno-r3',{rotation:90});p.enclosureWorkshop=C.enclosureWorkshopSync(p);assert.deepEqual(M.mounts(p.enclosureWorkshop).filter(h=>h.enabled).map(h=>h.id),ids);const a=M.effective(p.enclosureWorkshop);close(a.board.bounds.maxX-a.board.bounds.minX,53.34);for(const h of p.holes){const m=M.mounts(p.enclosureWorkshop).find(m=>m.id===h.id);close(m.x,h.x);close(m.y,-h.y);}const wire=C.enclosureMechanical(p);assert.deepEqual(wire.board.points,p.board.outline);
});
(async()=>{const create=(await import(require.resolve('manifold-3d/manifold.js'))).default,api=await create();api.setup();require('../enclosure-workshop/manifold-kernel')(S,api);
 for(const id of ['uno-r3','mkr','pi40','giga-r1-wifi'])test(id+' produces valid printable enclosure solids with all template supports',()=>{const p=C.fresh();C.applyBoardTemplate(p,id);const w=C.enclosureWorkshopCreate(p),r=G.build(w);assert.equal(r.mounts.length,C.boardTemplate(id).holes.length);assert(r.parts.length>=2);assert.deepEqual(r.findings.filter(f=>f.severity==='error'),[]);for(const part of r.parts){assert(part.audit.valid,part.name);assert.equal(part.audit.connectedComponents,1);assert(S.audit(S.readSTL(S.stl(part.mesh))).valid);fs.writeFileSync(path.join(out,id+'-'+part.id+'.stl'),Buffer.from(S.stl(part.mesh)));}fs.writeFileSync(path.join(out,id+'.circuitbench.json'),JSON.stringify(p,null,2));});
 console.log(count+' board-template engine/export/solid groups passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
