'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),C=require('../board-templates');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-output/board-templates-browser');fs.mkdirSync(out,{recursive:true});let count=0;
const pass=label=>{count++;console.log('PASS '+label);};process.on('exit',()=>{if(count!==7){console.error('Incomplete board-template browser verification '+count+'/7');process.exitCode=1;}});
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||'/tmp/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader']}),context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true}),page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});page.on('dialog',d=>d.accept());page.setDefaultTimeout(15000);
const act=a=>page.locator(`[data-action="${a}"]:visible`).first().click(),pcb=a=>page.locator(`[data-pcb="${a}"]:visible`).first().click(),project=()=>page.evaluate(()=>Circuitbench.project()),apply=()=>page.locator('[data-template=apply]').click();
try{
 await context.setOffline(true);await page.goto('file://'+path.join(root,'index.html'));await page.waitForFunction(()=>window.Circuitbench?.boardTools?.templates);
 const initial=C.fresh();initial.title='Board preset browser';initial.board.thickness=2;initial.components=[C.component(initial,'smd2',18,13)];initial.holes=[{id:'manual',x:28,y:17,drill:1,slot:0,rotation:0,plated:false}];const file=path.join(out,'fixture.json');fs.writeFileSync(file,JSON.stringify(initial));await act('import');await page.locator('#fileInput').setInputFiles(file);await page.waitForFunction(()=>Circuitbench.project().title==='Board preset browser');await page.locator('[data-view=pcb]').click();const before=await project();
 await pcb('templates');assert.equal(await page.locator('#boardTemplateFamily option').count(),3);await page.locator('#boardTemplateFamily').selectOption('mkr');await page.locator('#boardTemplateRotation').selectOption('90');assert((await page.locator('#boardTemplateDimensions').innerText()).includes('25 × 61.5'));await page.keyboard.press('Escape');assert.deepEqual(await project(),before);pass('Offline picker previews three source families and rotation; Escape cancels without changing the board');
 await pcb('size');await page.locator('#dialog [data-pcb=templates]').click();await apply();let uno=await project();assert.equal(uno.board.width,68.58);assert.equal(uno.board.outline.length,9);assert.equal(uno.holes.length,5);assert.deepEqual(uno.components,before.components);assert.equal(uno.board.thickness,2);await act('undo');assert.deepEqual(await project(),before);await act('redo');assert.deepEqual(await project(),uno);pass('Board size and toolbar both open the picker; apply, Undo and Redo retain the electrical design');
 await pcb('templates');await page.locator('#boardTemplateFamily').selectOption('mkr');await page.locator('#boardTemplateRotation').selectOption('90');await page.locator('#boardTemplateHoles').uncheck();await apply();let mkr=await project();assert.equal(mkr.board.width,25);assert.equal(mkr.board.height,61.5);assert.equal(mkr.holes.length,1);assert.deepEqual(mkr.components,before.components);await pcb('templates');await page.locator('#boardTemplateFamily').selectOption('pi40');await page.locator('#boardTemplateRotation').selectOption('0');await page.locator('#boardTemplateHoles').check();await page.screenshot({path:path.join(out,'desktop-picker.png')});await apply();let pi=await project();assert.equal(pi.board.width,65);assert.equal(pi.board.height,56);assert.equal(pi.holes.length,5);await pcb('templates');await apply();assert.deepEqual((await project()).holes,pi.holes);pass('MKR outline-only and Raspberry Pi with holes apply correctly; reapply creates no duplicate holes');
 await page.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('Saved'));await page.reload();await page.waitForFunction(()=>window.Circuitbench?.boardTools?.templates);assert.deepEqual((await project()).board,pi.board);assert.deepEqual((await project()).holes,pi.holes);const downloading=page.waitForEvent('download');await act('save');const saved=path.join(out,'saved.circuitbench.json');await(await downloading).saveAs(saved);assert.deepEqual(JSON.parse(fs.readFileSync(saved)).board,pi.board);await act('project');await page.locator('#dialog [data-action=new]').click();await act('import');await page.locator('#fileInput').setInputFiles(saved);await page.waitForFunction(()=>Circuitbench.project().title==='Board preset browser');assert.deepEqual((await project()).holes,pi.holes);pass('Autosave reload and downloaded project JSON retain real outlines, hole provenance and preset choices');
 await page.locator('[data-view=pcb]').click();await page.locator('[data-enc=open]').click();await page.waitForFunction(()=>document.querySelector('#enclosureWorkshopFrame')?.contentWindow.CBEmbedded?.get());const frame=page.frames().find(f=>f.parentFrame());await frame.waitForFunction(()=>CASEBENCH.getResult()&&!CASEBENCH.getBusy()&&CASEBENCH.isCurrent(),null,{timeout:45000});const enclosure=await frame.evaluate(()=>({mounts:CaseModel.mounts(CBEmbedded.get()).filter(m=>m.enabled).map(m=>[m.x,m.y]),valid:CASEBENCH.getResult().parts.every(p=>p.audit.valid),board:CaseModel.effective(CBEmbedded.get()).board}));assert.equal(enclosure.mounts.length,4);assert(enclosure.valid);assert.equal(enclosure.board.width,65);assert.equal(enclosure.board.height,56);assert.deepEqual(enclosure.mounts,[[3.5,-3.5],[61.5,-3.5],[3.5,-52.5],[61.5,-52.5]]);await page.screenshot({path:path.join(out,'pi-enclosure.png')});await act('closeDialog');pass('Enclosure workbench builds the selected Pi outline with four supports at its mounting-hole centers');
 await page.setViewportSize({width:390,height:844});await page.locator('#theme').selectOption('dark');await pcb('templates');await page.locator('#boardTemplateFamily').selectOption('mkr');assert(await page.locator('#dialog').evaluate(e=>e.scrollWidth<=e.clientWidth));await page.screenshot({path:path.join(out,'mobile-dark.png')});await act('closeDialog');await page.locator('#theme').selectOption('contrast');await pcb('templates');await page.locator('#boardTemplateFamily').focus();await page.keyboard.press('Home');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'boardTemplateRotation');await page.screenshot({path:path.join(out,'mobile-contrast.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));pass('Mobile dark/high-contrast picker fits the viewport and exposes native keyboard controls');
 await page.keyboard.press('Escape');assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);assert.equal(await page.locator('.version').innerText(),'v1.8.1');pass('No uncaught browser errors or runtime network requests; visible release version matches');
 console.log(count+' board-template browser groups passed');
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
