const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const root=path.resolve(__dirname,'..');
const output=process.env.TEST_OUTPUT||path.join(root,'test-output');
fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{let name=decodeURIComponent(req.url.split('?')[0]).replace(/^\/circuitbench\//,'')||'index.html';if(name.includes('..')){res.writeHead(403);return res.end();}let f=path.join(root,name);if(!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.html')?'text/html':'text/plain');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/circuitbench/`;let browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});let context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());const project=()=>page.evaluate(()=>Circuitbench.project());const act=a=>page.locator(`[data-action="${a}"]:visible`).first().click();const close=()=>act('closeDialog');const pass=name=>console.log('PASS',name);
try{
 await page.goto(url);await page.waitForFunction(()=>!!window.Circuitbench);assert.equal((await project()).components.length,5);await page.screenshot({path:path.join(output,'desktop-pcb.png')});pass('Cold start at a static subfolder');
 await page.locator('[data-view=sch]').click();await page.waitForTimeout(100);await page.screenshot({path:path.join(output,'desktop-schematic.png')});assert.equal(await page.locator('[data-tool=connect]').isVisible(),true);
 await act('new');assert.equal((await project()).components.length,0);await page.locator('.templates').evaluate(el=>el.open=true);await page.locator('[data-add=resistor]').click();await page.locator('[data-field=x]').fill('40');await page.locator('[data-field=x]').press('Tab');await page.locator('.templates').evaluate(el=>el.open=true);await page.locator('[data-add=led]').click();await page.locator('[data-field=x]').fill('85');await page.locator('[data-field=x]').press('Tab');assert.equal((await project()).components.length,2);pass('Fresh start and component placement');
 let cp=await project(),a=cp.components[0],b=cp.components[1];await page.locator('[data-tool=connect]').click();await page.locator(`[data-terminal="${a.id}"][data-pin="2"]`).last().click();await page.locator(`[data-terminal="${b.id}"][data-pin="1"]`).last().click();cp=await project();assert.equal(cp.components[0].pads[1].net,cp.components[1].pads[0].net);assert(cp.components[0].pads[1].net);pass('Pointer-based schematic connectivity');
 await page.locator('[data-view=pcb]').click();await page.locator('[data-left=design]').click();await page.locator(`[data-select="${a.id}"]`).click();await page.locator('[data-field=x]').fill('15');await page.locator('[data-field=x]').press('Tab');await page.locator('[data-field=y]').fill('15');await page.locator('[data-field=y]').press('Tab');await page.locator(`[data-select="${b.id}"]`).click();await page.locator('[data-field=x]').fill('40');await page.locator('[data-field=x]').press('Tab');await page.locator('[data-field=y]').fill('15');await page.locator('[data-field=y]').press('Tab');await page.locator('[data-tool=route]').click();await page.locator(`[data-terminal="${a.id}"][data-pin="2"]`).last().click();await page.locator(`[data-terminal="${b.id}"][data-pin="1"]`).last().click();assert.equal((await project()).tracks.length,1);assert.equal(await page.evaluate(()=>Circuitbench.checks().filter(f=>f.code==='UNROUTED').length),0);pass('Pad-to-pad routing resolves the actual airwire');
 await page.locator('[data-tool=select]').click();await page.locator(`[data-select="${b.id}"]`).click();await page.locator('#canvas').focus();await page.keyboard.press('ArrowDown');assert.equal((await project()).components[1].pcb.y,15.5);await act('undo');assert.equal((await project()).components[1].pcb.y,15);await act('redo');assert.equal((await project()).components[1].pcb.y,15.5);await act('undo');pass('Keyboard editing and undo/redo');
 await page.locator('#mode').selectOption('advanced');await page.locator(`[data-select="${b.id}"]`).click();await act('footprint');await page.locator('[data-pad-field=width]').first().fill('2');await page.locator('[data-pad-field=height]').first().fill('2');await page.locator('[data-extra=footprint-apply]').click();assert.equal((await project()).components[1].pads[0].width,2);await act('duplicate');assert.equal((await project()).components.length,3);await act('delete');assert.equal((await project()).components.length,2);await page.locator(`[data-select="${b.id}"]`).click();await act('rotate');assert.equal((await project()).components[1].pcb.rotation,90);await act('undo');pass('Footprint editing, duplicate, delete, rotation');
 await act('project');await page.locator('#titleEdit').fill('Browser verified');await act('projectApply');await page.waitForTimeout(350);await page.reload();assert.equal((await project()).title,'Browser verified');assert.equal((await project()).tracks.length,1);pass('Autosave survives reload');
 const saved=await project();let dlPromise=page.waitForEvent('download');await act('save');let dl=await dlPromise;const jsonPath=path.join(output,'roundtrip.json');await dl.saveAs(jsonPath);assert.deepEqual(JSON.parse(fs.readFileSync(jsonPath)),saved);await act('new');await page.locator('#fileInput').setInputFiles(jsonPath);await page.waitForFunction(()=>Circuitbench.project().title==='Browser verified');assert.deepEqual(await project(),saved);pass('JSON download/import round trip');
 await page.locator('#fileInput').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"format":"circuitbench","schema":99}')});await page.waitForFunction(()=>document.querySelector('#dialogTitle').textContent==='Could not open this project');assert.equal(await page.locator('#dialogTitle').textContent(),'Could not open this project');assert.deepEqual(await project(),saved);await close();pass('Malformed imports preserve the current project');
 await page.locator('[data-view=review]').click();await act('baseline');assert((await project()).baseline);await page.locator('summary').filter({hasText:'Assumptions & evidence'}).click();await page.locator('[data-register=evidence]').fill('Dimensions checked against a bench measurement.');await page.locator('[data-register=evidence]').press('Tab');assert((await project()).evidence.includes('bench measurement'));await page.screenshot({path:path.join(output,'review.png')});pass('Review, baseline and evidence register');
 await act('export');dlPromise=page.waitForEvent('download');await act('fab');dl=await dlPromise;await dl.saveAs(path.join(output,'fabrication.zip'));const JSZip=require('jszip'),zip=await JSZip.loadAsync(fs.readFileSync(path.join(output,'fabrication.zip')),{checkCRC32:true});assert(zip.file('F_Cu.gbr'));assert(zip.file('Plated.drl'));await close();pass('Fabrication ZIP download with valid CRC');
 await page.evaluate(()=>window.print=()=>{});await act('print');assert((await page.locator('#printReport').textContent()).includes('Browser verified'));await page.pdf({path:path.join(output,'design-report.pdf'),format:'A4',printBackground:true});pass('Printable PDF design report');
 for(let theme of ['dark','contrast','light']){await page.locator('#theme').selectOption(theme);assert.equal(await page.locator('body').getAttribute('data-theme'),theme);}await page.locator('[data-view=pcb]').click();await page.locator('#theme').selectOption('dark');await page.screenshot({path:path.join(output,'dark.png')});pass('Light, dark and high-contrast themes');

 await page.locator('[data-left=design]').click();await act('nets');await page.locator('[data-net-tool=manage]').click();await page.locator('#newNet').fill('TEST_NET');await act('addNet');let rename=page.locator('[data-rename-net=TEST_NET]');await rename.fill('BIAS');await rename.press('Tab');assert((await project()).nets.includes('BIAS'));await close();await page.locator('[data-net=BIAS]').click();await page.locator('[data-tool=via]').click();let bounds=await page.locator('#canvas').boundingBox();await page.mouse.click(bounds.x+bounds.width*.5,bounds.y+bounds.height*.5);assert.equal((await project()).vias.length,1);assert.equal((await project()).vias[0].net,'BIAS');await page.locator('[data-tool=select]').click();let via=(await project()).vias[0];await page.locator(`[data-terminal="${via.id}"]`).last().click();await page.locator('[data-field=diameter]').fill('1.1');await page.locator('[data-field=diameter]').press('Tab');assert.equal((await project()).vias[0].diameter,1.1);pass('Named nets, renaming, via placement and numeric via editing');
 await page.locator('[data-tool=pan]').click();let before=await page.locator('#canvas').getAttribute('viewBox');await page.mouse.move(bounds.x+80,bounds.y+90);await page.mouse.down();await page.mouse.move(bounds.x+130,bounds.y+140);await page.mouse.up();assert.notEqual(await page.locator('#canvas').getAttribute('viewBox'),before);await act('fit');await page.locator('#grid').selectOption('2.54');assert.equal(await page.locator('#dots').getAttribute('width'),'2.54');await page.locator('#grid').selectOption('0.5');pass('Pan, fit and rendered snap grid');
 await act('project');await page.locator('#titleEdit').fill('Recovery A');await act('projectApply');await page.waitForTimeout(300);await act('project');await page.locator('#titleEdit').fill('Recovery B');await act('projectApply');await page.waitForTimeout(300);await act('project');await act('recover');assert.equal((await project()).title,'Recovery A');await act('undo');assert.equal((await project()).title,'Recovery B');await act('project');await page.locator('#titleEdit').fill('Browser verified');await act('projectApply');await page.waitForTimeout(300);pass('Previous autosave recovery and undo of recovery');
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>!!window.Circuitbench);assert.equal((await project()).title,'Browser verified');await context.setOffline(false);pass('Offline reload at the installed subfolder');
 let mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));mp.on('dialog',d=>d.accept());await mp.goto(url);await mp.waitForFunction(()=>!!window.Circuitbench);assert.equal(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await mp.screenshot({path:path.join(output,'mobile.png')});await mp.locator('[data-action=toggleLeft]').click();await mp.locator('.templates').evaluate(el=>el.open=true);await mp.locator('[data-add=resistor]').click();assert.equal(await mp.evaluate(()=>Circuitbench.project().components.length),6);await mp.locator('[data-action=toggleLeft]').click();await mp.locator('[data-action=toggleRight]').click();assert.equal(await mp.locator('#inspector').isVisible(),true);await mp.locator('[data-field=value]').fill('2k2');await mp.locator('[data-field=value]').press('Tab');assert.equal(await mp.evaluate(()=>Circuitbench.project().components.at(-1).value),'2k2');await mobile.close();pass('390 px touch layout: panels, placement and property edit');
 let fileContext=await browser.newContext(),fp=await fileContext.newPage();fp.on('pageerror',e=>errors.push(e.message));await fp.goto('file://'+path.join(root,'index.html'));await fp.waitForFunction(()=>!!window.Circuitbench);assert.equal(await fp.evaluate(()=>Circuitbench.project().components.length),5);await fileContext.close();pass('Standalone file:// HTML works without a server');
 assert.deepEqual(errors,[]);pass('No uncaught browser errors');
}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
