const assert=require('node:assert/strict');
const C=require('../core.js');
let passed=0;
function test(name,fn){fn();console.log('PASS',name);passed++;}
function fixture(){let p=C.fresh();p.nets=['A','B'];for(let [i,x]of [[1,10],[2,30]]){let c=C.component(p,'custom',x,20);c.ref='X'+i;c.pads=[C.pad('1',0,0)];c.pads[0].net='A';p.components.push(c);}return p;}
function codes(p){return C.checks(p).map(f=>f.code);}
test('Example is a valid project with exactly six remaining connections',()=>{let p=C.validate(C.sample());assert.equal(C.connections(p).length,6);assert.deepEqual([...new Set(codes(p))],['UNROUTED']);});
test('Actual copper joins two pads and displacement breaks it',()=>{let p=fixture();assert.equal(C.connections(p).length,1);p.tracks.push({id:'t1',net:'A',layer:'F',width:.5,points:[{x:10,y:20},{x:30,y:20}]});assert.equal(C.connections(p).length,0);p.components[1].pcb.y=23;assert.equal(C.connections(p).length,1);});
test('Crossing segments connect same-net copper without shared vertices',()=>{let p=fixture();p.components[1].pcb={x:20,y:10,rotation:0,side:'F'};p.tracks=[{id:'t1',net:'A',layer:'F',width:.5,points:[{x:10,y:20},{x:30,y:20}]},{id:'t2',net:'A',layer:'F',width:.5,points:[{x:20,y:10},{x:20,y:30}]}];assert.equal(C.connections(p).length,0);p.tracks[1].layer='B';assert.equal(C.connections(p).length,1);p.vias.push({id:'v1',net:'A',x:20,y:20,diameter:.9,drill:.4});assert.equal(C.connections(p).length,0);});
test('Different-net tracks crossing on the same layer cause a short',()=>{let p=fixture();p.tracks=[{id:'t1',net:'A',layer:'F',width:.5,points:[{x:10,y:20},{x:30,y:20}]},{id:'t2',net:'B',layer:'F',width:.5,points:[{x:20,y:10},{x:20,y:30}]}];assert(codes(p).includes('SHORT'));p.tracks[1].layer='B';assert(!codes(p).includes('SHORT'));});
test('Clearance, edge, trace width and annular ring rules catch violations',()=>{let p=fixture();p.tracks=[{id:'t1',net:'A',layer:'F',width:.1,points:[{x:.1,y:.1},{x:.1,y:5}]},{id:'t2',net:'B',layer:'F',width:.5,points:[{x:9,y:21.2},{x:11,y:21.2}]}];p.components[0].pads[0].drill=1.6;for(let code of ['WIDTH','EDGE','ANNULAR','CLEARANCE'])assert(codes(p).includes(code),code);});
test('SMD pads only connect on their physical layer',()=>{let p=fixture();p.components[1].pads[0].mount='smd';p.components[1].pads[0].drill=0;p.components[1].pcb.side='B';p.tracks=[{id:'t1',net:'A',layer:'F',width:.5,points:[{x:10,y:20},{x:30,y:20}]}];assert.equal(C.connections(p).length,1);p.tracks[0].layer='B';assert.equal(C.connections(p).length,0);});
test('Unassigned pins remain distinct; NC declarations and output conflicts work',()=>{let p=fixture();p.components[0].pads[0].net='';p.components[1].pads[0].net='';p.components[1].pcb.x=10;assert(codes(p).includes('SHORT'));assert(codes(p).includes('UNASSIGNED'));p.components[0].pads[0].nc=true;assert.equal(C.checks(p).filter(f=>f.code==='UNASSIGNED').length,1);p.components.forEach(c=>{c.pads[0].net='A';c.pads[0].type='output';});assert(codes(p).includes('OUTPUT_CONFLICT'));assert(codes(p).includes('NC_CONFLICT'));});
test('Net merging updates pins, tracks and vias coherently',()=>{let p=fixture();p.components[1].pads[0].net='B';p.tracks=[{id:'t1',net:'B',layer:'B',width:.5,points:[{x:20,y:20},{x:30,y:20}]}];p.vias=[{id:'v1',net:'B',x:20,y:20,diameter:.9,drill:.4}];C.mergeNet(p,'A','B');assert.deepEqual(p.nets,['A']);assert.equal(p.tracks[0].net,'A');assert.equal(p.vias[0].net,'A');assert.equal(p.components[1].pads[0].net,'A');});
test('Rotation and bottom mirroring use one consistent transform',()=>{let p=fixture(),c=p.components[0];c.pads[0].x=2;c.pcb.rotation=90;assert.deepEqual(C.position(c,c.pads[0]),{x:10,y:22});c.pcb.side='B';assert.deepEqual(C.position(c,c.pads[0]),{x:10,y:18});});
test('Project JSON preserves all geometry and rejects malformed or future input',()=>{let p=C.sample();assert.deepEqual(C.validate(JSON.parse(JSON.stringify(p))),p);for(let mutate of [p=>p.schema=99,p=>p.board.width=-1,p=>p.components[0].pads[0].net='missing',p=>p.components[1].id=p.components[0].id,p=>p.tracks[0].width=NaN,p=>p.components[0].pads[0].drill=9,p=>p.rules.clearance=-1]){let bad=C.clone(p);mutate(bad);assert.throws(()=>C.validate(bad));}});
test('Gerber and drill share a lower-left origin without mirroring bottom',()=>{let p=fixture();let front=C.gerber(p,'F'),back=C.gerber(p,'B'),drill=C.drill(p);assert(front.includes('%FSLAX46Y46*%'));assert(front.includes('X10000000Y20000000D03*'));assert(back.includes('X10000000Y20000000D03*'));assert(drill.includes('X10.0000Y20.0000'));assert(C.gerber(p,'F','outline').endsWith('M02*'));});
test('Connecting two unassigned pins creates a new named net',()=>{let p=C.fresh();assert.equal(C.mergeNet(p,'',''),'N1');assert(p.nets.includes('N1'));});
console.log(`${passed} core test groups passed`);
// Check ZIP with an independent ZIP implementation.
const JSZip=require('jszip');
(async()=>{let files=C.fabrication(C.sample()),zip=await JSZip.loadAsync(C.zip(files),{checkCRC32:true});assert.equal(Object.keys(zip.files).length,Object.keys(files).length);for(let [name,value]of Object.entries(files))assert.equal(await zip.file(name).async('string'),value);console.log('PASS independent ZIP CRC and contents');})().catch(e=>{console.error(e);process.exitCode=1;});
