const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),C=require('../enclosure'),S=require('../enclosure-solid');
const out=path.join(__dirname,'../test-output/enclosure');fs.mkdirSync(out,{recursive:true});let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS',name);};
function fixture(){let p=C.fresh();p.title='Enclosure reference';p.board.outline=[{x:0,y:0},{x:60,y:0},{x:60,y:34},{x:54,y:40},{x:0,y:40}];p.holes=[[5,5],[55,5],[50,35],[5,35]].map(([x,y],i)=>({id:'hole'+i,x,y,drill:3.2,slot:0,rotation:0,plated:false}));let a=C.component(p,'custom',25,20);a.body=[10,8];a.height=12;a.pcb.rotation=30;a.pads.forEach(a=>a.nc=true);let b=C.component(p,'smd2',38,23);b.pcb.side='B';b.height=4;b.body=[5,5];b.pads.forEach(a=>a.nc=true);p.components=[a,b];p.enclosure=C.enclosureDefaults(p);return C.validate(p);}
test('Sizing uses front/back component heights, lead allowance, board thickness and rotated body bounds',()=>{let p=fixture(),q=C.enclosurePlan(p);assert.equal(q.width,70);assert.equal(q.depth,50);assert.equal(q.topHeight,12);assert.equal(q.bottomHeight,4);assert.equal(q.config.standoffHeight,6);assert(Math.abs(q.insideHeight-22.6)<1e-9);assert(Math.abs(q.totalHeight-26.6)<1e-9);p.components[0].pcb.x=-2;let expanded=C.enclosurePlan(p);assert(expanded.origin.x<-12);p.components[1].height=15;assert(C.enclosurePlan(p).issues.some(x=>x.code==='BELOW_BOARD'));assert(C.enclosureDefaults(p).standoffHeight>=16);});
test('Hole-linked standoffs follow board and footprint hole moves; small mechanical holes default off',()=>{let p=fixture(),id=p.enclosure.mounts[0].id;p.holes[0].x+=2;let q=C.enclosurePlan(p);assert.equal(q.mounts.find(m=>m.id===id).boardX,7);p.holes.push({id:'small',x:20,y:5,drill:1,slot:0,rotation:0,plated:false});C.enclosureSyncMounts(p,p.enclosure);assert.equal(p.enclosure.mounts.find(m=>m.anchor==='small').enabled,false);let c=C.component(p,'custom',20,12);c.mountingHoles=[{x:2,y:0,drill:3,slot:0,rotation:0}];c.pcb.side='B';c.pcb.rotation=90;p.components.push(c);let h=C.enclosureCandidates(p).find(h=>h.component===c.id);assert(Math.abs(h.x-20)<1e-6&&Math.abs(h.y-10)<1e-6);p.holes.shift();assert(C.enclosurePlan(p).issues.some(i=>i.code==='MISSING_HOLE'));});
test('Standoff defaults and overrides are configurable; holes, material and body conflicts are diagnosed',()=>{let p=fixture();p.enclosure.standoffDiameter=8;p.enclosure.bore=2;let q=C.enclosurePlan(p);assert(q.mounts.every(m=>m.diameter===8&&m.bore===2));p.enclosure.mounts[0].diameter=10;p.enclosure.mounts[0].bore=3;assert.equal(C.enclosurePlan(p).mounts[0].diameter,10);p.enclosure.bore=0;p.enclosure.mounts[0].bore=null;assert.equal(C.enclosurePlan(p).mounts[0].bore,0);p.enclosure.mounts[0].bore=10;assert(C.enclosurePlan(p).issues.some(i=>i.code==='STANDOFF_WALL'));p.enclosure.mounts[0].bore=2;p.holes[0].x=p.components[1].pcb.x;p.holes[0].y=p.components[1].pcb.y;assert(C.enclosurePlan(p).issues.some(i=>i.code==='STANDOFF_COMPONENT'));p.enclosure.heightMode='manual';p.enclosure.insideHeight=8;assert(C.enclosurePlan(p).issues.some(i=>i.code==='LID_CLEARANCE'));});
test('Openings reject face-edge breaks, warn on merging and protect floor-to-standoff attachment',()=>{let p=fixture(),e=p.enclosure;e.openings=[{id:'opening',name:'USB',face:'front',shape:'rect',u:35,v:10,width:12,height:6}];assert(!C.enclosurePlan(p).issues.some(i=>i.severity==='error'));e.openings[0].u=0;assert(C.enclosurePlan(p).issues.some(i=>i.code==='OPENING_EDGE'));e.openings[0].u=35;e.openings.push({...e.openings[0],id:'copy'});assert(C.enclosurePlan(p).issues.some(i=>i.code==='OPENINGS_MERGE'));e.openings=[{id:'baseHole',name:'Base',face:'floor',shape:'circle',u:10,v:10,width:3,height:3}];assert(C.enclosurePlan(p).issues.some(i=>i.code==='OPENING_STANDOFF'));});
test('Enclosure settings roundtrip with the project and malformed imports are rejected',()=>{let p=fixture();assert.deepEqual(C.validate(JSON.parse(JSON.stringify(p))).enclosure,p.enclosure);for(let mutate of [e=>e.wall=NaN,e=>e.standoffHeight=-1,e=>e.mounts[0].anchor='<script>'.repeat(100),e=>e.boreMode='threaded',e=>e.openings=Array(81).fill({})]){let q=C.clone(p);mutate(q.enclosure);assert.throws(()=>C.validate(q));}let old=C.clone(p);delete old.enclosure;assert.equal(C.validate(old).enclosure,undefined);});
(async()=>{let api=await (await import(require.resolve('manifold-3d/manifold.js'))).default();api.setup();
const p=fixture();p.enclosure.openings=[
 {id:'front',name:'Front rectangle',face:'front',shape:'rect',u:35,v:10,width:10,height:6},
 {id:'back',name:'Back round',face:'back',shape:'circle',u:40,v:12,width:8,height:8},
 {id:'left',name:'Left slot',face:'left',shape:'slot',u:25,v:12,width:14,height:4},
 {id:'right',name:'Right vertical slot',face:'right',shape:'slot',u:25,v:12,width:4,height:12},
 {id:'lid',name:'Lid rectangle',face:'lid',shape:'rect',u:35,v:25,width:12,height:8},
 {id:'floor',name:'Floor round',face:'floor',shape:'circle',u:35,v:35,width:5,height:5}
];let plan=C.enclosurePlan(p),solid;
test('Manifold creates fused one-piece base and lid with openings on all six faces',()=>{assert(!plan.issues.some(i=>i.severity==='error'));solid=S.build(plan,api);for(let key of ['base','lid']){assert.equal(solid[key].parts,1);assert(solid[key].volume>0);assert(solid[key].indices.length>100);fs.writeFileSync(path.join(out,key+'.stl'),S.stl(solid[key]));}fs.writeFileSync(path.join(out,'reference-project.json'),JSON.stringify(p,null,2));fs.writeFileSync(path.join(out,'reference-plan.json'),JSON.stringify(plan,null,2));});
test('Binary STL header/count and ZIP payload preserve exact bytes',()=>{let stl=S.stl(solid.base),count=new DataView(stl.buffer).getUint32(80,true);assert.equal(stl.length,84+50*count);assert.equal(count,solid.base.indices.length/3);let archive=C.zip({'base.stl':stl,'readme.txt':'millimeters'});fs.writeFileSync(path.join(out,'binary-test.zip'),archive);assert.equal(archive[0],80);});
test('Through bores and raised supports change real solid geometry; repeat builds remain deterministic',()=>{let q=C.clone(p);q.enclosure.boreMode='through';let a=S.build(C.enclosurePlan(q),api);assert(a.base.volume<solid.base.volume);fs.writeFileSync(path.join(out,'through.stl'),S.stl(a.base));q.enclosure.boreMode='solid';let b=S.build(C.enclosurePlan(q),api);assert(b.base.volume>solid.base.volume);fs.writeFileSync(path.join(out,'solid-posts.stl'),S.stl(b.base));q.enclosure.boreMode='blind';q.enclosure.standoffHeight=14;let taller=S.build(C.enclosurePlan(q),api);assert(taller.base.volume>solid.base.volume);fs.writeFileSync(path.join(out,'raised.stl'),S.stl(taller.base));assert.equal(S.build(plan,api).base.volume,solid.base.volume);});
console.log(count+' enclosure engine / solid groups passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
