'use strict';
const C=require('../enclosure-adapter'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),P=C.Planes,G=C.G;
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};process.on('exit',()=>{if(count!==18){console.error('Incomplete plane/net verification '+count+'/18');process.exitCode=1;}});
const out=path.join(__dirname,'../test-output/net-planes');fs.mkdirSync(out,{recursive:true});
function part(p,x,y,side='F',kind='smd2'){const c=C.component(p,kind,x,y);c.pcb.side=side;p.components.push(c);return c;}
const first=(p,c)=>C.pads(p).find(a=>a.component===c.id),copy=C.clone;
const zone=(net,layer='F',points=[])=>({id:C.uid(),net,layer,points,thermal:false,clearance:.25,thermalGap:.3,spoke:.5});
const sig=p=>JSON.stringify(p),net=(p,n)=>C.ensureNet(p,n);
test('Ground presets and arbitrary signal/supply planes preserve manual zones, pin nets and routing',()=>{let p=C.sample(),manual=zone('LED+');p.zones.push(manual);const before=copy(p);P.set(p,'F','+5V');P.ground(p);assert(!P.get(p,'F'));assert.equal(P.get(p,'B').net,'GND');for(const key of ['components','tracks','vias','wires','labels'])assert.deepEqual(p[key],before[key]);assert.deepEqual(p.zones[0],manual);P.ground(p,true);assert.equal(P.list(p).length,2);net(p,'SDA');P.set(p,'F','SDA');assert.equal(P.get(p,'F').net,'SDA');P.set(p,'F','');assert.equal(P.list(p).length,1);});
test('Managed-plane imports reject duplicate faces, custom boundaries and nonboolean metadata',()=>{let p=C.fresh();P.ground(p);assert.deepEqual(C.validate(JSON.parse(sig(p))),p);for(const change of [q=>q.zones.push({...copy(q.zones[0]),id:'duplicate'}),q=>q.zones[0].points=[{x:0,y:0},{x:10,y:0},{x:0,y:10}],q=>q.zones[0].boardPlane='true']){let q=copy(p);change(q);assert.throws(()=>C.validate(q),/plane|flag/i);}assert.throws(()=>net(p,''));assert.throws(()=>net(p,'x'.repeat(61)));});
test('Planes follow template/outline/dimension edits and clear board cutouts without saved fill polygons',()=>{let p=C.fresh();P.ground(p);C.applyBoardTemplate(p,'uno-r3');assert.equal(P.get(p,'B').points.length,0);let bounds=G.bounds(C.zones(p).flatMap(z=>z.paths));assert(bounds.maxX>68&&bounds.maxX<68.58);C.resizeBoard(p,80,60);bounds=G.bounds(C.zones(p).flatMap(z=>z.paths));assert(bounds.maxX>79&&bounds.maxX<80);p.cutouts=[{id:'cutout',points:[{x:25,y:20},{x:35,y:20},{x:35,y:30},{x:25,y:30}]}];assert(!G.inside({x:30,y:25},C.zones(p).flatMap(z=>z.paths)));});
test('Manual local pours outrank managed planes regardless of creation order and KiCad exports priority',()=>{let p=C.fresh();P.ground(p);const local=zone('+5V','B',[{x:20,y:10},{x:40,y:10},{x:40,y:30},{x:20,y:30}]);p.zones.push(local);const fill=C.zones(p);assert(G.inside({x:30,y:20},fill.filter(z=>z.owner===local.id).flatMap(z=>z.paths)));assert(!G.inside({x:30,y:20},fill.filter(z=>z.owner!==local.id).flatMap(z=>z.paths)));const tree=C.parseSexpr(C.exportKiCad(p)),zones=tree.filter(x=>x[0]==='zone');assert.equal(zones[0].find(x=>x[0]==='net_name')[1],'+5V');assert(zones[0].find(x=>x[0]==='priority')[1]>zones[1].find(x=>x[0]==='priority')[1]);});
test('Thermal relief and solid connections both make real same-face SMD copper contact',()=>{for(const thermal of [true,false]){let p=C.fresh(),c=part(p,15,15),id=first(p,c).id;P.set(p,'F','GND',{thermal});let before=sig(p),q=C.planPlaneConnections(p,[id],'F');assert.equal(sig(p),before);assert.equal(q.tracks.length,0);assert.equal(q.vias.length,0);assert.equal(P.status(q.document)[0].connected,1);}});
test('Through-hole leads connect directly to a back plane with no extra drill or trace',()=>{let p=C.fresh(),c=part(p,15,15,'F','header2');P.ground(p);const q=C.planPlaneConnections(p,[first(p,c).id],'B');assert.equal(q.vias.length,0);assert.equal(q.tracks.length,0);assert.equal(P.status(q.document)[0].connected,1);});
test('Opposite-face SMD proposal includes a safe stub and through-via; Gerber and drill contain copper',()=>{let p=C.fresh(),c=part(p,15,15);P.ground(p);let before=sig(p),q=C.planPlaneConnections(p,[first(p,c).id],'B');assert.equal(sig(p),before);assert.equal(q.vias.length,1);assert.equal(q.tracks.length,1);assert.equal(q.tracks[0].layer,'F');assert.equal(P.status(q.document)[0].connected,1);assert(C.drill(q.document).includes('X'+q.vias[0].x.toFixed(4)));for(const layer of ['F','B'])assert(C.gerber(q.document,layer).includes('G36'));assert(C.gerber(q.document,'B').includes('G36'));fs.writeFileSync(path.join(out,'plane-connected.json'),JSON.stringify(q.document,null,2));fs.writeFileSync(path.join(out,'plane-connected.kicad_pcb'),C.exportKiCad(q.document));fs.writeFileSync(path.join(out,'expected.json'),JSON.stringify({height:q.document.board.height,via:q.vias[0],pads:C.pads(q.document).filter(a=>a.net==='GND'),layers:Object.fromEntries(['F','B'].map(layer=>[layer+'_Cu.gbr',G.union(C.copper(q.document).filter(a=>a.layer==='both'||a.layer===layer).flatMap(a=>a.paths))]))}));for(const [name,value] of Object.entries(C.fabrication(q.document)))fs.writeFileSync(path.join(out,name),value);});
test('Plane helper reuses an attached existing via before adding another drill',()=>{let p=C.fresh(),c=part(p,15,15);P.ground(p);p.vias.push({id:'existingvia',x:9,y:15,net:'GND',diameter:.9,drill:.4});const q=C.planPlaneConnections(p,[first(p,c).id],'B');assert.equal(q.vias.length,0);assert.equal(q.tracks.length,1);assert.equal(q.steps[0].kind,'existing-via');assert.equal(P.status(q.document)[0].connected,1);});
test('Different-net and NC leads are rejected atomically without merging or relabeling other circuits',()=>{let p=C.fresh(),c=part(p,15,15);P.ground(p);let id=first(p,c).id;p=C.assignPinsToNet(p,[id],'+5V');let before=sig(p);assert.throws(()=>C.planPlaneConnections(p,[id],'B'),/never merges/);assert.equal(sig(p),before);p.components[0].pads[1].nc=true;before=sig(p);assert.throws(()=>C.planPlaneConnections(p,[p.components[0].id+':2'],'B'),/no-connect/);assert.equal(sig(p),before);});
test('Named assignment follows repeated physical pads and wired schematic pins without copper claims',()=>{let p=C.fresh(),a=part(p,15,15),b=part(p,30,15);a.pads.push({...copy(a.pads[0]),n:'3',pin:'1',y:4});let q=C.assignPinsToNet(p,[a.id+':1'],'GND');assert.equal(q.components[0].pads.find(a=>a.n==='3').net,'GND');assert.equal(p.components[0].pads[0].net,'');C.link(p,{kind:'pin',component:a.id,pin:'1'},{kind:'pin',component:b.id,pin:'1'});const auto=p.components[0].pads[0].net;q=C.assignPinsToNet(p,[a.id+':1'],auto);assert.equal(q.wires[0].net,auto);assert.equal(q.components[1].pads[0].net,auto);assert(C.connections(q).length>0);});
test('Plane names do not connect opposite faces; physical through-via makes the connection',()=>{let p=C.fresh(),a=part(p,15,15),b=part(p,30,15,'B');P.ground(p,true);p=C.assignPinsToNet(p,[first(p,a).id,first(p,b).id],'GND');assert.equal(C.connections(p).length,1);const r=P.status(p);assert(r.every(r=>r.connected===1&&r.total===2));p.vias.push({id:'joinfaces',x:22,y:20,net:'GND',diameter:.9,drill:.4});assert.equal(C.connections(p).length,0);assert(P.status(p).every(r=>r.connected===2));});
test('Split-plane regions and isolated leads remain visible to connectivity checks',()=>{let p=C.fresh(),a=part(p,10,20),b=part(p,43,20);P.set(p,'F','GND');p=C.assignPinsToNet(p,[first(p,a).id,first(p,b).id],'GND');p.tracks=[{id:'barrier',net:'+5V',layer:'F',width:1,points:[{x:25,y:0},{x:25,y:40}]}];let r=P.status(p)[0];assert.equal(r.regions,2);assert.equal(r.connected,1);assert(r.rows.some(a=>a.state==='isolated'));assert(C.checks(p).some(f=>f.code==='PLANE_SPLIT'));assert.equal(C.connections(p).length,1);});
test('Foreign copper, mechanical holes and via keepouts block unsafe plane proposals without editing the board',()=>{
 for(const mode of ['foreign','hole','via-keepout']){let p=C.fresh(),c=part(p,15,15),a=first(p,c);P.ground(p);if(mode==='foreign'){let other=part(p,15.1,15);p=C.assignPinsToNet(p,[first(p,other).id],'+5V');}if(mode==='hole')p.holes=[{id:'hole',x:a.x,y:a.y,drill:1,slot:0,rotation:0,plated:false}];if(mode==='via-keepout')c.keepouts=[{points:[{x:-100,y:-100},{x:100,y:-100},{x:100,y:100},{x:-100,y:100}],layers:['*.Cu'],prohibit:{tracks:false,vias:true,pads:false,copperpour:false,footprints:false}}];let before=sig(p);assert.throws(()=>C.planPlaneConnections(p,[a.id],'B'),/clearance|hole|path/i);assert.equal(sig(p),before);}
});
test('Wire preview joins picked leads on a signal net with checked real tracks and preserves unpicked pads',()=>{let p=C.fresh(),a=part(p,12,12),b=part(p,35,12),c=part(p,24,29);net(p,'SDA');let ids=[a,b,c].map(c=>first(p,c).id),before=sig(p),q=C.planNetWires(p,ids,'SDA');assert.equal(sig(p),before);assert.equal(q.assigned.length,3);assert(q.tracks.length>=2);assert.equal(C.connections(q.document).length,0);assert(q.document.components.every(c=>c.pads[1].net===''));let keys=new Set(ids),top=C.topology(q.document),roots=top.items.flatMap((a,i)=>keys.has(a.id)?[top.u.find(i)]:[]);assert.equal(new Set(roots).size,1);});
test('Opposite-side wire preview uses a through-via; disabling vias leaves source unchanged',()=>{let p=C.fresh(),a=part(p,12,12),b=part(p,35,12,'B'),ids=[first(p,a).id,first(p,b).id],before=sig(p);const q=C.planNetWires(p,ids,'GND');assert.equal(q.vias.length,1);assert.equal(q.tracks.length,2);assert.equal(C.connections(q.document).length,0);assert.throws(()=>C.planNetWires(p,ids,'GND',{vias:false}),/No complete route/);assert.equal(sig(p),before);});
test('Already-connected leads add no duplicate tracks; failed multi-lead wire proposals are atomic',()=>{let p=C.fresh(),a=part(p,12,12),b=part(p,35,12),ids=[first(p,a).id,first(p,b).id];let q=C.planNetWires(p,ids,'GND');let again=C.planNetWires(q.document,ids,'GND');assert.equal(again.tracks.length,0);assert.equal(again.vias.length,0);let c=part(p,-10,-10);ids.push(first(p,c).id);const before=sig(p);assert.throws(()=>C.planNetWires(p,ids,'GND'),/edge|path/);assert.equal(sig(p),before);});
test('Net-specific trace rules and annular-ring rules constrain proposals',()=>{let p=C.fresh(),a=part(p,12,12),b=part(p,35,12);p.netClasses=[{id:'powerclass',name:'Power',nets:['GND'],width:.8,clearance:.5}];let ids=[first(p,a).id,first(p,b).id];assert.throws(()=>C.planNetWires(p,ids,'GND',{width:.4}),/net rule/);assert.throws(()=>C.planNetWires(p,ids,'GND',{diameter:.5,drill:.4}),/annular/);assert(C.planNetWires(p,ids,'GND',{width:.8}).tracks.every(t=>t.width===.8));});
test('Plane and connection metadata survives JSON, with enclosure and board-template features intact',()=>{let p=C.fresh();C.applyBoardTemplate(p,'uno-r3');part(p,25,25);p.enclosureWorkshop=C.enclosureWorkshopCreate(p);const enc=copy(p.enclosureWorkshop);P.ground(p);p=C.planPlaneConnections(p,[C.pads(p)[0].id],'B').document;p=C.validate(JSON.parse(sig(p)));assert.equal(p.board.template.family,'uno-r3');assert.deepEqual(p.enclosureWorkshop,enc);assert.equal(P.status(p)[0].connected,1);assert.equal(C.enclosureMechanical(p).vias.length,1);});
console.log(count+' net/plane engine groups passed');
