'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const C=require('../enclosure-adapter'),M=require('../enclosure-workshop/model'),K=require('../enclosure-workshop/core'),G=require('../enclosure-workshop/geometry'),S=require('../enclosure-workshop/solid'),X=require('../enclosure-workshop/export');
const out=path.join(__dirname,'../test-output/workshop');fs.mkdirSync(out,{recursive:true});let passed=0,failed=0;const manifest=[];process.on('exit',()=>{if(passed+failed!==40){console.error('Incomplete geometry verification '+(passed+failed)+'/40');process.exitCode=1;}});
const board=()=>C.validate(JSON.parse(fs.readFileSync(path.join(__dirname,'../examples/enclosure-reference.circuitbench.json'))));
function fresh(){let p=board();delete p.enclosure;return C.enclosureWorkshopCreate(p);}
function good(r){assert(r.parts.length);for(const p of r.parts){assert(p.audit.valid,p.name+JSON.stringify(p.audit));assert.equal(p.audit.connectedComponents,1,p.name);assert(S.audit(S.readSTL(S.stl(p.mesh))).valid,p.name+' STL');}assert.deepEqual(r.findings?.filter(f=>f.severity==='error')||[],[]);}
function specimen(name,p,run=G.build){p=M.validate(p);const r=run(p);good(r);const files=X.packageFiles(r,p).files,dir=path.join(out,name);fs.mkdirSync(dir,{recursive:true});for(const [n,b] of Object.entries(files)){let file=path.join(dir,n);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,typeof b==='string'?b:Buffer.from(b));}assert.equal(X.read3MF(files['enclosure.3mf']).parts.length,r.parts.length);fs.writeFileSync(path.join(dir,'world.json'),JSON.stringify({dimensions:r.dimensions,mounts:r.mounts,parts:r.parts.map(p=>({id:p.id,mesh:p.mesh,bounds:p.audit.bounds,volume:p.audit.volumeMm3}))}));manifest.push({name,parts:r.parts.map(p=>p.id),dimensions:r.dimensions});return r;}
async function test(name,fn){try{await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+'\n'+e.stack);}}
(async()=>{const create=(await import(require.resolve('manifold-3d/manifold.js'))).default,api=await create();api.setup();require('../enclosure-workshop/manifold-kernel')(S,api);
await test('v1.4 migration preserves board, 70 × 50 mm footprint, six face openings and blind supports',()=>{let b=board(),before=JSON.stringify(b),p=C.enclosureWorkshopMigrate(b),d=M.dimensions(p);assert.equal(d.width,70);assert.equal(d.depth,50);assert.equal(d.boardZ,8);assert.equal(d.top,26.6);assert.equal(p.features.length,6);assert.equal(M.mounts(p).filter(m=>m.enabled).length,4);assert.equal(p.integration.supportMode,'blind');specimen('migrated',p);assert.equal(JSON.stringify(b),before);assert.deepEqual(M.validate(JSON.stringify(p)),p);});
await test('v1.4 mechanical handoff preserves top/bottom transformed pads, slots, board and holes',()=>{let b=board(),a=K.normalize(JSON.stringify(C.enclosureMechanical(b)));assert.equal(a.components.length,b.components.length);for(const pad of C.pads(b)){let q=a.pads.find(x=>x.ownerId===pad.component&&String(x.number)===String(pad.n));assert(q,JSON.stringify(pad));assert(Math.abs(q.x-pad.x)<.00006);assert(Math.abs(q.y+pad.y)<.00006);}for(const h of C.holes(b)){let q=a.bores.find(x=>x.id===h.id);assert(q);assert.equal(q.x,h.x);assert.equal(q.y,-h.y);assert.equal(q.overallLength,Math.max(h.slot||0,h.drill));}});
await test('v1.4 links follow stable component IDs after a PCB revision; deleted links block generation',()=>{let b=board();delete b.enclosure;let p=C.enclosureWorkshopCreate(b),id=b.components[0].id,f=M.feature('cutout','lid',id);p.features.push(f);let before=M.resolvedFeature(f,p);b.components[0].pcb.x+=4;b.enclosureWorkshop=p;let next=C.enclosureWorkshopSync(b),after=M.resolvedFeature(next.features[0],next);assert.equal(after.u-before.u,4);b.components.shift();b.enclosureWorkshop=next;let r=G.build(C.enclosureWorkshopSync(b));assert(r.findings.some(f=>f.severity==='error'&&/anchor|link/.test(f.code)));});
for(const closure of ['external','internal','insert'])await test('v1.4 real fastening geometry: '+closure,()=>{let p=fresh();p.system.closure.type=closure;p.settings.closure=true;specimen('closure-'+closure,p);});
for(const mode of ['blind','through','solid'])await test('v1.4 changing support bore style invalidates geometry cache: '+mode,()=>{let p=fresh();p.integration.supportMode=mode;p.integration.manualSupports=[{id:'manual-support',x:10,y:-20,diameter:6,bore:2.6,enabled:true}];let r=specimen('support-'+mode,p);assert.equal(r.mounts.length,5);});
for(const kind of ['text-raised','text-recessed','vent','pocket','art-raised','art-recessed'])await test('v1.4 generated '+kind+' survives STL and named 3MF round trip',()=>{let p=fresh(),f={...M.feature(kind,'lid'),text:'FIELD 16',size:3,depth:.6,width:18,height:10};if(kind==='vent')Object.assign(f,{columns:3,rows:2,width:2,height:3,pitchU:5,pitchV:6});if(kind.startsWith('art'))Object.assign(f,{artRule:'evenodd',contours:[[[-.5,-.5],[.5,-.5],[.5,.5],[-.5,.5]],[[-.25,-.25],[.25,-.25],[.25,.25],[-.25,.25]]],artGroups:[{rule:'evenodd',contours:[[[-.5,-.5],[.5,-.5],[.5,.5],[-.5,.5]],[[-.25,-.25],[.25,-.25],[.25,.25],[-.25,.25]]]}]});p.features.push(f);specimen('feature-'+kind,p);});
await test('v1.5 full-scale fit frame keeps supports and lowers material without editing design',()=>{let p=fresh(),before=JSON.stringify(p),r=specimen('fit-frame',p,G.fitFrame);assert(r.volumeReductionPercent>15);assert.equal(JSON.stringify(p),before);});
for(const type of ['connector','led','display','button'])await test('v1.5 functional '+type+' produces printable parts',()=>{let p=fresh();p.settings.autoHeight=false;p.settings.height=35;p.workflow.interfaces.push({...M.interfaceDefinition(type,'lid'),id:'interface-'+type,reviewed:true,stem:2,displayRetainer:type==='display',cableTies:type==='connector'});let r=specimen('interface-'+type,p);assert.equal(r.parts.length,type==='button'?4:type==='display'?3:2);});
await test('v1.5 local corrections preserve manual supports and stale physical evidence',()=>{let p=fresh();p.integration.manualSupports=[{id:'manual-one',x:30,y:-20,diameter:6,bore:2,enabled:true}];p=M.addEvidence(p,'fit',{name:'Synthetic test',result:'pass'});assert.equal(M.proofStatus(p).fit.status,'recorded-pass');let q=M.correction(p,{kind:'fit',delta:.1,note:'Synthetic correction'});assert.deepEqual(q.integration,p.integration);assert.equal(M.proofStatus(q).fit.status,'stale');p.integration.boreDepth+=1;assert.equal(M.proofStatus(p).fit.status,'stale');});
for(const kind of ['joint','hardware','opening'])await test('v1.5 targeted '+kind+' coupon uses current geometry',()=>{let p=fresh();p.features.push({...M.feature('cutout','lid'),width:15,height:6});specimen('coupon-'+kind,p,q=>G.targetedCoupon(q,kind,q.features[0].id));});
for(const family of ['rounded','circle','oval','polygon','board-following','tray','sloped'])await test('v1.6 shell '+family+' is independently exportable',()=>{let p=fresh();p.system.shell.family=family;specimen('shell-'+family,p);});
for(const type of ['sliding','snap','hinge'])await test('v1.6 '+type+' enclosure and matching mechanism coupon',()=>{let p=fresh();p.system.closure.type=type;let r=specimen('closure-'+type,p);assert.equal(r.parts.length,type==='hinge'?3:2);if(type==='hinge'){const raw=G.lastSolidBuild.raw,base=raw.find(p=>p.id==='base').solid,lid=raw.find(p=>p.id==='lid').solid,pin=raw.find(p=>p.id==='hinge-pin').solid,d=r.dimensions,y=d.maxY+p.system.closure.pin/2+1.8+.5,z=d.height+p.settings.roof/2;for(const angle of [0,-15,-30,-60,-90,-120]){let a=angle*Math.PI/180,opened=lid.transform(v=>[v[0],y+(v[1]-y)*Math.cos(a)-(v[2]-z)*Math.sin(a),z+(v[1]-y)*Math.sin(a)+(v[2]-z)*Math.cos(a)]);assert(opened.intersect(base).volume()<.001,'Hinge shell interference at '+angle);assert(opened.intersect(pin).volume()<.001,'Hinge pin interference at '+angle);}}specimen('coupon-'+type,p,q=>G.targetedCoupon(q,'joint'));p.system.shell.family='oval';assert.throws(()=>G.build(p),/requires a level rounded/);});
for(const retention of ['rails','cradle','hold-down'])await test('v1.6 '+retention+' board retention',()=>{let p=fresh();p.system.retention.type=retention;specimen('retention-'+retention,p);});
await test('v1.6 removable floor service panel remains a separate part',()=>{let p=fresh();p.features.push({...M.feature('panel','floor'),width:14,height:10,depth:1.6});assert.equal(specimen('service-panel',p).parts.length,3);});
await test('v1.6 additional PCB placement, device support and recipe mapping persist',()=>{let p=fresh();p.integration.supportMode='through';p=M.addBoard(p,p.source.text,'Second CIRCUITBENCH PCB');Object.assign(p.system.boards[0],{x:85,y:0,z:0,rotation:90,supports:true});p.system.objects.push({id:'battery-1',name:'Battery envelope',type:'battery',x:50,y:-75,z:1,width:22,depth:14,height:10,mount:'pad',enabled:true,evidence:'user-entered',notes:'Synthetic geometry test'});specimen('assembly',p);const c=M.effective(p).components[0];p.features.push({...M.feature('cutout','lid',c.id),width:5,height:4});let r=M.toRecipe(p,'Portable recipe'),q=M.applyRecipe(fresh(),r,{[c.id]:c.id});assert.equal(q.integration.supportMode,'through');assert.equal(q.features[0].componentId,c.id);assert.equal(q.system.evidence.length,0);assert.deepEqual(C.validate({...board(),enclosureWorkshop:p}).enclosureWorkshop,M.validate(p));});
await test('v1.6 invalid unsupported or detached geometry does not produce exportable results',()=>{let p=fresh();p.system.shell.family='polygon';p.system.shell.points=[[0,0],[50,40],[0,40],[50,0]];assert.throws(()=>G.build(p),/simple|polygon|nonzero/i);p=fresh();p.integration.manualSupports=[{id:'offboard',x:500,y:500,diameter:6,bore:2,enabled:true}];const r=G.build(p);assert(r.parts.some(p=>p.audit.connectedComponents!==1)||r.findings.some(f=>f.severity==='error'));});
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2));console.log(`${passed} workshop tests passed; ${failed} failed.`);if(failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
