/* Geometric checks are distinct from dimensional evidence and physical fit. */
(function(root,factory){let node=typeof module==='object'&&module.exports,a=factory(node?require('./solid.js'):root.CaseSolid,node?require('./model.js'):root.CaseModel);if(node)module.exports=a;else root.CaseChecks=a;})(globalThis,function(S,M){'use strict';
const EPS=1e-4,over=(a,b)=>a.minX<b.maxX-EPS&&a.maxX>b.minX+EPS&&a.minY<b.maxY-EPS&&a.maxY>b.minY+EPS&&a.minZ<b.maxZ-EPS&&a.maxZ>b.minZ+EPS;
const shape=b=>S.box(b.minX,b.minY,b.minZ,b.maxX-b.minX,b.maxY-b.minY,Math.max(.0001,b.maxZ-b.minZ));
function run(p,a,d,solids,parts,meta=[],progress=()=>{}){let out=[],s=p.settings;const add=(severity,code,message,ids=[],evidence='',confidence='geometric')=>out.push({id:code+':'+out.length,severity,code,message,objects:ids,evidence,confidence});
 for(const part of parts){if(!part.audit.valid)add('error','mesh-invalid',part.name+' failed closed-solid topology validation.',[part.id],JSON.stringify(part.audit));if(part.audit.connectedComponents!==1)add('error','disconnected-solid',part.name+' contains '+part.audit.connectedComponents+' disconnected solids.',[part.id],'Suppress or reposition unjoined additions or detached fastening bosses.');}
 const mounts=M.mounts(p,a).filter(h=>h.enabled),closers=M.closures(p,d).filter(h=>h.enabled),additions=meta.filter(f=>['add','text-raised','art-raised','panel'].includes(f.kind));
 if(!mounts.length&&(!p.system||['manual','standoffs'].includes(p.system.retention.type)))add('warning','board-retention','No PCB mounting supports are enabled. Add and review an internal cradle or ledges.',['board'],'Manual material pads on the inside floor can provide supports; retention is not automatically certified.');
 for(const h of mounts){if(!h.confirmed)add('warning','mount-review','Confirm that this hole is intended to mount the PCB.',[h.id],'A support is proposed at the imported center; the hole is not moved.','unverified');if(h.boreDiameter>h.diameter+.001)add('warning','bolt-pcb-hole','The support bore is larger than the imported PCB hole.',[h.id],h.boreDiameter+' mm versus PCB '+h.diameter+' mm.');if(p.integration?.supportMode!=='blind'&&p.integration?.nutPockets!==false&&(h.outerDiameter-s.nutFlats/Math.cos(Math.PI/6))/2<s.minFeature)add('warning','support-nut-wall','Support has a thin wall around its nut recess.',[h.id]);if(p.integration?.supportMode!=='blind'&&p.integration?.nutPockets!==false&&s.nutDepth>d.boardZ-s.minFeature)add('error','nut-depth','PCB-support nut recess reaches too close to the support top.',[h.id]);}
 for(const c of closers){if((c.diameter-s.nutFlats/Math.cos(Math.PI/6))/2<s.minFeature)add('warning','closure-nut-wall','Lid fastening ear has a thin wall around its nut recess.',[c.id]);if(s.nutDepth>d.height-s.minFeature)add('error','closure-nut-depth','Lid-fastener nut recess reaches too close to the ear top.',[c.id]);}
 if(s.headDepth>s.roof-s.minFeature)add('error','head-recess','Lid screw-head recess leaves insufficient roof thickness.',['lid']);
 if(!s.closure)add('warning','lid-retention','Lid fasteners are disabled; the locating skirt is not a validated friction closure.',['lid']);
 const rb=solids.base.bounds,baseBoxes=[{minX:d.minX,minY:d.minY,minZ:0,maxX:d.maxX,maxY:d.maxY,maxZ:s.floor},...mounts.map(h=>({minX:h.x-h.outerDiameter/2,minY:h.y-h.outerDiameter/2,minZ:s.floor,maxX:h.x+h.outerDiameter/2,maxY:h.y+h.outerDiameter/2,maxZ:d.boardZ+(h.z||0)})),...closers.map(h=>({minX:h.x-h.diameter/2,minY:h.y-h.diameter/2,minZ:0,maxX:h.x+h.diameter/2,maxY:h.y+h.diameter/2,maxZ:d.height}))];
 const possible=(b,part)=>{if(p.system&&(p.system.shell.family!=='rounded'||p.system.retention.type!=='standoffs'||p.system.objects.some(x=>x.enabled&&x.mount!=='none')))return true;const inset=Math.max(0,d.radius-s.wall);if(part==='base'){if(b.minX<d.innerMinX+inset||b.maxX>d.innerMaxX-inset||b.minY<d.innerMinY+inset||b.maxY>d.innerMaxY-inset)return true;if(baseBoxes.some(k=>over(b,k)))return true;}else if(b.maxZ>d.height-s.lipDepth-EPS)return true;return additions.filter(f=>f.targets?f.targets.includes(part):(['lid','inside-lid'].includes(f.face)?'lid':'base')===part).some(f=>over(b,{minX:f.bounds.min[0],minY:f.bounds.min[1],minZ:f.bounds.min[2],maxX:f.bounds.max[0],maxY:f.bounds.max[1],maxZ:f.bounds.max[2]}));};
 const check=(name,id,b,make,category='component')=>{progress('Checking '+name);let actual=null;for(const part of ['base','lid'])if(possible(b,part)){actual??=make();let volume=solids[part].intersect(actual).volume();if(volume>EPS)add(category==='access'?'warning':'error',category+'-collision',name+' intersects the '+part+'.',[id,part],volume.toFixed(3)+' mm³ overlap of modeled envelopes.');}if(category==='component'){let sw={...b,maxZ:Math.max(b.maxZ,d.top+10)};if(possible(sw,'base')){let swept=S.prism([[b.minX,b.minY],[b.maxX,b.minY],[b.maxX,b.maxY],[b.minX,b.maxY]],b.minZ,sw.maxZ);let v=solids.base.intersect(swept).volume();if(v>EPS)add('warning','insertion-path',name+' may not insert vertically with the lid removed.',[id],'Conservative XY envelope swept upward; rotate/tilt assembly paths are not solved.');}}};
 for(const c of a.components){if(!c.body||!c.body.height)continue;const b={...c.bounds,minZ:c.bounds.minZ+d.boardZ,maxZ:c.bounds.maxZ+d.boardZ};check(c.ref,c.id,b,()=>S.prism(c.vertices.slice(0,4),b.minZ,b.maxZ));}
 const badLeads=new Set();for(const lead of a.projections){let b={...lead.bounds,minZ:lead.bounds.minZ+d.boardZ,maxZ:lead.bounds.maxZ+d.boardZ};if(b.maxZ-b.minZ<EPS)continue;for(const part of ['base','lid']){const key=lead.ownerId+':'+part;if(!badLeads.has(key)&&possible(b,part)&&solids[part].intersect(shape(b)).volume()>EPS){badLeads.add(key);add('error','lead-collision','Lead/solder projection intersects the '+part+'.',[lead.ownerId,part],lead.known?'User-entered projection.':'Uses the visible '+s.leadAllowance+' mm assumed projection.','assumption-dependent');}}}
 for(const e of a.envelopes){if(e.unresolved){add('error','envelope-link',e.name+' has a missing component anchor.',[e.id]);continue;}let b={...e.bounds,minZ:e.bounds.minZ+d.boardZ,maxZ:e.bounds.maxZ+d.boardZ};check(e.name,e.id,b,()=>shape(b),e.role==='internal'?'reserved':'access');}
 // Exact extruded source outline; internal cutouts and all drilled apertures are removed
 // from the candidate intersection. Reference PCB geometry is never exported as a part.
 const pb={...a.board.bounds,minZ:d.boardZ,maxZ:d.boardZ+a.board.thickness};let pcb=null;
 const pcbAt=(maxZ)=>{let slab=S.prism(a.board.outline,pb.minZ,maxZ);for(const c of a.cutouts)slab=slab.subtract(S.prism(c.points,pb.minZ-.1,maxZ+.1));return slab;};
 const removeDrills=(hit,maxZ)=>{if(hit.volume()<EPS)return hit;for(const h of a.bores.filter(h=>!h.boardId||h.boardId==='primary')){let bb=hit.bounds;if(h.perimeter.some(q=>q.x>=bb.min[0]-h.diameter&&q.x<=bb.max[0]+h.diameter&&q.y>=bb.min[1]-h.diameter&&q.y<=bb.max[1]+h.diameter))hit=hit.subtract(S.prism(h.perimeter,pb.minZ-.1,maxZ+.1));}return hit;};
 if(pb.minZ<s.floor-EPS||pb.maxZ>d.height+EPS)add('error','pcb-height','PCB thickness is not contained between the floor and lid underside.',['board'],'PCB Z '+pb.minZ.toFixed(2)+'–'+pb.maxZ.toFixed(2)+' mm; usable Z '+s.floor+'–'+d.height.toFixed(2)+' mm.');
 for(const part of ['base','lid'])if(possible(pb,part)){progress('Checking PCB against '+part);pcb??=pcbAt(pb.maxZ);let hit=removeDrills(solids[part].intersect(pcb),pb.maxZ),volume=hit.volume();if(volume>EPS)add('error','pcb-collision','PCB material intersects the '+part+'.',['board',part],volume.toFixed(3)+' mm³ overlap after source cutouts and drill apertures.');}
 const sweep={...pb,maxZ:Math.max(pb.maxZ,d.top+10)};if(possible(sweep,'base')){let hit=removeDrills(solids.base.intersect(pcbAt(sweep.maxZ)),sweep.maxZ);if(hit.volume()>EPS)add('warning','pcb-insertion','PCB may not insert vertically with the lid removed.',['board'],'Extruded source XY outline swept upward; alternate tilted or rotated paths are not solved.');}
 if(solids.base.intersect(solids.lid).volume()>EPS)add('error','closure-overlap','Base and lid overlap in their assembled positions.',['base','lid'],'Review custom additions and joint parameters.');
 for(const part of parts){const raw=part.audit.size,o=part.orientation||'bottom',z=['front','back'].includes(o)?[raw[0],raw[2],raw[1]]:['left','right'].includes(o)?[raw[2],raw[1],raw[0]]:raw;if(z[0]>s.bedWidth||z[1]>s.bedDepth)add('warning','printer-bed',part.name+' exceeds the saved printer bed in its selected print orientation.',[part.id],z[0].toFixed(1)+' × '+z[1].toFixed(1)+' mm; bed '+s.bedWidth+' × '+s.bedDepth+' mm.');}
 if(p.features.some(f=>f.enabled&&['text-raised','art-raised','add'].includes(f.kind)&&f.face==='lid'&&(p.system?.orientations.lid||'top')==='top'))add('warning','raised-print-face','Raised exterior material affects face-down lid printing. Review supports or rotate the lid in your slicer.',['lid'],'STL/3MF are geometry only; no automatic supports or G-code are generated.');
 for(const id of Object.keys(p.overrides))if(!a.components.some(c=>c.id===id))add('warning','orphan-override','A mechanical override belongs to a component removed in a board revision.',[id],'Preserved in the project; not silently reassigned.');
 add('info','physical-fit','Physical print and hardware fit are untested.',[],'Use the calibration coupons and verify actual parts. No thermal, electrical safety or enclosure-rating certification.','unverified');
 return out;
}
function hardware(p,a,d){let s=p.settings,m=M.mounts(p,a).filter(h=>h.enabled&&h.boreDiameter>0),c=M.closures(p,d).filter(h=>h.enabled);let series=[6,8,10,12,16,20,25,30,35,40,45,50,60,70,80,100],choose=v=>series.find(x=>x>=v)||Math.ceil(v),items=[];
 const groups=(rows,boreKey,item,length,note)=>{const grouped=new Map();for(const h of rows){let bore=h[boreKey];if(!grouped.has(bore))grouped.set(bore,[]);grouped.get(bore).push(h.id);}for(const [bore,ids]of grouped)items.push({item,quantity:ids.length,bore,nutFlats:s.nutFlats,suggestedLength:choose(length),note:note+' Applies to '+ids.join(', ')+'.'});};
 groups(m,'boreDiameter',p.integration?.supportMode==='blind'?'PCB pilot-hole screws':'PCB through-bolts',d.boardZ+Math.max(a.board.thickness,...m.map(h=>(h.z||0)+(a.boards?.find(b=>b.id===h.boardId)?.board.thickness||a.board.thickness)))-s.nutDepth+2,'Nominal length candidate only. Check PCB hole, washer, head clearance and nut engagement.');
 groups(c,'bore',p.system?.closure.type==='insert'?'Lid insert screws':'Lid through-bolts',p.system?.closure.type==='insert'?s.roof-s.headDepth+p.system.hardware.insertLength*.7:d.top-s.headDepth-s.nutDepth+2,'Nominal length candidate only. Measure the selected screw and nut before printing.');
 items.push({item:'Hex nuts',quantity:(p.integration?.supportMode==='blind'||p.integration?.nutPockets===false?0:m.length)+(p.system?.closure.type==='insert'?0:c.length)+(p.system?.retention.type==='hold-down'?4:0),nutFlats:s.nutFlats,nutDepth:s.nutDepth,note:'Captive pockets open on the underside. Recess size is a user setting, not a verified hardware specification.'});if(p.system?.closure.type==='insert')items.push({item:'Heat-set inserts',quantity:c.length,note:'Pocket diameter '+p.system.hardware.insertDiameter+' mm, depth '+p.system.hardware.insertLength+' mm; actual hardware and insertion require review.'});if(p.system?.retention.type==='hold-down')items.push({item:'Hold-down bar screws',quantity:4,bore:s.boltDiameter,suggestedLength:choose(d.boardZ+a.board.thickness+p.system.retention.clearance+p.system.retention.barHeight),note:'Four through-bores, underside nuts; confirm length and washer access.'});for(const f of p.features.filter(f=>f.enabled&&f.kind==='panel'))items.push({item:f.name+' fasteners',quantity:4,bore:s.boltDiameter,note:'Panel and flange have through-bores. Nut/head seating and installation access require review.'});return items;
}
return{run,hardware,over};
});
