/* This source is inserted inside the workshop app closure. GPL-3.0-only. */
let embeddedHost=null;
saveNow=function(){clearTimeout(saveTimer);if(!embeddedHost||!project)return;try{project=M.validate(project);const result=embeddedHost.change(C.clone(project));saveDirty=false;saveFailed=false;setSave(result.saved?'saved':'unsaved',result.saved?'Saved with PCB project':'In PCB project · saving…');}catch(e){saveFailed=true;setSave('error','Not saved');notice(e.message+' Export the enclosure backup before leaving.','Retry save');}};
saveProject=function(){saveNow();embeddedHost?.exportProject();};
freshStart=async function(){if(!await confirm('Reset enclosure?','Replace this enclosure with a fresh case around the current PCB? The PCB is kept. You can undo this change.'))return;const next=embeddedHost.reset();pushUndo();project=M.validate(next);project.generated=true;assembly=M.effective(project);caseResult=null;resultKey='';renderAll(true);dirty();generateCase(true);};
loadSource=async function(){throw Error('Open the primary PCB from CIRCUITBENCH. Use Assembly to add a separate board, or Library to import a recipe.');};
const embeddedRender=renderAll;renderAll=function(reset=false){embeddedRender(reset);if(!project)return;const format=JSON.parse(project.source.text).app;if(format==='CIRCUITBENCH_MECHANICAL')$('sourceMeta').innerHTML='<span class="badge">CIRCUITBENCH PCB</span><span class="badge">Live project geometry · mm</span>';
 if(activeTab==='source'){for(const id of ['sourceRevisionBtn','updateSourceBtn','revisionBtn','compareBtn','baselineBtn'])if($(id))$(id).hidden=true;const btn=$('mechanicalHandoffBtn');if(btn)btn.onclick=()=>download(filename(project.title)+'-mechanical.json',project.source.text);}
 if(activeTab==='mounts'&&!$('supportOptions')){const b=document.createElement('button');b.id='supportOptions';b.className='full';b.textContent='Standoff bores + manual supports';b.onclick=supportOptions;$('drawerContent').prepend(b);}
};
function supportOptions(){let e=project.integration;modal('PCB standoffs',`<form id="supportForm"><div class="field-grid"><label>Bore style<select name="supportMode">${[['blind','Blind pilot hole'],['through','Through floor'],['solid','Solid support']].map(([v,l])=>`<option value="${v}" ${e.supportMode===v?'selected':''}>${l}</option>`).join('')}</select></label>${makeField('boreDepth','Blind bore depth · mm',e.boreDepth)}<label class="check"><input type="checkbox" name="nutPockets" ${e.nutPockets?'checked':''}>Through-hole nut pockets</label></div><p class="small muted">PCB lift and default diameters are in Enclosure. Blind bores keep the floor closed and leave 0.4 mm above it.</p><h3>Manual supports</h3><div id="manualSupportRows">${e.manualSupports.map(m=>`<div class="field-grid" data-manual="${esc(m.id)}"><label>X on PCB · mm<input data-key="x" type="number" value="${m.x}" step=".1"></label><label>Y on PCB · mm<input data-key="y" type="number" value="${-m.y}" step=".1"></label><label>Outer Ø<input data-key="diameter" type="number" value="${m.diameter}" step=".1"></label><label>Bore Ø<input data-key="bore" type="number" value="${m.bore}" step=".1"></label><label class="check"><input data-key="enabled" type="checkbox" ${m.enabled?'checked':''}>Enabled</label><button type="button" data-remove-manual="${esc(m.id)}">Remove</button></div>`).join('')}</div>${formFoot('Apply standoff settings')}</form><button id="addManualSupport" class="full">Add manual support</button>`,[{label:'Close',action:closeModal}]);
 bindForm('supportForm',v=>{const list=[...$('manualSupportRows').querySelectorAll('[data-manual]')].map(row=>{let m={id:row.dataset.manual};for(const el of row.querySelectorAll('[data-key]'))m[el.dataset.key]=el.type==='checkbox'?el.checked:Number(el.value)*(el.dataset.key==='y'?-1:1);return m;});if(changeProject(p=>Object.assign(p.integration,{supportMode:v.supportMode,boreDepth:v.boreDepth,nutPockets:v.nutPockets,manualSupports:list})))closeModal();});
 $('addManualSupport').onclick=()=>{changeProject(p=>p.integration.manualSupports.push({id:M.uid('manual'),x:assembly.board.width/2,y:-assembly.board.height/2,diameter:6,bore:2.6,enabled:true}));supportOptions();};$('manualSupportRows').onclick=e=>{let b=e.target.closest('[data-remove-manual]');if(b)b.closest('[data-manual]').remove();};
}
window.CBEmbedded={
 adaptPCB:raw=>embeddedHost.adaptPCB(raw),
 load(next,host){embeddedHost=host;project=null;caseResult=null;resultKey='';savePaused=false;clearNotice();installProject(M.validate(next));activeTab='case';$('workspace').classList.add('hide-right');project.view.theme=host.theme||'light';project.view.mode=host.mode||'easy';project.generated=true;renderAll(true);saveNow();generateCase(true);},
 saveStatus(text){let ok=text.includes('Saved'),fail=/failed|paused|conflict/i.test(text);setSave(ok?'saved':fail?'error':'saving',ok?'Saved with PCB project':fail?text:'Saving PCB project…');},
 flush(){saveNow();return !saveFailed;},get:()=>project?C.clone(project):null,
 dispose(){clearTimeout(saveTimer);stopWorker(false);embeddedHost=null;},
 edit(fn){return changeProject(fn);},select:selectObject,tab:setTab,
 exportBackup(){download('enclosure-backup.json',JSON.stringify({app:'CIRCUITBENCH_ENCLOSURE',schema:1,enclosure:project},null,2));}
};
$('openBtn').textContent='← PCB';$('openBtn').title='Save enclosure and return to PCB';$('openBtn').onclick=()=>{if(window.CBEmbedded.flush())embeddedHost?.close();};
$('examplesBtn').hidden=true;$('welcomeOpen').hidden=true;
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='o'){e.preventDefault();e.stopImmediatePropagation();if(window.CBEmbedded.flush())embeddedHost?.openProject();}},true);
window.addEventListener('beforeunload',()=>window.CBEmbedded.flush());

showHelp=function(){modal('Enclosure workbench · CIRCUITBENCH',`<p><strong>Review PCB → Enclose → Customize → Check + print.</strong> The primary PCB comes from CIRCUITBENCH. Returning to the PCB saves enclosure edits; reopening updates its mechanical source and keeps feature links by stable component ID.</p><h3>Enclose</h3><p>Choose the shell family and closure, then Apply enclosure system. Set clearances, wall/floor/lid, PCB lift and joint fit in the same panel. Hardware + board retention contains screw/insert dimensions, rails, cradles and hold-down bars. Mounting chooses real hole intent; Standoff bores + manual supports selects blind, through or solid posts.</p><h3>Customize</h3><p>Features adds openings, pockets, text, SVG artwork, vents, ribs and service panels. Edit a face to drag/resize, or use the inspector for exact coordinates, rotation, edge distances and persistent component anchors. Access creates connector, LED, display and button assemblies with editable measured dimensions.</p><h3>Check + print</h3><p>Review findings, then export separate STL, named-part 3MF or the complete print ZIP. Print also provides full-scale fit frames, feature/closure/hardware coupons, orientations, printer profiles and local fit corrections. Recorded physical evidence becomes stale after geometry or process changes.</p><h3>Advanced mode</h3><p>Assembly adds up to three additional parallel PCBs and device envelopes. Library stores recipes, hardware and reusable feature/interface definitions. All modes share the same enclosure. Use Undo/Redo to reverse edits.</p><h3>Closures</h3><p>Sliding, snap-fit and separate-pin hinges require a level rounded rectangular shell. They contain real grooves, beams/hooks or knuckles and a separate pin; their fit, force and wear have not been physically tested. Print the matching closure coupon first.</p><h3>Save and recovery</h3><p>Save project JSON downloads the complete CIRCUITBENCH design. Enclosure changes use the parent project's autosave, recovery and conflict handling. The original v1.3 enclosure settings remain a backup after migration. SVG scripts/links are rejected. Processing and geometry workers are local; no network service is needed.</p><h3>Controls</h3><p>Drag to orbit, Shift/right-drag to pan, wheel to zoom. Feature dragging has numeric alternatives. Ctrl/Command Z undoes enclosure edits; Ctrl/Command S saves the complete PCB project. Use the PCB button to return.</p><p>Adapted from CASEBENCH 2.3.1, with its MIT notice retained. CIRCUITBENCH is GPL-3.0-only. Manifold 3.5.4 performs solid operations; parts must pass mesh and export checks. Dimensioned body envelopes are not external STEP models.</p>`,[{label:'Export enclosure backup',action:()=>window.CBEmbedded.exportBackup()},{label:'Close',primary:true,action:closeModal}]);};

// Rebind controls after installing the embedded lifecycle.
$('helpBtn').onclick=()=>showHelp();$('freshBtn').onclick=()=>freshStart();$('exportBtn').onclick=()=>saveProject();
$('exportBtn').textContent='Save PCB + enclosure';
$('recoverBtn').onclick=()=>saveNow();
const packageEnclosure=X.packageFiles;X.packageFiles=function(result,design,report){const pack=packageEnclosure(result,design,report);if(embeddedHost&&design){delete pack.files['project.casebench.json'];pack.files['project.circuitbench.json']=embeddedHost.projectJSON(design);}pack.zip=X.zip(pack.files);return pack;};

const hostDrawer=renderDrawer;renderDrawer=function(){hostDrawer();if(!project)return;if(activeTab==='source'){const update=$('updateRevisionBtn');if(update)update.remove();const link=$('mechanicalHandoffBtn');if(link)link.onclick=()=>download(filename(project.title)+'-mechanical.json',project.source.text);}if(activeTab==='mounts'&&!$('supportOptions')){const button=document.createElement('button');button.id='supportOptions';button.className='full';button.textContent='Standoff bores + manual supports';button.onclick=supportOptions;$('drawerContent').prepend(button);}};
readFile=async function(){setError('Return to the PCB to open a complete CIRCUITBENCH project. Use Assembly for an additional PCB, or Library for a recipe.');};

persistPrefs=function(){embeddedHost?.preferences({theme:document.documentElement.dataset.theme,mode:document.documentElement.dataset.mode});};

const mountRecoveryDrawer=renderDrawer;renderDrawer=function(){mountRecoveryDrawer();if(!project||activeTab!=='mounts')return;const ids=new Set(assembly.bores.map(h=>h.id)),missing=Object.entries(project.supports).filter(([id,s])=>s.enabled!==false&&!ids.has(id));if(!missing.length)return;const box=document.createElement('section');box.className='callout warn';box.innerHTML='<strong>Missing support anchors</strong><p>These PCB holes were removed. Disable each old support, then explicitly enable a replacement hole if needed.</p>'+missing.map(([id])=>`<button class="full" data-disable-support="${esc(id)}">Disable missing ${esc(id)}</button>`).join('');box.querySelectorAll('[data-disable-support]').forEach(b=>b.onclick=()=>changeProject(p=>p.supports[b.dataset.disableSupport].enabled=false));$('drawerContent').prepend(box);};

const sizedValidation=M.validate;M.validate=function(value){const q=sizedValidation(value);embeddedHost?.checkSize(q);return q;};
