/* STL / 3MF / ZIP output and independent serialized-file readers.
 * Print files contain only named enclosure/accessory solids, never PCB references.
 */
(function(root,factory){let node=typeof module==='object'&&module.exports,a=factory(node?require('./solid.js'):root.CaseSolid,node?require('./archive.js'):root.CaseArchive);if(node)module.exports=a;else root.CaseExport=a;})(globalThis,function(S,A){'use strict';
const encode=s=>new TextEncoder().encode(s),decode=b=>new TextDecoder().decode(b),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function bytes(v){return typeof v==='string'?encode(v):v instanceof Uint8Array?v:new Uint8Array(v);}
function zip(entries){const files=Object.entries(entries).map(([name,data])=>{if(name.includes('..')||name.startsWith('/'))throw Error('Unsafe output path.');return{name:encode(name),data:bytes(data)};});let size=22;for(const f of files)size+=30+f.name.length+f.data.length+46+f.name.length;if(size>128*1024*1024)throw Error('Print package exceeds 128 MiB. Reduce geometry complexity.');const out=new Uint8Array(size),v=new DataView(out.buffer);let pos=0;const u16=(p,x)=>v.setUint16(p,x,true),u32=(p,x)=>v.setUint32(p,x,true);for(const f of files){f.offset=pos;f.crc=A.crc32(f.data);u32(pos,0x04034b50);u16(pos+4,20);u16(pos+6,0x800);u16(pos+12,33);u32(pos+14,f.crc);u32(pos+18,f.data.length);u32(pos+22,f.data.length);u16(pos+26,f.name.length);out.set(f.name,pos+30);out.set(f.data,pos+30+f.name.length);pos+=30+f.name.length+f.data.length;}const start=pos;for(const f of files){u32(pos,0x02014b50);u16(pos+4,20);u16(pos+6,20);u16(pos+8,0x800);u16(pos+14,33);u32(pos+16,f.crc);u32(pos+20,f.data.length);u32(pos+24,f.data.length);u16(pos+28,f.name.length);u32(pos+42,f.offset);out.set(f.name,pos+46);pos+=46+f.name.length;}u32(pos,0x06054b50);u16(pos+8,files.length);u16(pos+10,files.length);u32(pos+12,pos-start);u32(pos+16,start);return out;}
function unzipStored(input){let b=bytes(input),v=new DataView(b.buffer,b.byteOffset,b.byteLength),out={},pos=0;while(pos+30<=b.length&&v.getUint32(pos,true)===0x04034b50){const flags=v.getUint16(pos+6,true),method=v.getUint16(pos+8,true),size=v.getUint32(pos+18,true),n=v.getUint16(pos+26,true),extra=v.getUint16(pos+28,true),start=pos+30+n+extra;if(flags&9||method!==0||start+size>b.length)throw Error('Unsupported or malformed read-back ZIP.');let name=decode(b.slice(pos+30,pos+30+n)),data=b.slice(start,start+size);if(A.crc32(data)!==v.getUint32(pos+14,true))throw Error('Read-back CRC mismatch.');out[name]=data;pos=start+size;}return out;}
function orient(part){let orientation=part.orientation||(part.id==='lid'?'top':'bottom'),mesh=S.transformMesh(part.mesh,v=>orientation==='top'?[v[0],-v[1],-v[2]]:orientation==='front'?[v[0],v[2],-v[1]]:orientation==='back'?[v[0],-v[2],v[1]]:orientation==='left'?[v[2],v[1],-v[0]]:orientation==='right'?[-v[2],v[1],v[0]]:v.slice()),a=S.audit(mesh);return S.transformMesh(mesh,v=>v.map((x,i)=>x-a.bounds.min[i]));}
function layout(parts,bedWidth=220,gap=8){let x=0,y=0,row=0,width=0,height=0,items=[];for(const part of parts){let mesh=orient(part),a=S.audit(mesh);if(x>0&&x+a.size[0]>bedWidth){x=0;y+=row+gap;row=0;}let placed=S.transformMesh(mesh,v=>[v[0]+x,v[1]+y,v[2]]);items.push({...part,mesh:placed,printOffset:[x,y,0],audit:S.audit(placed)});width=Math.max(width,x+a.size[0]);height=Math.max(height,y+a.size[1]);row=Math.max(row,a.size[1]);x+=a.size[0]+gap;}return{parts:items,width,height};}
function threeMF(parts,title='CASEBENCH enclosure',bedWidth=220){const placed=layout(parts,bedWidth),model=`<?xml version="1.0" encoding="UTF-8"?><model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"><metadata name="Title">${esc(title)}</metadata><metadata name="Application">CIRCUITBENCH 1.8.0</metadata><resources>${placed.parts.map((p,i)=>`<object id="${i+1}" type="model" name="${esc(p.name)}"><mesh><vertices>${p.mesh.vertices.map(v=>`<vertex x="${v[0]}" y="${v[1]}" z="${v[2]}"/>`).join('')}</vertices><triangles>${p.mesh.triangles.map(t=>`<triangle v1="${t[0]}" v2="${t[1]}" v3="${t[2]}"/>`).join('')}</triangles></mesh></object>`).join('')}</resources><build>${placed.parts.map((p,i)=>`<item objectid="${i+1}"/>`).join('')}</build></model>`;return zip({'[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>','_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>','3D/3dmodel.model':model});}
function read3MF(data){let files=unzipStored(data),xml=decode(files['3D/3dmodel.model']||[]);if(!xml.includes('unit="millimeter"')||xml.includes('<!DOCTYPE'))throw Error('Unexpected 3MF units or document.');let parts=[];for(const m of xml.matchAll(/<object\b([^>]*)>([\s\S]*?)<\/object>/g)){let attrs=m[1],name=(attrs.match(/name="([^"]*)"/)||[])[1]||'Part',id=(attrs.match(/id="([^"]*)"/)||[])[1];const vertices=[...m[2].matchAll(/<vertex x="([^"]+)" y="([^"]+)" z="([^"]+)"\/>/g)].map(v=>v.slice(1).map(Number)),triangles=[...m[2].matchAll(/<triangle v1="([^"]+)" v2="([^"]+)" v3="([^"]+)"\/>/g)].map(v=>v.slice(1).map(Number));if(!vertices.flat().every(Number.isFinite)||triangles.some(t=>t.some(i=>!Number.isInteger(i)||i<0||i>=vertices.length)))throw Error('Invalid serialized 3MF mesh.');let mesh={vertices,triangles};parts.push({id:name.toLowerCase()==='base'?'base':name.toLowerCase()==='lid'?'lid':'object-'+id,name,mesh,audit:S.audit(mesh)});}if(!parts.length)throw Error('No objects read back from 3MF.');return{parts,units:'mm',serialized:true};}
function csv(rows){const quote=v=>{let x=String(v??'');if(typeof v==='string'&&/^[=+@-]/.test(x))x="'"+x;return'"'+x.replace(/"/g,'""')+'"';};return rows.map(r=>r.map(quote).join(',')).join('\r\n')+'\r\n';}
function hardwareCSV(items){return csv([['Item','Quantity','Nominal bore mm','Nut across-flats mm','Candidate length mm','Review note'],...items.map(i=>[i.item,i.quantity,i.bore||'',i.nutFlats||'',i.suggestedLength||'',i.note])]);}
function packageFiles(result,project,report=''){const files={};for(const p of result.parts){if(!p.audit.valid||p.audit.connectedComponents!==1)throw Error(p.name+' is not a validated single solid.');let m=orient(p),bin=S.stl(m,p.name),read=S.audit(S.readSTL(bin));if(!read.valid)throw Error('STL read-back failed for '+p.name);files[p.id+'.stl']=bin;}let mf=threeMF(result.parts,project?.title||'CASEBENCH',project?.settings?.bedWidth||220),back=read3MF(mf);if(back.parts.some(p=>!p.audit.valid))throw Error('3MF read-back validation failed.');files['enclosure.3mf']=mf;if(project)files['project.casebench.json']=JSON.stringify(project,null,2);if(report)files['review.html']=report;files['hardware.csv']=hardwareCSV(result.hardware||[]);files['README.txt']='CIRCUITBENCH 1.8.0\nAll dimensions are millimetres. STL does not encode units.\nOnly printable solids are included. PCB and clearance references are excluded.\nPart orientations are listed below. Raised lettering or overhangs may require a different orientation or supports.\nThese files do not include printer profiles, supports, slicing or G-code.\nPhysical fit has not been tested. Inspect every part in your slicer and confirm hardware dimensions.\n'+result.parts.map(p=>p.name+': '+(p.orientation||(p.id==='lid'?'top':'bottom'))+' face toward the bed.').join('\n')+'\n'+(result.instructions||'');if(project?.system){
 files['evidence.json']=JSON.stringify({note:'User-recorded trials are not independent certification. Check fingerprints for relevance.',records:project.system.evidence},null,2);
 files['assembly-steps.csv']=csv([['Step','Item','Direction from installed position','Distance mm','Notes'],...project.system.steps.map(s=>[s.name,s.itemId,s.direction,s.distance,s.notes])]);
 files['sources/primary-mechanical.json']=project.source.text;
 for(const b of project.system.boards)files['sources/'+b.id+'.json']=b.source.text;
 files['README.txt']='CIRCUITBENCH 1.8.0\nMillimetres; 3MF units are explicit. STL does not encode units.\n'+result.parts.map(p=>p.name+': '+(p.orientation||(p.id==='lid'?'top':'bottom'))+' face toward the bed.').join('\n')+'\nReference boards, hardware and access volumes are excluded.\nNo slicing, supports or G-code. Inspect exported parts in your slicer. Physical fit is not independently verified.\n'+(result.instructions||'');
 }return{files,zip:zip(files),readback:back};}
return{zip,unzipStored,orient,layout,threeMF,read3MF,csv,hardwareCSV,packageFiles,esc};
});
