/* Parametric enclosure solids. Preview and manufacture use these same meshes.
 * Hardware defaults are review-required nominal conveniences, not specifications.
 */
(function(root,factory){let node=typeof module==='object'&&module.exports;const a=factory(node?require('./solid.js'):root.CaseSolid,node?require('./model.js'):root.CaseModel,node?require('./features.js'):root.CaseFeatures,node?require('./checks.js'):root.CaseChecks);if(node)module.exports=a;else root.CaseGeometry=a;})(globalThis,function(S,M,F,K){'use strict';
const E=.025;
function roundedPrism(x,y,w,d,r,z,h,tag=''){return S.prism(S.rounded(x,y,w,d,r),z,z+h,tag);}
function hex(x,y,z,flats,h){return S.cylinder(x,y,z,flats/Math.sqrt(3),h,6);}
function shell(p,a=M.effective(p),d=M.dimensions(p,a),progress=()=>{}){const s=p.settings,n=s.curveSegments;if(d.innerWidth<=2*(s.fit+s.lipWall)||d.innerDepth<=2*(s.fit+s.lipWall))throw Error('Lid joint leaves no interior opening. Increase the case or reduce the joint.');if(d.height<=s.floor+s.lipDepth+.2)throw Error('Case height is insufficient for its floor and lid joint.');
 progress('Forming the base');let base=roundedPrism(d.minX,d.minY,d.width,d.depth,d.radius,0,d.height,'base').subtract(roundedPrism(d.innerMinX,d.innerMinY,d.innerWidth,d.innerDepth,Math.max(0,d.radius-s.wall),s.floor,d.height+1,'cavity'));
 const mounts=M.mounts(p,a);for(const h of mounts.filter(h=>h.enabled)){if(h.outerDiameter<=h.boreDiameter+.4)throw Error('Support '+h.id+' needs a larger outside diameter.');base=base.union(S.cylinder(h.x,h.y,s.floor-E,h.outerDiameter/2,d.support+E,n,'support:'+h.id));base=base.subtract(S.cylinder(h.x,h.y,-1,h.boreDiameter/2,d.boardZ+2,n));base=base.subtract(hex(h.x,h.y,-1,s.nutFlats,s.nutDepth+1));}
 return{base,mounts};
}
function lidAndClosure(p,a,d,base,progress=()=>{}){let s=p.settings,n=s.curveSegments;progress('Forming the lid and locating skirt');let lid=roundedPrism(d.minX,d.minY,d.width,d.depth,d.radius,d.height,s.roof,'lid');let sx=d.innerMinX+s.fit,sy=d.innerMinY+s.fit,sw=d.innerWidth-2*s.fit,sd=d.innerDepth-2*s.fit,sr=Math.max(0,d.radius-s.wall-s.fit);let skirt=roundedPrism(sx,sy,sw,sd,sr,d.height-s.lipDepth,s.lipDepth+E,'lip').subtract(roundedPrism(sx+s.lipWall,sy+s.lipWall,sw-2*s.lipWall,sd-2*s.lipWall,Math.max(0,sr-s.lipWall),d.height-s.lipDepth-1,s.lipDepth+2));lid=lid.union(skirt);
 const closers=M.closures(p,d);for(const c of closers.filter(c=>c.enabled)){if(c.diameter<=Math.max(c.bore,s.headDiameter)+.4)throw Error('Lid-fastener boss is too small for its holes.');base=base.union(S.cylinder(c.x,c.y,0,c.diameter/2,d.height,n,'closure:'+c.id));base=base.subtract(S.cylinder(c.x,c.y,-1,c.bore/2,d.height+2,n));base=base.subtract(hex(c.x,c.y,-1,s.nutFlats,s.nutDepth+1));lid=lid.union(S.cylinder(c.x,c.y,d.height,c.diameter/2,s.roof,n,'closure:'+c.id));lid=lid.subtract(S.cylinder(c.x,c.y,d.height-s.lipDepth-1,c.bore/2,s.roof+s.lipDepth+2,n));if(s.headDepth>0)lid=lid.subtract(S.cylinder(c.x,c.y,d.top-s.headDepth,s.headDiameter/2,s.headDepth+1,n));}
 return{base,lid,closers};
}
let cache=null;
function build(p,progress=()=>{}){p=M.validate(p);const a=M.effective(p),d=M.dimensions(p,a),key=JSON.stringify([p.settings,d,M.mounts(p,a),M.closures(p,d)]);let x,y;if(cache&&cache.key===key){x=cache.x;y={...cache.y};progress('Reusing unchanged shell');}else{x=shell(p,a,d,progress);y=lidAndClosure(p,a,d,x.base,progress);cache={key,x,y:{...y}};}y={...y,...F.apply({base:y.base,lid:y.lid},p,a,d,progress)};progress('Tessellating base');let parts=[{id:'base',name:'Base',mesh:S.mesh(y.base)}];progress('Tessellating lid');parts.push({id:'lid',name:'Lid',mesh:S.mesh(y.lid)});for(const part of parts)part.audit=S.audit(part.mesh);let findings=y.findings.concat(K.run(p,a,d,{base:y.base,lid:y.lid},parts,y.features,progress));progress('Reading back printable files');for(const part of parts){part.readback=S.audit(S.readSTL(S.stl(part.mesh,part.name)));if(!part.readback.valid)findings.push({id:'stl-'+part.id,severity:'error',code:'stl-readback',message:part.name+' failed STL read-back validation.',objects:[part.id],confidence:'geometric'});}return{version:M.VERSION,dimensions:d,parts,mounts:x.mounts,closers:y.closers,findings,features:y.features,hardware:K.hardware(p,a,d),physicalFit:'untested',kernel:'CASEBENCH bounded BSP',fingerprint:null};}
function coupon(p){const s=p.settings,gaps=[Math.max(.05,s.fit-.15),s.fit,s.fit+.15],n=s.curveSegments;let plate=S.box(0,0,0,58,28,3);for(let i=0;i<3;i++){let w=10+2*gaps[i];plate=plate.subtract(S.box(9+i*20-w/2,12-w/2,-1,w,w,5));}let plug=S.box(0,0,0,14,14,2).union(S.box(2,2,1.98,10,10,6.02));let gauge=S.box(0,0,0,58,14,3),bores=[s.boltDiameter-.3,s.boltDiameter-.15,s.boltDiameter,s.boltDiameter+.15];for(let i=0;i<4;i++)gauge=gauge.subtract(S.cylinder(8+i*14,7,-1,bores[i]/2,5,n));return{version:M.VERSION,parts:[['fit-plate','Fit plate',plate],['fit-plug','Fit plug',plug],['hole-gauge','Hole gauge',gauge]].map(([id,name,solid])=>{let mesh=S.mesh(solid);return{id,name,mesh,audit:S.audit(mesh)};}),gaps,bores,instructions:'Square sockets, left to right: '+gaps.map(g=>g.toFixed(2)+' mm per-side clearance').join(', ')+'. Fit plug is nominal 10 × 10 mm. Hole gauge left to right: '+bores.map(x=>x.toFixed(2)+' mm').join(', ')+'. Print using the intended material and orientation; record the actual fit.'};}

return{build,coupon,shell,lidAndClosure,roundedPrism,hex};
});
if(typeof module==='object'&&module.exports)module.exports=require('./system-geometry.js')(module.exports,require('./solid.js'),require('./model.js'),require('./features.js'),require('./checks.js'));

if(typeof module==='object'&&module.exports)require('./workflow-geometry.js')(module.exports,require('./solid.js'),require('./model.js'),require('./features.js'));
