/* CASEBENCH 1.0 — editable enclosure intent, mechanical overrides, stable links.
 * Geometry is derived. Imported source text is never rewritten by edits.
 * Source X / source Y remain available; mechanical Y is negative source Y.
 */
(function(root,factory){const a=factory(typeof module==='object'&&module.exports?require('./core.js'):root.CaseCore);if(typeof module==='object'&&module.exports)module.exports=a;else root.CaseModel=a;})(globalThis,function(C){'use strict';
const VERSION='1.0.0',SCHEMA=2,clone=C.clone,q=C.q;
const DEFAULTS=Object.freeze({margin:5,wall:2.4,floor:2.4,roof:2.4,radius:5,autoSize:true,innerWidth:80,innerDepth:60,offsetX:0,offsetY:0,autoHeight:true,height:24,autoSupport:true,supportHeight:5,bottomClearance:1.2,topClearance:3,leadAllowance:2,lipDepth:2.5,lipWall:1.4,fit:0.3,supportDiameter:8.4,supportBore:3.2,closure:true,closureDiameter:9.8,boltDiameter:3.4,nutFlats:5.8,nutDepth:2.6,headDiameter:6.4,headDepth:1.0,minFeature:0.8,bedWidth:220,bedDepth:220,layerHeight:.2,printerName:'Uncalibrated FDM profile',curveSegments:24});
const RANGES={margin:[.5,100],wall:[.8,12],floor:[.8,12],roof:[.8,12],radius:[0,80],innerWidth:[5,1000],innerDepth:[5,1000],offsetX:[-500,500],offsetY:[-500,500],height:[5,500],supportHeight:[1,100],bottomClearance:[0,30],topClearance:[.2,100],leadAllowance:[0,50],lipDepth:[0,15],lipWall:[.6,8],fit:[.05,2],supportDiameter:[2,30],supportBore:[0,20],closureDiameter:[5,30],boltDiameter:[1,15],nutFlats:[2,25],nutDepth:[.5,10],headDiameter:[2,25],headDepth:[0,6],minFeature:[.1,5],bedWidth:[20,2000],bedDepth:[20,2000],layerHeight:[.05,1],curveSegments:[16,80]};
const FACES=['lid','front','back','left','right','floor','inside-floor','inside-lid'],KINDS=['cutout','pocket','text-raised','text-recessed','vent','add'];
function uid(prefix='feature'){return prefix+'_'+(typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID().replace(/-/g,'').slice(0,12):Date.now().toString(36)+Math.random().toString(36).slice(2,8));}
function num(v,label,min=-1000,max=1000){if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw Error(label+' must be '+min+'–'+max+'.');return v;}
function str(v,limit=200){return typeof v==='string'?v.slice(0,limit):'';}
function array(v,label,n=100){if(!Array.isArray(v)||v.length>n)throw Error(label+' exceeds its '+n+'-entry limit.');return v;}
function id(v){if(typeof v!=='string'||!v.length||v.length>200||['constructor','prototype','__proto__'].includes(v))throw Error('Invalid stable object ID.');return v;}
function initializeMountSuggestions(p,sourceText,prefix='',existingIds=[]) {
 const previous=new Set(existingIds);
 for(const h of C.normalize(sourceText).bores){const key=prefix+h.id;
  if(h.role==='mounting-candidate'&&(h.ownerId||h.slot>0)&&!previous.has(h.id)&&
     !Object.prototype.hasOwnProperty.call(p.supports,key)&&!Object.prototype.hasOwnProperty.call(p.review.mounting,key))
    p.supports[key]={enabled:false};
 }
 return p;
}
function defaults(sourceText,filename='Copperbench.json',example=false){const p=C.createProject(sourceText,filename,example);p.version=VERSION;p.schema=SCHEMA;p.settings=clone(DEFAULTS);p.overrides={};p.supports={};p.closures={};p.features=[];p.envelopes=[];p.revisions=[];p.calibrations=[];p.generated=false;p.view.scene='board';p.view.showReferences=true;initializeMountSuggestions(p,sourceText);return p;}
function validate(input){const p=typeof input==='string'?C.parse(input):C.parse(JSON.stringify(input));if(p.app!=='CASEBENCH'||![1,SCHEMA].includes(p.schema))throw Error('Unsupported CASEBENCH project schema.');const old=C.validateProject({...p,schema:1}),o=defaults(old.source.text,old.source.filename,old.source.isExample);o.review=old.review;o.view={...old.view,scene:['board','assembled','exploded','transparent','section','print','export'].includes(p.view?.scene)?p.view.scene:'board',showReferences:p.view?.showReferences!==false};o.title=str(p.title,300)||old.title;o.created=old.created;o.updated=old.updated;if(p.schema===1)return o;
 // Preserve pre-2.3.1 implicit support choices in saved enclosure projects.
 o.supports={};
 if(p.settings)for(const [k,v]of Object.entries(p.settings)){if(k in RANGES)o.settings[k]=num(v,k,...RANGES[k]);else if(typeof DEFAULTS[k]==='boolean'){if(typeof v!=='boolean')throw Error(k+' must be boolean.');o.settings[k]=v;}else if(k==='printerName')o.settings[k]=str(v);}
 o.settings.curveSegments=Math.round(o.settings.curveSegments);o.generated=p.generated===true;
 // Orphan review notes and mounting decisions remain attached to their original IDs.
 if(p.review?.objects)for(const [k,v]of Object.entries(p.review.objects)){id(k);o.review.objects[k]=str(v,10000);}if(p.review?.mounting)for(const [k,v]of Object.entries(p.review.mounting)){id(k);if(['candidate','use','exclude'].includes(v))o.review.mounting[k]=v;}

 if(p.overrides)for(const [pid,v]of Object.entries(p.overrides)){id(pid);let r={};for(const k of ['width','depth','height','offsetX','offsetY','lift','leadProjection'])if(v[k]!==undefined&&v[k]!==null)r[k]=num(v[k],k,['offsetX','offsetY'].includes(k)?-500:0,k==='height'?500:2000);r.evidence=['representative','user-entered','datasheet-derived','measured'].includes(v.evidence)?v.evidence:'user-entered';r.notes=str(v.notes,4000);o.overrides[pid]=r;}
 for(const key of ['supports','closures'])if(p[key])for(const [pid,v]of Object.entries(p[key])){id(pid);let r={};if(typeof v.enabled==='boolean')r.enabled=v.enabled;for(const k of ['diameter','bore','x','y'])if(v[k]!==undefined)r[k]=num(v[k],k,['x','y'].includes(k)?-1000:k==='bore'?0:.5,1000);o[key][pid]=r;}
 let ids=new Set();for(const f of array(p.features||[],'Features',160)){let r={id:id(f.id),name:str(f.name)||'Feature',kind:f.kind,face:f.face,shape:f.shape||'rounded',enabled:f.enabled!==false,componentId:f.componentId? id(f.componentId):null};if(ids.has(r.id))throw Error('Duplicate feature ID.');ids.add(r.id);if(!KINDS.includes(r.kind)||!FACES.includes(r.face)||!['rect','rounded','circle','slot'].includes(r.shape))throw Error('Unsupported feature kind, face or shape.');for(const k of ['u','v','rotation'])r[k]=num(f[k]??0,k,-10000,10000);for(const [k,value,min,max]of[['width',12,.2,500],['height',6,.2,500],['depth',1,.05,100],['radius',1,0,100],['size',5,.8,50],['spacing',.25,0,10],['columns',4,1,20],['rows',2,1,20],['pitchU',4,.1,100],['pitchV',4,.1,100]])r[k]=num(f[k]??value,k,min,max);r.columns=Math.round(r.columns);r.rows=Math.round(r.rows);if(r.columns*r.rows>100)throw Error('A vent pattern supports at most 100 openings.');r.text=str(f.text??'LABEL',32);r.through=f.through!==false;r.alignment=['left','center','right'].includes(f.alignment)?f.alignment:'center';o.features.push(r);}
 for(const e of array(p.envelopes||[],'Envelopes',64)){let r={id:id(e.id),name:str(e.name)||'Reserved space',role:['internal','cable','tool'].includes(e.role)?e.role:'internal',componentId:e.componentId?id(e.componentId):null};if(ids.has(r.id))throw Error('Duplicate object ID.');ids.add(r.id);for(const k of ['x','y','z'])r[k]=num(e[k]??0,k);for(const k of ['width','depth','height'])r[k]=num(e[k]??10,k,.1,500);o.envelopes.push(r);}
 o.revisions=array(p.revisions||[],'Revision history',10).map(r=>({date:str(r.date),from:str(r.from),to:str(r.to),changes:array(r.changes||[],'Changes',20000).map(c=>({kind:str(c.kind),group:str(c.group),id:str(c.id)}))}));o.calibrations=array(p.calibrations||[],'Calibrations',20).map(r=>({name:str(r.name),date:str(r.date),fit:num(r.fit,'Fit',.05,2),boltDiameter:num(r.boltDiameter,'Bolt diameter',1,15),note:str(r.note,2000)}));return o;
}
function effective(p){const a=C.normalize(p.source.text),t=a.board.thickness;const resolved=new Set(),through=new Set(a.pads.filter(p=>p.drill>0).map(p=>p.ownerId));a.projections=[];
 for(const c of a.components){const o=p.overrides[c.id]||{};let w=o.width??c.body?.width,d=o.depth??c.body?.depth,h=o.height??c.body?.height,lift=o.lift||0;let status=o.evidence||'representative';if(w>0&&d>0&&h>0){let z0=c.side==='bottom'?-lift-h:t+lift,z1=c.side==='bottom'?-lift:t+lift+h;let verts=[[-w/2,-d/2],[w/2,-d/2],[w/2,d/2],[-w/2,d/2]].map(([x,y])=>C.world(c.sourcePlacement,{x:x+(o.offsetX||0),y:y+(o.offsetY||0)},z0));c.vertices=verts.concat(verts.map(v=>({...v,z:z1})));c.body={...c.body,width:w,depth:d,height:h,zMin:z0,zMax:z1};c.bounds=C.bounds(c.vertices);c.geometryStatus=status!=='representative'&&!['width','depth','height'].every(k=>o[k]>0)?'Partial override · other dimensions representative':status;c.envelopeCenter={x:(c.bounds.minX+c.bounds.maxX)/2,y:(c.bounds.minY+c.bounds.maxY)/2,z:(z0+z1)/2};if(status!=='representative'&&['width','depth','height'].every(k=>o[k]>0))resolved.add(c.id);}
 if(through.has(c.id)){let projection=o.leadProjection??p.settings.leadAllowance,known=o.leadProjection!==undefined;for(const pad of a.pads.filter(p=>p.ownerId===c.id&&p.drill>0)){let r=pad.drill/2+.45,z0=c.side==='top'?-projection:t,z1=c.side==='top'?0:t+projection;a.projections.push({id:pad.id+':projection',ownerId:c.id,known,bounds:{minX:pad.x-r,minY:pad.y-r,minZ:z0,maxX:pad.x+r,maxY:pad.y+r,maxZ:z1}});}c.leadProtrusion=known?projection:null;}}
 a.findings=a.findings.filter(f=>!(f.code==='body-review'&&resolved.has(f.objects[0]))&&!(f.code==='missing-body'&&a.components.find(c=>c.id===f.objects[0])?.body)&&!(f.code==='lead-protrusion'&&p.overrides[f.objects[0]]?.leadProjection!==undefined));
 a.envelopes=p.envelopes.map(e=>{let c=a.components.find(c=>c.id===e.componentId),origin=c?.envelopeCenter||c?.position||{x:0,y:0,z:0};return{...e,unresolved:!!e.componentId&&!c,bounds:{minX:origin.x+e.x-e.width/2,maxX:origin.x+e.x+e.width/2,minY:origin.y-e.y-e.depth/2,maxY:origin.y-e.y+e.depth/2,minZ:origin.z+e.z,maxZ:origin.z+e.z+e.height}};});
 let pts=a.board.outline.flatMap(v=>[{...v,z:0},{...v,z:t}]);for(const c of a.components)pts.push(...c.vertices);for(const pad of a.pads){let angle=pad.rotation*Math.PI/180,w=pad.shape==='circle'?Math.max(pad.width,pad.height):Math.abs(Math.cos(angle))*pad.width+Math.abs(Math.sin(angle))*pad.height,h=pad.shape==='circle'?w:Math.abs(Math.sin(angle))*pad.width+Math.abs(Math.cos(angle))*pad.height;pts.push({x:pad.x-w/2,y:pad.y-h/2,z:0},{x:pad.x+w/2,y:pad.y+h/2,z:t});}for(const e of [...a.projections,...a.envelopes.filter(e=>e.role==='internal'&&!e.unresolved)]){let b=e.bounds;pts.push({x:b.minX,y:b.minY,z:b.minZ},{x:b.maxX,y:b.maxY,z:b.maxZ});}
 a.summary.knownBounds=C.bounds(pts);a.summary.knownSize=C.size(a.summary.knownBounds);a.summary.knownTopBodyHeight=Math.max(0,...a.components.filter(c=>c.body).map(c=>c.body.zMax-t));a.summary.knownBottomBodyHeight=Math.max(0,...a.components.filter(c=>c.body).map(c=>-c.body.zMin));a.summary.unknownBodyCount=a.components.filter(c=>!c.body||!c.body.height).length;a.summary.assumedProjections=a.projections.some(e=>!e.known);a.summary.overriddenComponents=resolved.size;return a;
}
function dimensions(p,a=effective(p)){const s=p.settings,b=a.summary.knownBounds,cx=(b.minX+b.maxX)/2+s.offsetX,cy=(b.minY+b.maxY)/2-s.offsetY,iw=s.autoSize?b.maxX-b.minX+s.margin*2:s.innerWidth,id=s.autoSize?b.maxY-b.minY+s.margin*2:s.innerDepth,support=s.autoSupport?Math.max(2,-b.minZ+s.bottomClearance):s.supportHeight,boardZ=s.floor+support,height=s.autoHeight?Math.max(boardZ+b.maxZ+s.topClearance,s.floor+s.lipDepth+2):s.height;return{cx,cy,innerWidth:iw,innerDepth:id,width:iw+2*s.wall,depth:id+2*s.wall,minX:cx-iw/2-s.wall,maxX:cx+iw/2+s.wall,minY:cy-id/2-s.wall,maxY:cy+id/2+s.wall,innerMinX:cx-iw/2,innerMaxX:cx+iw/2,innerMinY:cy-id/2,innerMaxY:cy+id/2,support,boardZ,height,top:height+s.roof,radius:Math.min(s.radius,(iw+2*s.wall)/2,(id+2*s.wall)/2)};}
function mounts(p,a=effective(p)){return a.bores.filter(h=>h.role==='mounting-candidate').map(h=>({...h,enabled:p.supports[h.id]?.enabled??p.review.mounting[h.id]!=='exclude',confirmed:p.review.mounting[h.id]==='use',outerDiameter:p.supports[h.id]?.diameter??p.settings.supportDiameter,boreDiameter:p.supports[h.id]?.bore??p.settings.supportBore}));}
function closures(p,d=dimensions(p)){const s=p.settings;return[[-1,-1],[-1,1],[1,-1],[1,1]].map(([x,y],i)=>{let id='closure-'+i,o=p.closures[id]||{};return{id,x:o.x??(x<0?d.minX-3.2:d.maxX+3.2),y:o.y??(y<0?d.innerMinY+5:d.innerMaxY-5),enabled:s.closure&&o.enabled!==false,diameter:o.diameter??s.closureDiameter,bore:o.bore??s.boltDiameter};});}
function frame(face,d,s){switch(face){case'lid':return{origin:[d.cx,d.cy,d.top],u:[1,0,0],v:[0,1,0],n:[0,0,1],width:d.width,height:d.depth,thickness:s.roof,part:'lid'};case'inside-lid':return{origin:[d.cx,d.cy,d.height],u:[1,0,0],v:[0,-1,0],n:[0,0,-1],width:d.innerWidth,height:d.innerDepth,thickness:s.roof,part:'lid'};case'floor':return{origin:[d.cx,d.cy,0],u:[1,0,0],v:[0,-1,0],n:[0,0,-1],width:d.width,height:d.depth,thickness:s.floor,part:'base'};case'inside-floor':return{origin:[d.cx,d.cy,s.floor],u:[1,0,0],v:[0,1,0],n:[0,0,1],width:d.innerWidth,height:d.innerDepth,thickness:s.floor,part:'base'};case'front':return{origin:[d.cx,d.minY,d.height/2],u:[1,0,0],v:[0,0,1],n:[0,-1,0],width:d.width,height:d.height,thickness:s.wall,part:'base'};case'back':return{origin:[d.cx,d.maxY,d.height/2],u:[-1,0,0],v:[0,0,1],n:[0,1,0],width:d.width,height:d.height,thickness:s.wall,part:'base'};case'left':return{origin:[d.minX,d.cy,d.height/2],u:[0,-1,0],v:[0,0,1],n:[-1,0,0],width:d.depth,height:d.height,thickness:s.wall,part:'base'};case'right':return{origin:[d.maxX,d.cy,d.height/2],u:[0,1,0],v:[0,0,1],n:[1,0,0],width:d.depth,height:d.height,thickness:s.wall,part:'base'};default:throw Error('Unknown face.');}}
function toWorld(fr,p){return fr.origin.map((x,i)=>x+fr.u[i]*p[0]+fr.v[i]*p[1]+fr.n[i]*p[2]);}
function project(fr,p){let v=p.map((x,i)=>x-fr.origin[i]);return[v.reduce((s,x,i)=>s+x*fr.u[i],0),v.reduce((s,x,i)=>s+x*fr.v[i],0),v.reduce((s,x,i)=>s+x*fr.n[i],0)];}
function resolvedFeature(f,p,a=effective(p),d=dimensions(p,a)){let fr=frame(f.face,d,p.settings),u=f.u,v=f.v,unresolved=false;if(f.componentId){let c=a.components.find(c=>c.id===f.componentId);if(!c)unresolved=true;else{let pt=c.envelopeCenter||c.position;let uv=project(fr,[pt.x,pt.y,pt.z+d.boardZ]);u+=uv[0];v+=uv[1];}}return{...f,u,v,frame:fr,unresolved};}
function feature(kind='cutout',face='lid',componentId=null){return{id:uid(),name:kind==='text-raised'?'Raised label':kind==='text-recessed'?'Recessed label':kind==='vent'?'Vent pattern':kind==='add'?'Material pad':kind==='pocket'?'Pocket':'Access opening',kind,face,shape:'rounded',enabled:true,componentId,u:0,v:0,rotation:0,width:kind==='vent'?2:12,height:kind==='vent'?8:6,depth:kind.includes('text')?.6:kind==='add'?2:1,radius:1,text:'LABEL',size:5,spacing:.25,alignment:'center',through:kind!=='pocket',columns:4,rows:1,pitchU:5,pitchV:12};}
function revisionPreview(p,sourceText){const old=C.normalize(p.source.text),next=C.normalize(sourceText),changes=C.compare(next,old),ids=new Set(next.components.map(c=>c.id)),holes=new Set(next.bores.map(h=>h.id));return{changes,old,next,missingLinks:p.features.filter(f=>f.componentId&&!ids.has(f.componentId)).map(f=>f.id),orphanOverrides:Object.keys(p.overrides).filter(id=>!ids.has(id)),orphanMounts:Object.keys(p.supports).filter(id=>!holes.has(id)),differentBoard:!!old.source.id&&old.source.id!==next.source.id};}
function applyRevision(p,sourceText,filename){const preview=revisionPreview(p,sourceText),o=clone(p);o.review.baseline={sourceText:p.source.text,date:new Date().toISOString()};o.revisions.push({date:new Date().toISOString(),from:p.source.fingerprint.value,to:C.fingerprint(sourceText),changes:preview.changes});o.revisions=o.revisions.slice(-10);o.source={filename,text:sourceText,fingerprint:{algorithm:'FNV-1a-32 UTF-16 (change hint)',value:C.fingerprint(sourceText)},isExample:false};o.updated=new Date().toISOString();return validate(o);}
return{initializeMountSuggestions,VERSION,SCHEMA,DEFAULTS,RANGES,FACES,KINDS,uid,defaults,validate,effective,dimensions,mounts,closures,frame,toWorld,project,resolvedFeature,feature,revisionPreview,applyRevision};
});
// Node and browser load exactly the same versioned system extension.
if(typeof module==='object'&&module.exports)require('./system.js')(module.exports,require('./core.js'));

if(typeof module==='object'&&module.exports)require('./workflow.js')(module.exports,require('./core.js'));

if(typeof module==='object'&&module.exports)require('./integration-model.js')(module.exports,require('./core.js'));
