/* CASEBENCH v2 — versioned assembly intent, evidence and reusable recipes.
 * No imported PCB is rewritten. Geometry is derived; library data is user-reviewed.
 */
(function(root,factory){
  if(typeof module==='object'&&module.exports) module.exports=factory;
  else root.CaseSystem=factory(root.CaseModel,root.CaseCore);
})(globalThis,function(M,C){
'use strict';
if(M.VERSION==='2.3.1')return M;
const old={...M},clone=C.clone;
const families=['rounded','circle','oval','polygon','board-following','tray','sloped'];
const closureTypes=['external','internal','insert','sliding','snap','hinge','none'];
const orientations=['bottom','top','front','back','left','right'];
const hwDefault={name:'User-review M3-like hardware',shaft:3,length:20,headDiameter:6.4,headHeight:3,washerDiameter:7,washerThickness:.5,nutFlats:5.8,nutHeight:2.6,insertDiameter:4.6,insertLength:5,accessDiameter:8,accessLength:20,evidence:'nominal',source:''};
function defaultsSystem(){return{schema:1,shell:{family:'rounded',points:[[-45,-30],[35,-30],[45,-20],[45,30],[-45,30]],slope:8},closure:{type:'external',rail:2,engagement:1.2,flex:1.2,pin:2.5,knuckle:8},hardware:clone(hwDefault),process:{material:'Not specified',nozzle:.4,settingsNote:''},retention:{type:'standoffs',axis:'x',width:3,overlap:1,clearance:.3,barHeight:2},boards:[],objects:[],steps:[],evidence:[],library:{hardware:[],envelopes:[],groups:[]},orientations:{base:'bottom',lid:'top'},recipe:null};}
function finite(v,label,lo=-1000,hi=1000){if(typeof v!=='number'||!Number.isFinite(v)||v<lo||v>hi)throw Error(label+' must be between '+lo+' and '+hi+'.');return v;}
function text(v,label,max=300){if(typeof v!=='string'||v.length>max)throw Error(label+' must be text of at most '+max+' characters.');return v;}
function key(v){text(v,'Object ID',200);if(!v||['__proto__','constructor','prototype'].includes(v))throw Error('Unsafe or empty object ID.');return v;}
function list(v,label,n=64){if(!Array.isArray(v)||v.length>n)throw Error(label+' must contain at most '+n+' entries.');return v;}
function choice(v,options,label){if(!options.includes(v))throw Error('Unsupported '+label+': '+v);return v;}
function polygon(points,label,max=256){return list(points,label,max).map(p=>{if(!Array.isArray(p)||p.length!==2)throw Error(label+' needs [x,y] pairs.');return p.map(v=>finite(v,label,-2000,2000));});}
function source(v){if(!v||typeof v.text!=='string')throw Error('A board requires an embedded Copperbench source.');C.normalize(v.text);return{filename:text(v.filename||'board.json','Filename'),text:v.text,fingerprint:{algorithm:'FNV-1a-32 UTF-16 (change hint)',value:C.fingerprint(v.text)},isExample:false};}
function hardware(v){const h={...hwDefault,...v};text(h.name,'Hardware name');for(const k of ['shaft','length','headDiameter','headHeight','washerDiameter','washerThickness','nutFlats','nutHeight','insertDiameter','insertLength','accessDiameter','accessLength'])finite(h[k],k,k==='washerThickness'?0:.1,200);h.evidence=choice(h.evidence,['nominal','user-entered','datasheet-derived','measured'],'hardware evidence');h.source=text(h.source||'','Hardware source',4000);return h;}
function validate(input){
 const raw=typeof input==='string'?C.parse(input):C.parse(JSON.stringify(input));
 if(![1,2,3].includes(raw.schema)||raw.app!=='CASEBENCH')throw Error('Unsupported CASEBENCH project schema.');
 // v1 core validates source and old fields. v2 artwork uses a validated additive
 // carrier for that pass, then restores the explicitly checked new operation.
 const legacy=clone(raw);legacy.schema=raw.schema===1?1:2;
 for(const f of legacy.features||[])if(f.kind==='art-raised'||f.kind==='art-recessed'||f.kind==='panel')f.kind='add';
 const p=old.validate(legacy);p.schema=3;p.version='2.3.1';
 const s={...defaultsSystem(),...(raw.system||{})};if(s.schema!==1)throw Error('Unsupported enclosure-system schema.');
 s.shell={...defaultsSystem().shell,...s.shell};choice(s.shell.family,families,'shell family');s.shell.points=polygon(s.shell.points,'Shell polygon',64);finite(s.shell.slope,'Roof slope',0,20);
 s.closure={...defaultsSystem().closure,...s.closure};choice(s.closure.type,closureTypes,'closure');for(const k of ['rail','engagement','flex','pin','knuckle'])finite(s.closure[k],k,.2,25);
 s.hardware=hardware(s.hardware);s.process={...defaultsSystem().process,...s.process};s.process.material=text(s.process.material,'Material',160);s.process.nozzle=finite(s.process.nozzle,'Nozzle diameter',.1,3);s.process.settingsNote=text(s.process.settingsNote||'','Process settings',4000);s.retention={...defaultsSystem().retention,...s.retention};choice(s.retention.type,['standoffs','rails','cradle','hold-down','manual'],'board retention');choice(s.retention.axis,['x','y'],'rail axis');for(const k of ['width','overlap','clearance','barHeight'])finite(s.retention[k],k,.05,20);
 const seen=new Set();s.boards=list(s.boards,'Additional boards',3).map(b=>{key(b.id);if(seen.has(b.id))throw Error('Duplicate board instance.');seen.add(b.id);const o={id:b.id,name:text(b.name||'Additional board','Board name'),source:source(b.source),enabled:b.enabled!==false,supports:b.supports!==false};if(b.baseline)o.baseline={...source(b.baseline),date:text(b.baseline.date||'','Board baseline date')};for(const k of ['x','y','z','rotation'])o[k]=finite(b[k]??0,'Board '+k,k==='z'?-200:-1000,k==='rotation'?360:1000);return o;});
 s.objects=list(s.objects,'Assembly objects',24).map(o=>{key(o.id);if(seen.has(o.id))throw Error('Duplicate assembly object ID.');seen.add(o.id);const r={id:o.id,name:text(o.name||'Device part','Object name'),type:choice(o.type||'module',['module','battery','display','switch'],'object type'),mount:choice(o.mount||'none',['none','pad','cradle'],'object mounting'),enabled:o.enabled!==false,evidence:choice(o.evidence||'representative',['representative','user-entered','datasheet-derived','measured'],'object evidence'),notes:text(o.notes||'','Object notes',4000)};for(const k of ['x','y','z','rotation'])r[k]=finite(o[k]??0,k,-1000,1000);for(const k of ['width','depth','height'])r[k]=finite(o[k]??10,k,.1,500);return r;});
 s.steps=list(s.steps,'Assembly steps',32).map(st=>{key(st.id);return{id:st.id,name:text(st.name||'Assembly step','Step name'),itemId:text(st.itemId||'primary','Step item',200),direction:choice(st.direction||'z+',['x+','x-','y+','y-','z+','z-'],'insertion direction'),distance:finite(st.distance??80,'Insertion distance',1,500),notes:text(st.notes||'','Step notes',2000)};});
 s.evidence=list(s.evidence,'Verification records',50).map(e=>({id:key(e.id),kind:choice(e.kind,['slicer','fit'],'evidence kind'),date:text(e.date||'','Evidence date'),fingerprint:text(e.fingerprint||'','Evidence fingerprint'),name:text(e.name||'','Trial setup'),result:choice(e.result,['pass','fail','observed'],'evidence result'),notes:text(e.notes||'','Evidence notes',4000)}));
 s.orientations={...defaultsSystem().orientations,...s.orientations};for(const [k,v]of Object.entries(s.orientations)){key(k);choice(v,orientations,'print orientation');}
 const lib={...defaultsSystem().library,...s.library};lib.hardware=list(lib.hardware,'Hardware library',20).map(hardware);lib.envelopes=list(lib.envelopes,'Envelope library',40).map(e=>{let r={name:text(e.name,'Envelope name'),notes:text(e.notes||'','Envelope notes',4000),evidence:choice(e.evidence||'user-entered',['representative','user-entered','datasheet-derived','measured'],'envelope evidence')};for(const k of ['width','depth','height'])r[k]=finite(e[k],k,.05,1000);r.leadProjection=e.leadProjection==null?null:finite(e.leadProjection,'Lead projection',0,100);return r;});
 lib.groups=list(lib.groups,'Feature library',20).map(g=>({name:text(g.name,'Group name'),features:list(g.features,'Group features',32).map(f=>clone(f))}));s.library=lib;
 s.recipe=s.recipe?{name:text(s.recipe.name||'Recipe','Recipe name'),sourceFingerprint:text(s.recipe.sourceFingerprint||'','Recipe origin'),applied:text(s.recipe.applied||'','Recipe applied date')}:null;
 p.features.forEach((f,i)=>{const orig=raw.features[i];if(orig.kind==='panel')f.kind='panel';if(['art-raised','art-recessed'].includes(orig.kind)){f.kind=orig.kind;f.contours=list(orig.contours,'Artwork contours',40).map(c=>polygon(c,'Artwork contour',256));if(!f.contours.length||f.contours.some(c=>c.length<3))throw Error('Artwork needs closed contours.');f.artRule=choice(orig.artRule||'evenodd',['evenodd','union','nonzero'],'artwork fill');if(orig.artGroups)f.artGroups=list(orig.artGroups,'SVG shapes',24).map(g=>({rule:choice(g.rule,['evenodd','union','nonzero'],'SVG fill rule'),contours:list(g.contours,'SVG contours',40).map(c=>polygon(c,'SVG contour',256))}));}
 f.target=choice(orig.target||'auto',['auto','base','lid','both'],'operation target');if(f.target==='both'&&['add','text-raised','art-raised'].includes(f.kind))throw Error('Additive features must target one part.');f.positioning=choice(orig.positioning||'center',['center','edges'],'feature positioning');f.edgeX=choice(orig.edgeX||'left',['left','right','center'],'horizontal edge');f.edgeY=choice(orig.edgeY||'bottom',['bottom','top','center'],'vertical edge');f.edgeU=finite(orig.edgeU??5,'Edge distance U',-500,500);f.edgeV=finite(orig.edgeV??5,'Edge distance V',-500,500);f.groupId=orig.groupId?key(orig.groupId):null;
 });
 if(s.shell.family==='board-following'&&(!p.settings.autoSize||p.settings.offsetX||p.settings.offsetY))throw Error('Board-following requires automatic sizing and zero enclosure offsets. Use a polygon or rounded shell for fixed or shifted walls.');p.system=s;return p;
}
function defaults(t,n,e){const p=old.defaults(t,n,e);p.version='2.3.1';p.schema=3;p.system=defaultsSystem();return p;}
function planEnvelopePoints(a){const points=[...a.boards.flatMap(b=>b.board.outline),...a.components.flatMap(c=>c.vertices),...a.devices.flatMap(o=>o.vertices)];for(const e of [...a.projections,...a.envelopes.filter(e=>e.role==='internal'&&!e.unresolved)]){const b=e.bounds;points.push({x:b.minX,y:b.minY},{x:b.maxX,y:b.minY},{x:b.maxX,y:b.maxY},{x:b.minX,y:b.maxY});}for(const p of a.pads){let r=Math.max(p.width,p.height)/2;points.push({x:p.x-r,y:p.y-r},{x:p.x+r,y:p.y+r});}return points;}
const rotate=(x,y,deg)=>{let a=deg*Math.PI/180;return[x*Math.cos(a)-y*Math.sin(a),x*Math.sin(a)+y*Math.cos(a)];};
function effective(p){
 const a=old.effective(p);a.boards=[{id:'primary',name:a.title||p.title,board:clone(a.board),cutouts:clone(a.cutouts),bores:clone(a.bores),z:0,source:p.source,supports:true}];
 a.components.forEach(c=>c.boardId='primary');a.bores.forEach(h=>h.boardId='primary');a.pads.forEach(h=>{h.boardId='primary';h.boardZ=0;h.boardThickness=a.board.thickness;});
 for(const b of p.system?.boards||[]){if(!b.enabled)continue;
  const child=old.defaults(b.source.text,b.source.filename),norm=C.normalize(b.source.text),cb=norm.board.bounds,cx=(cb.minX+cb.maxX)/2,cy=(cb.minY+cb.maxY)/2,ab=a.board.bounds,tx=(ab.minX+ab.maxX)/2+b.x,ty=(ab.minY+ab.maxY)/2-b.y;
  child.settings={...p.settings};child.overrides={};for(const [id,o]of Object.entries(p.overrides))if(id.startsWith(b.id+'::'))child.overrides[id.slice(b.id.length+2)]=o;
  const ca=old.effective(child),prefix=id=>b.id+'::'+id,pt=v=>{let q=rotate(v.x-cx,v.y-cy,b.rotation);return{...v,x:q[0]+tx,y:q[1]+ty,z:(v.z||0)+b.z};},bounds=points=>C.bounds(points),moveBounds=bb=>bounds([0,1].flatMap(i=>[0,1].flatMap(j=>[0,1].map(k=>pt({x:i?bb.maxX:bb.minX,y:j?bb.maxY:bb.minY,z:k?bb.maxZ:bb.minZ})))));
  const board={...ca.board,outline:ca.board.outline.map(pt),bounds:moveBounds({...ca.board.bounds,minZ:0,maxZ:ca.board.thickness}),z:b.z};
  const bores=ca.bores.map(h=>({...h,...pt(h),id:prefix(h.id),ownerId:h.ownerId?prefix(h.ownerId):null,boardId:b.id,boardZ:b.z,supports:b.supports,perimeter:h.perimeter.map(pt),rotation:h.rotation+b.rotation}));
  const cuts=ca.cutouts.map(c=>({...c,id:prefix(c.id),boardId:b.id,points:c.points.map(pt)}));
  a.boards.push({id:b.id,name:b.name,board,bores,cutouts:cuts,z:b.z,source:b.source,supports:b.supports});
  for(const c of ca.components){const vertices=c.vertices.map(pt),pos=pt(c.position);a.components.push({...c,id:prefix(c.id),originalId:c.id,boardId:b.id,ref:b.name+'/'+c.ref,vertices,position:pos,bounds:vertices.length?bounds(vertices):{...moveBounds(c.bounds)},envelopeCenter:c.envelopeCenter?pt(c.envelopeCenter):pos,body:c.body?{...c.body,zMin:c.body.zMin+b.z,zMax:c.body.zMax+b.z}:null});}
  a.pads.push(...ca.pads.map(h=>({...h,...pt(h),id:prefix(h.id),ownerId:prefix(h.ownerId),boardId:b.id,boardZ:b.z,boardThickness:ca.board.thickness,rotation:h.rotation+b.rotation})));
  a.projections.push(...ca.projections.map(h=>({...h,id:prefix(h.id),ownerId:prefix(h.ownerId),bounds:moveBounds(h.bounds)})));
  a.bores.push(...bores);a.findings.push(...ca.findings.map(f=>({...f,id:prefix(f.id),objects:f.objects.map(id=>id==='board'?b.id:prefix(id)),message:b.name+': '+f.message})));
 }
 // Re-resolve every access envelope after all boards exist.
 a.envelopes=p.envelopes.map(e=>{const c=a.components.find(c=>c.id===e.componentId),o=c?.envelopeCenter||c?.position||{x:0,y:0,z:0};return{...e,unresolved:!!e.componentId&&!c,bounds:{minX:o.x+e.x-e.width/2,maxX:o.x+e.x+e.width/2,minY:o.y-e.y-e.depth/2,maxY:o.y-e.y+e.depth/2,minZ:o.z+e.z,maxZ:o.z+e.z+e.height}};});
 const bb=a.board.bounds,cx=(bb.minX+bb.maxX)/2,cy=(bb.minY+bb.maxY)/2;
 a.devices=(p.system?.objects||[]).filter(o=>o.enabled).map(o=>{const vertices=[[-1,-1],[1,-1],[1,1],[-1,1]].flatMap(([sx,sy])=>{let v=rotate(sx*o.width/2,sy*o.depth/2,o.rotation);return[{x:cx+o.x+v[0],y:cy-o.y+v[1],z:o.z},{x:cx+o.x+v[0],y:cy-o.y+v[1],z:o.z+o.height}];});return{...o,vertices,bounds:C.bounds(vertices)};});
 const points=[];for(const b of a.boards)points.push(...b.board.outline.flatMap(v=>[{...v,z:b.z},{...v,z:b.z+b.board.thickness}]));for(const c of a.components)points.push(...c.vertices);for(const x of [...a.projections,...a.devices,...a.envelopes.filter(e=>e.role==='internal'&&!e.unresolved)])points.push({x:x.bounds.minX,y:x.bounds.minY,z:x.bounds.minZ},{x:x.bounds.maxX,y:x.bounds.maxY,z:x.bounds.maxZ});
 for(const h of a.pads){let w=Math.max(h.width,h.height)/2;points.push({x:h.x-w,y:h.y-w,z:h.z||0},{x:h.x+w,y:h.y+w,z:h.z||0});}
 a.summary.knownBounds=C.bounds(points);a.summary.knownSize=C.size(a.summary.knownBounds);a.summary.components=a.components.length;a.summary.mountingCandidates=a.bores.filter(h=>h.role==='mounting-candidate').length;a.summary.boardCount=a.boards.length;a.summary.physicalBores=a.bores.length;a.summary.platedBores=a.bores.filter(h=>h.plated).length;a.summary.slottedBores=a.bores.filter(h=>h.slot>0).length;a.summary.linkedMountingCandidates=a.bores.filter(h=>h.role==='mounting-candidate'&&h.ownerId).length;a.summary.standaloneMountingCandidates=a.bores.filter(h=>h.role==='mounting-candidate'&&!h.ownerId).length;a.summary.pinDrills=a.bores.filter(h=>h.role==='pin-drill').length;a.summary.vias=a.bores.filter(h=>h.role==='via').length;a.summary.cutouts=a.boards.reduce((n,b)=>n+b.cutouts.length,0);a.summary.topComponents=a.components.filter(c=>c.side==='top').length;a.summary.bottomComponents=a.components.filter(c=>c.side==='bottom').length;
 a.summary.knownTopBodyHeight=Math.max(0,...a.components.filter(c=>c.body).map(c=>c.body.zMax-a.board.thickness));a.summary.knownBottomBodyHeight=Math.max(0,...a.components.filter(c=>c.body).map(c=>-c.body.zMin));return a;
}
function dimensions(p,a=effective(p)){
 let s=p.settings,f=p.system?.shell?.family||'rounded';if(s.autoSize&&['internal','insert'].includes(p.system?.closure.type))s={...s,margin:Math.max(s.margin,s.closureDiameter+1)};if(s.autoSize&&p.system?.retention.type==='hold-down')s={...s,margin:Math.max(s.margin,8)};let d=old.dimensions({...p,settings:s},a);
 if(s.autoSize&&['circle','oval'].includes(f)){let b=a.summary.knownBounds,w=(b.maxX-b.minX)/2+s.margin,h=(b.maxY-b.minY)/2+s.margin;if(f==='circle')w=h=Math.hypot(w,h);else{w*=Math.SQRT2;h*=Math.SQRT2;}const q={...p,settings:{...s,autoSize:false,innerWidth:w*2,innerDepth:h*2}};d=old.dimensions(q,a);}
 if(f==='polygon'){const pts=p.system.shell.points;if(pts.length>=3){const xs=pts.map(v=>v[0]),ys=pts.map(v=>v[1]);let w=Math.max(...xs)-Math.min(...xs),h=Math.max(...ys)-Math.min(...ys);d=old.dimensions({...p,settings:{...s,autoSize:false,innerWidth:w,innerDepth:h}},a);}}
 d.family=f;d.slope=f==='sloped'?Math.tan(p.system.shell.slope*Math.PI/180):0;
 if(d.slope&&s.autoHeight)d.height+=d.depth/2*d.slope;
 d.top=d.height+s.roof+d.depth/2*d.slope;d.centerTop=d.height+s.roof;if(p.system?.closure.type==='sliding'){d.lidTop=d.height-s.fit;d.lidBottom=d.lidTop-s.roof;d.top=d.height;d.centerTop=d.lidTop;}return d;
}
function mounts(p,a=effective(p)){let rows=old.mounts(p,a);return rows.map(h=>({...h,enabled:h.enabled&&(h.boardId!=='primary'||['standoffs','hold-down'].includes(p.system?.retention.type||'standoffs'))&&h.supports!==false,z:h.boardZ||0}));}
function attachmentOutline(p,d){const family=p.system.shell.family;if(['circle','oval'].includes(family))return Array.from({length:64},(_,i)=>[d.cx+d.innerWidth/2*Math.cos(i*Math.PI/32),d.cy+d.innerDepth/2*Math.sin(i*Math.PI/32)]);if(family==='polygon'){let points=p.system.shell.points,cx=(Math.min(...points.map(v=>v[0]))+Math.max(...points.map(v=>v[0])))/2,cy=(Math.min(...points.map(v=>v[1]))+Math.max(...points.map(v=>v[1])))/2;return points.map(v=>[v[0]-cx+d.cx,v[1]-cy+d.cy]);}if(family==='board-following'){let a=effective(p),points=planEnvelopePoints(a).map(v=>[v.x,v.y]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]),lo=[],hi=[],cross=(a,b,c)=>(b[0]-a[0])*(c[1]-b[1])-(b[1]-a[1])*(c[0]-b[0]);for(let v of points){while(lo.length>1&&cross(lo.at(-2),lo.at(-1),v)<=0)lo.pop();lo.push(v);}for(let v of points.slice().reverse()){while(hi.length>1&&cross(hi.at(-2),hi.at(-1),v)<=0)hi.pop();hi.push(v);}return lo.slice(0,-1).concat(hi.slice(0,-1));}return null;}
function closures(p,d=dimensions(p)){let type=p.system?.closure.type||'external';if(!['external','internal','insert'].includes(type)||p.system?.shell.family==='tray')return[];let rows=old.closures(p,d),outline=attachmentOutline(p,d);if(outline){let area=outline.reduce((s,v,i)=>{let w=outline[(i+1)%outline.length];return s+v[0]*w[1]-v[1]*w[0];},0);if(area<0)outline.reverse();const lengths=outline.map((v,i)=>Math.hypot(v[0]-outline[(i+1)%outline.length][0],v[1]-outline[(i+1)%outline.length][1])),perimeter=lengths.reduce((a,b)=>a+b,0);return rows.map((c,i)=>{let distance=perimeter*(i+.5)/4,j=0;while(j<lengths.length-1&&distance>lengths[j])distance-=lengths[j++];let a=outline[j],b=outline[(j+1)%outline.length],dx=(b[0]-a[0])/lengths[j],dy=(b[1]-a[1])/lengths[j],radius=c.diameter/2,off=type==='external'?p.settings.wall+radius*.6:-(radius-1);if(p.system.shell.family==='board-following')off+=p.settings.margin;let o=p.closures[c.id]||{};return{...c,x:o.x??a[0]+dx*distance+dy*off,y:o.y??a[1]+dy*distance-dx*off,internal:type!=='external',insert:type==='insert'};});}if(type==='external')return rows;const r=p.settings.closureDiameter/2;return rows.map((c,i)=>{let o=p.closures[c.id]||{};return{...c,x:o.x??(i<2?d.innerMinX+r-1:d.innerMaxX-r+1),y:o.y??(i%2===0?d.innerMinY+r-1:d.innerMaxY-r+1),internal:true,insert:type==='insert'};});}
function frame(face,d,s){let f=old.frame(face,{...d,top:d.centerTop??d.top},s);if(d.lidTop!==undefined&&['lid','inside-lid'].includes(face))f.origin[2]=face==='lid'?d.lidTop:d.lidBottom;if(d.slope&&['lid','inside-lid'].includes(face)){let c=1/Math.sqrt(1+d.slope*d.slope),sn=d.slope*c,sg=face==='lid'?1:-1;f.v=[0,sg*c,sg*sn];f.n=[0,-sg*sn,sg*c];f.height/=c;f.thickness=s.roof*c;}else if(d.slope&&['front','back'].includes(face)){let z=d.height+d.slope*(face==='front'?d.minY-d.cy:d.maxY-d.cy);f.origin[2]=z/2;f.height=z;}return f;}
function resolvedFeature(f,p,a=effective(p),d=dimensions(p,a)){
 const fr=frame(f.face,d,p.settings);let u=f.u,v=f.v,unresolved=false;
 if(f.positioning==='edges'&&!f.componentId){u=f.edgeX==='left'?-fr.width/2+f.edgeU:f.edgeX==='right'?fr.width/2-f.edgeU:f.edgeU;v=f.edgeY==='bottom'?-fr.height/2+f.edgeV:f.edgeY==='top'?fr.height/2-f.edgeV:f.edgeV;}
 if(f.componentId){const c=a.components.find(c=>c.id===f.componentId);if(!c)unresolved=true;else{const pt=c.envelopeCenter||c.position,uv=old.project(fr,[pt.x,pt.y,pt.z+d.boardZ]);u+=uv[0];v+=uv[1];}}
 return{...f,u,v,frame:fr,unresolved};
}
function feature(...args){return{...old.feature(...args),target:'auto',positioning:'center',edgeX:'left',edgeY:'bottom',edgeU:5,edgeV:5,groupId:null};}
function shiftFeature(f,du,dv){if(f.positioning==='edges'&&!f.componentId){f.edgeU+=(f.edgeX==='right'?-1:1)*du;f.edgeV+=(f.edgeY==='top'?-1:1)*dv;}else{f.u+=du;f.v+=dv;}return f;}
function geometryState(p){const s=clone(p.system||{});delete s.evidence;delete s.library;delete s.recipe;return JSON.stringify([p.source.text,p.settings,p.overrides,p.supports,p.closures,p.features,p.envelopes,p.review.mounting,s]);}
function geometryFingerprint(p){return C.fingerprint(geometryState(p));}
function proofStatus(p){const stamp=geometryFingerprint(p),find=kind=>{const records=p.system.evidence.filter(e=>e.kind===kind),current=records.filter(e=>e.fingerprint===stamp),last=current.at(-1);return last?{status:last.result==='pass'?'recorded-pass':last.result==='fail'?'recorded-fail':'observed',record:last}:records.length?{status:'stale'}:{status:'untested'};};return{geometryFingerprint:stamp,slicer:find('slicer'),fit:find('fit')};}
function addEvidence(p,kind,values){const q=clone(p);q.system.evidence.push({id:old.uid('trial'),kind,date:new Date().toISOString(),fingerprint:geometryFingerprint(p),name:values.name,result:values.result,notes:values.notes||''});return validate(q);}
function addBoard(p,sourceText,name){const q=clone(p),a=C.normalize(sourceText),b=C.normalize(p.source.text);q.system.boards.push({id:old.uid('board-instance'),name:name||a.source.title||'Board '+(q.system.boards.length+2),source:{text:sourceText,filename:name||'board.json'},x:0,y:0,z:20,rotation:0,enabled:true,supports:false});old.initializeMountSuggestions(q,sourceText,q.system.boards.at(-1).id+'::');return validate(q);}
function applyRevision(p,t,n){const preview=revisionPreview(p,t),q=clone(p),date=new Date().toISOString();q.review.baseline={sourceText:p.source.text,date};q.revisions.push({date,from:p.source.fingerprint.value,to:C.fingerprint(t),changes:preview.changes});q.revisions=q.revisions.slice(-10);q.source=source({text:t,filename:n});old.initializeMountSuggestions(q,t,'',preview.old.bores.map(h=>h.id));q.updated=date;return validate(q);}
function revisionPreview(p,t){let v=old.revisionPreview(p,t);const next=new Map(v.next.components.map(c=>[c.id,c]));v.mechanical=[];for(const c of v.old.components){let n=next.get(c.id);if(!n)continue;const keys=['position','rotation','side','body'];let changed=keys.filter(k=>JSON.stringify(c[k])!==JSON.stringify(n[k]));if(changed.length)v.mechanical.push({id:c.id,ref:c.ref,changed,overrideNeedsReview:!!p.overrides[c.id]});}return v;}
function toRecipe(p,name){const a=effective(p),anchors={};for(const f of p.features)if(f.componentId&&!anchors[f.componentId]){let c=a.components.find(c=>c.id===f.componentId);anchors[f.componentId]={id:f.componentId,label:c?.ref||'Missing component',body:c?.body?{width:c.body.width,depth:c.body.depth,height:c.body.height}:null};}return{app:'CASEBENCH_RECIPE',schema:1,name:text(name,'Recipe name'),sourceFingerprint:p.source.fingerprint.value,settings:clone(p.settings),shell:clone(p.system.shell),closure:clone(p.system.closure),hardware:clone(p.system.hardware),process:clone(p.system.process),retention:clone(p.system.retention),orientations:clone(p.system.orientations),features:clone(p.features),anchors:Object.values(anchors),evidenceNote:'A recipe transfers design intent, not fit verification. Components must be explicitly mapped.'};}
function applyRecipe(p,r,mapping={}){if(r.app!=='CASEBENCH_RECIPE'||r.schema!==1)throw Error('Not a CASEBENCH recipe.');const q=clone(p);q.settings={...q.settings,...r.settings};for(const k of ['shell','closure','hardware','process','retention','orientations'])if(r[k])q.system[k]=clone(r[k]);const ids=new Set(effective(p).components.map(c=>c.id));q.features=list(r.features,'Recipe features',64).map(f=>{let target=f.componentId?mapping[f.componentId]:null;if(target&&!ids.has(target))throw Error('Recipe mapping refers to a missing component.');return{...clone(f),id:old.uid('feature'),componentId:f.componentId?(target||'recipe-unmapped:'+f.componentId):null};});q.system.recipe={name:text(r.name,'Recipe name'),sourceFingerprint:r.sourceFingerprint||'',applied:new Date().toISOString()};q.system.evidence=[];q.generated=false;return validate(q);}
Object.assign(M,{VERSION:'2.3.1',SCHEMA:3,validate,defaults,effective,dimensions,mounts,closures,frame,resolvedFeature,feature,applyRevision,revisionPreview,defaultsSystem,hardware,planEnvelopePoints,shiftFeature,geometryState,geometryFingerprint,proofStatus,addEvidence,addBoard,toRecipe,applyRecipe,families,closureTypes,orientations});
return M;
});
