/* CASEBENCH inspection renderer. Small dependency-free WebGL viewport plus SVG plan.
 * The preview is not the mechanical model and has no manufacturing/export authority.
 * Board faces use a raster alpha mask for visible bores; original dimensions stay analytic.
 * v1.0 displays solid-engine meshes, with optional visual-only exploded offsets/cutaway.
 */
(function(root){'use strict';const C=root.CaseCore;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],sub=(a,b)=>a.map((v,i)=>v-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],unit=a=>{let n=Math.hypot(...a)||1;return a.map(x=>x/n);};
function multiply(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++){let v=0;for(let k=0;k<4;k++)v+=a[k*4+r]*b[c*4+k];o[c*4+r]=v;}return o;}
function lookAt(eye,target,up){let z=unit(sub(eye,target)),x=unit(cross(up,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
function ortho(l,r,b,t,n,f){return new Float32Array([2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-2/(f-n),0,-(r+l)/(r-l),-(t+b)/(t-b),-(f+n)/(f-n),1]);}
function triInside(p,a,b,c){const d=(b.y-c.y)*(a.x-c.x)+(c.x-b.x)*(a.y-c.y);if(Math.abs(d)<1e-9)return null;let u=((b.y-c.y)*(p.x-c.x)+(c.x-b.x)*(p.y-c.y))/d,v=((c.y-a.y)*(p.x-c.x)+(a.x-c.x)*(p.y-c.y))/d;return u>=0&&v>=0&&u+v<=1?[u,v,1-u-v]:null;}
function triangulate(points){let poly=C.ccw(points),ids=poly.map((_,i)=>i),out=[],guard=0;while(ids.length>3&&guard++<poly.length*poly.length){let found=false;for(let j=0;j<ids.length;j++){let ia=ids[(j+ids.length-1)%ids.length],ib=ids[j],ic=ids[(j+1)%ids.length],a=poly[ia],b=poly[ib],c=poly[ic];if((b.x-a.x)*(c.y-b.y)-(b.y-a.y)*(c.x-b.x)<=1e-10)continue;if(ids.some(k=>k!==ia&&k!==ib&&k!==ic&&triInside(poly[k],a,b,c)))continue;out.push([a,b,c]);ids.splice(j,1);found=true;break;}if(!found){ // Collinear boundary points can be removed for display tessellation only.
  let removed=false;for(let j=0;j<ids.length;j++){let a=poly[ids[(j+ids.length-1)%ids.length]],b=poly[ids[j]],c=poly[ids[(j+1)%ids.length]];if(Math.abs((b.x-a.x)*(c.y-b.y)-(b.y-a.y)*(c.x-b.x))<1e-8){ids.splice(j,1);removed=true;break;}}if(!removed)throw Error('Preview triangulation failed; use the exact-coordinate plan and import report.');}}
if(ids.length===3)out.push(ids.map(i=>poly[i]));return out;}
function hex(h){return[(h>>16&255)/255,(h>>8&255)/255,(h&255)/255];}
function path2(points){return points.map((p,i)=>(i?'L':'M')+p.x.toFixed(4)+' '+(-p.y).toFixed(4)).join(' ')+' Z';}
function padPoints(p){const a=p.rotation*Math.PI/180,w=p.width,h=p.height;let pts;if(p.shape==='circle')pts=Array.from({length:32},(_,i)=>({x:Math.cos(i/32*2*Math.PI)*Math.max(w,h)/2,y:Math.sin(i/32*2*Math.PI)*Math.max(w,h)/2}));else if(p.shape==='oval'){let horizontal=w>=h;pts=C.capsule({x:0,y:0,diameter:Math.min(w,h),slot:Math.abs(w-h),rotation:horizontal?0:90});}else pts=[{x:-w/2,y:-h/2},{x:w/2,y:-h/2},{x:w/2,y:h/2},{x:-w/2,y:h/2}];return pts.map(q=>({x:p.x+q.x*Math.cos(a)-q.y*Math.sin(a),y:p.y+q.x*Math.sin(a)+q.y*Math.cos(a)}));}
let planSequence=0;
function planSVG(a,opt={},selection=null){const maskId='voids-'+(++planSequence);const b=a.boards?.length>1||a.devices?.length?a.summary.knownBounds:a.board.bounds,margin=10,x=b.minX-margin,y=-b.maxY-margin,w=b.maxX-b.minX+2*margin,h=b.maxY-b.minY+2*margin,stroke=.18;
let boardPath=path2(a.board.outline),maskContent=[...a.cutouts.map(c=>c.points),...a.bores.filter(h=>!h.boardId||h.boardId==='primary').map(h=>h.perimeter)].map(poly=>`<path d="${path2(poly)}" fill="black"/>`).join('');let s=`<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="PCB top-view coordinate plan in millimetres" viewBox="${x} ${y} ${w} ${h}"><defs><mask id="${maskId}" maskUnits="userSpaceOnUse" x="${x}" y="${y}" width="${w}" height="${h}"><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="white"/>${maskContent}</mask><pattern id="plan-grid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M5 0H0V5" fill="none" stroke="#bbc4bf" stroke-width=".09"/></pattern></defs><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${opt.theme==='dark'?'#1c282c':opt.theme==='contrast'?'#080808':'#eef0e9'}"/><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="url(#plan-grid)"/><path d="${boardPath}" fill="#286954" fill-opacity="${opt.ghost?.55:1}" mask="url(#${maskId})" stroke="#9cbb76" stroke-width=".15" data-object="board"/>`;
if((a.boards||[]).length>1){for(const board of a.boards.filter(b=>b.id!=='primary')){const id=maskId+'-'+esc(board.id),cuts=[...board.cutouts.map(c=>c.points),...board.bores.map(h=>h.perimeter)];s+=`<defs><mask id="${id}" maskUnits="userSpaceOnUse" x="${x}" y="${y}" width="${w}" height="${h}"><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="white"/>${cuts.map(c=>`<path d="${path2(c)}" fill="black"/>`).join('')}</mask></defs><path data-object="${esc(board.id)}" d="${path2(board.board.outline)}" fill="#246f85" fill-opacity=".72" stroke="#82b4bf" stroke-width=".2" mask="url(#${id})"/>`;}}
for(const o of a.devices||[])s+=`<path data-object="${esc(o.id)}" d="${path2(o.vertices.filter((_,i)=>i%2===0))}" fill="#b49666" fill-opacity=".6" stroke="#725d37" stroke-width=".25"/><text x="${(o.bounds.minX+o.bounds.maxX)/2}" y="${-(o.bounds.minY+o.bounds.maxY)/2}" font-family="system-ui,sans-serif" font-size="2" text-anchor="middle">${esc(o.name)}</text>`;
if(opt.pads!==false)for(const p of a.pads)s+=`<path d="${path2(padPoints(p))}" fill="${p.side==='bottom'?'#8dced8':'#dcb96e'}" fill-opacity=".85" mask="url(#${p.boardId&&p.boardId!=='primary'?maskId+'-'+esc(p.boardId):maskId})" stroke="#302c23" stroke-width=".08"/>`;
for(const p of a.components){if(opt[p.side]===false)continue;if(p.body){const pts=p.vertices.slice(0,4);s+=`<path d="${path2(pts)}" data-object="${esc(p.id)}" fill="${selection===p.id?'#f8aa4b':p.side==='bottom'?'#5bb9d4':'#263437'}" fill-opacity="${p.side==='bottom'?.58:.94}" stroke="${selection===p.id?'#ffcf79':p.side==='bottom'?'#72d9f0':'#d9cfab'}" stroke-width="${selection===p.id?.5:.18}" ${p.side==='bottom'?'stroke-dasharray=".7 .5"':''}/>`;}else s+=`<circle data-object="${esc(p.id)}" cx="${p.position.x}" cy="${-p.position.y}" r="1.4" fill="#ed7055"/>`;
if(opt.labels!==false)s+=`<text x="${p.position.x}" y="${-p.position.y-(p.body?Math.max(1.3,p.body.depth/2+1):2)}" text-anchor="middle" fill="${p.side==='bottom'?'#83e2f7':'#f4edcf'}" stroke="#123a30" stroke-width=".22" paint-order="stroke" font-family="system-ui,sans-serif" font-size="1.9" font-weight="700" pointer-events="none">${esc(p.ref)}${p.side==='bottom'?' ↓':''}</text>`;}
if(opt.holes!==false)for(const h of a.bores.filter(h=>h.role==='mounting-candidate')){s+=`<path data-object="${esc(h.id)}" d="${path2(h.perimeter)}" fill="#e8eee5" stroke="${selection===h.id?'#fa963a':'#a98a50'}" stroke-width="${selection===h.id?.6:.3}"/><path d="M${h.x-2} ${-h.y}h4 M${h.x} ${-h.y-2}v4" stroke="#866944" stroke-width=".1" pointer-events="none"/>`;}
s+=`<g fill="${opt.theme==='dark'||opt.theme==='contrast'?'#ffffff':'#314c44'}" stroke="none" font-family="system-ui,sans-serif" font-size="2"><text x="${(b.minX+b.maxX)/2}" y="${-b.minY+6}" text-anchor="middle">${C.q(b.maxX-b.minX)} mm</text><text transform="translate(${b.maxX+6},${-(b.minY+b.maxY)/2}) rotate(-90)" text-anchor="middle">${C.q(b.maxY-b.minY)} mm</text><text x="${b.minX}" y="${-b.maxY-5}" font-size="1.5">TOP-VIEW DATUM · X → · SOURCE Y ↓</text></g><path d="M${b.minX} ${-b.minY+3}v2m0 -1H${b.maxX}m0 -1v2" stroke="#789085" stroke-width=".15" fill="none"/></svg>`;return s;}
class Viewer{
 constructor(host,onSelect,onView){this.host=host;this.onSelect=onSelect;this.onView=onView;this.canvas=document.createElement('canvas');this.canvas.className='view-canvas';this.canvas.tabIndex=0;this.canvas.setAttribute('aria-label','3D PCB inspection. Drag to orbit; Shift-drag to pan; wheel to zoom. Use view buttons and object list for keyboard access.');this.overlay=document.createElement('div');this.overlay.className='view-labels';this.plan=document.createElement('div');this.plan.className='plan-view';host.append(this.canvas,this.plan,this.overlay);this.camera={yaw:-.95,elev:.85,scale:1,panX:0,panY:0};this.selection=null;this.opt={};this.meshes=[];this.labels=[];
 try{this.gl=this.canvas.getContext('webgl',{alpha:true,antialias:true,preserveDrawingBuffer:true});if(!this.gl)throw Error('WebGL unavailable');this.initGL();}catch(e){this.gl=null;this.failure=e.message;}
 this.softCanvas=document.createElement('canvas');this.softCanvas.className='view-canvas';this.softCanvas.tabIndex=0;this.softCanvas.setAttribute('aria-label',this.canvas.getAttribute('aria-label'));this.softCanvas.hidden=true;host.insertBefore(this.softCanvas,this.plan);this.ctx=this.softCanvas.getContext('2d');
 this.plan.addEventListener('click',e=>{let el=e.target.closest('[data-object]');if(el)this.onSelect(el.dataset.object);});
 let down=null;this.canvas.addEventListener('pointerdown',e=>{(this.gl?this.canvas:this.softCanvas).focus();down={x:e.clientX,y:e.clientY,px:e.clientX,py:e.clientY,moved:0,pan:e.shiftKey||e.button===1||e.button===2};try{(this.gl?this.canvas:this.softCanvas).setPointerCapture(e.pointerId);}catch(_){}});
 this.canvas.addEventListener('pointermove',e=>{if(!down)return;let dx=e.clientX-down.px,dy=e.clientY-down.py;down.moved+=Math.abs(dx)+Math.abs(dy);if(down.pan){this.camera.panX+=dx;this.camera.panY+=dy;}else{this.camera.yaw-=dx*.007;this.camera.elev=Math.max(-1.565,Math.min(1.565,this.camera.elev+dy*.007));}down.px=e.clientX;down.py=e.clientY;this.request();});
 this.canvas.addEventListener('pointerup',e=>{if(down&&down.moved<6){const r=this.host.getBoundingClientRect();this.pick(e.clientX-r.left,e.clientY-r.top);}if(down?.moved>=6)this.onView?.('orbit');down=null;});this.canvas.addEventListener('pointercancel',()=>down=null);this.canvas.addEventListener('contextmenu',e=>e.preventDefault());this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.camera.scale=Math.max(.12,Math.min(20,this.camera.scale*Math.exp(-e.deltaY*.001)));this.request();},{passive:false});
 this.canvas.addEventListener('keydown',e=>{let hit=true;if(e.key==='ArrowLeft')this.camera.yaw+=.12;else if(e.key==='ArrowRight')this.camera.yaw-=.12;else if(e.key==='ArrowUp')this.camera.elev=Math.min(1.565,this.camera.elev+.12);else if(e.key==='ArrowDown')this.camera.elev=Math.max(-1.565,this.camera.elev-.12);else if(['+','='].includes(e.key))this.zoom(1.2);else if(e.key==='-')this.zoom(1/1.2);else if(e.key==='Home')this.preset('iso');else hit=false;if(hit){e.preventDefault();this.request();}});
 for(const type of ['pointerdown','pointermove','pointerup','pointercancel','contextmenu','wheel','keydown'])this.softCanvas.addEventListener(type,e=>{e.preventDefault();const E=type==='wheel'?WheelEvent:type==='keydown'?KeyboardEvent:type.startsWith('pointer')?PointerEvent:MouseEvent;this.canvas.dispatchEvent(new E(type,{bubbles:false,cancelable:true,clientX:e.clientX,clientY:e.clientY,button:e.button,buttons:e.buttons,shiftKey:e.shiftKey,key:e.key,deltaY:e.deltaY,pointerId:e.pointerId}));},{passive:false});
 this.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.failure='3D graphics context lost; exact-coordinate plan remains available.';this.lost=true;this.request();});this.canvas.addEventListener('webglcontextrestored',()=>{this.lost=false;this.initGL();if(this.assembly)this.set(this.assembly,this.opt);});
 new ResizeObserver(()=>this.request()).observe(host);
 }
 initGL(){let gl=this.gl;const vs=`attribute vec3 aPos;attribute vec3 aNormal;attribute vec3 aColor;attribute vec2 aUV;attribute float aMask;uniform mat4 uMVP;varying vec3 vColor;varying vec3 vNormal;varying vec2 vUV;varying float vMask;void main(){gl_Position=uMVP*vec4(aPos,1.);vColor=aColor;vNormal=aNormal;vUV=aUV;vMask=aMask;}`;
 const fs=`precision mediump float;varying vec3 vColor;varying vec3 vNormal;varying vec2 vUV;varying float vMask;uniform sampler2D uMask;uniform float uAlpha;void main(){if(vMask>.5 && texture2D(uMask,vUV).a<.5)discard;float light=.48+.35*max(dot(normalize(vNormal),normalize(vec3(-.35,-.45,.85))),0.)+.17*max(dot(normalize(vNormal),normalize(vec3(.4,.6,-.4))),0.);gl_FragColor=vec4(vColor*light,uAlpha);}`;
 const shader=(kind,src)=>{let s=gl.createShader(kind);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};let p=gl.createProgram(),v=shader(gl.VERTEX_SHADER,vs),f=shader(gl.FRAGMENT_SHADER,fs);gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);gl.deleteShader(v);gl.deleteShader(f);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));this.program=p;this.buffer=gl.createBuffer();this.texture=gl.createTexture();this.boardMasks=new Map();this.loc={};for(const k of ['aPos','aNormal','aColor','aUV','aMask'])this.loc[k]=gl.getAttribLocation(p,k);for(const k of ['uMVP','uMask','uAlpha'])this.loc[k]=gl.getUniformLocation(p,k);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.disable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);}
 set(a,opt){this.assembly=a;this.opt={...opt};this.build();this.request();}
 clear(){this.assembly=null;this.meshes=[];this.overlay.replaceChildren();this.plan.replaceChildren();if(this.ctx)this.ctx.clearRect(0,0,this.softCanvas.width,this.softCanvas.height);if(this.gl){this.gl.clearColor(0,0,0,0);this.gl.clear(this.gl.COLOR_BUFFER_BIT|this.gl.DEPTH_BUFFER_BIT);}}
 preset(name){this.opt.preset=name;const presets={iso:[-.95,.85],top:[-Math.PI/2,Math.PI/2-.001],bottom:[-Math.PI/2,-Math.PI/2+.001],front:[-Math.PI/2,.03],right:[0,.03]};if(presets[name]){[this.camera.yaw,this.camera.elev]=presets[name];this.camera.panX=this.camera.panY=0;this.camera.scale=1;}this.request();}
 zoom(n){this.camera.scale=Math.max(.12,Math.min(20,this.camera.scale*n));this.request();}
 fit(){this.camera.panX=this.camera.panY=0;this.camera.scale=1;this.request();}
 select(id){this.selection=id;this.build();this.request();}
 build(){if(!this.assembly)return;const a=this.assembly,b=a.board.bounds;this.meshes=[];this.labels=[];
 const scene=this.opt.scene||'board',result=this.caseResult,hasCase=!!result&&scene!=='board',printing=['print','export'].includes(scene),showRefs=!printing&&this.opt.showReferences!==false,boardOffset=hasCase?result.dimensions.boardZ+(scene==='exploded'?result.dimensions.height+8:0):0;this.boardOffset=boardOffset;this.showReferences=showRefs;
 // Preview-only per-board alpha masks avoid expensive synchronous Boolean work.
 // Source outlines/bores remain authoritative in the separate solid worker.
 this.boardMasks??=new Map();const boards=a.boards||[{id:'primary',board:a.board,bores:a.bores,cutouts:a.cutouts,z:0}],masks=new Map();
 for(const board of boards){const bounds=board.board.bounds||C.bounds(board.board.outline),cuts=[...board.cutouts.map(c=>c.points),...board.bores.map(h=>h.perimeter)],key=JSON.stringify([bounds,cuts]);let m=this.boardMasks.get(board.id);if(!m||m.key!==key){if(m?.texture&&this.gl&&!this.lost)this.gl.deleteTexture(m.texture);const cn=document.createElement('canvas');cn.width=cn.height=2048;const ctx=cn.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,2048,2048);ctx.globalCompositeOperation='destination-out';for(const poly of cuts){ctx.beginPath();poly.forEach((p,i)=>{const x=(p.x-bounds.minX)/(bounds.maxX-bounds.minX)*2048,y=(bounds.maxY-p.y)/(bounds.maxY-bounds.minY)*2048;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.closePath();ctx.fill();}m={key,bounds,data:ctx.getImageData(0,0,2048,2048).data,texture:null};if(this.gl&&!this.lost){const gl=this.gl;m.texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,m.texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,cn);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);}this.boardMasks.set(board.id,m);}masks.set(board.id,m);}
 for(const [id,m] of this.boardMasks)if(!masks.has(id)){if(m.texture&&this.gl&&!this.lost)this.gl.deleteTexture(m.texture);this.boardMasks.delete(id);}
 const add=(verts,color,id='board',mask=0,kind='body',alpha=1)=>{const maskInfo=mask===1?masks.get('primary'):mask||null,mb=maskInfo?.bounds||b;if(kind!=='case'){if(!showRefs)return;verts=verts.map(t=>t.map(p=>({...p,z:p.z+boardOffset})));}const data=[],rgb=hex(color);for(const tr of verts){let av=tr[0],bv=tr[1],cv=tr[2],n=unit(cross([bv.x-av.x,bv.y-av.y,bv.z-av.z],[cv.x-av.x,cv.y-av.y,cv.z-av.z]));for(const p of tr)data.push(p.x,p.y,p.z,...n,...rgb,(p.x-mb.minX)/(mb.maxX-mb.minX),(p.y-mb.minY)/(mb.maxY-mb.minY),maskInfo?1:0);}this.meshes.push({data:new Float32Array(data),verts,id,kind,alpha,maskInfo});};
 const horizontal=(pts,z,up=true)=>triangulate(pts).map(t=>{let p=t.map(p=>({...p,z}));return up?p:p.reverse();});
 const sides=(pts,z0,z1,inward=false)=>{let out=[];for(let i=0;i<pts.length;i++){let p=pts[i],q=pts[(i+1)%pts.length],a={...p,z:z0},b={...q,z:z0},c={...q,z:z1},d={...p,z:z1};out.push(inward?[a,c,b]:[a,b,c],inward?[a,d,c]:[a,c,d]);}return out;};
 try{for(const board of boards){const id=board.id==='primary'?'board':board.id,col=board.id==='primary'?0x328166:0x3183a3,z=board.z||0,t=board.board.thickness;add([...horizontal(board.board.outline,z,false),...horizontal(board.board.outline,z+t,true)],col,id,masks.get(board.id),'board');add(sides(board.board.outline,z,z+t),0xb2ba80,id,0,'board');for(const c of board.cutouts)add(sides(c.points,z,z+t,true),0xb2ba80,id,0,'board');for(const h of board.bores)add(sides(h.perimeter,z,z+t,true),h.plated?0xc4b079:0xc9c792,h.id,0,'bore');}
 if(this.opt.pads!==false)for(const p of a.pads){const pts=padPoints(p),z=p.boardZ||0,t=p.boardThickness||a.board.thickness,mask=masks.get(p.boardId||'primary');if(p.side!=='bottom')add(horizontal(pts,z+t+.016),0xe3c47c,p.ownerId,mask,'pad');if(p.side!=='top')add(horizontal(pts,z-.016,false),0xcbc395,p.ownerId,mask,'pad');}
 for(const device of a.devices||[]){const pts=device.vertices.filter((_,i)=>i%2===0).map(v=>({x:v.x,y:v.y})),lo=device.bounds.minZ,hi=device.bounds.maxZ;add([...horizontal(pts,lo,false),...horizontal(pts,hi),...sides(pts,lo,hi)],this.selection===device.id?0xffb04f:device.type==='battery'?0xb99160:0x538fac,device.id,0,'device',.85);this.labels.push({id:device.id,text:device.name,side:'top',pos:{x:(device.bounds.minX+device.bounds.maxX)/2,y:(device.bounds.minY+device.bounds.maxY)/2,z:hi+.8}});}
 for(const p of a.components){if(this.opt[p.side]===false)continue;let col=this.selection===p.id?0xffb04f:p.side==='bottom'?0x58c4dd:['capacitor','led'].includes(p.kind)?0xdda35a:p.kind==='terminal'?0x6da1bf:0x405157;if(p.body){let pts=C.ccw(p.vertices.slice(0,4).map(v=>({x:v.x,y:v.y}))),z0=p.body.zMin,z1=p.body.zMax;add([...horizontal(pts,z0,false),...horizontal(pts,z1),...sides(pts,z0,z1)],col,p.id,0,'component');
 // Inset top-face stripe is a visual face cue; it never changes the envelope.
 const faceZ=p.side==='bottom'?z0-.008:z1+.008,fac=pts.map(v=>({x:p.position.x+(v.x-p.position.x)*.72,y:p.position.y+(v.y-p.position.y)*.72}));add(horizontal(fac,faceZ,p.side==='top'),p.side==='bottom'?0x99dfec:0x798c86,p.id,0,'component');
 this.labels.push({id:p.id,text:p.boardId&&p.boardId!=='primary'?(a.boards.findIndex(b=>b.id===p.boardId)+1)+':'+p.ref.split('/').at(-1):p.ref,title:p.ref,side:p.side,pos:{x:p.position.x,y:p.position.y,z:p.side==='bottom'?z0-.8:z1+.8}});
 }else this.labels.push({id:p.id,text:p.ref+' · ?',side:p.side,pos:p.position});}
 for(const e of [...(a.envelopes||[]),...(this.opt.envelopes?(a.projections||[]):[])]){if(!this.opt.envelopes&&this.selection!==e.id)continue;if(e.unresolved)continue;let b=e.bounds,pts=[{x:b.minX,y:b.minY},{x:b.maxX,y:b.minY},{x:b.maxX,y:b.maxY},{x:b.minX,y:b.maxY}];add([...horizontal(pts,b.minZ,false),...horizontal(pts,b.maxZ),...sides(pts,b.minZ,b.maxZ)],e.role==='internal'?0x71baa1:0xe49c57,e.id,0,'space',.28);if(e.name)this.labels.push({id:e.id,text:e.name,side:'top',pos:{x:(b.minX+b.maxX)/2,y:(b.minY+b.maxY)/2,z:b.maxZ+1}});}
 this.geomFailure=null;
 }catch(e){this.geomFailure=e.message;}

 for(const l of this.labels)l.pos={...l.pos,z:l.pos.z+boardOffset};
 if(!showRefs||scene==='assembled')this.labels=[];
 if(hasCase){let parts=printing?(scene==='export'&&this.exportParts?this.exportParts:CaseExport.layout(result.parts,this.bedWidth||220).parts):result.parts;
 const clipTriangle=(tr,cut)=>{let poly=[];for(let i=0;i<tr.length;i++){let a=tr[i],b=tr[(i+1)%tr.length],ina=a.x<=cut,inb=b.x<=cut;if(ina)poly.push(a);if(ina!==inb){let t=(cut-a.x)/(b.x-a.x);poly.push({x:cut,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t});}}let out=[];for(let i=1;i<poly.length-1;i++)out.push([poly[0],poly[i],poly[i+1]]);return out;};
 for(const part of parts){const explode=scene==='exploded',withLid=part.id==='lid'||part.parentPart==='lid',n=part.explodeNormal||[0,0,0],gap=explode?(part.explodeDistance||0):0,shift=explode&&withLid?result.dimensions.height+16:0;let verts=part.mesh.triangles.map(t=>t.map(i=>{let v=part.mesh.vertices[i];return{z:v[2]+shift+n[2]*gap,x:v[0]+(explode&&withLid?result.dimensions.width*.78:0)+n[0]*gap,y:v[1]+(explode&&withLid?result.dimensions.depth*.25:0)+n[1]*gap};}));if(scene==='section')verts=verts.flatMap(t=>clipTriangle(t,result.dimensions.cx));add(verts,part.id==='base'?0xe0ad68:part.parentPart?0xb99972:0x799eaa,part.id,0,'case',scene==='transparent'?.20:1);}
 }
 if(this.meshes.length){let b={minX:Infinity,minY:Infinity,minZ:Infinity,maxX:-Infinity,maxY:-Infinity,maxZ:-Infinity};for(const m of this.meshes)for(const t of m.verts)for(const p of t){b.minX=Math.min(b.minX,p.x);b.minY=Math.min(b.minY,p.y);b.minZ=Math.min(b.minZ,p.z);b.maxX=Math.max(b.maxX,p.x);b.maxY=Math.max(b.maxY,p.y);b.maxZ=Math.max(b.maxZ,p.z);}this.renderBounds=b;}else this.renderBounds=a.summary.knownBounds;
 this.mask=masks.get('primary')?.data;
 }
 request(){if(this.pending)return;this.pending=true;requestAnimationFrame(()=>{this.pending=false;this.draw();});}
 fitHalf(b,v,aspect){let xs=[],ys=[];for(const x of[b.minX,b.maxX])for(const y of[b.minY,b.maxY])for(const z of[b.minZ,b.maxZ]){xs.push(v[0]*x+v[4]*y+v[8]*z+v[12]);ys.push(v[1]*x+v[5]*y+v[9]*z+v[13]);}return Math.max(10,(Math.max(...ys)-Math.min(...ys))*.6,(Math.max(...xs)-Math.min(...xs))*.6/aspect);}
 project(p){const m=this.mvp,x=m[0]*p.x+m[4]*p.y+m[8]*p.z+m[12],y=m[1]*p.x+m[5]*p.y+m[9]*p.z+m[13],z=m[2]*p.x+m[6]*p.y+m[10]*p.z+m[14];return{x:(x+1)/2*this.width,y:(1-y)/2*this.height,z};}
 draw(){if(!this.assembly)return;const software=!this.gl||this.lost,fallback=!!this.geomFailure||(software&&!this.ctx),isPlan=this.opt.preset==='plan'||fallback;this.canvas.hidden=isPlan||software;this.softCanvas.hidden=isPlan||!software;this.overlay.hidden=isPlan;this.plan.hidden=!isPlan;
 if(isPlan){this.plan.innerHTML=planSVG(this.assembly,this.opt,this.selection);this.host.dataset.renderer=fallback?'plan-fallback':'plan';this.host.dataset.reason=this.geomFailure||this.failure||'';return;}
 this.host.dataset.renderer=software?'software-3d':'webgl';const r=this.host.getBoundingClientRect(),W=Math.max(1,r.width),H=Math.max(1,r.height),dpr=Math.min(devicePixelRatio||1,2),gl=this.gl;this.width=W;this.height=H;if(!software){this.canvas.width=Math.round(W*dpr);this.canvas.height=Math.round(H*dpr);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);}let b=this.renderBounds||this.assembly.summary.knownBounds,c=[(b.minX+b.maxX)/2,(b.minY+b.maxY)/2,(b.minZ+b.maxZ)/2],diag=Math.hypot(b.maxX-b.minX,b.maxY-b.minY,b.maxZ-b.minZ)||20,rad=diag*4,cam=this.camera;
 let eye=[c[0]+rad*Math.cos(cam.elev)*Math.cos(cam.yaw),c[1]+rad*Math.cos(cam.elev)*Math.sin(cam.yaw),c[2]+rad*Math.sin(cam.elev)],v=lookAt(eye,c,[0,0,1]),half=this.fitHalf(b,v,W/H)/cam.scale,aspect=W/H,px=cam.panX/W*half*2*aspect,py=-cam.panY/H*half*2;this.mvp=multiply(ortho(-half*aspect-px,half*aspect-px,-half-py,half-py,.01,rad*4),v);if(software)this.drawSoftware();else{gl.useProgram(this.program);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);for(const[k,n,off]of[['aPos',3,0],['aNormal',3,3],['aColor',3,6],['aUV',2,9],['aMask',1,11]]){gl.enableVertexAttribArray(this.loc[k]);gl.vertexAttribPointer(this.loc[k],n,gl.FLOAT,false,48,off*4);}gl.uniformMatrix4fv(this.loc.uMVP,false,this.mvp);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.uniform1i(this.loc.uMask,0);
 for(const m of [...this.meshes].sort((a,b)=>((a.alpha<1||this.opt.ghost&&['board','bore'].includes(a.kind))?1:0)-((b.alpha<1||this.opt.ghost&&['board','bore'].includes(b.kind))?1:0))){const alpha=m.alpha<1?m.alpha:this.opt.ghost&&['board','bore'].includes(m.kind)?.22:1;gl.bindTexture(gl.TEXTURE_2D,m.maskInfo?.texture||this.texture);gl.depthMask(alpha===1);gl.uniform1f(this.loc.uAlpha,alpha);gl.bufferData(gl.ARRAY_BUFFER,m.data,gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,m.data.length/12);}gl.depthMask(true);}
 this.overlay.replaceChildren();if(this.opt.labels!==false)for(const l of this.labels){if(!this.opt.ghost&&((cam.elev>=0&&l.side==='bottom')||(cam.elev<0&&l.side==='top')))continue;let p=this.project(l.pos);if(p.x<0||p.x>W||p.y<0||p.y>H)continue;let el=document.createElement('button');el.className='part-label '+l.side+(l.id===this.selection?' selected':'');el.textContent=l.text+(l.side==='bottom'?' ↓':'');el.style.left=p.x+'px';el.style.top=p.y+'px';el.title='Inspect '+(l.title||l.text)+' ('+l.side+')';el.onclick=()=>this.onSelect(l.id);this.overlay.append(el);}
 if(this.showReferences&&this.opt.scene!=='assembled'&&this.opt.holes!==false)for(const [i,h]of this.assembly.bores.filter(h=>h.role==='mounting-candidate').entries()){let p=this.project({x:h.x,y:h.y,z:(h.boardZ||0)+(cam.elev<0?-.1:(this.assembly.boards?.find(b=>b.id===(h.boardId||'primary'))?.board.thickness||this.assembly.board.thickness)+.1)+(this.boardOffset||0)}),el=document.createElement('button');el.className='mount-label'+(h.id===this.selection?' selected':'');el.textContent='H'+(i+1);el.style.left=p.x+'px';el.style.top=p.y+'px';el.title='Inspect mounting candidate H'+(i+1);el.onclick=()=>this.onSelect(h.id);this.overlay.append(el);}
 if(this.opt.envelopes){let points=[{x:b.minX,y:b.minY,z:b.minZ},{x:b.maxX,y:b.minY,z:b.minZ},{x:b.maxX,y:b.maxY,z:b.minZ},{x:b.minX,y:b.maxY,z:b.minZ},{x:b.minX,y:b.minY,z:b.maxZ},{x:b.maxX,y:b.minY,z:b.maxZ},{x:b.maxX,y:b.maxY,z:b.maxZ},{x:b.minX,y:b.maxY,z:b.maxZ}].map(p=>this.project(p));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.classList.add('envelope-overlay');for(const [i,j]of[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]]){let l=document.createElementNS(svg.namespaceURI,'line');l.setAttribute('x1',points[i].x);l.setAttribute('y1',points[i].y);l.setAttribute('x2',points[j].x);l.setAttribute('y2',points[j].y);svg.append(l);}this.overlay.prepend(svg);}
 }
 // Depth-buffered CPU fallback. Same triangles and board-bore alpha mask as WebGL.
 // Rendering resolution is bounded; model units and source precision are untouched.
 drawSoftware(){const factor=Math.min(1,850/this.width,700/this.height),W=Math.max(1,Math.round(this.width*factor)),H=Math.max(1,Math.round(this.height*factor));this.softCanvas.width=W;this.softCanvas.height=H;const im=this.ctx.createImageData(W,H),out=im.data,depth=new Float32Array(W*H).fill(Infinity),l1=unit([-.35,-.45,.85]),l2=unit([.4,.6,-.4]);
 const meshes=[...this.meshes].sort((a,b)=>((a.alpha<1||this.opt.ghost&&['board','bore'].includes(a.kind))?1:0)-((b.alpha<1||this.opt.ghost&&['board','bore'].includes(b.kind))?1:0));
 for(const m of meshes){const d=m.data,alpha=m.alpha<1?m.alpha:this.opt.ghost&&['board','bore'].includes(m.kind)?.22:1;for(let i=0;i<d.length;i+=36){const pp=[];for(let j=0;j<3;j++){let k=i+j*12,p=this.project({x:d[k],y:d[k+1],z:d[k+2]});pp.push({x:p.x*factor,y:p.y*factor,z:p.z,u:d[k+9],v:d[k+10]});}const [a,b,c]=pp,den=(b.y-c.y)*(a.x-c.x)+(c.x-b.x)*(a.y-c.y);if(Math.abs(den)<1e-8)continue;const minY=Math.max(0,Math.ceil(Math.min(a.y,b.y,c.y)-.5)),maxY=Math.min(H-1,Math.floor(Math.max(a.y,b.y,c.y)-.5)),n=[d[i+3],d[i+4],d[i+5]],light=.56+.37*Math.max(dot(n,l1),0)+.17*Math.max(dot(n,l2),0),rgb=[d[i+6]*light*255,d[i+7]*light*255,d[i+8]*light*255],mask=d[i+11]>.5,du=(b.y-c.y)/den,dv=(c.y-a.y)/den;
 // Scan only covered spans. Skinny CSG triangles no longer rasterize their entire bounding box.
 for(let y=minY;y<=maxY;y++){const yy=y+.5,xs=[];for(let k=0;k<3;k++){let p=pp[k],q=pp[(k+1)%3];if(yy>=Math.min(p.y,q.y)&&yy<Math.max(p.y,q.y))xs.push(p.x+(yy-p.y)*(q.x-p.x)/(q.y-p.y));}if(xs.length<2)continue;let x0=Math.max(0,Math.ceil(Math.min(...xs)-.5)),x1=Math.min(W-1,Math.floor(Math.max(...xs)-.5)),u=((b.y-c.y)*(x0+.5-c.x)+(c.x-b.x)*(yy-c.y))/den,v=((c.y-a.y)*(x0+.5-c.x)+(a.x-c.x)*(yy-c.y))/den;
 for(let x=x0;x<=x1;x++,u+=du,v+=dv){let w=1-u-v,z=u*a.z+v*b.z+w*c.z,k=y*W+x;if(z>depth[k]+1e-7)continue;if(mask&&m.maskInfo?.data){let tx=Math.max(0,Math.min(2047,Math.floor((u*a.u+v*b.u+w*c.u)*2048))),ty=Math.max(0,Math.min(2047,Math.floor((1-u*a.v-v*b.v-w*c.v)*2048)));if(m.maskInfo.data[(ty*2048+tx)*4+3]<128)continue;}let j=k*4;if(alpha===1){out[j]=rgb[0];out[j+1]=rgb[1];out[j+2]=rgb[2];out[j+3]=255;depth[k]=z;}else{let old=out[j+3]/255,combined=alpha+old*(1-alpha);for(let t=0;t<3;t++)out[j+t]=(rgb[t]*alpha+out[j+t]*old*(1-alpha))/combined;out[j+3]=combined*255;}}}
 }}this.ctx.putImageData(im,0,0);}
 pick(x,y){if(!this.mvp)return;let best=null;for(const m of this.meshes){if(!['component','case','space','device','board'].includes(m.kind))continue;if(m.kind==='case'&&this.opt.scene==='transparent')continue;let comp=this.assembly.components.find(p=>p.id===m.id);if(!this.opt.ghost&&comp&&((this.camera.elev>=0&&comp.side==='bottom')||(this.camera.elev<0&&comp.side==='top')))continue;for(const t of m.verts){let a=t.map(p=>this.project(p)),b=triInside({x,y},...a);if(b){let z=b[0]*a[0].z+b[1]*a[1].z+b[2]*a[2].z;if(!best||z<best.z){let id=m.id;if(m.kind==='case'&&!['print','export'].includes(this.opt.scene)){let p=t[0],q=t[1],r=t[2],n=unit(cross([q.x-p.x,q.y-p.y,q.z-p.z],[r.x-p.x,r.y-p.y,r.z-p.z]));const surface=m.id==='base'&&Math.abs(n[2])<.1?Object.entries(this.caseResult?.dimensions?.planarFaces||{}).find(([key,f])=>n.reduce((sum,v,i)=>sum+v*f.n[i],0)>.99&&Math.abs((p.x-f.origin[0])*f.n[0]+(p.y-f.origin[1])*f.n[1])<.1):null;id=surface?'face:'+surface[0]:'face:'+(Math.abs(n[2])>.8?(m.id==='lid'?(n[2]>0?'lid':'inside-lid'):(n[2]>0?'inside-floor':'floor')):Math.abs(n[0])>Math.abs(n[1])?(n[0]>0?'right':'left'):(n[1]>0?'back':'front'));}best={id,z};}}}}this.onSelect(best?best.id:'board');}

}
root.CaseViewer={Viewer,planSVG,triangulate,esc};
})(globalThis);
